import { Prisma, type PrismaClient, type ProcessRoute, type WorkStage } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { userCanMutateStage } from "./worker-access";
import { assertValidStageTransition, createWorkRouteSnapshot, parseWorkRouteSnapshot, recommendedNextStage, routeFingerprint, type WorkRouteSnapshotV2 } from "./dynamic-route";
import { getGroupedWork, type GroupedWorkSource } from "./grouped-work";
import { resolveRouteStageMetadata, type PostPickRoute } from "./route-selection";

type Client=PrismaClient;
const CHOICE:Record<ProcessRoute,PostPickRoute>={PICK_PACK:"DIRECT_PACK",PICK_MARK_PACK:"MARK",PICK_ASSEMBLE_PACK:"ASSEMBLE",PICK_MARK_ASSEMBLE_PACK:"MARK_ASSEMBLE"};
function processRoute(value:string|null){try{return(JSON.parse(value??"")as{processRoute?:ProcessRoute}).processRoute??null;}catch{return null;}}
function sourceWhere(task:{sourceType:"ORDER"|"CONSIGNMENT";orderId:string|null;consignmentLineId:string|null}){return task.sourceType==="ORDER"?{orderId:task.orderId!}:{consignmentLineId:task.consignmentLineId!};}
function transient(error:unknown){const message=error instanceof Error?error.message:String(error);return error instanceof Prisma.PrismaClientKnownRequestError&&["P1008","P2002","P2028","P2034"].includes(error.code)||/database is locked|write conflict|transaction.*(?:closed|conflict|timeout)/i.test(message);}
function nextSnapshot(snapshot:WorkRouteSnapshotV2,from:WorkStage,to:WorkStage|undefined,actorUserId:string,useDefault:boolean){return{...snapshot,routeVersion:snapshot.routeVersion+1,currentStage:to??from,selectedNextStage:to,actualStages:to?[...snapshot.actualStages,to]:snapshot.actualStages,completedStages:[...new Set([...snapshot.completedStages,from])],decisions:to?[...snapshot.decisions,{fromStage:from,toStage:to,actorUserId,decidedAt:new Date().toISOString(),reason:useDefault?"DEFAULT" as const:"WORKER_SELECTION" as const}]:snapshot.decisions};}

export async function completeGroupedStage(input:{actorUserId:string;selectedAccountId:string;sourceType:GroupedWorkSource;stage:WorkStage;groupKey:string;expectedGroupVersion:string;nextStage?:WorkStage;useRecommendedNextStage?:boolean;clientRequestId:string},client:Client=prisma){const requestFingerprint=routeFingerprint({sourceType:input.sourceType,stage:input.stage,groupKey:input.groupKey,expectedGroupVersion:input.expectedGroupVersion,nextStage:input.nextStage??null,useRecommendedNextStage:Boolean(input.useRecommendedNextStage)});let last:unknown;
 for(let attempt=0;attempt<6;attempt++){try{return await client.$transaction(async tx=>{const resolved=await getGroupedWork({actorUserId:input.actorUserId,accountId:input.selectedAccountId,stage:input.stage,sourceType:input.sourceType,pageSize:50,includeMemberIds:true,targetGroupKey:input.groupKey},tx);const card=resolved.cards[0];if(!card||card.groupVersion!==input.expectedGroupVersion)throw new Error("Work changed. The card has been refreshed.");if(!userCanMutateStage(resolved.user,input.stage))throw new Error(`${input.stage} permission is required.`);const tasks=await tx.workTask.findMany({where:{id:{in:card.memberTaskIds},accountId:input.selectedAccountId,sourceType:input.sourceType,stage:input.stage},include:{consignmentLine:{select:{processRoute:true}},order:{select:{id:true,batchId:true,trackingId:true,awb:true}}},orderBy:[{assignedUserId:"desc"},{createdAt:"asc"},{id:"asc"}]});if(tasks.length!==card.memberTaskIds.length)throw new Error("Work changed. The card has been refreshed.");
  if(input.stage==="PACK"&&input.sourceType==="ORDER"){const first=tasks[0].order;if(!first)throw new Error("Packing source is unavailable.");const packageId=first.trackingId??first.awb;const siblings=await tx.order.findMany({where:{accountId:input.selectedAccountId,batchId:first.batchId,OR:[{trackingId:packageId},{trackingId:null,awb:packageId}]},select:{id:true}});const memberOrderIds=new Set(tasks.map(task=>task.orderId));if(siblings.some(order=>!memberOrderIds.has(order.id)))throw new Error("This shipment package is not fully ready for packing.");const upstream=await tx.workTask.count({where:{orderId:{in:siblings.map(order=>order.id)},stage:{not:"PACK"},status:{in:["READY","IN_PROGRESS","PROBLEM"]}}});if(upstream)throw new Error("Finish every required upstream stage before packing this shipment.");}
  const prior=await tx.workActionLog.findMany({where:{taskId:{in:card.memberTaskIds},actorUserId:input.actorUserId,clientRequestId:input.clientRequestId,requestKind:"COMPLETE"}});if(prior.length){if(prior.length!==tasks.length||prior.some(log=>{try{return(JSON.parse(log.metadataJson??"")as{requestFingerprint?:string}).requestFingerprint!==requestFingerprint;}catch{return true;}}))throw new Error("Request ID was already used with a different group action.");return{groupKey:card.groupKey,completedTaskCount:tasks.length,nextStage:input.nextStage??card.recommendedNextStage,idempotent:true};}
  if(tasks.some(task=>!["READY","IN_PROGRESS"].includes(task.status)||task.completedQuantity>task.requiredQuantity||task.assignedUserId&&task.assignedUserId!==input.actorUserId&&resolved.user.role!=="OWNER"))throw new Error("Work changed. The card has been refreshed.");const firstSnapshot=parseWorkRouteSnapshot(tasks[0].routeSnapshotJson)??createWorkRouteSnapshot({processRoute:processRoute(tasks[0].metadataJson)??tasks[0].consignmentLine?.processRoute,currentStage:input.stage});if(input.stage==="PACK"&&input.nextStage)throw new Error("Packing is final and cannot route work backwards.");const next=input.stage==="PACK"?undefined:input.useRecommendedNextStage?recommendedNextStage(firstSnapshot,input.stage):input.nextStage;assertValidStageTransition(firstSnapshot,input.stage,next);
  const prepared:Array<{task:typeof tasks[number];snapshot:ReturnType<typeof nextSnapshot>;nextMetadata:string|null;existing:Awaited<ReturnType<typeof tx.workTask.findFirst>>}>=[];for(const task of tasks){const snapshot=parseWorkRouteSnapshot(task.routeSnapshotJson)??createWorkRouteSnapshot({processRoute:processRoute(task.metadataJson)??task.consignmentLine?.processRoute,currentStage:input.stage});assertValidStageTransition(snapshot,input.stage,next);let nextMetadata:string|null=null;if(next==="MARK"||next==="ASSEMBLE"){const route=processRoute(task.metadataJson)??task.consignmentLine?.processRoute;const choice=route?CHOICE[route]:next==="MARK"?"MARK":"ASSEMBLE";const metadata=await resolveRouteStageMetadata(tx,{accountId:input.selectedAccountId,actorUserId:input.actorUserId,sourceType:task.sourceType,sourceId:task.orderId??task.consignmentLineId!,route:choice,requestFingerprint});nextMetadata=metadata.get(next)??null;if(!nextMetadata)throw new Error(next==="MARK"?"Marking instructions need owner review.":"Assembly instructions need owner review.");}const existing=next?await tx.workTask.findFirst({where:{accountId:input.selectedAccountId,orderId:task.orderId,consignmentLineId:task.consignmentLineId,stage:next}}):null;if(existing?.status==="COMPLETED")throw new Error(`${next} was already completed.`);prepared.push({task,snapshot:nextSnapshot(snapshot,input.stage,next,input.actorUserId,Boolean(input.useRecommendedNextStage)),nextMetadata,existing});}
  const now=new Date();for(const item of prepared){const task=item.task;const changed=await tx.workTask.updateMany({where:{id:task.id,version:task.version,status:task.status,completedQuantity:task.completedQuantity,assignedUserId:task.assignedUserId},data:{completedQuantity:task.requiredQuantity,status:"COMPLETED",assignedUserId:task.assignedUserId??input.actorUserId,startedAt:task.startedAt??now,startedByUserId:task.startedByUserId??input.actorUserId,completedAt:now,completedByUserId:input.actorUserId,routeSnapshotJson:JSON.stringify(item.snapshot),version:{increment:1}}});if(changed.count!==1)throw new Error("Work changed. The card has been refreshed.");if(next){if(item.existing)await tx.workTask.update({where:{id:item.existing.id},data:{status:"READY",metadataJson:item.nextMetadata??item.existing.metadataJson,routeSnapshotJson:JSON.stringify(item.snapshot),version:{increment:1}}});else{const max=await tx.workTask.aggregate({where:sourceWhere(task),_max:{sequenceNumber:true}});await tx.workTask.create({data:{accountId:input.selectedAccountId,sourceType:task.sourceType,orderId:task.orderId,consignmentLineId:task.consignmentLineId,stage:next,sequenceNumber:(max._max.sequenceNumber??0)+1,requiredQuantity:task.requiredQuantity,status:"READY",metadataJson:item.nextMetadata,workCardSnapshotJson:task.workCardSnapshotJson,routeSnapshotJson:JSON.stringify(item.snapshot)}});}await tx.workTask.updateMany({where:{accountId:input.selectedAccountId,...sourceWhere(task),id:{not:task.id},stage:{not:next},status:{in:["READY","LOCKED"]}},data:{status:"LOCKED",routeSnapshotJson:JSON.stringify(item.snapshot),version:{increment:1}}});}if(task.sourceType==="ORDER"&&task.orderId){if(task.stage==="PICK")await tx.order.update({where:{id:task.orderId},data:{pickStatus:"PICKED",packStatus:"READY"}});if(task.stage==="PACK")await tx.order.update({where:{id:task.orderId},data:{packStatus:"PACKED",status:"PACKED",packedAt:now}});}if(task.sourceType==="CONSIGNMENT"&&task.stage==="PACK"&&task.consignmentLineId)await tx.consignmentLine.update({where:{id:task.consignmentLineId},data:{completedAt:now,completedByUserId:input.actorUserId}});await tx.workActionLog.create({data:{accountId:input.selectedAccountId,taskId:task.id,actorUserId:input.actorUserId,action:"TASK_COMPLETED",requestKind:"COMPLETE",clientRequestId:input.clientRequestId,quantityBefore:task.completedQuantity,quantityAfter:task.requiredQuantity,metadataJson:JSON.stringify({requestFingerprint,groupKey:card.groupKey,nextStage:next??null})}});}
  await tx.auditLog.create({data:{userId:input.actorUserId,accountId:input.selectedAccountId,action:"WORK_GROUP_COMPLETED_AND_ROUTED",entityType:"WorkGroup",entityId:card.groupKey,metadata:JSON.stringify({sourceType:input.sourceType,stage:input.stage,nextStage:next??null,taskCount:tasks.length})}});await tx.workChangeEvent.create({data:{accountId:input.selectedAccountId,eventType:next?"WORK_ROUTED":"STAGE_COMPLETED",sourceType:input.sourceType,stage:next??input.stage,groupKey:card.groupKey}});return{groupKey:card.groupKey,completedTaskCount:tasks.length,nextStage:next??null,idempotent:false};});}catch(error){last=error;if(!transient(error)||attempt===5)throw transient(error)?new Error("Work is busy; retry the action."):error;await new Promise(resolve=>setTimeout(resolve,20*(attempt+1)));}}
 throw last;
}
