import { createHash } from "node:crypto";
import { Prisma,type PrismaClient,type User,type WorkStage } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { hasWorkPermission } from "@/lib/work-permissions";
import { marketplaceCapabilityEnabled } from "@/src/lib/marketplace-capabilities";
import { parseWorkRouteSnapshot,recommendedNextStage } from "./dynamic-route";
import { assertWorkerAccountAccess } from "./worker-access";

type Client=PrismaClient|Prisma.TransactionClient;
export type GroupedWorkSource="ORDER"|"CONSIGNMENT";
export type GroupedWorkCard={groupKey:string;groupVersion:string;accountId:string;marketplace:string;sourceType:GroupedWorkSource;stage:WorkStage;sourceBatchId:string;sellerSku:string;variantKey:string;instructionHash:string;routeHash:string;assignmentKey:string;assignedUserId:string|null;assignedUserName:string|null;productTitle:string|null;productImageUrl:string|null;operationalIdentifier:string|null;reference:string;memberCount:number;requiredQuantity:number;completedQuantity:number;pendingQuantity:number;problemCount:number;status:string;recommendedNextStage:WorkStage|null;oldestWaitingAt:string;memberTaskIds:string[];detailTaskIds:string[]};
const WORK_INCLUDE=Prisma.validator<Prisma.WorkTaskInclude>()({assignedUser:{select:{name:true}},order:{select:{id:true,batchId:true,marketplace:true,sku:true,color:true,size:true,trackingId:true,awb:true,orderNo:true,productDescription:true,imageUrl:true}},consignmentLine:{select:{id:true,consignmentBatchId:true,sellerSkuSnapshot:true,sellerSkuSource:true,colorSource:true,sizeSource:true,fnskuSnapshot:true,fnskuSource:true,barcodeSnapshot:true,fsnSnapshot:true,listingIdSnapshot:true,productTitleSnapshot:true,productNameSource:true,productImageSnapshot:true,consignmentBatch:{select:{marketplace:true,externalConsignmentNumber:true}}}}});
type GroupTask=Prisma.WorkTaskGetPayload<{include:typeof WORK_INCLUDE}>;
const sha=(value:unknown)=>createHash("sha256").update(typeof value==="string"?value:JSON.stringify(value)).digest("hex");
export function safeWorkSnapshot(value:string|null){try{const parsed=JSON.parse(value??"") as Record<string,unknown>;return parsed&&typeof parsed==="object"?parsed:{};}catch{return{};}}
function visibility(user:User):Prisma.WorkTaskWhereInput{return user.role==="OWNER"||user.canViewAllWork?{}:{OR:[{assignedUserId:null},{assignedUserId:user.id}]};}

export async function getGroupedWork(input:{actorUserId:string;accountId:string;stage:WorkStage;sourceType:GroupedWorkSource;page?:number;pageSize?:number;includeMemberIds?:boolean;targetGroupKey?:string},client:Client=prisma){
 const {user}=await assertWorkerAccountAccess(input.actorUserId,input.accountId,client),account=await client.account.findUniqueOrThrow({where:{id:input.accountId},select:{marketplace:true}}),permission=input.stage==="PICK"?"canPick":input.stage==="MARK"?"canMark":input.stage==="ASSEMBLE"?"canAssemble":"canPack";
 const page=Math.max(1,input.page??1),pageSize=Math.min(Math.max(input.pageSize??25,1),50);if(!hasWorkPermission(user,permission)&&!user.canViewAllWork)throw new Error(`${input.stage} permission is required.`);if(input.sourceType==="ORDER"&&!marketplaceCapabilityEnabled(account.marketplace,"dailyOrders"))return{cards:[],page,pageSize,hasMore:false,user};
 const active=await client.workTask.findMany({where:{accountId:input.accountId,sourceType:input.sourceType,stage:input.stage,status:{in:["READY","IN_PROGRESS","PROBLEM"]},...visibility(user)},include:WORK_INCLUDE,orderBy:[{assignedUserId:"desc"},{createdAt:"asc"},{id:"asc"}],take:pageSize*60});
 const orderBatchIds=[...new Set(active.flatMap(task=>task.order?.batchId?[task.order.batchId]:[]))],consignmentBatchIds=[...new Set(active.flatMap(task=>task.consignmentLine?.consignmentBatchId?[task.consignmentLine.consignmentBatchId]:[]))];
 const completed=active.length?await client.workTask.findMany({where:{accountId:input.accountId,sourceType:input.sourceType,stage:input.stage,status:"COMPLETED",...visibility(user),OR:[...(orderBatchIds.length?[{order:{batchId:{in:orderBatchIds}}}]:[]),...(consignmentBatchIds.length?[{consignmentLine:{consignmentBatchId:{in:consignmentBatchIds}}}]:[])]},include:WORK_INCLUDE,orderBy:[{completedAt:"desc"},{id:"asc"}],take:pageSize*60}):[];
 const tasks=[...new Map([...active,...completed].map(task=>[task.id,task])).values()] as GroupTask[],grouped=new Map<string,{keyParts:string[];displaySku:string;tasks:GroupTask[]}>();
 for(const task of tasks){const source=task.order,line=task.consignmentLine;if(!source&&!line)continue;const snapshot=safeWorkSnapshot(task.workCardSnapshotJson),marketplace=source?.marketplace??line?.consignmentBatch.marketplace??String(account.marketplace),sku=String(snapshot.sellerSku??source?.sku??line?.sellerSkuSnapshot??line?.sellerSkuSource??""),groupingIdentity=input.stage==="PACK"&&source?`PACKAGE:${source.trackingId??source.awb}`:sku,batch=source?.batchId??line?.consignmentBatchId??"unbatched",variant=sha([groupingIdentity,snapshot.variantIdentity??null,source?.color??line?.colorSource??null,source?.size??line?.sizeSource??null]),instruction=input.stage==="PACK"?"PACK":sha(task.metadataJson??""),route=input.stage==="PACK"?"PACK":sha(task.routeSnapshotJson??task.metadataJson??""),assignment=task.assignedUserId??"UNASSIGNED",parts=[input.accountId,marketplace,input.sourceType,input.stage,batch,groupingIdentity,variant,instruction,route,assignment],raw=parts.join("\u0000"),current=grouped.get(raw)??{keyParts:parts,displaySku:sku,tasks:[]};current.tasks.push(task);grouped.set(raw,current);}
 const cards:GroupedWorkCard[]=[];for(const group of grouped.values()){const actionable=group.tasks.filter(task=>task.status!=="PROBLEM"&&task.status!=="COMPLETED");if(!actionable.length)continue;const members=group.tasks.filter(task=>task.status!=="PROBLEM"),first=actionable[0],order=first.order,line=first.consignmentLine,snapshot=safeWorkSnapshot(first.workCardSnapshotJson),routeSnapshot=parseWorkRouteSnapshot(first.routeSnapshotJson),required=members.reduce((sum,task)=>sum+task.requiredQuantity,0),completedQuantity=members.reduce((sum,task)=>sum+task.completedQuantity,0),groupKey=sha(group.keyParts),groupVersion=sha(group.tasks.slice().sort((a,b)=>a.id.localeCompare(b.id)).map(task=>[task.id,task.version,task.status,task.completedQuantity,task.assignedUserId]));cards.push({groupKey,groupVersion,accountId:input.accountId,marketplace:group.keyParts[1],sourceType:input.sourceType,stage:input.stage,sourceBatchId:group.keyParts[4],sellerSku:group.displaySku,variantKey:group.keyParts[6],instructionHash:group.keyParts[7],routeHash:group.keyParts[8],assignmentKey:group.keyParts[9],assignedUserId:first.assignedUserId,assignedUserName:first.assignedUser?.name??null,productTitle:String(snapshot.productTitle??order?.productDescription??line?.productTitleSnapshot??line?.productNameSource??"")||null,productImageUrl:String(snapshot.primaryImage??order?.imageUrl??line?.productImageSnapshot??"")||null,operationalIdentifier:String(snapshot.operationalBarcode??order?.trackingId??order?.awb??line?.fnskuSnapshot??line?.fnskuSource??line?.barcodeSnapshot??line?.fsnSnapshot??line?.listingIdSnapshot??"")||null,reference:order?.trackingId??order?.orderNo??line?.consignmentBatch.externalConsignmentNumber??"",memberCount:group.tasks.length,requiredQuantity:required,completedQuantity,pendingQuantity:required-completedQuantity,problemCount:group.tasks.length-members.length,status:actionable.some(task=>task.status==="IN_PROGRESS")?"IN_PROGRESS":"READY",recommendedNextStage:input.stage==="PACK"?null:routeSnapshot?recommendedNextStage(routeSnapshot,input.stage):"PACK",oldestWaitingAt:actionable.reduce((oldest,task)=>task.createdAt<oldest?task.createdAt:oldest,first.createdAt).toISOString(),memberTaskIds:input.includeMemberIds?actionable.map(task=>task.id):[],detailTaskIds:input.includeMemberIds?group.tasks.map(task=>task.id):[]});}
 cards.sort((a,b)=>(a.assignedUserId===user.id?0:1)-(b.assignedUserId===user.id?0:1)||a.oldestWaitingAt.localeCompare(b.oldestWaitingAt)||a.groupKey.localeCompare(b.groupKey));const start=(page-1)*pageSize,visible=input.targetGroupKey?cards.filter(card=>card.groupKey===input.targetGroupKey):cards.slice(start,start+pageSize);return{cards:visible,page,pageSize,hasMore:!input.targetGroupKey&&cards.length>start+pageSize,user};
}

export async function getSmartStageSummary(input:{actorUserId:string;accountId:string;stage:WorkStage},client:Client=prisma){const [orders,consignments]=await Promise.all([getGroupedWork({...input,sourceType:"ORDER",pageSize:50},client),getGroupedWork({...input,sourceType:"CONSIGNMENT",pageSize:50},client)]),summarize=(cards:GroupedWorkCard[])=>({cardCount:cards.length,itemCount:cards.reduce((sum,card)=>sum+card.memberCount,0),requiredQuantity:cards.reduce((sum,card)=>sum+card.requiredQuantity,0),problems:cards.reduce((sum,card)=>sum+card.problemCount,0),assignedToMe:cards.filter(card=>card.assignedUserId===input.actorUserId).length,oldestWaitingAt:cards[0]?.oldestWaitingAt??null});return{ORDER:summarize(orders.cards),CONSIGNMENT:summarize(consignments.cards)};}
export async function getGroupedWorkDetails(input:{actorUserId:string;accountId:string;stage:WorkStage;sourceType:GroupedWorkSource;groupKey:string},client:Client=prisma){const resolved=await getGroupedWork({...input,pageSize:50,includeMemberIds:true,targetGroupKey:input.groupKey},client),card=resolved.cards[0];if(!card)throw new Error("This work group is no longer available.");const tasks=await client.workTask.findMany({where:{id:{in:card.detailTaskIds},accountId:input.accountId},include:{assignedUser:{select:{id:true,name:true}},order:true,consignmentLine:{include:{consignmentBatch:{select:{displayName:true,externalConsignmentNumber:true,marketplace:true}}}},actionLogs:{include:{actorUser:{select:{name:true}}},orderBy:{createdAt:"desc"},take:20}},orderBy:[{assignedUserId:"desc"},{createdAt:"asc"},{id:"asc"}]});if(tasks.length!==card.detailTaskIds.length)throw new Error("Work changed. Return to the stage queue and refresh.");return{card,tasks:tasks.map(task=>({...task,workCardSnapshot:safeWorkSnapshot(task.workCardSnapshotJson),routeSnapshot:safeWorkSnapshot(task.routeSnapshotJson),instructions:safeWorkSnapshot(task.metadataJson)})),user:resolved.user};}
