import { Prisma, type PrismaClient, type User, type WorkStage } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { hasWorkPermission } from "@/lib/work-permissions";
import { marketplaceCapabilityEnabled } from "@/src/lib/marketplace-capabilities";
import { assertWorkerAccountAccess } from "./worker-access";
import { ensureWorkGroupProjection, safeWorkSnapshot, type ProjectionSource } from "./work-group-projection";
import { parseImmutableRouteProvenance } from "./route-provenance";

type Client=PrismaClient|Prisma.TransactionClient;
export type GroupedWorkSource=ProjectionSource;
export type GroupedWorkCard={groupKey:string;groupVersion:string;accountId:string;marketplace:string;sourceType:GroupedWorkSource;stage:WorkStage;sourceBatchId:string;sellerSku:string;variantKey:string;instructionHash:string;routeHash:string;assignmentKey:string;assignedUserId:string|null;assignedUserName:string|null;productTitle:string|null;productImageUrl:string|null;operationalIdentifier:string|null;reference:string;memberCount:number;requiredQuantity:number;completedQuantity:number;completeMemberCount:number;partialMemberCount:number;pendingQuantity:number;problemCount:number;status:string;recommendedNextStage:WorkStage|null;hasExplicitSavedRoute:boolean;savedProcessRoute:string|null;missingInstructionStages:WorkStage[];oldestWaitingAt:string;memberTaskIds:string[];detailTaskIds:string[]};

function permission(stage:WorkStage){return stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack";}
function visibility(user:User):Prisma.WorkGroupProjectionWhereInput{return user.role==="OWNER"||user.canViewAllWork?{}:{OR:[{assignedUserId:null},{assignedUserId:user.id}]};}
function card(row:Prisma.WorkGroupProjectionGetPayload<Record<string,never>>,ids:{actionable:string[];all:string[]}={actionable:[],all:[]},missingInstructionStages:WorkStage[]=[]):GroupedWorkCard{return{groupKey:row.groupKey,groupVersion:row.groupVersion,accountId:row.accountId,marketplace:row.marketplace,sourceType:row.sourceType,stage:row.stage,sourceBatchId:row.sourceBatchId,sellerSku:row.sellerSku,variantKey:row.variantHash,instructionHash:row.instructionHash,routeHash:row.routeHash,assignmentKey:row.assignmentKey,assignedUserId:row.assignedUserId,assignedUserName:row.assignedUserName,productTitle:row.productTitle,productImageUrl:row.productImageUrl,operationalIdentifier:row.operationalIdentifier,reference:row.reference,memberCount:row.memberCount,requiredQuantity:row.requiredQuantity,completedQuantity:row.completedQuantity,completeMemberCount:row.completeMemberCount,partialMemberCount:row.partialMemberCount,pendingQuantity:row.requiredQuantity-row.completedQuantity,problemCount:row.problemCount,status:row.status,recommendedNextStage:row.recommendedNextStage,hasExplicitSavedRoute:row.hasExplicitSavedRoute,savedProcessRoute:row.savedProcessRoute,missingInstructionStages,oldestWaitingAt:row.oldestWaitingAt.toISOString(),memberTaskIds:ids.actionable,detailTaskIds:ids.all};}

export async function getGroupedWork(input:{actorUserId:string;accountId:string;stage:WorkStage;sourceType:GroupedWorkSource;page?:number;pageSize?:number;includeMemberIds?:boolean;targetGroupKey?:string},client:Client=prisma){
 const {user}=await assertWorkerAccountAccess(input.actorUserId,input.accountId,client),account=await client.account.findUniqueOrThrow({where:{id:input.accountId},select:{marketplace:true}}),page=Math.max(1,input.page??1),pageSize=Math.min(Math.max(input.pageSize??25,1),50);
 if(!hasWorkPermission(user,permission(input.stage))&&!user.canViewAllWork)throw new Error(`${input.stage} permission is required.`);if(input.sourceType==="ORDER"&&!marketplaceCapabilityEnabled(account.marketplace,"dailyOrders"))return{cards:[],page,pageSize,hasMore:false,user};
 await ensureWorkGroupProjection({accountId:input.accountId,sourceType:input.sourceType,stage:input.stage},client);
 const base:Prisma.WorkGroupProjectionWhereInput={accountId:input.accountId,sourceType:input.sourceType,stage:input.stage,...visibility(user)};
 let rows;if(input.targetGroupKey){rows=await client.workGroupProjection.findMany({where:{...base,groupKey:input.targetGroupKey}});}else{const assignedWhere={...base,assignedUserId:user.id},otherWhere:Prisma.WorkGroupProjectionWhereInput={...base,OR:user.role==="OWNER"||user.canViewAllWork?[{assignedUserId:null},{assignedUserId:{not:user.id}}]:[{assignedUserId:null}]},skip=(page-1)*pageSize,assignedCount=await client.workGroupProjection.count({where:assignedWhere});const assigned=skip<assignedCount?await client.workGroupProjection.findMany({where:assignedWhere,orderBy:[{oldestWaitingAt:"asc"},{groupKey:"asc"}],skip,take:pageSize}):[],remaining=pageSize-assigned.length,otherSkip=Math.max(0,skip-assignedCount),other=remaining?await client.workGroupProjection.findMany({where:otherWhere,orderBy:[{oldestWaitingAt:"asc"},{groupKey:"asc"}],skip:otherSkip,take:remaining}):[];rows=[...assigned,...other];}
 const cards:GroupedWorkCard[]=[];for(const row of rows){let ids={actionable:[] as string[],all:[] as string[]};const memberships=await client.workGroupMember.findMany({where:{groupKey:row.groupKey},include:{task:{select:{id:true,status:true,workCardSnapshotJson:true,routeSnapshotJson:true}}},orderBy:{taskId:"asc"},take:input.includeMemberIds?undefined:1});if(input.includeMemberIds)ids={all:memberships.map(item=>item.taskId),actionable:memberships.filter(item=>item.task.status!=="PROBLEM"&&item.task.status!=="COMPLETED").map(item=>item.taskId)};const representative=memberships[0]?.task,provenance=parseImmutableRouteProvenance(representative?.workCardSnapshotJson)??parseImmutableRouteProvenance(representative?.routeSnapshotJson),missing:WorkStage[]=[];if(!provenance?.markingInstructionSnapshot)missing.push("MARK");if(!provenance?.assemblyInstructionSnapshot)missing.push("ASSEMBLE");cards.push(card(row,ids,missing));}
 const total=await client.workGroupProjection.count({where:base});return{cards,page,pageSize,hasMore:!input.targetGroupKey&&total>page*pageSize,user};
}

export async function getSmartStageSummary(input:{actorUserId:string;accountId:string;stage:WorkStage},client:Client=prisma){const {user}=await assertWorkerAccountAccess(input.actorUserId,input.accountId,client);if(!hasWorkPermission(user,permission(input.stage))&&!user.canViewAllWork)throw new Error(`${input.stage} permission is required.`);const summarize=async(sourceType:GroupedWorkSource)=>{await ensureWorkGroupProjection({accountId:input.accountId,sourceType,stage:input.stage},client);const where={accountId:input.accountId,sourceType,stage:input.stage,...visibility(user)},[aggregate,assigned]=await Promise.all([client.workGroupProjection.aggregate({where,_count:{_all:true},_sum:{memberCount:true,requiredQuantity:true,problemCount:true},_min:{oldestWaitingAt:true}}),client.workGroupProjection.count({where:{...where,assignedUserId:input.actorUserId}})]);return{cardCount:aggregate._count._all,itemCount:aggregate._sum.memberCount??0,requiredQuantity:aggregate._sum.requiredQuantity??0,problems:aggregate._sum.problemCount??0,assignedToMe:assigned,oldestWaitingAt:aggregate._min.oldestWaitingAt?.toISOString()??null};};const [ORDER,CONSIGNMENT]=await Promise.all([summarize("ORDER"),summarize("CONSIGNMENT")]);return{ORDER,CONSIGNMENT};}

export async function getGroupedWorkDetails(input:{actorUserId:string;accountId:string;stage:WorkStage;sourceType:GroupedWorkSource;groupKey:string},client:Client=prisma){const resolved=await getGroupedWork({...input,pageSize:50,includeMemberIds:true,targetGroupKey:input.groupKey},client),selected=resolved.cards[0];if(!selected)throw new Error("This work group is no longer available.");const tasks=await client.workTask.findMany({where:{id:{in:selected.detailTaskIds},accountId:input.accountId},include:{assignedUser:{select:{id:true,name:true}},order:true,consignmentLine:{include:{consignmentBatch:{select:{displayName:true,externalConsignmentNumber:true,marketplace:true}}}},actionLogs:{include:{actorUser:{select:{name:true}}},orderBy:{createdAt:"desc"},take:20}},orderBy:[{assignedUserId:"desc"},{createdAt:"asc"},{id:"asc"}]});if(tasks.length!==selected.detailTaskIds.length)throw new Error("Work changed. Return to the stage queue and refresh.");return{card:selected,tasks:tasks.map(task=>({...task,workCardSnapshot:safeWorkSnapshot(task.workCardSnapshotJson),routeSnapshot:safeWorkSnapshot(task.routeSnapshotJson),instructions:safeWorkSnapshot(task.metadataJson)})),user:resolved.user};}
