import { Prisma, type PrismaClient, type ProcessRoute, type WorkStage } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { userCanMutateStage, assertWorkerAccountAccess } from "./worker-access";
import { assertValidStageTransition, createWorkRouteSnapshot, parseWorkRouteSnapshot, recommendedNextStage, routeFingerprint, type WorkRouteDecisionReason } from "./dynamic-route";
import { resolveRouteStageMetadata, type PostPickRoute } from "./route-selection";

type Client = PrismaClient;
type Tx = Prisma.TransactionClient;
const PROCESS_TO_CHOICE: Record<ProcessRoute, PostPickRoute> = { PICK_PACK:"DIRECT_PACK", PICK_MARK_PACK:"MARK", PICK_ASSEMBLE_PACK:"ASSEMBLE", PICK_MARK_ASSEMBLE_PACK:"MARK_ASSEMBLE" };

function sourceWhere(task:{sourceType:"ORDER"|"CONSIGNMENT";orderId:string|null;consignmentLineId:string|null}) { return task.sourceType === "ORDER" ? { orderId: task.orderId! } : { consignmentLineId: task.consignmentLineId! }; }
function processRouteFromMetadata(value:string|null) { try { const parsed=JSON.parse(value??"") as {processRoute?:ProcessRoute}; return parsed.processRoute??null; } catch { return null; } }
function transient(error:unknown){const message=error instanceof Error?error.message:String(error);return error instanceof Prisma.PrismaClientKnownRequestError&&["P1008","P2002","P2028","P2034"].includes(error.code)||/database is locked|write conflict|transaction.*(?:closed|conflict|timeout)/i.test(message);}

async function replay(tx:Tx,input:{taskId:string;actorUserId:string;clientRequestId?:string;fingerprint:string}){if(!input.clientRequestId)return null;const log=await tx.workActionLog.findFirst({where:{taskId:input.taskId,clientRequestId:input.clientRequestId},orderBy:{createdAt:"asc"}});if(!log)return null;if(log.actorUserId!==input.actorUserId||log.requestKind!=="COMPLETE"||log.action!=="TASK_COMPLETED")throw new Error("Request ID was already used for a different actor or action.");const metadata=log.metadataJson?JSON.parse(log.metadataJson) as {requestFingerprint?:string,newVersion?:number,nextStage?:WorkStage}:{};if(metadata.requestFingerprint!==input.fingerprint)throw new Error("Request ID was already used with a different route decision.");return{taskId:input.taskId,nextStage:metadata.nextStage??null,version:metadata.newVersion??0,idempotent:true};}

async function recover<T>(input:{clientRequestId?:string;mutate:()=>Promise<T>;replay:()=>Promise<T|null>}){let last:unknown;for(let attempt=0;attempt<6;attempt++){try{return await input.mutate();}catch(error){last=error;if(!input.clientRequestId)throw error;const prior=await input.replay();if(prior)return prior;if(!transient(error))throw error;if(attempt<5)await new Promise(resolve=>setTimeout(resolve,20*(attempt+1)));}}if(transient(last))throw new Error("Work is busy; retry the action.");throw last;}

function routeChoice(processRoute:ProcessRoute|null,next:WorkStage){if(processRoute)return PROCESS_TO_CHOICE[processRoute];return next==="MARK"?"MARK":next==="ASSEMBLE"?"ASSEMBLE":"DIRECT_PACK";}

export async function completeStageAndChooseNext(input:{actorUserId:string;selectedAccountId:string;taskId:string;currentStage:WorkStage;expectedVersion:number;expectedCompletedQuantity:number;nextStage?:WorkStage;useRecommendedNextStage?:boolean;reason?:WorkRouteDecisionReason;clientRequestId:string},client:Client=prisma){
 const fingerprint=routeFingerprint({taskId:input.taskId,currentStage:input.currentStage,expectedVersion:input.expectedVersion,expectedCompletedQuantity:input.expectedCompletedQuantity,nextStage:input.nextStage??null,useRecommendedNextStage:Boolean(input.useRecommendedNextStage),reason:input.reason??null});
 return recover({clientRequestId:input.clientRequestId,mutate:()=>client.$transaction(async tx=>{
  const {user}=await assertWorkerAccountAccess(input.actorUserId,input.selectedAccountId,tx);if(!userCanMutateStage(user,input.currentStage))throw new Error(`${input.currentStage} permission is required.`);
  const task=await tx.workTask.findFirst({where:{id:input.taskId,accountId:input.selectedAccountId,stage:input.currentStage},include:{consignmentLine:{select:{accountId:true,processRoute:true}},order:{select:{accountId:true,pickStatus:true,packStatus:true}}}});if(!task||(task.order?.accountId??task.consignmentLine?.accountId)!==input.selectedAccountId)throw new Error("Work is unavailable in the selected account.");
  const prior=await replay(tx,{taskId:task.id,actorUserId:user.id,clientRequestId:input.clientRequestId,fingerprint});if(prior)return prior;if(task.version!==input.expectedVersion||task.completedQuantity!==input.expectedCompletedQuantity)throw new Error("Work changed. The card has been refreshed.");if(!["READY","IN_PROGRESS"].includes(task.status))throw new Error("This stage is no longer actionable.");if(task.assignedUserId&&task.assignedUserId!==user.id&&user.role!=="OWNER")throw new Error("This work was taken by another worker.");
  const processRoute=processRouteFromMetadata(task.metadataJson)??task.consignmentLine?.processRoute??null;const snapshot=parseWorkRouteSnapshot(task.routeSnapshotJson)??createWorkRouteSnapshot({processRoute,currentStage:task.stage,routeVersion:task.version});if(snapshot.currentStage!==input.currentStage)throw new Error("Work changed. The card has been refreshed.");
  if(input.currentStage==="PACK"&&input.nextStage)throw new Error("Packing is final and cannot route work backwards.");const next=input.currentStage==="PACK"?undefined:input.useRecommendedNextStage?recommendedNextStage(snapshot,input.currentStage):input.nextStage;assertValidStageTransition(snapshot,input.currentStage,next);
  const all=await tx.workTask.findMany({where:{accountId:input.selectedAccountId,...sourceWhere(task)},orderBy:[{sequenceNumber:"asc"},{id:"asc"}]});if(all.some(item=>item.stage!==task.stage&&item.status==="IN_PROGRESS"))throw new Error("Downstream work has already started and cannot be rerouted.");
  let nextMetadata:string|null=null;if(next==="MARK"||next==="ASSEMBLE"){const choice=routeChoice(processRoute,next);const sourceId=task.sourceType==="ORDER"?task.orderId!:task.consignmentLineId!;const metadata=await resolveRouteStageMetadata(tx,{accountId:input.selectedAccountId,actorUserId:user.id,sourceType:task.sourceType,sourceId,route:choice,requestFingerprint:fingerprint});nextMetadata=metadata.get(next)??null;if(!nextMetadata)throw new Error(next==="MARK"?"Marking instructions need owner review.":"Assembly instructions need owner review.");}
  const now=new Date();const changed=await tx.workTask.updateMany({where:{id:task.id,version:task.version,status:task.status,completedQuantity:task.completedQuantity,assignedUserId:task.assignedUserId},data:{completedQuantity:task.requiredQuantity,status:"COMPLETED",assignedUserId:task.assignedUserId??user.id,startedAt:task.startedAt??now,startedByUserId:task.startedByUserId??user.id,completedAt:now,completedByUserId:user.id,version:{increment:1}}});if(changed.count!==1)throw new Error("Work changed. The card has been refreshed.");
  const nextSnapshot={...snapshot,routeVersion:snapshot.routeVersion+1,currentStage:next??input.currentStage,selectedNextStage:next,actualStages:next?[...snapshot.actualStages,next]:snapshot.actualStages,completedStages:[...new Set([...snapshot.completedStages,input.currentStage])],decisions:next?[...snapshot.decisions,{fromStage:input.currentStage,toStage:next,actorUserId:user.id,decidedAt:now.toISOString(),reason:input.reason??(input.useRecommendedNextStage?"DEFAULT":"WORKER_SELECTION") as WorkRouteDecisionReason}]:snapshot.decisions};
  if(next){const existing=all.find(item=>item.stage===next);if(existing?.status==="COMPLETED")throw new Error(`${next} was already completed.`);if(existing){await tx.workTask.update({where:{id:existing.id},data:{status:"READY",metadataJson:nextMetadata??existing.metadataJson,routeSnapshotJson:JSON.stringify(nextSnapshot),version:{increment:1}}});}else{await tx.workTask.create({data:{accountId:input.selectedAccountId,sourceType:task.sourceType,orderId:task.orderId,consignmentLineId:task.consignmentLineId,stage:next,sequenceNumber:Math.max(...all.map(item=>item.sequenceNumber),0)+1,requiredQuantity:task.requiredQuantity,status:"READY",metadataJson:nextMetadata,workCardSnapshotJson:task.workCardSnapshotJson,routeSnapshotJson:JSON.stringify(nextSnapshot)}});}await tx.workTask.updateMany({where:{accountId:input.selectedAccountId,...sourceWhere(task),id:{not:task.id},stage:{not:next},status:{in:["READY","LOCKED"]}},data:{status:"LOCKED",routeSnapshotJson:JSON.stringify(nextSnapshot),version:{increment:1}}});}
  await tx.workTask.update({where:{id:task.id},data:{routeSnapshotJson:JSON.stringify(nextSnapshot)}});if(task.sourceType==="ORDER"&&task.orderId){if(task.stage==="PICK")await tx.order.update({where:{id:task.orderId},data:{pickStatus:"PICKED",packStatus:"READY"}});if(task.stage==="PACK")await tx.order.update({where:{id:task.orderId},data:{packStatus:"PACKED",status:"PACKED",packedAt:now}});}if(task.sourceType==="CONSIGNMENT"&&task.stage==="PACK"&&task.consignmentLineId)await tx.consignmentLine.update({where:{id:task.consignmentLineId},data:{completedAt:now,completedByUserId:user.id}});
  await tx.workActionLog.create({data:{accountId:input.selectedAccountId,taskId:task.id,actorUserId:user.id,action:"TASK_COMPLETED",requestKind:"COMPLETE",clientRequestId:input.clientRequestId,quantityBefore:task.completedQuantity,quantityAfter:task.requiredQuantity,metadataJson:JSON.stringify({requestFingerprint:fingerprint,newVersion:task.version+1,nextStage:next??null})}});await tx.auditLog.create({data:{userId:user.id,accountId:input.selectedAccountId,action:"WORK_STAGE_COMPLETED_AND_ROUTED",entityType:"WorkTask",entityId:task.id,metadata:JSON.stringify({fromStage:task.stage,toStage:next??null,reason:input.reason??(input.useRecommendedNextStage?"DEFAULT":"WORKER_SELECTION")})}});await tx.workChangeEvent.create({data:{accountId:input.selectedAccountId,eventType:"STAGE_COMPLETED",sourceType:task.sourceType,stage:task.stage,entityId:task.id}});if(next)await tx.workChangeEvent.create({data:{accountId:input.selectedAccountId,eventType:"WORK_ROUTED",sourceType:task.sourceType,stage:next,entityId:task.id}});return{taskId:task.id,nextStage:next??null,version:task.version+1,idempotent:false};
 }),replay:()=>client.$transaction(async tx=>{await assertWorkerAccountAccess(input.actorUserId,input.selectedAccountId,tx);return replay(tx,{taskId:input.taskId,actorUserId:input.actorUserId,clientRequestId:input.clientRequestId,fingerprint});})});
}
