import { performance } from "node:perf_hooks";
import type { Prisma, PrismaClient, WorkStage } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { hasWorkPermission } from "@/lib/work-permissions";
import { normalizeListingIdentifier } from "@/src/lib/marking/identifiers";
import { getWorkTaskCapabilities, userCanViewAllConsignmentWork } from "./worker-access";

type Client=PrismaClient|Prisma.TransactionClient;
export type UniversalScanIntent="ANY"|"PICK"|"MARK"|"PACK";
export type UniversalWorkCandidate={candidateKey:string;sourceType:"CUSTOMER_ORDER"|"CONSIGNMENT_TASK";actionType:"ORDER_PICK"|"ORDER_PACK"|"CONSIGNMENT_PICK"|"CONSIGNMENT_MARK"|"CONSIGNMENT_PACK"|"PROBLEM"|"READ_ONLY";sourceId:string;taskId?:string;orderId?:string;consignmentLineId?:string;accountId:string;accountName:string;marketplace:string;matchType:string;matchedIdentifierMasked?:string;productTitle:string|null;productImageUrl:string|null;sellerSku:string|null;awb?:string|null;trackingId?:string|null;orderNumber?:string|null;fsn?:string|null;listingId?:string|null;asin?:string|null;fnsku?:string|null;stage?:WorkStage;status:string;requiredQuantity:number;completedQuantity:number;remainingQuantity:number;assignedUserId?:string|null;assignedUserName?:string|null;markingFileAvailable?:boolean;canAct:boolean;readOnlyReason?:string|null};

const IDENTIFIER_TYPES=["SELLER_SKU","INTERNAL_SKU","FSN","LISTING_ID","LID","ASIN","FNSKU","EAN","UPC","GTIN","BARCODE","EXTERNAL_ID"] as const;

export function normalizeUniversalScanCode(value:string){const normalized=value.normalize("NFKC").trim();if(!normalized)throw new Error("Enter or scan a code.");if(normalized.length>160||/[\u0000-\u001F\u007F]/.test(normalized))throw new Error("Scanned code is invalid.");return normalized;}
function mask(value:string){return value.length<=4?value:`...${value.slice(-4)}`;}

export async function getAuthorizedWorkAccounts(actorUserId:string,client:Client=prisma){const user=await client.user.findUnique({where:{id:actorUserId},include:{assignedAccounts:{where:{active:true},select:{id:true,name:true,accountDisplayName:true,marketplace:true,active:true}},account:{select:{id:true,name:true,accountDisplayName:true,marketplace:true,active:true}}}});if(!user?.active)throw new Error("Worker account is unavailable.");const accounts=user.role==="OWNER"?await client.account.findMany({where:{active:true},select:{id:true,name:true,accountDisplayName:true,marketplace:true,active:true},orderBy:[{marketplace:"asc"},{name:"asc"}]}):[...user.assignedAccounts,...(user.account?.active?[user.account]:[])];return{user,accounts:[...new Map(accounts.map((account)=>[account.id,account])).values()]};}

function orderMatchType(order:{awb:string;trackingId:string|null;orderNo:string;shipmentId:string|null;orderItemId:string|null;sku:string},code:string){const upper=code.toUpperCase();if(order.awb.toUpperCase()===upper)return"AWB";if(order.trackingId?.toUpperCase()===upper)return"TRACKING_ID";if(order.orderNo.toUpperCase()===upper)return"ORDER_NUMBER";if(order.shipmentId?.toUpperCase()===upper)return"SHIPMENT_ID";if(order.orderItemId?.toUpperCase()===upper)return"ORDER_ITEM_ID";return order.sku.toUpperCase()===upper?"SELLER_SKU":"EXACT";}
function taskAction(stage:WorkStage,status:string){if(status==="PROBLEM")return"PROBLEM" as const;if(stage==="PICK")return"CONSIGNMENT_PICK" as const;if(stage==="MARK")return"CONSIGNMENT_MARK" as const;if(stage==="PACK")return"CONSIGNMENT_PACK" as const;return"READ_ONLY" as const;}
const MATCH_PRIORITY=["AWB","TRACKING_ID","FNSKU","SELLER_SKU","FSN","ASIN","LISTING_ID","LID","EAN","UPC","GTIN","BARCODE","ORDER_NUMBER","SHIPMENT_ID","ORDER_ITEM_ID","WORK_TASK_ID"];
function matchRank(matchType:string){const index=MATCH_PRIORITY.indexOf(matchType);return index<0?MATCH_PRIORITY.length:index;}

export async function resolveUniversalWork(input:{actorUserId:string;code:string;accountId?:string;intent?:UniversalScanIntent;includeCompleted?:boolean;limit?:number},client:Client=prisma){const started=performance.now();const code=normalizeUniversalScanCode(input.code);const intent=input.intent??"ANY";const limit=Math.min(Math.max(input.limit??25,1),50);const scope=await getAuthorizedWorkAccounts(input.actorUserId,client);let accounts=scope.accounts;if(input.accountId){if(!accounts.some((account)=>account.id===input.accountId))throw new Error("Selected account is outside your work access.");accounts=accounts.filter((account)=>account.id===input.accountId);}const accountIds=accounts.map((account)=>account.id);if(!accountIds.length)return{normalizedInput:code,searchedAccountCount:0,exactMatch:true,candidates:[],completedMatchCount:0,durationMs:Math.round(performance.now()-started)};const accountMap=new Map(accounts.map((account)=>[account.id,account]));const upper=code.toUpperCase();const orderWhere:Prisma.OrderWhereInput={accountId:{in:accountIds},OR:[{awb:code},{awb:upper},{trackingId:code},{trackingId:upper},{orderNo:code},{orderNo:upper},{shipmentId:code},{shipmentId:upper},{orderItemId:code},{orderItemId:upper},{sku:code},{sku:upper}]};const normalizedOr=IDENTIFIER_TYPES.flatMap((identifierType)=>{const normalizedValue=normalizeListingIdentifier(identifierType,code);return normalizedValue?[{identifierType,normalizedValue}]:[];});
 const [orders,identifierRows]=await Promise.all([client.order.findMany({where:{...orderWhere,packStatus:{not:"PACKED"}},select:{id:true,accountId:true,marketplace:true,shipmentId:true,orderItemId:true,fsn:true,trackingId:true,awb:true,sku:true,qty:true,orderNo:true,productDescription:true,imageUrl:true,pickStatus:true,packStatus:true,status:true},take:limit*4,orderBy:{importedAt:"desc"}}),client.marketplaceListingIdentifier.findMany({where:{accountId:{in:accountIds},active:true,OR:normalizedOr},select:{marketplaceListingId:true,identifierType:true,normalizedValue:true},take:limit*8})]);
 const listingIds=[...new Set(identifierRows.map((row)=>row.marketplaceListingId))];const taskLineMatch:Prisma.ConsignmentLineWhereInput={completedAt:null,consignmentBatch:{status:{in:["ACTIVE","PROBLEM"]}},OR:[...(listingIds.length?[{marketplaceListingId:{in:listingIds}}]:[]),{sellerSkuSnapshot:{equals:code}},{sellerSkuSnapshot:{equals:upper}},{fsnSnapshot:{equals:code}},{fsnSnapshot:{equals:upper}},{listingIdSnapshot:{equals:code}},{listingIdSnapshot:{equals:upper}},{consignmentBatch:{externalConsignmentNumber:{equals:code}}}]};const taskWhere:Prisma.WorkTaskWhereInput={accountId:{in:accountIds},sourceType:"CONSIGNMENT",stage:intent==="ANY"?{in:["PICK","MARK","PACK"]}:intent,status:{in:["READY","IN_PROGRESS","PROBLEM"]},OR:[{id:code},{consignmentLine:taskLineMatch}]};
 const tasks=await client.workTask.findMany({where:taskWhere,select:{id:true,accountId:true,stage:true,status:true,requiredQuantity:true,completedQuantity:true,assignedUserId:true,assignedUser:{select:{name:true}},problemReportedByUserId:true,consignmentLine:{select:{id:true,marketplaceListingId:true,sellerSkuSnapshot:true,sellerSkuSource:true,fsnSnapshot:true,fsnSource:true,listingIdSnapshot:true,productTitleSnapshot:true,productNameSource:true,productImageSnapshot:true,markingAsset:{select:{files:{where:{attachmentType:"MARKING_FILE",activeVersion:true},take:1,select:{id:true}}}},consignmentBatch:{select:{externalConsignmentNumber:true}}}}},take:limit*4,orderBy:[{status:"asc"},{updatedAt:"asc"}]});
 const candidates:UniversalWorkCandidate[]=[];const canSeeProblems=scope.user.role==="OWNER"||hasWorkPermission(scope.user,"canReportProblem")||hasWorkPermission(scope.user,"canManageConsignments")||hasWorkPermission(scope.user,"canViewAllWork");for(const order of orders){const account=accountMap.get(order.accountId);if(!account)continue;const wantsPick=intent==="ANY"||intent==="PICK";const wantsPack=intent==="ANY"||intent==="PACK";const common={sourceType:"CUSTOMER_ORDER" as const,sourceId:order.id,orderId:order.id,accountId:order.accountId,accountName:account.accountDisplayName??account.name,marketplace:order.marketplace,matchType:orderMatchType(order,code),matchedIdentifierMasked:mask(code),productTitle:order.productDescription,productImageUrl:order.imageUrl,sellerSku:order.sku,awb:order.awb,trackingId:order.trackingId,orderNumber:order.orderNo,fsn:order.fsn,requiredQuantity:order.qty,completedQuantity:0,remainingQuantity:order.qty};if(intent!=="MARK"&&(order.status==="PROBLEM"||order.pickStatus==="PROBLEM"||order.packStatus==="PROBLEM")&&canSeeProblems)candidates.push({...common,candidateKey:`order:${order.id}:problem`,actionType:"PROBLEM",status:"PROBLEM",canAct:false,readOnlyReason:"Problem requires review."});else{if(wantsPick&&order.pickStatus==="READY"&&order.packStatus!=="PACKED"&&hasWorkPermission(scope.user,"canPick"))candidates.push({...common,candidateKey:`order:${order.id}:pick`,actionType:"ORDER_PICK",status:order.pickStatus,canAct:true});if(wantsPack&&order.packStatus==="READY"&&order.pickStatus==="PICKED"&&hasWorkPermission(scope.user,"canPack"))candidates.push({...common,candidateKey:`order:${order.id}:pack`,actionType:"ORDER_PACK",status:order.packStatus,canAct:true});}}
 for(const task of tasks){const line=task.consignmentLine,account=accountMap.get(task.accountId);if(!line||!account)continue;const visibleProblem=task.status!=="PROBLEM"||userCanViewAllConsignmentWork(scope.user)||task.assignedUserId===scope.user.id||task.problemReportedByUserId===scope.user.id;if(!visibleProblem)continue;const caps=getWorkTaskCapabilities(scope.user,task);const canAct=task.status==="PROBLEM"?false:caps.canProgress;candidates.push({candidateKey:`task:${task.id}`,sourceType:"CONSIGNMENT_TASK",actionType:canAct?taskAction(task.stage,task.status):task.status==="PROBLEM"?"PROBLEM":"READ_ONLY",sourceId:task.id,taskId:task.id,consignmentLineId:line.id,accountId:task.accountId,accountName:account.accountDisplayName??account.name,marketplace:String(account.marketplace),matchType:task.id===code?"WORK_TASK_ID":listingIds.includes(line.marketplaceListingId??"")?identifierRows.find((row)=>row.marketplaceListingId===line.marketplaceListingId)?.identifierType??"EXACT_IDENTIFIER":"SNAPSHOT_OR_CONSIGNMENT",matchedIdentifierMasked:mask(code),productTitle:line.productTitleSnapshot??line.productNameSource,productImageUrl:line.productImageSnapshot,sellerSku:line.sellerSkuSnapshot??line.sellerSkuSource,fsn:line.fsnSnapshot??line.fsnSource,listingId:line.listingIdSnapshot,stage:task.stage,status:task.status,requiredQuantity:task.requiredQuantity,completedQuantity:task.completedQuantity,remainingQuantity:task.requiredQuantity-task.completedQuantity,assignedUserId:task.assignedUserId,assignedUserName:task.assignedUser?.name,markingFileAvailable:task.stage==="MARK"?Boolean(line.markingAsset?.files.length):undefined,canAct,readOnlyReason:canAct?null:task.status==="PROBLEM"?"Problem requires review.":"Task is assigned to another worker or you lack stage permission."});}
 const completedOrders=await client.order.count({where:{...orderWhere,packStatus:"PACKED"}});const completedTasks=await client.workTask.count({where:{accountId:{in:accountIds},sourceType:"CONSIGNMENT",status:"COMPLETED",stage:intent==="ANY"?{in:["PICK","MARK","PACK"]}:intent,OR:[{id:code},{consignmentLine:{OR:[...(listingIds.length?[{marketplaceListingId:{in:listingIds}}]:[]),{sellerSkuSnapshot:{in:[code,upper]}},{fsnSnapshot:{in:[code,upper]}},{listingIdSnapshot:{in:[code,upper]}},{consignmentBatch:{externalConsignmentNumber:code}}]}}]}});const rank=(candidate:UniversalWorkCandidate)=>[candidate.canAct?0:1,candidate.assignedUserId===scope.user.id?0:1,String(matchRank(candidate.matchType)).padStart(2,"0"),candidate.status==="READY"?0:1,candidate.candidateKey].join("|");candidates.sort((a,b)=>rank(a).localeCompare(rank(b)));return{normalizedInput:code,searchedAccountCount:accounts.length,exactMatch:true,candidates:candidates.slice(0,limit),completedMatchCount:completedOrders+completedTasks,durationMs:Math.round(performance.now()-started)};}
