ALTER TABLE "ImportJob" ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'QUEUED';
ALTER TABLE "ImportJob" ADD COLUMN "currentFile" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "totalFiles" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ImportJob" ADD COLUMN "processedFiles" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ImportJob" ADD COLUMN "manifestJson" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "progressJson" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "reportJson" TEXT;
ALTER TABLE "ImportJob" ADD COLUMN "cancelRequestedAt" TIMESTAMP(3);
ALTER TABLE "ImportJob" ADD COLUMN "mergeStartedAt" TIMESTAMP(3);
