import { randomUUID } from "node:crypto";
import type { Marketplace,MarketplaceImportPurpose } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export async function pauseConsignmentForHeaderMapping(input:{batchId:string;accountId:string;actorUserId:string;marketplace:Marketplace;purpose:MarketplaceImportPurpose;fileName:string;mappingRequest:{headers:string[];fingerprint:string;requiredFields:string[];optionalFields:string[]}}){
  const importType=`${input.marketplace}_${input.purpose}`;let job=await prisma.importJob.findFirst({where:{accountId:input.accountId,batchId:input.batchId,importType,status:"NEEDS_MAPPING"},orderBy:{createdAt:"desc"}});if(job)job=await prisma.importJob.update({where:{id:job.id},data:{progressJson:JSON.stringify(input.mappingRequest),lastError:"Owner header mapping is required."}});else job=await prisma.importJob.create({data:{id:`job_${randomUUID()}`,accountId:input.accountId,createdByUserId:input.actorUserId,marketplace:input.marketplace,importType,fileName:input.fileName,batchId:input.batchId,status:"NEEDS_MAPPING",stage:"NEEDS_MAPPING",progressJson:JSON.stringify(input.mappingRequest),lastError:"Owner header mapping is required."}});
  await prisma.$transaction([prisma.consignmentImportIssue.deleteMany({where:{consignmentBatchId:input.batchId,issueType:"HEADER_MAPPING_REQUIRED"}}),prisma.consignmentImportIssue.create({data:{consignmentBatchId:input.batchId,issueType:"HEADER_MAPPING_REQUIRED",severity:"ERROR",message:"Owner header mapping is required. The retained upload can be retried without re-uploading."}}),prisma.consignmentBatch.update({where:{id:input.batchId},data:{status:"REVIEW_REQUIRED"}})]);return job;
}

export async function completeConsignmentHeaderMapping(input:{batchId:string;profileId:string|null}){await prisma.importJob.updateMany({where:{batchId:input.batchId,status:{in:["NEEDS_MAPPING","QUEUED","RUNNING"]},importType:{contains:"CONSIGNMENT"}},data:{status:"COMPLETED",stage:"COMPLETED",lastError:null,progressJson:JSON.stringify({profileId:input.profileId,reused:Boolean(input.profileId)}),finishedAt:new Date()}});await prisma.consignmentImportIssue.deleteMany({where:{consignmentBatchId:input.batchId,issueType:"HEADER_MAPPING_REQUIRED"}});}
