import { readFile } from "node:fs/promises";
import type { User } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { sanitizeImportJobError } from "@/src/lib/import-jobs/safe-error";
import { resolveExistingConsignmentPath } from "./storage";
import { importFlipkartConsignmentDraft } from "./import-service";
import { importAmazonConsignmentDraft } from "./amazon/import-service";

export async function resumeMappedConsignmentImport(input:{jobId:string;accountId:string;user:Pick<User,"id">}){
 const job=await prisma.importJob.findFirst({where:{id:input.jobId,accountId:input.accountId,batchId:{not:null}}});if(!job?.batchId)throw new Error("Mapped consignment import is unavailable.");const batch=await prisma.consignmentBatch.findFirst({where:{id:job.batchId,accountId:input.accountId,status:{in:["DRAFT","PARSING","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"]}}});if(!batch)throw new Error("Mapped consignment draft is unavailable.");await prisma.importJob.update({where:{id:job.id},data:{status:"RUNNING",stage:"PARSING",lastError:null}});
 try{if(batch.marketplace==="FLIPKART"){if(!batch.sourceUploadRelativePath)throw new Error("Retained Flipkart source is unavailable.");const data=await readFile(await resolveExistingConsignmentPath(batch.sourceUploadRelativePath));await importFlipkartConsignmentDraft({accountId:input.accountId,user:input.user,externalConsignmentNumber:batch.externalConsignmentNumber,displayName:batch.displayName,destinationText:batch.destinationText??undefined,existingBatchId:batch.id,file:new File([data],batch.sourceFileName)});}
 else{const stored=await prisma.consignmentImportFile.findMany({where:{consignmentBatchId:batch.id,managedRelativePath:{not:null},supersededAt:null},orderBy:[{createdAt:"asc"},{id:"asc"}]});const files:File[]=[],storedFileIds:string[]=[];for(const item of stored){if(!item.managedRelativePath)continue;files.push(new File([await readFile(await resolveExistingConsignmentPath(item.managedRelativePath))],item.originalFileName));storedFileIds.push(item.id);}if(!files.length)throw new Error("Retained Amazon sources are unavailable.");const selected=stored.find(item=>item.isCurrentSource&&item.selectedTableName);await importAmazonConsignmentDraft({accountId:input.accountId,user:input.user,externalConsignmentNumber:batch.externalConsignmentNumber,displayName:batch.displayName,destinationText:batch.destinationText??undefined,existingBatchId:batch.id,files,storedFileIds,selectedCandidate:selected?.selectedTableName?{fileId:selected.id,tableName:selected.selectedTableName}:undefined});}
 await prisma.importJob.update({where:{id:job.id},data:{status:"COMPLETED",stage:"COMPLETED",lastError:null,finishedAt:new Date()}});return{batchId:batch.id};}catch(error){await prisma.importJob.update({where:{id:job.id},data:{status:"FAILED",stage:"FAILED",lastError:sanitizeImportJobError(error)??"Mapped consignment retry failed.",finishedAt:new Date()}});throw error;}
}
