import type { Marketplace } from "@prisma/client";
import { normalizeFlipkartHeader, parseFlipkartListingRows, type FlipkartRawRow } from "@/src/lib/marketplaces/flipkart/parser";
import type { AmazonParsedFile, AmazonSourceProfile } from "@/src/lib/consignments/amazon/types";
import type { CatalogSourceProfile, MarketplaceCatalogRowV1 } from "./catalog";

export type CatalogFileClassification="FLIPKART_LISTING_IDENTITY"|"FLIPKART_CATEGORY_CATALOG"|"FLIPKART_IMAGE_ENRICHMENT"|"AMAZON_ALL_LISTINGS"|"AMAZON_CATEGORY_CATALOG"|"AMAZON_PRODUCT_CATALOG"|"CATALOG_SUPPORTING"|"REFERENCE"|"UNKNOWN";
export function classifyFlipkartHeaders(headers:string[]):{classification:CatalogFileClassification;confidence:number}{const values=new Set(headers.map(normalizeFlipkartHeader));const has=(...names:string[])=>names.some(name=>values.has(normalizeFlipkartHeader(name)));const sku=has("Seller SKU Id","Seller SKU","SKU");const identity=sku&&(has("Listing ID","LID")||has("Flipkart Serial Number","FSN"));const category=has("Category","Sub-category","Product Type","Vertical","Brand");const images=headers.some(header=>/image.*url/i.test(header));if(identity)return{classification:"FLIPKART_LISTING_IDENTITY",confidence:95};if(sku&&category)return{classification:"FLIPKART_CATEGORY_CATALOG",confidence:80};if((sku||has("Listing ID","FSN"))&&images)return{classification:"FLIPKART_IMAGE_ENRICHMENT",confidence:75};if(sku)return{classification:"CATALOG_SUPPORTING",confidence:45};return{classification:"UNKNOWN",confidence:0};}
const raw=(row:FlipkartRawRow,names:string[])=>{const entries=new Map(Object.entries(row).map(([key,value])=>[normalizeFlipkartHeader(key),value]));for(const name of names){const value=entries.get(normalizeFlipkartHeader(name));if(value!==undefined&&value!==null&&String(value).trim())return String(value).trim();}return null;};
export function flipkartCatalogRows(input:{rows:FlipkartRawRow[];accountId:string;sourceFileId:string;sourceTable?:string}):{classification:CatalogFileClassification;rows:MarketplaceCatalogRowV1[]}{const headers=Object.keys(input.rows[0]??{});const classified=classifyFlipkartHeaders(headers);if(classified.classification==="FLIPKART_LISTING_IDENTITY"){const parsed=parseFlipkartListingRows(input.rows);return{classification:classified.classification,rows:parsed.listings.map(item=>({version:1,marketplace:"FLIPKART",accountId:input.accountId,sourceFileId:input.sourceFileId,sourceTable:input.sourceTable??"Data",sourceRow:item.rowNumber,sourceProfile:"FLIPKART_LISTING_IDENTITY",sourceAuthority:80,sellerSku:item.sellerSkuId,internalSku:item.sku,fsn:item.fsn,listingId:item.listingId,title:item.productTitle,brand:item.liveBrand,category:item.liveCategory,subCategory:item.subCategory,description:item.description,listingStatus:item.listingStatus,mrp:item.mrp,sellingPrice:item.sellingPrice,mainImageUrl:item.mainImageUrl,imageUrls:item.imageUrls.filter((value):value is string=>Boolean(value))}))};}
 const profile=classified.classification==="FLIPKART_CATEGORY_CATALOG"?"FLIPKART_CATEGORY_CATALOG":classified.classification==="FLIPKART_IMAGE_ENRICHMENT"?"FLIPKART_IMAGE_ENRICHMENT":"CATALOG_SUPPORTING";return{classification:classified.classification,rows:input.rows.map((item,index)=>({version:1,marketplace:"FLIPKART",accountId:input.accountId,sourceFileId:input.sourceFileId,sourceTable:input.sourceTable??"Data",sourceRow:index+2,sourceProfile:profile as CatalogSourceProfile,sourceAuthority:60,sellerSku:raw(item,["Seller SKU Id","Seller SKU","SKU"]),fsn:raw(item,["Flipkart Serial Number","FSN"]),listingId:raw(item,["Listing ID","LID"]),title:raw(item,["Product Title","Title","Product"]),brand:raw(item,["Brand","Live Brand"]),category:raw(item,["Category","Live Category","Vertical"]),subCategory:raw(item,["Sub-category","Sub Category","Product Type"]),productType:raw(item,["Product Type","Vertical"]),material:raw(item,["Material"]),color:raw(item,["Color","Colour"]),size:raw(item,["Size"]),modelNumber:raw(item,["Model","Model Number"]),mainImageUrl:raw(item,["Main Image URL","Image URL 1"]),imageUrls:headers.filter(h=>/image.*url/i.test(h)).map(h=>raw(item,[h])).filter((v):v is string=>Boolean(v))}))};}
const amazonProfile=(profile:AmazonSourceProfile):CatalogSourceProfile=>profile==="ALL_LISTINGS"?"AMAZON_ALL_LISTINGS":profile==="CATEGORY_CATALOG"?"AMAZON_CATEGORY_CATALOG":profile==="PRODUCT_CATALOG"?"AMAZON_PRODUCT_CATALOG":"CATALOG_SUPPORTING";
export function amazonCatalogRows(parsed:AmazonParsedFile,accountId:string,sourceFileId:string){return parsed.tables.filter(table=>table.sheetUsage!=="REFERENCE"&&table.profile!=="SHIPMENT"&&table.profile!=="UNKNOWN").flatMap(table=>table.rows.map(row=>({version:1 as const,marketplace:"AMAZON" as Marketplace,accountId,sourceFileId,sourceTable:table.sheet,sourceRow:row.rowNumber,sourceProfile:amazonProfile(table.profile),sourceAuthority:table.profile==="ALL_LISTINGS"?90:70,sellerSku:row.sellerSku,asin:row.asin,fnsku:row.fnsku,externalId:row.externalId,ean:row.ean,upc:row.upc,gtin:row.gtin,modelNumber:row.modelNumber,title:row.productTitle,brand:row.brand,category:row.category,subCategory:row.subCategory,material:row.material,color:row.color,size:row.size,description:row.description,bulletPoints:row.bulletPoints,listingStatus:row.listingStatus,mainImageUrl:row.mainImageUrl,imageUrls:row.imageUrls})));}
