import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Account, User } from "@prisma/client";
import yauzl, { type Entry, type ZipFile } from "yauzl";
import { parseSpreadsheetRowsFromPath } from "@/lib/import/files";
import { prisma } from "@/lib/prisma";
import { parseAmazonBuffer } from "@/src/lib/consignments/amazon/parser";
import { IMPORT_JOB_STORAGE_DIR } from "@/src/lib/import-jobs/runner";
import { amazonCatalogRows, flipkartCatalogRows, type CatalogFileClassification } from "./classifier";
import { mergeMarketplaceCatalogRows } from "./merge";

export const PRODUCT_INVENTORY_MAX_FILES=100,PRODUCT_INVENTORY_MAX_TOTAL_BYTES=150*1024*1024,PRODUCT_INVENTORY_MAX_FILE_BYTES=50*1024*1024;
const SUPPORTED=new Set([".csv",".tsv",".txt",".xlsx",".xlsm"]),BLOCKED=new Set([".exe",".com",".bat",".cmd",".ps1",".js",".msi",".dll",".lnk",".apk",".aab",".zip",".rar",".7z"]);
export type CatalogManifestEntry={id:string;displayName:string;relativePath:string;normalizedPath?:string;size:number;sha256:string;extension:string;classification?:CatalogFileClassification;confidence?:number;status:"QUEUED"|"PROCESSING"|"PARSED"|"COMPLETED"|"WARNING"|"FAILED";parsedRows:number;inserted:number;enriched:number;unchanged:number;warnings:number;error?:string};
export type CatalogJobManifest={version:1;marketplace:"FLIPKART"|"AMAZON";entries:CatalogManifestEntry[]};
const active=new Set<string>();const safeName=(value:string)=>path.basename(value).normalize("NFKC").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)||"catalog-file";
const sha=(data:Buffer)=>createHash("sha256").update(data).digest("hex");
export function validateCatalogArchiveEntryName(name:string){const normalized=name.replace(/\\/g,"/");if(normalized.startsWith("/")||/^[a-z]:/i.test(normalized)||normalized.split("/").some(part=>part===".."||part==="."))throw new Error("Archive contains an unsafe entry path.");const ext=path.extname(normalized).toLowerCase();if(BLOCKED.has(ext)||!SUPPORTED.has(ext))throw new Error("Archive contains an executable, nested archive, or unsupported file.");return ext;}
const validateName=validateCatalogArchiveEntryName;
function openZip(data:Buffer){return new Promise<ZipFile>((resolve,reject)=>yauzl.fromBuffer(data,{lazyEntries:true,validateEntrySizes:true},(error,zip)=>error||!zip?reject(error??new Error("Could not open ZIP.")):resolve(zip)));}
function readEntry(zip:ZipFile,entry:Entry){return new Promise<Buffer>((resolve,reject)=>zip.openReadStream(entry,(error,stream)=>{if(error||!stream)return reject(error??new Error("Could not read ZIP entry."));const parts:Buffer[]=[];let size=0;stream.on("data",(part:Buffer)=>{size+=part.length;if(size>PRODUCT_INVENTORY_MAX_FILE_BYTES)stream.destroy(new Error("Archive entry exceeds the file limit."));else parts.push(part);});stream.on("error",reject);stream.on("end",()=>resolve(Buffer.concat(parts)));}));}
async function extractZip(data:Buffer,dir:string,start:number){const zip=await openZip(data);return new Promise<CatalogManifestEntry[]>((resolve,reject)=>{const rows:CatalogManifestEntry[]=[];let total=0,settled=false;const fail=(e:unknown)=>{if(!settled){settled=true;zip.close();reject(e);}};zip.on("error",fail);zip.on("entry",async entry=>{try{if(/\/$/.test(entry.fileName)){zip.readEntry();return;}if(rows.length+start>=PRODUCT_INVENTORY_MAX_FILES)throw new Error("Product Inventory upload contains too many files.");if((entry.generalPurposeBitFlag&1)!==0)throw new Error("Encrypted ZIP entries are not supported.");const extension=validateName(entry.fileName);total+=entry.uncompressedSize;if(total>PRODUCT_INVENTORY_MAX_TOTAL_BYTES)throw new Error("ZIP uncompressed content exceeds the aggregate limit.");const body=await readEntry(zip,entry);const id=`file_${randomUUID()}`;const displayName=safeName(entry.fileName);const relativePath=path.join("uploads",`${id}${extension}`);await writeFile(path.join(dir,relativePath),body);rows.push({id,displayName,relativePath,size:body.length,sha256:sha(body),extension,status:"QUEUED",parsedRows:0,inserted:0,enriched:0,unchanged:0,warnings:0});zip.readEntry();}catch(e){fail(e);}});zip.on("end",()=>{if(!settled){settled=true;resolve(rows);}});zip.readEntry();});}
export async function createProductInventoryImportJob(input:{files:File[];account:Account;user:User}){if(!["FLIPKART","AMAZON"].includes(input.account.marketplace))throw new Error("Selected account marketplace does not support Product Inventory Refresh.");if(!input.files.length||input.files.length>PRODUCT_INVENTORY_MAX_FILES)throw new Error("Select between 1 and 100 files.");const total=input.files.reduce((sum,file)=>sum+file.size,0);if(total>PRODUCT_INVENTORY_MAX_TOTAL_BYTES)throw new Error("Product Inventory upload exceeds the aggregate limit.");const id=`job_${randomUUID()}`;const dir=path.join(IMPORT_JOB_STORAGE_DIR,id);await mkdir(path.join(dir,"uploads"),{recursive:true});await mkdir(path.join(dir,"reports"),{recursive:true});const entries:CatalogManifestEntry[]=[];
 for(const file of input.files){if(file.size>PRODUCT_INVENTORY_MAX_FILE_BYTES)throw new Error("One Product Inventory file exceeds the file limit.");const data=Buffer.from(await file.arrayBuffer());const extension=path.extname(file.name).toLowerCase();if(extension===".zip")entries.push(...await extractZip(data,dir,entries.length));else{if(!SUPPORTED.has(extension))throw new Error("Unsupported Product Inventory file type.");const fileId=`file_${randomUUID()}`;const relativePath=path.join("uploads",`${fileId}${extension}`);await writeFile(path.join(dir,relativePath),data);entries.push({id:fileId,displayName:safeName(file.name),relativePath,size:data.length,sha256:sha(data),extension,status:"QUEUED",parsedRows:0,inserted:0,enriched:0,unchanged:0,warnings:0});}}
 const manifest:CatalogJobManifest={version:1,marketplace:input.account.marketplace as "FLIPKART"|"AMAZON",entries};await writeFile(path.join(dir,"manifest.json"),JSON.stringify(manifest));return prisma.importJob.create({data:{id,accountId:input.account.id,createdByUserId:input.user.id,marketplace:input.account.marketplace,importType:input.account.marketplace==="AMAZON"?"AMAZON_PRODUCT_INVENTORY":"FLIPKART_PRODUCT_INVENTORY",fileName:`${entries.length} catalog file${entries.length===1?"":"s"}`,filePath:dir,status:"QUEUED",stage:"QUEUED",totalFiles:entries.length,manifestJson:JSON.stringify(manifest)}});}
export function startProductInventoryJob(id:string){if(active.has(id))return;active.add(id);void processProductInventoryJob(id).catch(async error=>{await prisma.importJob.update({where:{id},data:{status:"FAILED",stage:"FAILED",lastError:safeError(error),finishedAt:new Date()}}).catch(()=>undefined);}).finally(()=>active.delete(id));}
export async function processProductInventoryJob(id:string){const stale=new Date(Date.now()-120000);const claimed=await prisma.importJob.updateMany({where:{id,mergeStartedAt:null,OR:[{status:{in:["QUEUED","FAILED"]}},{status:"RUNNING",updatedAt:{lt:stale}}]},data:{status:"RUNNING",stage:"CLASSIFYING",startedAt:new Date(),lastError:null}});if(claimed.count!==1)return;const job=await prisma.importJob.findUniqueOrThrow({where:{id}});const manifest=JSON.parse(job.manifestJson??"") as CatalogJobManifest;let totals={processed:0,inserted:0,enriched:0,unchanged:0,conflicts:0,warnings:0};
 for(const entry of manifest.entries){if(await cancelled(job.id)){await finishCancelled(job.id);return;}entry.status="PROCESSING";await persist(job.id,manifest,{stage:"CLASSIFYING",currentFile:entry.displayName});try{const filePath=path.join(job.filePath!,entry.relativePath);let rows;let classification:CatalogFileClassification;if(job.marketplace==="AMAZON"){const parsed=await parseAmazonBuffer(await readFile(filePath),entry.displayName);rows=amazonCatalogRows(parsed,job.accountId,entry.id);classification=amazonClassification(parsed);}else{const rawRows=await parseSpreadsheetRowsFromPath(filePath);const parsed=flipkartCatalogRows({rows:rawRows,accountId:job.accountId,sourceFileId:entry.id});rows=parsed.rows;classification=parsed.classification;}entry.classification=classification;entry.parsedRows=rows.length;entry.normalizedPath=path.join("reports",`${entry.id}.json`);await writeFile(path.join(job.filePath!,entry.normalizedPath),JSON.stringify(rows));entry.status=rows.length?"PARSED":"WARNING";if(!rows.length){entry.warnings++;totals.warnings++;}}catch(error){entry.status="FAILED";entry.error=safeError(error);totals.warnings++;}await persist(job.id,manifest,{stage:"CLASSIFYING",currentFile:entry.displayName,processedFiles:manifest.entries.filter(item=>["PARSED","WARNING","FAILED"].includes(item.status)).length});}
 if(await cancelled(job.id)){await finishCancelled(job.id);return;}await prisma.importJob.update({where:{id},data:{stage:"MERGING",mergeStartedAt:new Date()}});
 for(const entry of [...manifest.entries].filter(item=>item.status==="PARSED").sort((a,b)=>authorityHint(a)-authorityHint(b))){await persist(job.id,manifest,{stage:"MERGING",currentFile:entry.displayName});try{const rows=JSON.parse(await readFile(path.join(job.filePath!,entry.normalizedPath!),"utf8"));const merged=await mergeMarketplaceCatalogRows({accountId:job.accountId,marketplace:job.marketplace as "FLIPKART"|"AMAZON",rows});entry.inserted=merged.inserted;entry.enriched=merged.enriched;entry.unchanged=merged.unchanged;entry.warnings=merged.warnings.length+merged.conflicts.length;entry.status=entry.warnings?"WARNING":"COMPLETED";totals={processed:totals.processed+merged.processed,inserted:totals.inserted+merged.inserted,enriched:totals.enriched+merged.enriched,unchanged:totals.unchanged+merged.unchanged,conflicts:totals.conflicts+merged.conflicts.length,warnings:totals.warnings+merged.warnings.length};}catch(error){entry.status="FAILED";entry.error=safeError(error);}await persist(job.id,manifest,{stage:"MERGING",currentFile:entry.displayName,...totals});}
 const usable=manifest.entries.some(entry=>entry.inserted+entry.enriched+entry.unchanged>0);await prisma.importJob.update({where:{id},data:{status:usable?"COMPLETED":"FAILED",stage:usable?"COMPLETED":"FAILED",currentFile:null,processedFiles:manifest.entries.length,processedRows:totals.processed,createdRows:totals.inserted,updatedRows:totals.enriched,unchangedRows:totals.unchanged,warningRows:totals.warnings+totals.conflicts,errorRows:manifest.entries.filter(e=>e.status==="FAILED").length,manifestJson:JSON.stringify(manifest),progressJson:JSON.stringify(totals),reportJson:JSON.stringify({version:1,files:manifest.entries.map(({displayName,classification,status,parsedRows,inserted,enriched,unchanged,warnings,error})=>({displayName,classification,status,parsedRows,inserted,enriched,unchanged,warnings,error}))}),lastError:usable?null:"No catalog rows were merged.",finishedAt:new Date()}});}
export async function requestProductInventoryJobCancel(id:string,accountId:string){const result=await prisma.importJob.updateMany({where:{id,accountId,status:{in:["QUEUED","RUNNING"]},mergeStartedAt:null},data:{cancelRequestedAt:new Date(),stage:"CANCEL_REQUESTED"}});return result.count===1;}
async function persist(id:string,manifest:CatalogJobManifest,data:Record<string,unknown>){await prisma.importJob.update({where:{id},data:{...data,manifestJson:JSON.stringify(manifest),progressJson:JSON.stringify(data)}});}
const safeError=(error:unknown)=>(error instanceof Error?error.message:"Import failed.").replace(/[A-Z]:\\[^\s]+/gi,"[private path]").slice(0,500);
const authorityHint=(entry:CatalogManifestEntry)=>["FLIPKART_LISTING_IDENTITY","AMAZON_ALL_LISTINGS"].includes(entry.classification??"")?0:["FLIPKART_CATEGORY_CATALOG","AMAZON_CATEGORY_CATALOG","AMAZON_PRODUCT_CATALOG"].includes(entry.classification??"")?1:2;
const amazonClassification=(parsed:Awaited<ReturnType<typeof parseAmazonBuffer>>):CatalogFileClassification=>{const profiles=parsed.tables.filter(table=>table.sheetUsage!=="REFERENCE").map(table=>table.profile);return profiles.includes("ALL_LISTINGS")?"AMAZON_ALL_LISTINGS":profiles.includes("CATEGORY_CATALOG")?"AMAZON_CATEGORY_CATALOG":profiles.includes("PRODUCT_CATALOG")?"AMAZON_PRODUCT_CATALOG":profiles.some(profile=>profile==="SUPPORTING")?"CATALOG_SUPPORTING":"UNKNOWN";};
async function cancelled(id:string){return Boolean((await prisma.importJob.findUniqueOrThrow({where:{id},select:{cancelRequestedAt:true}})).cancelRequestedAt);}
async function finishCancelled(id:string){await prisma.importJob.update({where:{id},data:{status:"CANCELLED",stage:"CANCELLED",finishedAt:new Date()}});}
