import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { resolveUniversalWork } from "../src/lib/workflow/universal-resolver";
import { getWorkerTaskQueue } from "../src/lib/workflow/queues";

const temp=resolve(process.cwd(),".codex-tmp");mkdirSync(temp,{recursive:true});const file=resolve(temp,"amazon-snapshot-scan.db");rmSync(file,{force:true,maxRetries:5,retryDelay:100});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve(process.cwd(),"prisma/migrations"),{withFileTypes:true}).filter((entry)=>entry.isDirectory()).map((entry)=>entry.name).sort())sqlite.exec(readFileSync(join(process.cwd(),"prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();const db=new PrismaClient({datasourceUrl:`file:${file.replace(/\\/g,"/")}`});
try{
 await db.account.createMany({data:[{id:"amazon-scan-a",name:"Amazon A",code:"ASA",companyName:"Fake",marketplace:"AMAZON",active:true},{id:"amazon-scan-b",name:"Amazon B",code:"ASB",companyName:"Fake",marketplace:"AMAZON",active:true},{id:"amazon-hidden",name:"Amazon Hidden",code:"ASH",companyName:"Fake",marketplace:"AMAZON",active:true}]});
 await db.user.create({data:{id:"amazon-scanner",username:"fake-amazon-scanner",passwordHash:"fake",name:"Fake Scanner",role:"PICKER",active:true,accountId:"amazon-scan-a",canPick:true,assignedAccounts:{connect:{id:"amazon-scan-b"}}}});
 await db.consignmentBatch.createMany({data:[{id:"amazon-batch-a",accountId:"amazon-scan-a",marketplace:"AMAZON",externalConsignmentNumber:"AMZ-A",displayName:"Amazon A",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha-a"},{id:"amazon-batch-b",accountId:"amazon-scan-b",marketplace:"AMAZON",externalConsignmentNumber:"AMZ-B",displayName:"Amazon B",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha-b"},{id:"amazon-batch-hidden",accountId:"amazon-hidden",marketplace:"AMAZON",externalConsignmentNumber:"AMZ-H",displayName:"Amazon Hidden",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha-h"}]});
 const line=(id:string,batch:string,accountId:string,rowNumber:number,snapshots:Record<string,string>,completed=false)=>({id,consignmentBatchId:batch,accountId,rowNumber,requiredQuantity:1,matchStatus:"OWNER_SELECTED" as const,processRoute:"PICK_PACK" as const,activated:true,...snapshots,...(completed?{completedAt:new Date(),completedByUserId:"amazon-scanner"}:{})});
 await db.consignmentLine.createMany({data:[line("line-fnsku","amazon-batch-a","amazon-scan-a",1,{fnskuSnapshot:"ONLY-FNSKU"}),line("line-asin","amazon-batch-a","amazon-scan-a",2,{asinSnapshot:"ONLY-ASIN"}),line("line-external","amazon-batch-a","amazon-scan-a",3,{externalIdSnapshot:"ONLY-EXTERNAL"}),line("line-barcode","amazon-batch-a","amazon-scan-a",4,{barcodeSnapshot:"8900000000999"}),line("line-done","amazon-batch-a","amazon-scan-a",5,{fnskuSnapshot:"DONE-FNSKU"},true),line("line-shared-a","amazon-batch-a","amazon-scan-a",6,{fnskuSnapshot:"SHARED-FNSKU"}),line("line-shared-b","amazon-batch-b","amazon-scan-b",1,{fnskuSnapshot:"SHARED-FNSKU"}),line("line-shared-hidden","amazon-batch-hidden","amazon-hidden",1,{fnskuSnapshot:"SHARED-FNSKU"})]});
 await db.workTask.createMany({data:[{id:"task-fnsku",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-fnsku",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-asin",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-asin",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-external",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-external",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-barcode",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-barcode",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-done",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-done",stage:"PICK",sequenceNumber:1,requiredQuantity:1,completedQuantity:1,status:"COMPLETED",completedAt:new Date(),completedByUserId:"amazon-scanner"},{id:"task-shared-a",accountId:"amazon-scan-a",sourceType:"CONSIGNMENT",consignmentLineId:"line-shared-a",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-shared-b",accountId:"amazon-scan-b",sourceType:"CONSIGNMENT",consignmentLineId:"line-shared-b",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"},{id:"task-shared-hidden",accountId:"amazon-hidden",sourceType:"CONSIGNMENT",consignmentLineId:"line-shared-hidden",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY"}]});
 for(const [code,taskId] of [["ONLY-FNSKU","task-fnsku"],["ONLY-ASIN","task-asin"],["ONLY-EXTERNAL","task-external"],["8900000000999","task-barcode"]]){const result=await resolveUniversalWork({actorUserId:"amazon-scanner",code},db);assert.ok(result.candidates.some((candidate)=>candidate.taskId===taskId),`${code} resolves directly from immutable snapshot`);}
 const completed=await resolveUniversalWork({actorUserId:"amazon-scanner",code:"DONE-FNSKU"},db);assert.equal(completed.candidates.length,0);assert.equal(completed.completedMatchCount,1);
 const shared=await resolveUniversalWork({actorUserId:"amazon-scanner",code:"SHARED-FNSKU"},db);assert.deepEqual(new Set(shared.candidates.map((candidate)=>candidate.accountId)),new Set(["amazon-scan-a","amazon-scan-b"]),"Authorized Amazon accounts remain separate and unauthorized account is excluded");
 const queue=await getWorkerTaskQueue({actorUserId:"amazon-scanner",accountId:"amazon-scan-a",stage:"PICK",search:"ONLY-ASIN"},db);assert.ok(queue.tasks.some((task)=>task.id==="task-asin"),"Selected-account queue searches Amazon snapshots directly");
}finally{await db.$disconnect();try{rmSync(file,{force:true,maxRetries:5,retryDelay:100});}catch{}}
console.log("Amazon snapshot-only scanner and queue tests passed.");
