import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import ExcelJS from "exceljs";

const tempRoot=resolve(process.cwd(),".codex-tmp");mkdirSync(tempRoot,{recursive:true});const databaseFile=resolve(tempRoot,"amazon-consignment-integration.db");const storageRoot=resolve(tempRoot,"amazon-consignment-storage");rmSync(databaseFile,{force:true});rmSync(storageRoot,{recursive:true,force:true});
const sqlite=new DatabaseSync(databaseFile);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve(process.cwd(),"prisma/migrations"),{withFileTypes:true}).filter((entry)=>entry.isDirectory()).map((entry)=>entry.name).sort())sqlite.exec(readFileSync(join(process.cwd(),"prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();
process.env.DATABASE_URL=`file:${databaseFile.replace(/\\/g,"/")}`;process.env.CONSIGNMENT_IMPORT_ROOT=storageRoot;
const db=new PrismaClient({datasourceUrl:process.env.DATABASE_URL});
try {
 await db.account.create({data:{id:"amazon-account",name:"Fake Amazon",code:"AMZFAKE",companyName:"Fake Company",marketplace:"AMAZON",active:true}});
 await db.user.create({data:{id:"owner-amazon",username:"fake-amazon-owner",passwordHash:"fake-hash",name:"Fake Owner",role:"OWNER",active:true}});
 await db.marketplaceListing.create({data:{id:"amazon-listing",accountId:"amazon-account",marketplace:"AMAZON",sellerSkuId:"SKU-FAKE",sku:"SKU-FAKE",productTitle:"Existing title",mainImageUrl:"https://example.invalid/existing.png"}});
 await db.marketplaceListingIdentifier.createMany({data:[{accountId:"amazon-account",marketplaceListingId:"amazon-listing",marketplace:"AMAZON",identifierType:"SELLER_SKU",rawValue:"SKU-FAKE",normalizedValue:"SKU-FAKE"},{accountId:"amazon-account",marketplaceListingId:"amazon-listing",marketplace:"AMAZON",identifierType:"FNSKU",rawValue:"FNSKU-FAKE",normalizedValue:"FNSKU-FAKE"}]});
 await db.productProcessRule.create({data:{id:"amazon-rule",accountId:"amazon-account",marketplaceListingId:"amazon-listing",route:"PICK_PACK",active:true,createdByUserId:"owner-amazon",updatedByUserId:"owner-amazon"}});
 const shipment=new File(["Shipment ID,Shipment Name,Seller SKU,FNSKU,ASIN,Quantity,Destination\nSHIP-FAKE,Fake Shipment,SKU-FAKE,FNSKU-FAKE,B000FAKE01,2,FC-FAKE\n"],"shipment.csv",{type:"text/csv"});
 const listings=new File(["Seller SKU,ASIN,FNSKU,Item Name,Listing Status,Main Image URL\nSKU-FAKE,B000FAKE01,FNSKU-FAKE,Updated fake title,Active,https://example.invalid/listing.png\n"],"all-listings.csv",{type:"text/csv"});
 const catalog=new File(["Seller SKU,ASIN,Item Name,Category,Brand,Description,Main Image URL,Bullet Point 1\nSKU-FAKE,B000FAKE01,Enriched fake title,Fake Category,Fake Brand,Fake description,https://example.invalid/catalog.png,Fake feature\n"],"catalog.csv",{type:"text/csv"});
 const { importAmazonConsignmentDraft }=await import("../src/lib/consignments/amazon/import-service");const { activateConsignmentBatch }=await import("../src/lib/workflow/task-store");
 const imported=await importAmazonConsignmentDraft({accountId:"amazon-account",user:{id:"owner-amazon"},externalConsignmentNumber:"SHIP-FAKE",files:[shipment,listings,catalog]});
 assert.equal(imported.requiresMainSelection,false);assert.equal(await db.workTask.count(),0,"Preview never creates worker tasks");
 const batch=await db.consignmentBatch.findUniqueOrThrow({where:{id:imported.batchId}});assert.equal(batch.marketplace,"AMAZON");assert.equal(batch.status,"READY_TO_ACTIVATE");assert.equal(batch.totalRequiredQuantity,2);
 const line=await db.consignmentLine.findFirstOrThrow({where:{consignmentBatchId:batch.id}});assert.equal(line.matchStatus,"EXACT_FNSKU");assert.equal(line.marketplaceListingId,"amazon-listing");assert.equal(line.processRoute,"PICK_PACK");
 const updatedListing=await db.marketplaceListing.findUniqueOrThrow({where:{id:"amazon-listing"},include:{identifiers:true}});assert.equal(updatedListing.productTitle,"Enriched fake title");assert.equal(updatedListing.liveCategory,"Fake Category");assert.ok(updatedListing.identifiers.some((identifier)=>identifier.identifierType==="ASIN"&&identifier.normalizedValue==="B000FAKE01"));
 const activation=await activateConsignmentBatch({batchId:batch.id,accountId:"amazon-account",actorUserId:"owner-amazon"},db);assert.equal(activation.activated,true);const tasks=await db.workTask.findMany({where:{consignmentLineId:line.id},orderBy:{sequenceNumber:"asc"}});assert.deepEqual(tasks.map((task)=>[task.stage,task.status]),[["PICK","READY"],["PACK","LOCKED"]]);
 const activated=await db.consignmentLine.findUniqueOrThrow({where:{id:line.id}});assert.equal(activated.asinSnapshot,"B000FAKE01");assert.equal(activated.fnskuSnapshot,"FNSKU-FAKE");assert.ok(activated.catalogSnapshotJson?.includes("Fake Category"));
 await db.marketplaceListing.update({where:{id:"amazon-listing"},data:{productTitle:"Changed after activation",mainImageUrl:"https://example.invalid/changed.png"}});const immutable=await db.consignmentLine.findUniqueOrThrow({where:{id:line.id}});assert.notEqual(immutable.productTitleSnapshot,"Changed after activation");assert.equal(immutable.catalogSnapshotJson,activated.catalogSnapshotJson,"Activated catalog snapshot remains immutable");
 const replay=await activateConsignmentBatch({batchId:batch.id,accountId:"amazon-account",actorUserId:"owner-amazon"},db);assert.equal(replay.alreadyActive,true);assert.equal(await db.workTask.count({where:{consignmentLineId:line.id}}),2);

 const multiBook=new ExcelJS.Workbook();for(const [name,quantity] of [["Shipment One",4],["Shipment Two",7]] as const){const sheet=multiBook.addWorksheet(name);sheet.addRow(["Shipment ID","Seller SKU","FNSKU","ASIN","Quantity","Sub Category"]);sheet.addRow([`SHIP-${quantity}`,"SKU-FAKE","FNSKU-FAKE","B000FAKE01",quantity,"Shipment fallback subcategory"]);}const multiFile=new File([Buffer.from(await multiBook.xlsx.writeBuffer())],"multi-shipment.xlsx",{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
 const multiListings=new File(["Seller SKU,ASIN,FNSKU,Item Name,Listing Status\nSKU-FAKE,B000FAKE01,FNSKU-FAKE,Listing fallback title,Active\n"],"multi-listings.csv",{type:"text/csv"});
 const catalogZ=new File(["Seller SKU,ASIN,Item Name,Category,Brand,Main Image URL\nSKU-FAKE,B000FAKE01,Catalog Z title,,Fake Brand,https://example.invalid/z.png\n"],"z-catalog.csv",{type:"text/csv"});
 const catalogBook=new ExcelJS.Workbook();const referenceHeaders=["item_sku","item_name","feed_product_type","brand_name","external_product_id"];
 for(const [name,externalId] of [["Instructions","REF-INSTRUCTION"],["Examples","REF-EXAMPLE"]] as const){const sheet=catalogBook.addWorksheet(name);sheet.addRow(referenceHeaders);sheet.addRow(["SKU-FAKE",`${name} must not enrich`,"wrong-category","Wrong Brand",externalId]);}
 const template=catalogBook.addWorksheet("Template");template.addRow(["Template metadata","attributeRow=3","labelRow=2","dataRow=4"]);template.addRow(["Seller SKU","ASIN","Item Name","Product Type","Brand","Material","Colour","Size","Model","Description","Bullet 1","Bullet 2","Bullet 3","Bullet 4","Bullet 5","Main Image",...Array.from({length:10},(_,index)=>`Other Image ${index+1}`)]);template.addRow(["item_sku","asin","item_name","feed_product_type","brand_name","material_type","color_name","size_name","model_number","product_description","bullet_point1","bullet_point2","bullet_point3","bullet_point4","bullet_point5","main_image_url",...Array.from({length:10},(_,index)=>`other_image_url${index+1}`)]);template.addRow(["SKU-FAKE","B000FAKE01","Catalog A authoritative","Selected Category","Fake Brand","Stainless Steel","Black","22 inch","BR-2026","Detailed fake catalog description","Feature one","Feature two","Feature three","Feature four","Feature five","https://example.invalid/a.png",...Array.from({length:10},(_,index)=>`https://example.invalid/gallery-${index}.png`)]);const catalogA=new File([Buffer.from(await catalogBook.xlsx.writeBuffer())],"a-catalog.xlsx",{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
 const multiFiles=[multiFile,multiListings,catalogZ,catalogA];const multi=await importAmazonConsignmentDraft({accountId:"amazon-account",user:{id:"owner-amazon"},externalConsignmentNumber:"SHIP-MULTI",files:multiFiles});assert.equal(multi.requiresMainSelection,true);assert.equal(await db.consignmentLine.count({where:{consignmentBatchId:multi.batchId}}),0,"Multiple source preview creates no lines or tasks before selection");
 const storedBefore=await db.consignmentImportFile.findMany({where:{consignmentBatchId:multi.batchId}});assert.equal(storedBefore.length,4);const workbookRecord=storedBefore.find((item)=>item.originalFileName==="multi-shipment.xlsx")!;const candidates=JSON.parse(workbookRecord.candidateTablesJson??"[]") as Array<{tableName:string;profile:string}>;assert.deepEqual(candidates.filter((item)=>item.profile==="SHIPMENT").map((item)=>item.tableName),["Shipment One","Shipment Two"]);
 const ids=multiFiles.map((file)=>storedBefore.find((item)=>item.originalFileName===file.name)!.id);await importAmazonConsignmentDraft({accountId:"amazon-account",user:{id:"owner-amazon"},externalConsignmentNumber:"SHIP-MULTI",displayName:"Selected multi shipment",files:multiFiles,storedFileIds:ids,existingBatchId:multi.batchId,selectedCandidate:{fileId:workbookRecord.id,tableName:"Shipment Two"}});
 assert.equal(await db.consignmentImportFile.count({where:{consignmentBatchId:multi.batchId}}),4,"Source selection reuses stored records without duplication");const selectedLine=await db.consignmentLine.findFirstOrThrow({where:{consignmentBatchId:multi.batchId}});assert.equal(selectedLine.requiredQuantity,7,"Only the selected shipment worksheet creates work quantity");assert.equal((await db.consignmentImportFile.findUniqueOrThrow({where:{id:workbookRecord.id}})).selectedTableName,"Shipment Two");
 const selectedListing=await db.marketplaceListing.findUniqueOrThrow({where:{id:"amazon-listing"}});assert.equal(selectedListing.productTitle,"Catalog A authoritative","Catalog authority is stable regardless upload or worksheet order");assert.equal(selectedListing.liveCategory,"Selected Category","Blank lower-priority cells never erase enrichment");assert.equal(selectedListing.mainImageUrl,"https://example.invalid/a.png");assert.ok(await db.consignmentImportIssue.findFirst({where:{consignmentBatchId:multi.batchId,issueType:"CATALOG_FIELD_CONFLICT"}}),"Conflicting nonblank catalog values create a warning");assert.equal(await db.marketplaceListingIdentifier.count({where:{accountId:"amazon-account",normalizedValue:{in:["REF-INSTRUCTION","REF-EXAMPLE"]}}}),0,"Reference sheets never create identifiers");
 const enrichedSnapshot=JSON.parse(selectedLine.catalogSnapshotJson??"{}") as {subCategory?:string;material?:string;color?:string;size?:string;modelNumber?:string;description?:string;bulletPoints?:string[];imageUrls?:string[]};assert.equal(enrichedSnapshot.subCategory,"Shipment fallback subcategory","Shipment remains fallback when catalog enrichment is blank");assert.equal(enrichedSnapshot.material,"Stainless Steel");assert.equal(enrichedSnapshot.color,"Black");assert.equal(enrichedSnapshot.size,"22 inch");assert.equal(enrichedSnapshot.modelNumber,"BR-2026");assert.equal(enrichedSnapshot.description,"Detailed fake catalog description");assert.equal(enrichedSnapshot.bulletPoints?.length,5);assert.equal(enrichedSnapshot.imageUrls?.length,10,"Gallery is deduplicated and capped at ten safe images");
 await importAmazonConsignmentDraft({accountId:"amazon-account",user:{id:"owner-amazon"},externalConsignmentNumber:"SHIP-MULTI",displayName:"Reselected multi shipment",files:multiFiles,storedFileIds:ids,existingBatchId:multi.batchId,selectedCandidate:{fileId:workbookRecord.id,tableName:"Shipment One"}});assert.equal(await db.consignmentImportFile.count({where:{consignmentBatchId:multi.batchId}}),4,"Reselection still does not duplicate files");const reselectedLine=await db.consignmentLine.findFirstOrThrow({where:{consignmentBatchId:multi.batchId}});assert.equal(reselectedLine.requiredQuantity,4,"Exact worksheet can be reselected before activation");assert.equal(reselectedLine.catalogSnapshotJson,selectedLine.catalogSnapshotJson,"Reselection preserves authoritative enriched snapshot");
} finally { const { prisma }=await import("../lib/prisma");await prisma.$disconnect();await db.$disconnect();rmSync(databaseFile,{force:true});rmSync(storageRoot,{recursive:true,force:true}); }
console.log("Amazon import preview, enrichment, activation, and snapshot integration tests passed.");
