import assert from "node:assert/strict";
import { rmSync } from "node:fs";
import { resolve, sep } from "node:path";
import ExcelJS from "exceljs";
import type { DynamicListingFormSchema } from "../src/lib/catalog/dynamic-form-profiles";
import { createPhase736Database } from "./phase-7-3-6-test-db";

const fixture=createPhase736Database("amazon-product-inventory-profile"),jobPaths:string[]=[];
const{prisma}=await import("../lib/prisma");
const{headerFingerprint,persistDetectedAmazonTemplateProfile}=await import("../src/lib/imports/header-profiles");
const{parseAmazonBuffer}=await import("../src/lib/consignments/amazon/parser");
const{createProductInventoryImportJob,processProductInventoryJob}=await import("../src/lib/product-inventory/jobs");
const{IMPORT_JOB_STORAGE_DIR}=await import("../src/lib/import-jobs/runner");

const technical=["contribution_sku#1.value","product_type#1.value","item_name[marketplace_id=A21TJRUUN4KGV]#1.value","brand[language_tag=en_IN]#1.value","main_product_image_locator[marketplace_id=A21TJRUUN4KGV]#1.media_location","bullet_point[language_tag=en_IN]#1.value"];
const human=["Seller SKU","Product type","Item name","Brand","Main image","Bullet point 1"];
const referenceTechnical=["contribution_sku#1.value","product_type#1.value","item_name[marketplace_id=REFERENCE]#1.value","brand[language_tag=en_IN]#1.value","reference_only_attribute#1.value","bullet_point[language_tag=en_IN]#1.value"];

async function templateWorkbook(input:{human:string[];technical:string[];sku:string}){
  const workbook=new ExcelJS.Workbook(),reference=workbook.addWorksheet("Dropdown Lists");
  reference.addRow(["Reference SKU","Reference type","Reference name","Reference brand","Reference only","Reference bullet"]);reference.addRow(referenceTechnical);reference.addRow(["REF-ONLY","REFERENCE","Never profile this sheet","Reference","Reference","Reference"]);
  const sheet=workbook.addWorksheet("Sheet 42");sheet.addRow(["Template metadata","attributeRow=6","labelRow=4","dataRow=8"]);sheet.addRow([{formula:'WEBSERVICE("https://example.invalid/never-run")',result:"Formula result only"}]);sheet.addRow([{text:"External documentation",hyperlink:"https://example.invalid/not-fetched"}]);sheet.addRow(input.human);sheet.addRow([]);sheet.addRow(input.technical);sheet.addRow([]);sheet.addRow([input.sku,"KEYCHAIN",`Synthetic ${input.sku}`,{formula:'WEBSERVICE("https://example.invalid/brand")',result:"Synthetic Brand"},{text:"https://example.invalid/product.jpg",hyperlink:"https://example.invalid/product.jpg"},"Synthetic bullet"]);
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

async function createJob(account:Awaited<ReturnType<typeof prisma.account.findUniqueOrThrow>>,user:Awaited<ReturnType<typeof prisma.user.findUniqueOrThrow>>,buffer:Buffer,fileName:string){
  const body=Uint8Array.from(buffer).buffer,job=await createProductInventoryImportJob({files:[new File([body],fileName,{type:"application/vnd.ms-excel.sheet.macroEnabled.12"})],account,user});if(job.filePath)jobPaths.push(job.filePath);return job;
}
async function runJob(account:Awaited<ReturnType<typeof prisma.account.findUniqueOrThrow>>,user:Awaited<ReturnType<typeof prisma.user.findUniqueOrThrow>>,buffer:Buffer,fileName:string){const job=await createJob(account,user,buffer,fileName);await processProductInventoryJob(job.id);return prisma.importJob.findUniqueOrThrow({where:{id:job.id}});}

try{
  const account=await prisma.account.create({data:{id:"amazon-a",name:"Amazon A",code:"AM-A",marketplace:"AMAZON"}}),otherAccount=await prisma.account.create({data:{id:"amazon-b",name:"Amazon B",code:"AM-B",marketplace:"AMAZON"}}),owner=await prisma.user.create({data:{id:"owner",username:"amazon-profile-owner",passwordHash:"synthetic",name:"Owner",role:"OWNER"}});await prisma.marketplaceListing.createMany({data:[{accountId:account.id,marketplace:"AMAZON",sellerSkuId:"AMZ-TECH-1",sku:"AMZ-TECH-1"},{accountId:account.id,marketplace:"AMAZON",sellerSkuId:"AMZ-TECH-2",sku:"AMZ-TECH-2"},{accountId:account.id,marketplace:"AMAZON",sellerSkuId:"AMZ-TECH-3",sku:"AMZ-TECH-3"},{accountId:account.id,marketplace:"AMAZON",sellerSkuId:"AMZ-RACE-A",sku:"AMZ-RACE-A"},{accountId:account.id,marketplace:"AMAZON",sellerSkuId:"AMZ-RACE-B",sku:"AMZ-RACE-B"},{accountId:otherAccount.id,marketplace:"AMAZON",sellerSkuId:"AMZ-TECH-1",sku:"AMZ-TECH-1"}]});
  const firstBuffer=await templateWorkbook({human,technical,sku:"AMZ-TECH-1"}),parsed=await parseAmazonBuffer(firstBuffer,"unrelated-quarterly-data.xlsm"),operational=parsed.tables.find(table=>table.sheet==="Sheet 42")!,reference=parsed.tables.find(table=>table.sheet==="Dropdown Lists")!;
  assert.equal(operational.profile,"PRODUCT_CATALOG","Technical content, not filename, identifies the Amazon template");assert.equal(operational.technicalHeaderRow,6);assert.equal(operational.humanHeaderRow,4);assert.equal(operational.dataRow,8);assert.deepEqual(operational.technicalHeaders,technical);assert.deepEqual(operational.humanHeaders,human);assert.equal(operational.rows[0]?.sellerSku,"AMZ-TECH-1");assert.equal(operational.rows[0]?.brand,"Synthetic Brand","Formula text is never executed or retained; only its cached result is read");assert.equal(reference.sheetUsage,"REFERENCE");
  const technicalFingerprint=headerFingerprint(technical);await prisma.marketplaceFileProfile.create({data:{id:"legacy-null-schema",accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",profileName:"Legacy Amazon mapping",headerFingerprint:technicalFingerprint,fieldMappingJson:JSON.stringify({sellerSku:technical[0]}),requiredFieldsJson:JSON.stringify(["sellerSku"]),version:1,active:true,createdByUserId:owner.id}});
  const firstJob=await runJob(account,owner,firstBuffer,"not-an-amazon-template.xlsm");assert.match(firstJob.status,/^COMPLETED/,`${firstJob.lastError??"Amazon Product Inventory job must complete"} ${firstJob.reportJson??firstJob.manifestJson??""}`);
  let profiles=await prisma.marketplaceFileProfile.findMany({where:{accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG"},orderBy:{createdAt:"asc"}});const upgraded=profiles.find(profile=>profile.formSchemaJson!==null)!;assert.ok(upgraded,"A real Product Inventory job persists a UI form schema");assert.equal(upgraded.version,2,"A matched legacy null-schema profile is version-upgraded");assert.equal(upgraded.accountId,account.id);assert.equal((await prisma.marketplaceFileProfile.findUniqueOrThrow({where:{id:"legacy-null-schema"}})).active,false);assert.equal(JSON.parse(upgraded.dataStartRuleJson??"{}").technicalHeaderRow,6);assert.equal(JSON.parse(upgraded.dataStartRuleJson??"{}").humanHeaderRow,4);assert.equal(JSON.parse(upgraded.dataStartRuleJson??"{}").dataRow,8);assert.doesNotMatch(`${upgraded.profileName}${upgraded.workbookSignatureJson}${upgraded.formSchemaJson}`,/not-an-amazon-template|WEBSERVICE|not-fetched/i);
  const upgradedSchema=JSON.parse(upgraded.formSchemaJson!) as DynamicListingFormSchema;assert.equal(upgradedSchema.fields.find(field=>field.technicalKey===technical[2])?.label,"Item name");assert.equal(await prisma.marketplaceListing.count({where:{accountId:account.id,sellerSkuId:"AMZ-TECH-1"}}),1);const profilesBeforeTamper=await prisma.marketplaceFileProfile.count();const tamperedSchema:DynamicListingFormSchema={...upgradedSchema,fields:upgradedSchema.fields.map((field,index)=>index===0?{...field,technicalKey:"tampered_sku#1.value"}:field)};await assert.rejects(()=>persistDetectedAmazonTemplateProfile({actorUserId:owner.id,accountId:account.id,technicalHeaders:technical,humanHeaders:human,technicalHeaderRow:6,humanHeaderRow:4,dataRow:8,formSchema:tamperedSchema}),/technical schema is inconsistent/);await assert.rejects(()=>persistDetectedAmazonTemplateProfile({actorUserId:owner.id,accountId:account.id,technicalHeaders:[...technical,...Array.from({length:245},(_,index)=>`extra_${index}#1.value`)],humanHeaders:human,technicalHeaderRow:6,humanHeaderRow:4,dataRow:8,formSchema:upgradedSchema}),/too many headers/);assert.equal(await prisma.marketplaceFileProfile.count(),profilesBeforeTamper,"Tampered or oversized schemas create no profile");
  const validProfileInput={actorUserId:owner.id,accountId:account.id,technicalHeaders:technical,humanHeaders:human,technicalHeaderRow:6,humanHeaderRow:4,dataRow:8,formSchema:upgradedSchema};let unrelatedAttempts=0;const unrelatedP2002=Object.assign(new Error("Synthetic unrelated uniqueness failure"),{code:"P2002",meta:{target:["accountId","profileName"]}});await assert.rejects(()=>persistDetectedAmazonTemplateProfile(validProfileInput,{$transaction:async()=>{unrelatedAttempts+=1;throw unrelatedP2002;}} as never),error=>error===unrelatedP2002,"An unrelated P2002 is not hidden or broadly retried");assert.equal(unrelatedAttempts,1,"Only the exact profile-version constraint is retryable");let exactRaceAttempts=0;await assert.rejects(()=>persistDetectedAmazonTemplateProfile(validProfileInput,{$transaction:async()=>{exactRaceAttempts+=1;throw Object.assign(new Error("Synthetic profile version collision"),{code:"P2002",meta:{target:["marketplace","importPurpose","headerFingerprint","version"]}});}} as never),/Detected Amazon template profile changed concurrently; retry the import/);assert.equal(exactRaceAttempts,5,"The exact profile-version race uses a bounded retry count and a controlled terminal error");

  const countAfterFirst=profiles.length,auditAfterFirst=await prisma.auditLog.count({where:{entityType:"MarketplaceFileProfile",accountId:account.id}});const repeatJob=await runJob(account,owner,firstBuffer,"renamed-again.xlsm");assert.match(repeatJob.status,/^COMPLETED/);profiles=await prisma.marketplaceFileProfile.findMany({where:{accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG"}});assert.equal(profiles.length,countAfterFirst,"An identical detected template reuses its profile");assert.equal(await prisma.auditLog.count({where:{entityType:"MarketplaceFileProfile",accountId:account.id}}),auditAfterFirst,"Profile reuse writes no duplicate audit mutation");

  await prisma.marketplaceFileProfile.create({data:{id:"other-account-high-version",accountId:otherAccount.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",profileName:"Other account inactive history",headerFingerprint:technicalFingerprint,fieldMappingJson:JSON.stringify({sellerSku:technical[0]}),requiredFieldsJson:JSON.stringify(["sellerSku"]),version:50,active:false,createdByUserId:owner.id}});const relabelledHuman=human.map(label=>`Updated ${label}`),relabelledBuffer=await templateWorkbook({human:relabelledHuman,technical,sku:"AMZ-TECH-2"});await runJob(account,owner,relabelledBuffer,"anything.xlsm");const relabelled=await prisma.marketplaceFileProfile.findFirstOrThrow({where:{accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",headerFingerprint:technicalFingerprint,active:true}});assert.equal(relabelled.technicalHeaderFingerprint,upgraded.technicalHeaderFingerprint,"Human relabeling preserves the stable technical fingerprint");assert.notEqual(relabelled.humanHeaderFingerprint,upgraded.humanHeaderFingerprint);assert.notEqual(relabelled.id,upgraded.id);assert.equal(relabelled.version,upgraded.version+1,"Another account's high version does not change this account's next logical version");const relabelledSchema=JSON.parse(relabelled.formSchemaJson!) as {fields:Array<{technicalKey:string;label:string}>};assert.equal(relabelledSchema.fields.find(field=>field.technicalKey===technical[2])?.label,"Updated Item name");

  const changedTechnical=[...technical.slice(0,-1),"generic_keyword[language_tag=en_IN]#1.value"],changedBuffer=await templateWorkbook({human:[...human.slice(0,-1),"Search terms"],technical:changedTechnical,sku:"AMZ-TECH-3"});await runJob(account,owner,changedBuffer,"same-name.xlsm");const changedFingerprint=headerFingerprint(changedTechnical),changed=await prisma.marketplaceFileProfile.findFirstOrThrow({where:{accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",headerFingerprint:changedFingerprint,active:true}});assert.notEqual(changed.id,relabelled.id,"Changed technical keys create a distinct profile");assert.notEqual(changed.technicalHeaderFingerprint,relabelled.technicalHeaderFingerprint);assert.equal(changed.formSchemaJson!==null,true);

  await runJob(otherAccount,owner,firstBuffer,"cross-account.xlsm");assert.equal(await prisma.marketplaceFileProfile.count({where:{accountId:otherAccount.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",formSchemaJson:{not:null}}}),1,"Detected profiles remain account scoped");assert.equal(await prisma.marketplaceFileProfile.count({where:{accountId:account.id,headerFingerprint:headerFingerprint(referenceTechnical)}}),0,"Reference worksheets never create marketplace form profiles");
  const uiProfiles=await prisma.marketplaceFileProfile.findMany({where:{OR:[{accountId:account.id},{accountId:null}],marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",active:true,formSchemaJson:{not:null}},orderBy:[{accountId:"desc"},{updatedAt:"desc"}]});assert.ok(uiProfiles.some(profile=>profile.id===relabelled.id));assert.ok(uiProfiles.some(profile=>profile.id===changed.id));assert.ok(uiProfiles.every(profile=>profile.formSchemaJson!==null),"Owner form queries receive only non-null schemas");

  const raceTechnical=[...technical,"special_feature[language_tag=en_IN]#1.value"],raceHuman=[...human,"Special feature"],raceFingerprint=headerFingerprint(raceTechnical),raceBuffers=await Promise.all([templateWorkbook({human:raceHuman,technical:raceTechnical,sku:"AMZ-RACE-A"}),templateWorkbook({human:raceHuman,technical:raceTechnical,sku:"AMZ-RACE-B"})]),raceJobs=await Promise.all([createJob(account,owner,raceBuffers[0],"race-a.xlsm"),createJob(account,owner,raceBuffers[1],"race-b.xlsm")]);
  await Promise.all(raceJobs.map(job=>processProductInventoryJob(job.id)));
  const finishedRaceJobs=await prisma.importJob.findMany({where:{id:{in:raceJobs.map(job=>job.id)}},orderBy:{id:"asc"}});assert.equal(finishedRaceJobs.length,2);assert.ok(finishedRaceJobs.every(job=>job.status.startsWith("COMPLETED")),finishedRaceJobs.map(job=>`${job.id}: ${job.status} / ${job.lastError??"no error"} / ${job.reportJson??job.manifestJson??"no report"}`).join("\n"));const raceProfiles=await prisma.marketplaceFileProfile.findMany({where:{accountId:account.id,marketplace:"AMAZON",importPurpose:"PRODUCT_CATALOG",headerFingerprint:raceFingerprint}});assert.equal(raceProfiles.length,1,"Two Product Inventory runners persist one identical detected profile");assert.equal(raceProfiles[0].active,true);assert.equal(await prisma.auditLog.count({where:{accountId:account.id,entityType:"MarketplaceFileProfile",entityId:raceProfiles[0].id}}),1,"The profile uniqueness race writes one coherent audit record");assert.equal(await prisma.marketplaceListing.count({where:{accountId:account.id,sellerSkuId:{in:["AMZ-RACE-A","AMZ-RACE-B"]}}}),2,"Both concurrent jobs still merge their distinct catalog rows");
}finally{
  await prisma.$disconnect();const storageRoot=resolve(IMPORT_JOB_STORAGE_DIR)+sep;for(const jobPath of jobPaths){const target=resolve(jobPath);if(target.startsWith(storageRoot))rmSync(target,{recursive:true,force:true});}fixture.cleanup();
}

console.log("Amazon Product Inventory technical-template profile integration tests passed.");
