import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read=(path:string)=>readFileSync(path,"utf8");
const schema=read("prisma/schema.prisma");const postgres=read("prisma/schema.postgres.prisma");const parser=read("src/lib/consignments/amazon/parser.ts");const archive=read("src/lib/consignments/amazon/archive.ts");const importer=read("src/lib/consignments/amazon/import-service.ts");const matching=read("src/lib/consignments/amazon/matching.ts");const card=read("app/work/WorkTaskCard.tsx");const details=read("app/work/marking/[taskId]/page.tsx");const scanner=read("src/lib/workflow/universal-resolver.ts");const queues=read("src/lib/workflow/queues.ts");const actions=read("app/owner/consignments/actions.ts");const mobile=read("mobile-app/App.tsx");
for(const source of [schema,postgres]){assert.match(source,/AMAZON_SHIPMENT/);assert.match(source,/asinSnapshot\s+String\?/);assert.match(source,/fnskuSnapshot\s+String\?/);assert.match(source,/catalogSnapshotJson\s+String\?/);assert.doesNotMatch(source,/model\s+(Inventory|StockLedger|StockBalance)/);}
assert.match(parser,/resolveAmazonHeaderLayout/);assert.match(parser,/attributeRow/);assert.match(parser,/HEADER_SCAN_ROWS/);assert.match(parser,/AMAZON_WORKBOOK_MAX_SHEETS/);assert.match(parser,/cell\.formula[^]*cellText\(cell\.result\)/,"Formula cells use cached results only");assert.match(archive,/generalPurposeBitFlag&1/);assert.match(archive,/symlink/i);assert.match(archive,/AMAZON_ZIP_MAX_UNCOMPRESSED_BYTES/);assert.match(importer,/selectedCandidate/);assert.match(importer,/candidateTablesJson/);assert.match(importer,/CATALOG_FIELD_CONFLICT/);assert.match(importer,/status:"PARSING"/);assert.doesNotMatch(importer,/workTask\.(create|createMany)/,"Amazon preview creates no worker tasks");assert.match(matching,/FNSKU[^]*SELLER_SKU[^]*ASIN[^]*EXTERNAL_ID/);assert.doesNotMatch(matching,/productTitle|contains:/,"Matching never uses titles");
assert.match(card,/productImageSnapshot\?\?catalog\?\.mainImageUrl\?\?line\.marketplaceListing/);assert.match(card,/ASIN/);assert.match(card,/FNSKU/);assert.doesNotMatch(card,/Download marking file|Open marking file|managedRelativePath/);assert.match(details,/parseConsignmentCatalogSnapshot/);assert.doesNotMatch(details,/managedRelativePath/);for(const field of ["fnskuSnapshot","asinSnapshot","externalIdSnapshot","barcodeSnapshot"]){assert.match(scanner,new RegExp(field));assert.match(queues,new RegExp(field));}assert.match(actions,/reparseAmazonStoredBatch/);assert.match(actions,/storedFileIds/);assert.doesNotMatch(read("components/UniversalScannerPanel.tsx"),/Download marking file|Open marking file/);assert.doesNotMatch(mobile,/AMAZON_CONSIGNMENT|PHASE_6_AMAZON/,"Mobile app remains unchanged by Phase 6.1");
console.log("Amazon consignment source-policy tests passed.");
