import assert from "node:assert/strict";
import { createTempWorkflowDb } from "./temp-workflow-db";
import { applyUniversalCandidateAction } from "../src/lib/workflow/universal-actions";
import { resolveUniversalWork } from "../src/lib/workflow/universal-resolver";
import { createImmutableRouteProvenance } from "../src/lib/workflow/route-provenance";
import { createWorkRouteSnapshot,parseWorkRouteSnapshot } from "../src/lib/workflow/dynamic-route";
import { canonicalRouteFingerprint } from "../src/lib/workflow/work-group-projection";
import { resolveConsignmentLineWorkflowPrerequisites } from "../src/lib/workflow/workflow-prerequisites";

const {db,cleanup}=createTempWorkflowDb("backend-freeze-route");
try{
 await db.account.create({data:{id:"account",name:"Backend Freeze",code:"BF",marketplace:"FLIPKART"}});await db.user.createMany({data:[{id:"owner",username:"freeze-owner",passwordHash:"x",name:"Owner",role:"OWNER",active:true},{id:"picker",username:"freeze-picker",passwordHash:"x",name:"Picker",role:"PICKER",active:true,accountId:"account",canPick:true}]});await db.marketplaceListing.create({data:{id:"listing",accountId:"account",marketplace:"FLIPKART",sku:"SKU-FREEZE",sellerSkuId:"SKU-FREEZE",productTitle:"Original frozen product"}});await db.marketplaceListingIdentifier.create({data:{accountId:"account",marketplaceListingId:"listing",marketplace:"FLIPKART",identifierType:"SELLER_SKU",rawValue:"SKU-FREEZE",normalizedValue:"SKU-FREEZE"}});await db.markingAsset.create({data:{id:"asset",name:"Frozen marking",masterDesignId:"MD-FROZEN",instructions:"Original marking instructions",status:"ACTIVE",active:true}});await db.productProcessRule.create({data:{id:"rule",accountId:"account",marketplaceListingId:"listing",route:"PICK_MARK_ASSEMBLE_PACK",markingRequired:true,markingAssetId:"asset",assemblyRequired:true,assemblyTitle:"Frozen assembly",assemblyInstructions:"Original assembly instructions",active:true}});await db.consignmentBatch.create({data:{id:"batch",accountId:"account",marketplace:"FLIPKART",externalConsignmentNumber:"CN-FREEZE",displayName:"Freeze",status:"ACTIVE",sourceFileName:"synthetic.csv",sourceFileSha256:"synthetic"}});
 const explicit=(route:"PICK_PACK"|"PICK_MARK_ASSEMBLE_PACK")=>createImmutableRouteProvenance({route,rule:{id:"rule",route,markingRequired:true,markingAsset:{id:"asset",name:"Frozen marking",masterDesignId:"MD-FROZEN",instructions:"Original marking instructions"},assemblyRequired:true,assemblyTitle:"Frozen assembly",assemblyInstructions:"Original assembly instructions"}}),fallback=createImmutableRouteProvenance({route:"PICK_PACK"});
 async function pick(id:string,provenance:ReturnType<typeof explicit>|typeof fallback){const lineId=`line-${id}`;await db.consignmentLine.create({data:{id:lineId,consignmentBatchId:"batch",accountId:"account",rowNumber:Number(id.replace(/\D/g,""))||1,sellerSkuSource:"SKU-FREEZE",sellerSkuSnapshot:"SKU-FREEZE",productTitleSnapshot:"Original frozen product",requiredQuantity:1,marketplaceListingId:"listing",matchStatus:"OWNER_SELECTED",processRoute:provenance.routeRecommendation,activated:true}});return db.workTask.create({data:{id:`pick-${id}`,accountId:"account",sourceType:"CONSIGNMENT",consignmentLineId:lineId,stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY",workCardSnapshotJson:JSON.stringify({version:2,sellerSku:"SKU-FREEZE",productTitle:"Original frozen product",...provenance}),routeSnapshotJson:JSON.stringify({...createWorkRouteSnapshot({processRoute:provenance.routeRecommendation,currentStage:"PICK"}),...provenance})}});}
 const follow=await pick("1",explicit("PICK_MARK_ASSEMBLE_PACK"));await applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:follow.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"MARK_ASSEMBLE",clientRequestId:"follow"},db);assert.equal((await db.workRouteDecision.findFirstOrThrow({where:{taskId:follow.id}})).decisionType,"FOLLOWED_SAVED_ROUTE");
 const override=await pick("2",explicit("PICK_PACK"));await assert.rejects(()=>applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:override.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"MARK",confirmMissingInstructions:true,clientRequestId:"override-no-reason"},db),/reason/i);await applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:override.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"MARK",routeReason:"Marking required",clientRequestId:"override-reason"},db);
 const manual=await pick("3",fallback);await assert.rejects(()=>applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:manual.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"MARK",clientRequestId:"fallback-no-confirm"},db),/Confirm Continue/i);await applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:manual.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"MARK",confirmMissingInstructions:true,workerNote:"Use manual station three",clientRequestId:"fallback-confirm"},db);const manualMark=await db.workTask.findFirstOrThrow({where:{consignmentLineId:manual.consignmentLineId!,stage:"MARK"}});assert.match(manualMark.metadataJson??"",/Use manual station three/);assert.equal((await db.workRouteDecision.findFirstOrThrow({where:{taskId:manual.id}})).reason,null);
 const assembly=await pick("4",fallback);await assert.rejects(()=>applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:assembly.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"ASSEMBLE",clientRequestId:"assembly-no-confirm"},db),/Confirm Continue/i);await applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:assembly.id,action:"TASK_PICK_ROUTE",expectedQuantity:0,route:"ASSEMBLE",confirmMissingInstructions:true,clientRequestId:"assembly-confirm"},db);
 const frozen=await db.workTask.findMany({where:{consignmentLineId:follow.consignmentLineId!},orderBy:{sequenceNumber:"asc"}});assert.deepEqual(frozen.map(task=>task.stage),["PICK","MARK","ASSEMBLE","PACK"]);assert.ok(frozen.every(task=>task.workCardSnapshotJson===frozen[0].workCardSnapshotJson));assert.ok(frozen.every(task=>task.routeSnapshotJson===frozen[0].routeSnapshotJson));const snapshot=parseWorkRouteSnapshot(frozen[0].routeSnapshotJson)!;assert.deepEqual(snapshot.recommendedStages,["PICK","MARK","ASSEMBLE","PACK"]);assert.deepEqual(snapshot.actualStages,["PICK","MARK","ASSEMBLE","PACK"]);assert.deepEqual(snapshot.completedStages,["PICK"]);assert.equal(snapshot.currentStage,"MARK");assert.match(frozen.find(task=>task.stage==="MARK")?.metadataJson??"",/Original marking instructions/);assert.match(frozen.find(task=>task.stage==="ASSEMBLE")?.metadataJson??"",/Original assembly instructions/);
 await db.productProcessRule.update({where:{id:"rule"},data:{route:"PICK_PACK",assemblyTitle:"Changed later",assemblyInstructions:"Changed later"}});assert.match((await db.workTask.findFirstOrThrow({where:{consignmentLineId:follow.consignmentLineId!,stage:"ASSEMBLE"}})).metadataJson??"",/Original assembly instructions/);
 const explicitHash=canonicalRouteFingerprint(frozen[0].routeSnapshotJson,frozen[0].metadataJson,frozen[0].workCardSnapshotJson,"PICK"),fallbackTasks=await db.workTask.findMany({where:{consignmentLineId:manual.consignmentLineId!}}),fallbackHash=canonicalRouteFingerprint(fallbackTasks[0].routeSnapshotJson,fallbackTasks[0].metadataJson,fallbackTasks[0].workCardSnapshotJson,"PICK");assert.notEqual(explicitHash,fallbackHash);const prerequisites=await resolveConsignmentLineWorkflowPrerequisites({accountId:"account",consignmentLineId:follow.consignmentLineId!},db);assert.equal(prerequisites.stages.MARK.required,true);assert.equal(prerequisites.stages.ASSEMBLE.required,true);assert.equal(prerequisites.stages.PACK.state,"LOCKED");
 await pick("5",fallback);const before=await db.workTask.count();const lookup=await resolveUniversalWork({actorUserId:"picker",accountId:"account",code:"SKU-FREEZE",intent:"PICK"},db);assert.equal(await db.workTask.count(),before);const candidate=lookup.candidates.find(item=>item.taskId&&item.stage==="PICK");assert.ok(candidate?.routeDecision);assert.equal(candidate?.routeDecision?.recommendationSource,"SYSTEM_FALLBACK");assert.equal(candidate?.routeDecision?.options.find(option=>option.route==="MARK")?.reasonRequired,false);
 await db.uploadBatch.create({data:{id:"orders",accountId:"account",fileName:"orders.csv"}});await db.order.create({data:{id:"order",accountId:"account",batchId:"orders",marketplace:"FLIPKART",awb:"AWB-FREEZE",sku:"SKU-FREEZE",qty:1,orderNo:"ORDER-FREEZE",pickStatus:"READY",packStatus:"READY"}});const orderProvenance=explicit("PICK_PACK");await db.workTask.create({data:{id:"order-pick",accountId:"account",sourceType:"ORDER",orderId:"order",stage:"PICK",sequenceNumber:1,requiredQuantity:1,status:"READY",workCardSnapshotJson:JSON.stringify({version:2,sellerSku:"SKU-FREEZE",...orderProvenance}),routeSnapshotJson:JSON.stringify({...createWorkRouteSnapshot({processRoute:"PICK_PACK",currentStage:"PICK"}),...orderProvenance})}});await applyUniversalCandidateAction({actorUserId:"picker",accountId:"account",sourceId:"order",action:"ORDER_PICK_ROUTE",route:"MARK",routeReason:"Marking required",clientRequestId:"order-route"},db);assert.equal((await db.order.findUniqueOrThrow({where:{id:"order"}})).pickStatus,"PICKED");assert.ok(await db.workTask.findFirst({where:{orderId:"order",stage:"MARK"}}));
}finally{await cleanup();}
console.log("Backend-freeze scanner confirmation and immutable route snapshot tests passed.");
