import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync,readFileSync,readdirSync,rmSync } from "node:fs";
import { join,resolve } from "node:path";
import { PrismaClient } from "@prisma/client";

const root=resolve(process.cwd(),".codex-tmp"),file=resolve(root,"backend-freeze-amazon.db"),storage=resolve(root,"backend-freeze-amazon-storage");mkdirSync(root,{recursive:true});rmSync(file,{force:true});rmSync(storage,{recursive:true,force:true});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve("prisma/migrations"),{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>item.name).sort())sqlite.exec(readFileSync(join("prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();process.env.DATABASE_URL=`file:${file.replace(/\\/g,"/")}`;process.env.CONSIGNMENT_IMPORT_ROOT=storage;const db=new PrismaClient({datasourceUrl:process.env.DATABASE_URL});
try{
 await db.account.create({data:{id:"amazon",name:"Amazon",code:"AMZ",marketplace:"AMAZON"}});await db.user.create({data:{id:"owner",username:"mapped-amazon-owner",passwordHash:"x",name:"Owner",role:"OWNER"}});await db.marketplaceListing.create({data:{id:"listing",accountId:"amazon",marketplace:"AMAZON",sku:"SKU-1",sellerSkuId:"SKU-1",productTitle:"Mapped product"}});await db.marketplaceListingIdentifier.createMany({data:[{accountId:"amazon",marketplaceListingId:"listing",marketplace:"AMAZON",identifierType:"SELLER_SKU",rawValue:"SKU-1",normalizedValue:"SKU-1"},{accountId:"amazon",marketplaceListingId:"listing",marketplace:"AMAZON",identifierType:"ASIN",rawValue:"B000000001",normalizedValue:"B000000001"},{accountId:"amazon",marketplaceListingId:"listing",marketplace:"AMAZON",identifierType:"FNSKU",rawValue:"FN-1",normalizedValue:"FN-1"}]});await db.productProcessRule.create({data:{id:"rule",accountId:"amazon",marketplaceListingId:"listing",route:"PICK_PACK",active:true}});
 const csv=["Odd SKU,Odd ASIN,Odd FNSKU,Odd Sent","SKU-1,B000000001,FN-1,2","SKU-1,B000000001,FN-1,0","SKU-1,B000000001,FN-1,","SKU-1,B000000001,FN-1,-2","SKU-1,B000000001,FN-1,1.5","SKU-1,B000000001,FN-1,words"].join("\n"),fileUpload=new File([csv],"unknown-quantity.csv",{type:"text/csv"});const {importAmazonConsignmentDraft}=await import("../src/lib/consignments/amazon/import-service");const {saveHeaderProfile}=await import("../src/lib/imports/header-profiles");const {resumeMappedConsignmentImport}=await import("../src/lib/consignments/resume-mapped-import");
 const first=await importAmazonConsignmentDraft({accountId:"amazon",user:{id:"owner"},externalConsignmentNumber:"MAP-1",files:[fileUpload]});assert.equal(first.needsMapping,true);const job=await db.importJob.findUniqueOrThrow({where:{id:first.mappingJobId!}});assert.equal(job.status,"NEEDS_MAPPING");await saveHeaderProfile({actorUserId:"owner",accountId:"amazon",marketplace:"AMAZON",importPurpose:"CONSIGNMENT_QUANTITY",profileName:"Mapped quantity test",headers:["Odd SKU","Odd ASIN","Odd FNSKU","Odd Sent"],mapping:{sellerSku:"Odd SKU",asin:"Odd ASIN",fnsku:"Odd FNSKU",quantity:"Odd Sent"},requiredFields:["sellerSku","asin","fnsku","quantity"],optionalFields:[]},db);await resumeMappedConsignmentImport({jobId:job.id,accountId:"amazon",user:{id:"owner"}});
 const batch=await db.consignmentBatch.findUniqueOrThrow({where:{id:first.batchId}});assert.equal(batch.status,"REVIEW_REQUIRED");assert.equal(batch.totalSourceRows,6);assert.equal(batch.totalValidLines,1);assert.equal(batch.totalRequiredQuantity,2);assert.equal(await db.consignmentLine.count({where:{consignmentBatchId:batch.id}}),1);assert.equal(await db.consignmentImportIssue.count({where:{consignmentBatchId:batch.id,issueType:"INVALID_QUANTITY",severity:"ERROR"}}),4);assert.equal(await db.workTask.count(),0);const issues=await db.consignmentImportIssue.findMany({where:{consignmentBatchId:batch.id,issueType:"INVALID_QUANTITY"}});assert.deepEqual(issues.map(issue=>issue.rowNumber).sort((a,b)=>(a??0)-(b??0)),[4,5,6,7]);assert.ok(issues.every(issue=>issue.safeDataJson?.includes("unknown-quantity.csv")&&issue.safeDataJson.includes("Mapped headers")));
 const repeated=await importAmazonConsignmentDraft({accountId:"amazon",user:{id:"owner"},externalConsignmentNumber:"MAP-2",files:[new File([`${csv}\n`],"unknown-quantity-repeat.csv",{type:"text/csv"})]});assert.equal(repeated.needsMapping,undefined);const repeatedBatch=await db.consignmentBatch.findUniqueOrThrow({where:{id:repeated.batchId}});assert.equal(repeatedBatch.status,"REVIEW_REQUIRED");assert.equal(await db.consignmentImportIssue.count({where:{consignmentBatchId:repeated.batchId,issueType:"INVALID_QUANTITY"}}),4);
}finally{const {prisma}=await import("../lib/prisma");await prisma.$disconnect();await db.$disconnect();rmSync(file,{force:true});rmSync(storage,{recursive:true,force:true});}
console.log("Backend-freeze real mapped Amazon quantity import tests passed.");
