import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { completeStageAndChooseNext } from "../src/lib/workflow/stage-transition";
import { createWorkRouteSnapshot } from "../src/lib/workflow/dynamic-route";

const root=resolve(process.cwd(),".codex-tmp");mkdirSync(root,{recursive:true});const file=resolve(root,"direct-stage.db");rmSync(file,{force:true});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve("prisma/migrations"),{withFileTypes:true}).filter(entry=>entry.isDirectory()).map(entry=>entry.name).sort())sqlite.exec(readFileSync(join("prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();const db=new PrismaClient({datasourceUrl:`file:${file.replace(/\\/g,"/")}`});
try{
 await db.account.create({data:{id:"account",name:"Direct",code:"DR",marketplace:"FLIPKART"}});await db.user.createMany({data:[{id:"owner",username:"direct-owner",passwordHash:"fake",name:"Owner",role:"OWNER",active:true},{id:"picker",username:"direct-picker",passwordHash:"fake",name:"Picker",role:"PICKER",active:true,accountId:"account",canPick:true},{id:"marker",username:"direct-marker",passwordHash:"fake",name:"Marker",role:"PICKER",active:true,accountId:"account",canMark:true},{id:"assembler",username:"direct-assembler",passwordHash:"fake",name:"Assembler",role:"PICKER",active:true,accountId:"account",canAssemble:true},{id:"packer",username:"direct-packer",passwordHash:"fake",name:"Packer",role:"PACKER",active:true,accountId:"account",canPack:true}]});
 await db.markingAsset.create({data:{id:"asset",name:"Reviewed",masterDesignId:"MD-DIRECT",markingPosition:"Front",markingWidthMm:10,markingHeightMm:10,powerSetting:50,speedSetting:400,instructions:"Use reviewed settings.",status:"ACTIVE",active:true}});await db.marketplaceListing.create({data:{id:"listing",accountId:"account",marketplace:"FLIPKART",sku:"SKU-1",sellerSkuId:"SKU-1",productTitle:"Product"}});await db.productProcessRule.create({data:{id:"rule",accountId:"account",marketplaceListingId:"listing",route:"PICK_MARK_ASSEMBLE_PACK",markingRequired:true,markingAssetId:"asset",assemblyRequired:true,assemblyTitle:"Assemble",assemblyInstructions:"Attach securely.",active:true}});await db.consignmentBatch.create({data:{id:"batch",accountId:"account",marketplace:"FLIPKART",externalConsignmentNumber:"CN",displayName:"Synthetic",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"fake"}});await db.consignmentLine.create({data:{id:"line",consignmentBatchId:"batch",accountId:"account",rowNumber:1,sellerSkuSource:"SKU-1",sellerSkuSnapshot:"SKU-1",requiredQuantity:2,marketplaceListingId:"listing",matchStatus:"OWNER_SELECTED",processRoute:"PICK_MARK_ASSEMBLE_PACK",activated:true}});const pick=await db.workTask.create({data:{id:"pick",accountId:"account",sourceType:"CONSIGNMENT",consignmentLineId:"line",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"READY",metadataJson:JSON.stringify({version:1,processRoute:"PICK_MARK_ASSEMBLE_PACK"}),routeSnapshotJson:JSON.stringify(createWorkRouteSnapshot({processRoute:"PICK_MARK_ASSEMBLE_PACK",currentStage:"PICK"}))}});
 const picked=await completeStageAndChooseNext({actorUserId:"picker",selectedAccountId:"account",taskId:pick.id,currentStage:"PICK",expectedVersion:1,expectedCompletedQuantity:0,useRecommendedNextStage:true,clientRequestId:"pick-default"},db);assert.equal(picked.nextStage,"MARK");const mark=await db.workTask.findFirstOrThrow({where:{consignmentLineId:"line",stage:"MARK"}});assert.equal(mark.status,"READY");
 const marked=await completeStageAndChooseNext({actorUserId:"marker",selectedAccountId:"account",taskId:mark.id,currentStage:"MARK",expectedVersion:mark.version,expectedCompletedQuantity:0,useRecommendedNextStage:true,clientRequestId:"mark-default"},db);assert.equal(marked.nextStage,"ASSEMBLE");const assembly=await db.workTask.findFirstOrThrow({where:{consignmentLineId:"line",stage:"ASSEMBLE"}});
 const assembled=await completeStageAndChooseNext({actorUserId:"assembler",selectedAccountId:"account",taskId:assembly.id,currentStage:"ASSEMBLE",expectedVersion:assembly.version,expectedCompletedQuantity:0,useRecommendedNextStage:true,clientRequestId:"assembly-default"},db);assert.equal(assembled.nextStage,"PACK");const pack=await db.workTask.findFirstOrThrow({where:{consignmentLineId:"line",stage:"PACK"}});
 await assert.rejects(()=>completeStageAndChooseNext({actorUserId:"packer",selectedAccountId:"account",taskId:pack.id,currentStage:"PACK",expectedVersion:pack.version,expectedCompletedQuantity:0,nextStage:"MARK",clientRequestId:"pack-back"},db),/final|backwards/i);const packed=await completeStageAndChooseNext({actorUserId:"packer",selectedAccountId:"account",taskId:pack.id,currentStage:"PACK",expectedVersion:pack.version,expectedCompletedQuantity:0,clientRequestId:"pack-complete"},db);assert.equal(packed.nextStage,null);assert.equal(await db.workChangeEvent.count({where:{accountId:"account"}}),4);
}finally{await db.$disconnect();rmSync(file,{force:true});}
console.log("Direct stage transition tests passed.");
