import assert from "node:assert/strict";
import type { ProcessRoute,WorkStage } from "@prisma/client";
import { createTempWorkflowDb } from "./temp-workflow-db";
import { completeStageAndChooseNext } from "../src/lib/workflow/stage-transition";
import { createWorkRouteSnapshot } from "../src/lib/workflow/dynamic-route";
const {db,cleanup}=createTempWorkflowDb("explicit-destination-overrides");
try{
 await db.account.create({data:{id:"a",name:"A",code:"A",marketplace:"FLIPKART"}});
 await db.user.createMany({data:[{id:"picker",username:"override-picker",passwordHash:"x",name:"Picker",role:"PICKER",accountId:"a",canPick:true},{id:"marker",username:"override-marker",passwordHash:"x",name:"Marker",role:"PICKER",accountId:"a",canMark:true},{id:"assembler",username:"override-assembler",passwordHash:"x",name:"Assembler",role:"PICKER",accountId:"a",canAssemble:true}]});
 await db.markingAsset.create({data:{id:"asset",name:"Asset",masterDesignId:"M",instructions:"Mark",status:"ACTIVE",active:true}});
 await db.marketplaceListing.createMany({data:[{id:"listing",accountId:"a",marketplace:"FLIPKART",sku:"SKU",sellerSkuId:"SKU",productTitle:"Product"},{id:"missing-listing",accountId:"a",marketplace:"FLIPKART",sku:"MISSING",sellerSkuId:"MISSING",productTitle:"Missing"}]});
 await db.productProcessRule.create({data:{id:"instruction-rule",accountId:"a",marketplaceListingId:"listing",route:"PICK_PACK",markingRequired:true,markingAssetId:"asset",assemblyRequired:true,assemblyTitle:"Assemble",assemblyInstructions:"Attach",active:true}});
 await db.consignmentBatch.create({data:{id:"b",accountId:"a",marketplace:"FLIPKART",externalConsignmentNumber:"C",displayName:"C",status:"ACTIVE",sourceFileName:"x",sourceFileSha256:"x"}});
 async function make(id:string,currentStage:WorkStage,route:ProcessRoute,listingId="listing"){await db.consignmentLine.create({data:{id:"l-"+id,consignmentBatchId:"b",accountId:"a",rowNumber:await db.consignmentLine.count()+1,sellerSkuSource:"SKU",sellerSkuSnapshot:"SKU",requiredQuantity:1,marketplaceListingId:listingId,matchStatus:"OWNER_SELECTED",processRoute:route,activated:true}});return db.workTask.create({data:{id:"t-"+id,accountId:"a",sourceType:"CONSIGNMENT",consignmentLineId:"l-"+id,stage:currentStage,sequenceNumber:1,requiredQuantity:1,status:"READY",metadataJson:JSON.stringify({version:1,processRoute:route}),routeSnapshotJson:JSON.stringify(createWorkRouteSnapshot({processRoute:route,currentStage}))}});}
 const pickMark=await make("pick-mark","PICK","PICK_PACK");await completeStageAndChooseNext({actorUserId:"picker",selectedAccountId:"a",taskId:pickMark.id,currentStage:"PICK",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"MARK",routeReason:"Marking required",clientRequestId:"pick-mark"},db);assert.ok(await db.workTask.findFirst({where:{consignmentLineId:"l-pick-mark",stage:"MARK",status:"READY"}}));
 const pickAssembly=await make("pick-assembly","PICK","PICK_PACK");await completeStageAndChooseNext({actorUserId:"picker",selectedAccountId:"a",taskId:pickAssembly.id,currentStage:"PICK",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"ASSEMBLE",routeReason:"Assembly required",clientRequestId:"pick-assembly"},db);assert.ok(await db.workTask.findFirst({where:{consignmentLineId:"l-pick-assembly",stage:"ASSEMBLE",status:"READY"}}));
 const markAssembly=await make("mark-assembly","MARK","PICK_MARK_PACK");await completeStageAndChooseNext({actorUserId:"marker",selectedAccountId:"a",taskId:markAssembly.id,currentStage:"MARK",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"ASSEMBLE",routeReason:"Assembly required",clientRequestId:"mark-assembly"},db);assert.ok(await db.workTask.findFirst({where:{consignmentLineId:"l-mark-assembly",stage:"ASSEMBLE",status:"READY"}}));
 const assemblyMark=await make("assembly-mark","ASSEMBLE","PICK_ASSEMBLE_PACK");await completeStageAndChooseNext({actorUserId:"assembler",selectedAccountId:"a",taskId:assemblyMark.id,currentStage:"ASSEMBLE",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"MARK",routeReason:"Marking required",clientRequestId:"assembly-mark"},db);assert.ok(await db.workTask.findFirst({where:{consignmentLineId:"l-assembly-mark",stage:"MARK",status:"READY"}}));
 const missing=await make("missing","PICK","PICK_PACK","missing-listing");await assert.rejects(()=>completeStageAndChooseNext({actorUserId:"picker",selectedAccountId:"a",taskId:missing.id,currentStage:"PICK",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"MARK",clientRequestId:"missing"},db),/Confirm Continue/);assert.equal((await db.workTask.findUniqueOrThrow({where:{id:missing.id}})).status,"READY");
 await completeStageAndChooseNext({actorUserId:"picker",selectedAccountId:"a",taskId:missing.id,currentStage:"PICK",expectedVersion:1,expectedCompletedQuantity:0,nextStage:"MARK",confirmMissingInstructions:true,workerNote:"Use manual placement",clientRequestId:"missing-confirmed"},db);const manual=await db.workTask.findFirstOrThrow({where:{consignmentLineId:"l-missing",stage:"MARK"}});const metadata=JSON.parse(manual.metadataJson??"{}");assert.equal(metadata.instructionStatus,"MISSING");assert.match(metadata.warning,/MANUAL ROUTE/);assert.equal(metadata.workerNote,"Use manual placement");assert.equal(metadata.powerSetting,undefined);assert.equal(await db.workRouteDecision.count({where:{missingInstructionStage:"MARK",decisionType:"SELECTED_FROM_SYSTEM_FALLBACK"}}),1);
}finally{await cleanup();}
console.log("Explicit destination override tests passed.");
