import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { inventoryDatabase, purgeDatabase, ROOT, TEMP_ROOT } from "../scripts/fresh-db/core.mjs";

mkdirSync(TEMP_ROOT, { recursive: true });
const file = resolve(TEMP_ROOT, "fresh-db-unit-test.db");
rmSync(file, { force: true });
const db = new DatabaseSync(file);
db.exec("PRAGMA foreign_keys=ON;");
const migrations = readdirSync(resolve(ROOT, "prisma", "migrations"), { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();
for (const name of migrations) db.exec(readFileSync(join(ROOT, "prisma", "migrations", name, "migration.sql"), "utf8"));
db.exec(`CREATE TABLE IF NOT EXISTS "_prisma_migrations" (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, finished_at DATETIME, migration_name TEXT NOT NULL, logs TEXT, rolled_back_at DATETIME, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, applied_steps_count INTEGER NOT NULL DEFAULT 0)`);
for (const [index, name] of migrations.entries()) db.prepare('INSERT INTO "_prisma_migrations" (id,checksum,finished_at,migration_name,applied_steps_count) VALUES (?,?,?,?,1)').run(`migration-${index}`, `checksum-${index}`, new Date().toISOString(), name);
const now = new Date().toISOString();
db.prepare('INSERT INTO "User" (id,username,passwordHash,name,role,active,failedLoginCount,accountId,createdAt,updatedAt) VALUES (?,?,?,?,?,1,3,NULL,?,?)').run("owner-id", "synthetic-owner", "synthetic-hash-kept-byte-for-byte", "Synthetic Owner", "OWNER", now, now);
db.prepare('INSERT INTO "User" (id,username,passwordHash,name,role,active,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?)').run("worker-id", "synthetic-worker", "synthetic-worker-hash", "Synthetic Worker", "PICKER", now, now);
db.prepare('INSERT INTO "Account" (id,name,code,companyName,marketplace,active,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?)').run("account-id", "Synthetic Account", "SYNTH", "Synthetic Company", "FLIPKART", now, now);
db.prepare('UPDATE "User" SET accountId=? WHERE id=?').run("account-id", "owner-id");
db.prepare('INSERT INTO "_UserAssignedAccounts" (A,B) VALUES (?,?)').run("account-id", "owner-id");
db.prepare('INSERT INTO "UserDeviceSession" (id,userId,firstSeenAt,lastSeenAt,active) VALUES (?,?,?,?,1)').run("session-id", "owner-id", now, now);
db.prepare('INSERT INTO "PasswordResetRequest" (id,username,userId,status,createdAt,updatedAt) VALUES (?,?,?,?,?,?)').run("reset-id", "synthetic-owner", "owner-id", "OPEN", now, now);
db.prepare('INSERT INTO "AuditLog" (id,userId,accountId,action,createdAt) VALUES (?,?,?,?,?)').run("audit-id", "owner-id", "account-id", "SYNTHETIC_EVENT", now);
db.prepare('INSERT INTO "MarketplaceListing" (id,accountId,marketplace,sellerSkuId,sku,productTitle,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)').run("listing-id", "account-id", "FLIPKART", "SYNTHETIC-SELLER-SKU", "SYNTHETIC-SKU", "Synthetic Product", now, now);
db.close();

const before = inventoryDatabase(file, "synthetic-owner");
assert.equal(before.selectedOwner.username, "synthetic-owner");
assert.equal(before.inventory.find((row) => row.table === "MarketplaceListing").preResetCount, 1);
assert.equal(before.inventory.find((row) => row.table === "_prisma_migrations").classification, "preserve-all");
assert.throws(() => inventoryDatabase(file, "synthetic-worker"), /not OWNER/);
assert.throws(() => inventoryDatabase(file, "missing-owner"), /matched 0 rows/);

const result = purgeDatabase(file, "synthetic-owner", { vacuum: true });
assert.equal(result.passed, true);
assert.equal(result.passwordHashUnchanged, true);
assert.equal(result.migrationsUnchanged, true);
assert.equal(result.counts.User, 1);
assert.equal(result.counts.Account, 0);
assert.equal(result.counts.MarketplaceListing, 0);
assert.equal(result.counts.UserDeviceSession, 0);
assert.equal(result.counts.PasswordResetRequest, 0);
assert.equal(result.counts.AuditLog, 0);
assert.equal(result.counts._prisma_migrations, migrations.length);
const check = new DatabaseSync(file, { readOnly: true });
const preserved = { ...check.prepare('SELECT username,passwordHash,accountId,failedLoginCount,lockedUntil,lastLoginAt FROM "User"').get() };
assert.deepEqual(preserved, { username: "synthetic-owner", passwordHash: "synthetic-hash-kept-byte-for-byte", accountId: null, failedLoginCount: 0, lockedUntil: null, lastLoginAt: null });
check.close();

const refused = spawnSync(process.execPath, ["scripts/fresh-db/reset.mjs", "--owner-username", "synthetic-owner"], { cwd: ROOT, encoding: "utf8" });
assert.equal(refused.status, 2);
assert.match(`${refused.stdout}${refused.stderr}`, /Real reset was not run/);
const sources = ["scripts/fresh-db/core.mjs", "scripts/fresh-db/reset.mjs", "scripts/fresh-db/restore.mjs"].map((path) => readFileSync(resolve(ROOT, path), "utf8")).join("\n");
assert.doesNotMatch(sources, /migrate\s+reset|db\s+push|db\s+seed/i);
assert.match(sources, /DELETE ALL DATA EXCEPT THIS OWNER/);
assert.match(sources, /passwordHashUnchanged/);
assert.ok(existsSync(file));
rmSync(file, { force: true });
console.log("Fresh-start database safety tests passed on a synthetic disposable database.");
