import assert from "node:assert/strict";
import { createTempWorkflowDb } from "./temp-workflow-db";
import { createWorkRouteSnapshot } from "../src/lib/workflow/dynamic-route";
import { getGroupedWork } from "../src/lib/workflow/grouped-work";
import { completeSelectedGroupMembers, setGroupedProgress } from "../src/lib/workflow/grouped-progress";

const {db,cleanup}=createTempWorkflowDb("grouped-member-allocation");
try{
 await db.account.create({data:{id:"a",name:"A",code:"A",marketplace:"FLIPKART"}});await db.user.create({data:{id:"w",username:"allocation-worker",passwordHash:"x",name:"Worker",role:"PICKER",accountId:"a",canPick:true}});await db.uploadBatch.create({data:{id:"b",accountId:"a",fileName:"synthetic.csv"}});
 const quantities=[8,7,6,5,5,5,4,4,3,3],route=JSON.stringify(createWorkRouteSnapshot({processRoute:"PICK_PACK",currentStage:"PICK"}));
 for(let index=0;index<quantities.length;index++){await db.order.create({data:{id:`o${index}`,accountId:"a",batchId:"b",marketplace:"FLIPKART",trackingId:`T${index}`,awb:`A${index}`,sku:"SKU",qty:quantities[index],orderNo:`O${index}`,createdAt:new Date(1_700_000_000_000+index)}});await db.workTask.create({data:{id:`t${index}`,accountId:"a",sourceType:"ORDER",orderId:`o${index}`,stage:"PICK",sequenceNumber:1,requiredQuantity:quantities[index],status:"READY",routeSnapshotJson:route,workCardSnapshotJson:JSON.stringify({sellerSku:"SKU",productTitle:"Varied quantities"}),createdAt:new Date(1_700_000_000_000+index)}});}
 await db.order.create({data:{id:"other-order",accountId:"a",batchId:"b",marketplace:"FLIPKART",trackingId:"OTHER",awb:"OTHER",sku:"OTHER",qty:2,orderNo:"OTHER"}});await db.workTask.create({data:{id:"other-task",accountId:"a",sourceType:"ORDER",orderId:"other-order",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"READY",routeSnapshotJson:route,workCardSnapshotJson:JSON.stringify({sellerSku:"OTHER"})}});
 const initialCards=await getGroupedWork({actorUserId:"w",accountId:"a",stage:"PICK",sourceType:"ORDER",includeMemberIds:true},db),initial=initialCards.cards.find(card=>card.sellerSku==="SKU")!,unrelated=await db.workGroupProjection.findFirstOrThrow({where:{accountId:"a",sellerSku:"OTHER",stage:"PICK"}});
 await setGroupedProgress({actorUserId:"w",selectedAccountId:"a",sourceType:"ORDER",stage:"PICK",groupKey:initial.groupKey,expectedGroupVersion:initial.groupVersion,targetCompletedQuantity:35,useRecommendedNextStage:true,clientRequestId:"fast-35"},db);
 assert.equal(await db.workTask.count({where:{stage:"PACK",order:{sku:"SKU"}}}),5,"Only five fully completed members move forward");assert.deepEqual((await db.workTask.findMany({where:{id:{in:["t0","t1","t2","t3","t4"]}},select:{status:true}})).map(item=>item.status),Array(5).fill("COMPLETED"));const partial=await db.workTask.findUniqueOrThrow({where:{id:"t5"}});assert.equal(partial.completedQuantity,4);assert.equal(partial.status,"IN_PROGRESS");assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"t6"}})).completedQuantity,0);const unrelatedAfter=await db.workGroupProjection.findUniqueOrThrow({where:{groupKey:unrelated.groupKey}});assert.equal(unrelatedAfter.groupVersion,unrelated.groupVersion);assert.equal(unrelatedAfter.updatedAt.getTime(),unrelated.updatedAt.getTime(),"Unrelated projection timestamp remains unchanged");
 const afterFast=(await getGroupedWork({actorUserId:"w",accountId:"a",stage:"PICK",sourceType:"ORDER",includeMemberIds:true},db)).cards.find(card=>card.sellerSku==="SKU")!;assert.equal(afterFast.completedQuantity,35);assert.equal(afterFast.completeMemberCount,5);assert.equal(afterFast.partialMemberCount,1);
 await assert.rejects(()=>completeSelectedGroupMembers({actorUserId:"w",selectedAccountId:"a",sourceType:"ORDER",stage:"PICK",groupKey:afterFast.groupKey,expectedGroupVersion:initial.groupVersion,selectedTaskIds:["t6"],useRecommendedNextStage:true,clientRequestId:"stale"},db),/Work changed/);
 await assert.rejects(()=>completeSelectedGroupMembers({actorUserId:"w",selectedAccountId:"a",sourceType:"ORDER",stage:"PICK",groupKey:afterFast.groupKey,expectedGroupVersion:afterFast.groupVersion,selectedTaskIds:["other-task"],useRecommendedNextStage:true,clientRequestId:"cross-group"},db),/not eligible/);
 await completeSelectedGroupMembers({actorUserId:"w",selectedAccountId:"a",sourceType:"ORDER",stage:"PICK",groupKey:afterFast.groupKey,expectedGroupVersion:afterFast.groupVersion,selectedTaskIds:["t6","t8"],useRecommendedNextStage:true,clientRequestId:"exact"},db);assert.equal(await db.workTask.count({where:{stage:"PACK",order:{sku:"SKU"}}}),7);assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"t7"}})).status,"READY","Unselected member remains");assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"t5"}})).status,"IN_PROGRESS","Partial unselected member remains");
}finally{await cleanup();}
console.log("Grouped varied allocation and exact selection tests passed.");
