import assert from "node:assert/strict";
import { performance } from "node:perf_hooks";
import { createTempWorkflowDb } from "./temp-workflow-db";
import { getGroupedWork,getGroupedWorkDetails,getSmartStageSummary } from "../src/lib/workflow/grouped-work";
import { rebuildWorkGroupProjection } from "../src/lib/workflow/work-group-projection";

const{db,cleanup}=createTempWorkflowDb("grouped-scale"),pickTotal=30_000,packageMembers=4_000,historyTotal=10_000;
const percentile=(values:number[],p:number)=>[...values].sort((a,b)=>a-b)[Math.min(values.length-1,Math.ceil(values.length*p)-1)];
try{
 await db.account.create({data:{id:"scale",name:"Scale",code:"SCALE",marketplace:"FLIPKART"}});await db.user.create({data:{id:"worker",username:"scale-worker",passwordHash:"x",name:"Worker",role:"PICKER",accountId:"scale",canPick:true,canPack:true}});await db.uploadBatch.create({data:{id:"batch",accountId:"scale",fileName:"synthetic.csv"}});
 for(let start=0;start<pickTotal;start+=500){const end=Math.min(pickTotal,start+500);await db.order.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`pick-o${index}`,accountId:"scale",batchId:"batch",marketplace:"FLIPKART",awb:`P-AWB-${index}`,trackingId:`P-TRACK-${index}`,sku:`SKU-${index%500}`,qty:1,orderNo:`P-ORDER-${index}`,orderItemId:`P-ITEM-${index}`,shipmentId:`P-SHIP-${index}`};})});await db.workTask.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`pick-t${index}`,accountId:"scale",sourceType:"ORDER" as const,orderId:`pick-o${index}`,stage:"PICK" as const,sequenceNumber:1,requiredQuantity:1,status:"READY" as const,workCardSnapshotJson:JSON.stringify({sellerSku:`SKU-${index%500}`,productTitle:"Synthetic exact card"})};})});}
 for(let start=0;start<packageMembers;start+=500){const end=Math.min(packageMembers,start+500);await db.order.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`pack-o${index}`,accountId:"scale",batchId:"batch",marketplace:"FLIPKART",awb:`K-AWB-${index}`,trackingId:"PACKAGE-4000",sku:`PACK-SKU-${index%20}`,qty:1,orderNo:`K-ORDER-${index}`,orderItemId:`K-ITEM-${index}`,pickStatus:"PICKED"};})});await db.workTask.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`pack-t${index}`,accountId:"scale",sourceType:"ORDER" as const,orderId:`pack-o${index}`,stage:"PACK" as const,sequenceNumber:2,requiredQuantity:1,status:"READY" as const,workCardSnapshotJson:JSON.stringify({sellerSku:`PACK-SKU-${index%20}`,productTitle:"Synthetic package member"})};})});}
 for(let start=0;start<historyTotal;start+=500){const end=Math.min(historyTotal,start+500);await db.order.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`history-o${index}`,accountId:"scale",batchId:"batch",marketplace:"FLIPKART",awb:`H-AWB-${index}`,trackingId:`H-TRACK-${index}`,sku:"HISTORY",qty:1,orderNo:`H-ORDER-${index}`,orderItemId:`H-ITEM-${index}`,pickStatus:"PICKED"};})});await db.workTask.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:`history-t${index}`,accountId:"scale",sourceType:"ORDER" as const,orderId:`history-o${index}`,stage:"PICK" as const,sequenceNumber:1,requiredQuantity:1,completedQuantity:1,status:"COMPLETED" as const,completedAt:new Date("2024-01-01"),workCardSnapshotJson:JSON.stringify({sellerSku:"HISTORY",productTitle:"Completed history"})};})});}
 await rebuildWorkGroupProjection({accountId:"scale",sourceType:"ORDER",stage:"PICK"},db);await rebuildWorkGroupProjection({accountId:"scale",sourceType:"ORDER",stage:"PACK"},db);
 const first=await getGroupedWork({actorUserId:"worker",accountId:"scale",stage:"PICK",sourceType:"ORDER",page:1,pageSize:25},db),page20=await getGroupedWork({actorUserId:"worker",accountId:"scale",stage:"PICK",sourceType:"ORDER",page:20,pageSize:25},db);assert.equal(await db.workGroupProjection.count({where:{accountId:"scale",sourceType:"ORDER",stage:"PICK"}}),pickTotal);assert.equal(first.cards.length,25);assert.equal(first.hasMore,true);assert.equal(page20.cards.length,25);assert.ok(first.cards.every(card=>card.memberCount===1&&card.requiredQuantity===1),"Pick remains one exact card per Order");
 const summary=await getSmartStageSummary({actorUserId:"worker",accountId:"scale",stage:"PICK"},db);assert.equal(summary.ORDER.cardCount,pickTotal);assert.equal(summary.ORDER.requiredQuantity,pickTotal);
 const pack=(await getGroupedWork({actorUserId:"worker",accountId:"scale",stage:"PACK",sourceType:"ORDER",pageSize:25},db)).cards.find(card=>card.trackingId==="PACKAGE-4000")!;assert.equal(pack.memberCount,packageMembers);assert.equal(pack.requiredQuantity,packageMembers,"Pack remains one Tracking-ID package card");const detail1=await getGroupedWorkDetails({actorUserId:"worker",accountId:"scale",stage:"PACK",sourceType:"ORDER",groupKey:pack.groupKey,page:1,pageSize:50,historyPage:1,historyPageSize:25},db),detail20=await getGroupedWorkDetails({actorUserId:"worker",accountId:"scale",stage:"PACK",sourceType:"ORDER",groupKey:pack.groupKey,page:20,pageSize:50,historyPage:1,historyPageSize:25},db);assert.equal(detail1.tasks.length,50);assert.equal(detail1.total,packageMembers);assert.equal(detail20.tasks.length,50);
 const timings:number[]=[];for(let index=0;index<12;index++){const started=performance.now();await getGroupedWork({actorUserId:"worker",accountId:"scale",stage:"PICK",sourceType:"ORDER",page:1,pageSize:25},db);timings.push(performance.now()-started);}const p95=percentile(timings,0.95);assert.ok(p95<=1000,`Warm first-page p95 ${p95.toFixed(1)}ms exceeds 1 second`);console.log(`Exact-card scale: ${pickTotal} Pick cards, ${packageMembers}-member Pack package, ${historyTotal} completed tasks; first-page p50=${percentile(timings,0.5).toFixed(1)}ms p95=${p95.toFixed(1)}ms max=${Math.max(...timings).toFixed(1)}ms.`);
}finally{await cleanup();}
console.log("Exact-card and package-scale tests passed.");
