import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root=resolve(process.cwd(),".codex-tmp");mkdirSync(root,{recursive:true});const file=resolve(root,"import-job-recovery.db");rmSync(file,{force:true});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve("prisma/migrations"),{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>item.name).sort())sqlite.exec(readFileSync(join("prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();process.env.DATABASE_URL=`file:${file.replace(/\\/g,"/")}`;
const {prisma}=await import("../lib/prisma"),{processImportJob}=await import("../src/lib/import-jobs/runner"),{processProductInventoryJob}=await import("../src/lib/product-inventory/jobs");

try{
 await prisma.account.create({data:{id:"account",name:"Synthetic",code:"SYN",marketplace:"FLIPKART"}});await prisma.user.create({data:{id:"owner",username:"recovery-owner",passwordHash:"x",name:"Owner",role:"OWNER"}});
 const orderFile=resolve(root,"recovery-orders.csv");await writeFile(orderFile,"Shipment ID,ORDER ITEM ID,Order Id,FSN,SKU,Product,Quantity,City,State,Tracking ID\nSHIP-R,ITEM-R,ORDER-R,FSN-R,SKU-R,Synthetic product,1,City,State,TRACK-R\n");
 await prisma.importJob.create({data:{id:"general",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"QUEUED",stage:"QUEUED"}});await Promise.all([processImportJob("general"),processImportJob("general")]);const general=await prisma.importJob.findUniqueOrThrow({where:{id:"general"}});assert.equal(general.status,"COMPLETED");assert.equal(general.attemptNumber,1,"Two runners acquire one conditional lease");assert.equal(await prisma.order.count({where:{accountId:"account",orderItemId:"ITEM-R"}}),1);
 await prisma.importJob.create({data:{id:"stale-parse",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"RUNNING",stage:"PARSING",runnerId:"dead-runner",leaseExpiresAt:new Date(0),attemptNumber:1}});await processImportJob("stale-parse");const stale=await prisma.importJob.findUniqueOrThrow({where:{id:"stale-parse"}});assert.equal(stale.status,"COMPLETED");assert.equal(stale.attemptNumber,2,"Expired parsing lease is reclaimable");
 await prisma.importJob.create({data:{id:"cancelled",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"QUEUED",stage:"QUEUED",cancelRequestedAt:new Date()}});await processImportJob("cancelled");assert.equal((await prisma.importJob.findUniqueOrThrow({where:{id:"cancelled"}})).status,"CANCELLED");
 const catalogDir=resolve(root,"catalog-recovery"),reports=join(catalogDir,"reports");await mkdir(reports,{recursive:true});const entry={id:"entry",displayName:"synthetic.json",relativePath:"unused.csv",normalizedPath:join("reports","entry.json"),size:1,sha256:"synthetic",extension:".csv",classification:"FLIPKART_LISTING_IDENTITY",status:"PARSED",parsedRows:1,inserted:0,enriched:0,unchanged:0,warnings:0};await writeFile(join(reports,"entry.json"),JSON.stringify([{version:1,marketplace:"FLIPKART",accountId:"account",sourceFileId:"entry",sourceTable:"Synthetic",sourceRow:2,sourceProfile:"FLIPKART_LISTING_IDENTITY",sourceAuthority:100,sellerSku:"RECOVERED-SKU",title:"Recovered catalog product",imageUrls:[]} ]));await prisma.importJob.create({data:{id:"catalog",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_PRODUCT_INVENTORY",fileName:"catalog",filePath:catalogDir,status:"RUNNING",stage:"MERGING",runnerId:"dead-catalog-runner",leaseExpiresAt:new Date(0),heartbeatAt:new Date(0),attemptNumber:1,mergeStartedAt:new Date(0),totalFiles:1,manifestJson:JSON.stringify({version:1,marketplace:"FLIPKART",entries:[entry]})}});await Promise.all([processProductInventoryJob("catalog"),processProductInventoryJob("catalog")]);const catalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog"}});assert.equal(catalog.status,"COMPLETED");assert.equal(catalog.attemptNumber,2,"A stale merge resumes under one new lease");assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:"RECOVERED-SKU"}}),1,"Recovered merge remains idempotent");assert.match(catalog.mergeCompletedEntryIdsJson??"",/entry/);
}finally{await prisma.$disconnect();rmSync(file,{force:true});}
console.log("Import runner lease, stale recovery, cancellation, and merge checkpoint tests passed.");
