import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root=resolve(process.cwd(),".codex-tmp");mkdirSync(root,{recursive:true});const file=resolve(root,"import-job-recovery.db");rmSync(file,{force:true});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve("prisma/migrations"),{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>item.name).sort())sqlite.exec(readFileSync(join("prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();process.env.DATABASE_URL=`file:${file.replace(/\\/g,"/")}`;
const {prisma}=await import("../lib/prisma"),{processImportJob}=await import("../src/lib/import-jobs/runner"),{processProductInventoryJob,queueProductInventoryJobRetry}=await import("../src/lib/product-inventory/jobs"),{renewImportJobLease,updateImportJobProgress}=await import("../src/lib/import-jobs/store");
let retryCatalogDir:string|null=null;

try{
 await prisma.account.create({data:{id:"account",name:"Synthetic",code:"SYN",marketplace:"FLIPKART"}});await prisma.user.create({data:{id:"owner",username:"recovery-owner",passwordHash:"x",name:"Owner",role:"OWNER"}});
 const orderFile=resolve(root,"recovery-orders.csv");await writeFile(orderFile,"Shipment ID,ORDER ITEM ID,Order Id,FSN,SKU,Product,Quantity,City,State,Tracking ID\nSHIP-R,ITEM-R,ORDER-R,FSN-R,SKU-R,Synthetic product,1,City,State,TRACK-R\n");
 await prisma.importJob.create({data:{id:"general",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"QUEUED",stage:"QUEUED"}});await Promise.all([processImportJob("general"),processImportJob("general")]);const general=await prisma.importJob.findUniqueOrThrow({where:{id:"general"}});assert.equal(general.status,"COMPLETED");assert.equal(general.attemptNumber,1,"Two runners acquire one conditional lease");assert.equal(await prisma.order.count({where:{accountId:"account",orderItemId:"ITEM-R"}}),1);
 await prisma.importJob.create({data:{id:"stale-parse",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"RUNNING",stage:"PARSING",runnerId:"dead-runner",leaseExpiresAt:new Date(0),attemptNumber:1}});await processImportJob("stale-parse");const stale=await prisma.importJob.findUniqueOrThrow({where:{id:"stale-parse"}});assert.equal(stale.status,"COMPLETED");assert.equal(stale.attemptNumber,2,"Expired parsing lease is reclaimable");
 await prisma.importJob.create({data:{id:"heartbeat",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"heartbeat.csv",status:"RUNNING",stage:"PARSING",runnerId:"runner-a",leaseExpiresAt:new Date(Date.now()+1000)}});await renewImportJobLease("heartbeat","runner-a","PARSING",200);const runnerB=await prisma.importJob.updateMany({where:{id:"heartbeat",status:"RUNNING",leaseExpiresAt:{lt:new Date()}},data:{runnerId:"runner-b",leaseExpiresAt:new Date(Date.now()+1000)}});assert.equal(runnerB.count,0,"A heartbeat keeps the lease exclusive and prevents a second claimant");await prisma.importJob.update({where:{id:"heartbeat"},data:{runnerId:"runner-b",leaseExpiresAt:new Date(Date.now()+1000)}});await assert.rejects(()=>updateImportJobProgress("heartbeat",{processedRows:99},"runner-a"),/lease was lost/i);assert.equal((await prisma.importJob.findUniqueOrThrow({where:{id:"heartbeat"}})).processedRows,0,"The old runner cannot write progress after lease ownership changes");
 await prisma.importJob.create({data:{id:"cancelled",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"recovery-orders.csv",filePath:orderFile,status:"QUEUED",stage:"QUEUED",cancelRequestedAt:new Date()}});await processImportJob("cancelled");assert.equal((await prisma.importJob.findUniqueOrThrow({where:{id:"cancelled"}})).status,"CANCELLED");
 const catalogDir=resolve(root,"catalog-recovery"),reports=join(catalogDir,"reports");await mkdir(reports,{recursive:true});const entry={id:"entry",displayName:"synthetic.json",relativePath:"unused.csv",normalizedPath:join("reports","entry.json"),size:1,sha256:"synthetic",extension:".csv",classification:"FLIPKART_LISTING_IDENTITY",status:"PARSED",parsedRows:1,inserted:0,enriched:0,unchanged:0,warnings:0};await writeFile(join(reports,"entry.json"),JSON.stringify([{version:1,marketplace:"FLIPKART",accountId:"account",sourceFileId:"entry",sourceTable:"Synthetic",sourceRow:2,sourceProfile:"FLIPKART_LISTING_IDENTITY",sourceAuthority:100,sellerSku:"RECOVERED-SKU",title:"Recovered catalog product",imageUrls:[]} ]));await prisma.importJob.create({data:{id:"catalog",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_PRODUCT_INVENTORY",fileName:"catalog",filePath:catalogDir,status:"RUNNING",stage:"MERGING",runnerId:"dead-catalog-runner",leaseExpiresAt:new Date(0),heartbeatAt:new Date(0),attemptNumber:1,mergeStartedAt:new Date(0),totalFiles:1,manifestJson:JSON.stringify({version:1,marketplace:"FLIPKART",entries:[entry]})}});await Promise.all([processProductInventoryJob("catalog"),processProductInventoryJob("catalog")]);const catalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog"}});assert.equal(catalog.status,"COMPLETED");assert.equal(catalog.attemptNumber,2,"A stale merge resumes under one new lease");assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:"RECOVERED-SKU"}}),1,"Recovered merge remains idempotent");assert.match(catalog.mergeCompletedEntryIdsJson??"",/entry/);
 retryCatalogDir=resolve("storage/import-jobs",`job_${randomUUID()}`);const retryReports=join(retryCatalogDir,"reports"),retryEntry={...entry,id:"retry-entry",displayName:"retry.json",normalizedPath:join("reports","retry-entry.json")};await mkdir(retryReports,{recursive:true});await writeFile(join(retryReports,"retry-entry.json"),JSON.stringify([{version:1,marketplace:"FLIPKART",accountId:"account",sourceFileId:"retry-entry",sourceTable:"Synthetic",sourceRow:2,sourceProfile:"FLIPKART_LISTING_IDENTITY",sourceAuthority:100,sellerSku:"RETRY-SKU",title:"Retried catalog product",imageUrls:[]} ]));await writeFile(join(retryCatalogDir,"manifest.json"),JSON.stringify({version:1,marketplace:"FLIPKART",entries:[retryEntry]}));await prisma.importJob.create({data:{id:"catalog-owner-retry",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_PRODUCT_INVENTORY",fileName:"retry catalog",filePath:retryCatalogDir,status:"FAILED",stage:"FAILED",lastError:"Synthetic transient failure",finishedAt:new Date(),totalFiles:1,manifestJson:JSON.stringify({version:1,marketplace:"FLIPKART",entries:[retryEntry]})}});await queueProductInventoryJobRetry({jobId:"catalog-owner-retry",accountId:"account",actorUserId:"owner"});assert.equal((await prisma.importJob.findUniqueOrThrow({where:{id:"catalog-owner-retry"}})).status,"QUEUED","Owner retry reuses the failed job and retained checkpoints");await Promise.all([processProductInventoryJob("catalog-owner-retry"),processProductInventoryJob("catalog-owner-retry")]);const ownerRetriedCatalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog-owner-retry"}});assert.equal(ownerRetriedCatalog.status,"COMPLETED");assert.equal(ownerRetriedCatalog.attemptNumber,1);assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:"RETRY-SKU"}}),1,"Owner retry creates one listing under one lease");assert.equal(await prisma.auditLog.count({where:{action:"PRODUCT_INVENTORY_RETRY_QUEUED",entityId:"catalog-owner-retry"}}),1);
 await prisma.importJob.update({where:{id:"catalog-owner-retry"},data:{status:"RUNNING",stage:"MERGING",runnerId:"live-catalog-runner",leaseExpiresAt:new Date(Date.now()+60_000)}});
 await assert.rejects(()=>queueProductInventoryJobRetry({jobId:"catalog-owner-retry",accountId:"account",actorUserId:"owner"}),/does not need a retry/i,"An active Product Inventory lease cannot be stolen by the owner retry action");
 await prisma.importJob.update({where:{id:"catalog-owner-retry"},data:{runnerId:"dead-catalog-runner",leaseExpiresAt:new Date(0),heartbeatAt:new Date(0)}});
 await queueProductInventoryJobRetry({jobId:"catalog-owner-retry",accountId:"account",actorUserId:"owner"});
 const staleQueuedCatalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog-owner-retry"}});
 assert.equal(staleQueuedCatalog.status,"QUEUED","An expired Product Inventory lease is explicitly reclaimable");
 assert.equal(staleQueuedCatalog.runnerId,null);
 await Promise.all([processProductInventoryJob("catalog-owner-retry"),processProductInventoryJob("catalog-owner-retry")]);
 const staleRetriedCatalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog-owner-retry"}});
 assert.equal(staleRetriedCatalog.status,"COMPLETED");
 assert.equal(staleRetriedCatalog.attemptNumber,2,"Stale owner recovery obtains one new database lease");
 assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:"RETRY-SKU"}}),1,"Checkpoint recovery does not duplicate the listing");
 assert.equal(await prisma.auditLog.count({where:{action:"PRODUCT_INVENTORY_RETRY_QUEUED",entityId:"catalog-owner-retry"}}),2);
 await prisma.importJob.create({data:{id:"catalog-cancelled-retry",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_PRODUCT_INVENTORY",fileName:"cancelled catalog",filePath:retryCatalogDir,status:"CANCELLED",stage:"CANCELLED",manifestJson:JSON.stringify({version:1,marketplace:"FLIPKART",entries:[retryEntry]})}});await assert.rejects(()=>queueProductInventoryJobRetry({jobId:"catalog-cancelled-retry",accountId:"account",actorUserId:"owner"}),/require a new upload/i,"Cancelled Product Inventory retry policy is explicit");

 const cancellationRows=Array.from({length:201},(_,index)=>`SHIP-CANCEL-${index+1},ITEM-CANCEL-${index+1},ORDER-CANCEL-${index+1},FSN-CANCEL,SKU-CANCEL,Synthetic cancellation product,1,City,State,TRACK-CANCEL-${index+1}`);
 const cancellationFile=resolve(root,"cancel-mid-import.csv");
 await writeFile(cancellationFile,["Shipment ID,ORDER ITEM ID,Order Id,FSN,SKU,Product,Quantity,City,State,Tracking ID",...cancellationRows].join("\n"));
 await prisma.marketplaceListing.create({data:{accountId:"account",marketplace:"FLIPKART",sellerSkuId:"SKU-CANCEL",sku:"SKU-CANCEL",fsn:"FSN-CANCEL"}});
 await prisma.importJob.create({data:{id:"cancel-mid-import",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"cancel-mid-import.csv",filePath:cancellationFile,status:"QUEUED",stage:"QUEUED"}});
 await prisma.$executeRawUnsafe(`CREATE TRIGGER cancel_daily_import_after_chunk AFTER INSERT ON "Order" WHEN NEW."orderItemId" = 'ITEM-CANCEL-200' BEGIN UPDATE "Account" SET "active" = 0 WHERE "id" = 'account'; UPDATE "ImportJob" SET "cancelRequestedAt" = CURRENT_TIMESTAMP, "stage" = 'ACCOUNT_DEACTIVATED' WHERE "id" = 'cancel-mid-import'; END`);
 try{await processImportJob("cancel-mid-import");}finally{await prisma.$executeRawUnsafe("DROP TRIGGER IF EXISTS cancel_daily_import_after_chunk");}
 const cancelledDaily=await prisma.importJob.findUniqueOrThrow({where:{id:"cancel-mid-import"}});
 assert.equal(cancelledDaily.status,"CANCELLED","Account deactivation is acknowledged as cancellation rather than failure");
 assert.equal(await prisma.order.count({where:{accountId:"account",orderItemId:{startsWith:"ITEM-CANCEL-"}}}),200,"No later Daily Order chunk mutates after deactivation");
 assert.equal(await prisma.order.count({where:{accountId:"account",orderItemId:"ITEM-CANCEL-201"}}),0);
 assert.equal(await prisma.workTask.count({where:{accountId:"account",order:{orderItemId:"ITEM-CANCEL-201"}}}),0);
 await prisma.account.update({where:{id:"account"},data:{active:true}});

 const cancelledCatalogDir=resolve(root,"catalog-cancel"),cancelledCatalogReports=join(cancelledCatalogDir,"reports");
 await mkdir(cancelledCatalogReports,{recursive:true});
 const cancelledCatalogEntry={...entry,id:"cancel-entry",displayName:"cancel-entry.json",normalizedPath:join("reports","cancel-entry.json"),parsedRows:3};
 const cancelledCatalogRows=Array.from({length:3},(_,index)=>({version:1,marketplace:"FLIPKART",accountId:"account",sourceFileId:"cancel-entry",sourceTable:"Synthetic",sourceRow:index+2,sourceProfile:"FLIPKART_LISTING_IDENTITY",sourceAuthority:400,sellerSku:`CATALOG-CANCEL-${index+1}`,title:`Cancelled catalog ${index+1}`,imageUrls:[]}));
 await writeFile(join(cancelledCatalogReports,"cancel-entry.json"),JSON.stringify(cancelledCatalogRows));
 await prisma.importJob.create({data:{id:"catalog-cancel",accountId:"account",createdByUserId:"owner",marketplace:"FLIPKART",importType:"FLIPKART_PRODUCT_INVENTORY",fileName:"catalog-cancel",filePath:cancelledCatalogDir,status:"QUEUED",stage:"QUEUED",totalFiles:1,manifestJson:JSON.stringify({version:1,marketplace:"FLIPKART",entries:[cancelledCatalogEntry]})}});
 await prisma.$executeRawUnsafe(`CREATE TRIGGER cancel_catalog_import_after_first AFTER INSERT ON "MarketplaceListing" WHEN NEW."sellerSkuId" = 'CATALOG-CANCEL-1' BEGIN UPDATE "Account" SET "active" = 0 WHERE "id" = 'account'; UPDATE "ImportJob" SET "cancelRequestedAt" = CURRENT_TIMESTAMP, "stage" = 'ACCOUNT_DEACTIVATED' WHERE "id" = 'catalog-cancel'; END`);
 try{await processProductInventoryJob("catalog-cancel");}finally{await prisma.$executeRawUnsafe("DROP TRIGGER IF EXISTS cancel_catalog_import_after_first");}
 const cancelledCatalog=await prisma.importJob.findUniqueOrThrow({where:{id:"catalog-cancel"}});
 assert.equal(cancelledCatalog.status,"CANCELLED","Product Inventory deactivation is acknowledged as cancellation rather than failure");
 assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:{startsWith:"CATALOG-CANCEL-"}}}),1,"Per-row lease checks stop the remaining catalog merge");
 assert.equal(await prisma.marketplaceListing.count({where:{accountId:"account",sellerSkuId:"CATALOG-CANCEL-2"}}),0);
 const importJobPage=readFileSync(resolve("app/owner/imports/[jobId]/page.tsx"),"utf8");
 assert.match(importJobPage,/\["QUEUED","RUNNING"\]\.includes\(job\.status\)/,"Queued and running Product Inventory jobs expose cancellation");
 assert.doesNotMatch(importJobPage,/&&\s*!job\.mergeStartedAt/,"The owner cancellation control remains available during merge");
 assert.match(importJobPage,/Cancel import safely/);
 assert.match(importJobPage,/staleProductInventoryRun/);
 const importJobActions=readFileSync(resolve("app/owner/imports/[jobId]/actions.ts"),"utf8");
 assert.match(importJobActions,/sanitizePublicActionError\(error,/,"Product Inventory retry errors cross a sanitized public boundary");
}finally{await prisma.$disconnect();rmSync(file,{force:true});if(retryCatalogDir)rmSync(retryCatalogDir,{recursive:true,force:true});}
console.log("Import runner lease, stale recovery, cancellation, and merge checkpoint tests passed.");
