import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { PUBLIC_IMPORT_JOB_FIELDS, sanitizePublicImportJobError, toPublicImportJob } from "../src/lib/import-jobs/public-job";
import { failImportJob, type ImportJobRecord } from "../src/lib/import-jobs/store";
import { createTempWorkflowDb } from "./temp-workflow-db";

const now=new Date("2026-01-02T03:04:05.000Z");
const internal:ImportJobRecord={id:"job-public",accountId:"private-account",createdByUserId:"private-user",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"C:\\private\\orders.xlsx",filePath:"C:\\private\\retained\\job.bin",batchId:"batch-public",status:"FAILED",totalRows:10,processedRows:5,createdRows:2,updatedRows:1,unchangedRows:2,duplicateRows:3,warningRows:1,errorRows:1,missingListingRows:1,missingImageRows:1,startedAt:now,finishedAt:now,lastError:"Failed at /home/runner/private/orders.xlsx and C:\\private\\secret.xlsx",stage:"FAILED",currentFile:"/srv/private/chunk-2.xlsx",totalFiles:2,processedFiles:1,manifestJson:'{"private":"manifest"}',progressJson:'{"private":"progress"}',reportJson:'{"private":"report"}',cancelRequestedAt:now,mergeStartedAt:now,runnerId:"lease-owner-private",leaseExpiresAt:now,heartbeatAt:now,attemptNumber:4,checkpointJson:'{"private":"checkpoint"}',currentEntryId:"private-entry",currentChunk:7,mergeCompletedEntryIdsJson:'["private-entry"]',createdAt:now,updatedAt:now};
const publicJob=toPublicImportJob(internal),serialized=JSON.stringify(publicJob);
assert.deepEqual(Object.keys(publicJob).sort(),[...PUBLIC_IMPORT_JOB_FIELDS].sort(),"The browser DTO is an explicit field allowlist");
for(const key of ["accountId","createdByUserId","filePath","manifestJson","progressJson","reportJson","cancelRequestedAt","mergeStartedAt","runnerId","leaseExpiresAt","heartbeatAt","attemptNumber","checkpointJson","currentEntryId","currentChunk","mergeCompletedEntryIdsJson"])assert.ok(!(key in publicJob),`${key} is server-only`);
assert.equal(publicJob.fileName,"orders.xlsx");assert.equal(publicJob.currentFile,"chunk-2.xlsx");assert.doesNotMatch(serialized,/C:\\\\private|\/home\/runner|\/srv\/private|lease-owner-private|checkpoint|manifest|progress/i);const generic="Import failed. Review the job and retry when safe.";for(const unsafe of ["C:\\Private Folder\\x.xlsx","/srv/private folder/x.xlsx","Error:/opt/private folder/x.xlsx","\\\\server\\private share\\x.xlsx","file:///tmp/private folder/x.xlsx","Failed at /var/private/job.log","PrismaClientKnownRequestError P2002","P2034 write conflict","P2028 transaction error","P1008 timeout","SQLITE_BUSY database is locked","SQLITE_CONSTRAINT unique constraint failed","INSERT INTO ImportJob VALUES (secret)","UPDATE ImportJob SET lastError = secret"])assert.equal(sanitizePublicImportJobError(unsafe),generic);assert.equal(sanitizePublicImportJobError("Download https://example.test/help"),"Download https://example.test/help");assert.equal(sanitizePublicImportJobError("\u0000\nImport failed"),"Import failed");

const {db,cleanup}=createTempWorkflowDb("import-job-public-error");try{await db.account.create({data:{id:"safe-account",name:"Safe",code:"SAFE",marketplace:"FLIPKART"}});await db.user.create({data:{id:"safe-owner",username:"safe-owner",passwordHash:"fake",name:"Safe Owner",role:"OWNER",active:true}});await db.importJob.create({data:{id:"stored-error",accountId:"safe-account",createdByUserId:"safe-owner",marketplace:"FLIPKART",importType:"FLIPKART_ORDER",fileName:"synthetic.xlsx"}});await failImportJob("stored-error",new Error("Failed C:\\Private Folder\\a.xlsx, \\\\server\\private share\\b.xlsx, file:///tmp/private folder/c.xlsx and /home/runner/private folder/d.xlsx"),db);const stored=await db.importJob.findUniqueOrThrow({where:{id:"stored-error"},select:{lastError:true}});assert.equal(stored.lastError,generic);}finally{await cleanup();}

const page=readFileSync(resolve("app/owner/imports/[jobId]/page.tsx"),"utf8"),statusRoute=readFileSync(resolve("app/owner/imports/[jobId]/status/route.ts"),"utf8"),component=readFileSync(resolve("components/ImportJobProgress.tsx"),"utf8"),mobileRoute=readFileSync(resolve("app/api/mobile/owner/imports/[jobId]/route.ts"),"utf8"),exportRoute=readFileSync(resolve("app/owner/imports/export/route.ts"),"utf8"),retryActions=readFileSync(resolve("app/owner/imports/[jobId]/actions.ts"),"utf8"),refreshActions=readFileSync(resolve("app/owner/product-inventory/refresh/actions.ts"),"utf8");
assert.match(page,/initialJob=\{toPublicImportJob\(job\)\}/);assert.match(statusRoute,/job:\s*toPublicImportJob\(job\)/);assert.match(component,/PublicImportJobRecord/);assert.doesNotMatch(component,/import-jobs\/store/);assert.doesNotMatch(component,/\bImportJobRecord\b/);assert.match(mobileRoute,/job:\s*toPublicImportJob\(job\)/);assert.doesNotMatch(mobileRoute,/\.\.\.job/);assert.match(exportRoute,/sanitizePublicImportJobError\(job\.lastError\)/);
assert.match(retryActions,/sanitizePublicActionError\(error,/,"Retry redirects sanitize internal errors");assert.match(refreshActions,/sanitizePublicActionError\(error,/,"Product Inventory upload redirects sanitize internal errors");
console.log("Public ImportJob DTO and private-path sanitization tests passed.");
