import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { classifyFlipkartHeaders, flipkartCatalogRows } from "../src/lib/product-inventory/classifier";
import { mergeMarketplaceCatalogRows } from "../src/lib/product-inventory/merge";
import { safeCatalogImageUrl, type MarketplaceCatalogRowV1 } from "../src/lib/product-inventory/catalog";
import { consumeProductInventoryArchiveBudget, createProductInventoryArchiveBudget, PRODUCT_INVENTORY_MAX_TOTAL_BYTES, validateCatalogArchiveEntryName } from "../src/lib/product-inventory/jobs";
import { searchProductInventory } from "../src/lib/product-inventory/search";

const root=resolve(process.cwd(),".codex-tmp");mkdirSync(root,{recursive:true});const file=resolve(root,"product-inventory-import.db");rmSync(file,{force:true});const sqlite=new DatabaseSync(file);sqlite.exec("PRAGMA foreign_keys=ON;");for(const name of readdirSync(resolve("prisma/migrations"),{withFileTypes:true}).filter(item=>item.isDirectory()).map(item=>item.name).sort())sqlite.exec(readFileSync(join("prisma/migrations",name,"migration.sql"),"utf8"));sqlite.close();const db=new PrismaClient({datasourceUrl:`file:${file.replace(/\\/g,"/")}`});
const row=(values:Partial<MarketplaceCatalogRowV1>):MarketplaceCatalogRowV1=>({version:1,marketplace:"AMAZON",accountId:"a1",sourceFileId:"fake-file",sourceTable:"Fake Data",sourceRow:2,sourceProfile:"AMAZON_ALL_LISTINGS",sourceAuthority:90,...values});
try{
 assert.throws(()=>validateCatalogArchiveEntryName("../private.csv"),/unsafe entry path/);assert.throws(()=>validateCatalogArchiveEntryName("nested.zip"),/nested archive/);assert.throws(()=>validateCatalogArchiveEntryName("run.exe"),/executable/);assert.equal(validateCatalogArchiveEntryName("catalog/data.xlsx"),".xlsx");
 const aggregateBytes=createProductInventoryArchiveBudget();consumeProductInventoryArchiveBudget(aggregateBytes,PRODUCT_INVENTORY_MAX_TOTAL_BYTES-1);assert.throws(()=>consumeProductInventoryArchiveBudget(aggregateBytes,2),/job-wide aggregate/i,"Separate archives and standalone entries share one byte budget");const aggregateEntries=createProductInventoryArchiveBudget();for(let index=0;index<100;index++)consumeProductInventoryArchiveBudget(aggregateEntries,0);assert.throws(()=>consumeProductInventoryArchiveBudget(aggregateEntries,0),/too many files/i,"Separate archives share one entry budget");
 await db.account.createMany({data:[{id:"a1",name:"Fake A",code:"FA",companyName:"Fake",marketplace:"AMAZON",active:true},{id:"a2",name:"Fake B",code:"FB",companyName:"Fake",marketplace:"AMAZON",active:true}]});await db.user.create({data:{id:"u1",username:"fake-owner",passwordHash:"fake",name:"Fake Owner",role:"OWNER"}});
 await db.marketplaceListing.create({data:{id:"existing",accountId:"a1",marketplace:"AMAZON",sellerSkuId:"SKU-EXISTING",sku:"SKU-EXISTING",productTitle:"Manual title",mainImageUrl:"https://example.invalid/existing.jpg",manualLocksJson:JSON.stringify({productTitle:true})}});await db.marketplaceListingIdentifier.create({data:{accountId:"a1",marketplaceListingId:"existing",marketplace:"AMAZON",identifierType:"ASIN",rawValue:"B000EXIST1",normalizedValue:"B000EXIST1"}});await db.productProcessRule.create({data:{id:"rule",accountId:"a1",marketplaceListingId:"existing",route:"PICK_PACK",active:true}});await db.markingAsset.create({data:{id:"asset",name:"Fake Asset"}});await db.markingAssetListingLink.create({data:{id:"link",markingAssetId:"asset",marketplaceListingId:"existing",accountId:"a1",marketplace:"AMAZON",matchMethod:"MANUAL"}});
 const first=await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sellerSku:"SKU-NEW",internalSku:"INT-NEW",fsn:"FSN-NEW",listingId:"LISTING-NEW",asin:"B000FAKE01",title:"Fake Searchable New Product",brand:"Fake Brand",mainImageUrl:"https://example.invalid/new.jpg",imageUrls:Array.from({length:12},(_,i)=>`https://example.invalid/${i}.jpg`)}),row({sellerSku:"SKU-EXISTING",title:"Automated replacement",brand:"Enriched Brand",mainImageUrl:"javascript:alert(1)"})]},db);assert.equal(first.inserted,1);assert.equal(first.enriched,1);assert.ok(first.conflicts.some(item=>item.reason.includes("productTitle")));const existing=await db.marketplaceListing.findUniqueOrThrow({where:{id:"existing"}});assert.equal(existing.productTitle,"Manual title","Nonblank value is preserved");assert.equal(existing.liveBrand,"Enriched Brand");assert.equal(await db.productProcessRule.count({where:{marketplaceListingId:"existing"}}),1);assert.equal(await db.markingAssetListingLink.count({where:{marketplaceListingId:"existing"}}),1);
 const created=await db.marketplaceListing.findFirstOrThrow({where:{accountId:"a1",sellerSkuId:"SKU-NEW"}});assert.equal(created.imageUrl10,"https://example.invalid/8.jpg");assert.equal(await db.marketplaceListingIdentifier.count({where:{marketplaceListingId:created.id,identifierType:"ASIN"}}),1);
 await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sellerSku:"SKU-BLANK",asin:"B000BLANK1"})]},db);const blank=await db.marketplaceListing.findFirstOrThrow({where:{accountId:"a1",sellerSkuId:"SKU-BLANK"}});const blankProvenance=JSON.parse(blank.fieldProvenanceJson??"{}") as Record<string,unknown>;assert.equal(blankProvenance.productTitle,undefined,"Blank fields receive no false high-authority provenance");await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sourceProfile:"AMAZON_CATEGORY_CATALOG",sellerSku:"IGNORED",asin:"B000BLANK1",title:"Category filled title",mainImageUrl:"https://example.invalid/category-filled.jpg"})]},db);const filled=await db.marketplaceListing.findUniqueOrThrow({where:{id:blank.id}});assert.equal(filled.productTitle,"Category filled title");assert.equal(filled.mainImageUrl,"https://example.invalid/category-filled.jpg");
 const category=await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sourceProfile:"AMAZON_CATEGORY_CATALOG",sellerSku:"UNKNOWN-CATALOG-SKU",asin:"B000EXIST1",description:"Catalog enrichment"}),row({sourceProfile:"AMAZON_CATEGORY_CATALOG",sellerSku:"CATEGORY-ONLY",title:"Must not create"})]},db);assert.equal(category.inserted,0,"Amazon category rows cannot create products");assert.equal((await db.marketplaceListing.findUniqueOrThrow({where:{id:"existing"}})).description,"Catalog enrichment","Category-only refresh can enrich an exact existing product");assert.equal(await db.marketplaceListing.count({where:{sellerSkuId:"CATEGORY-ONLY"}}),0);
 await db.marketplaceListing.update({where:{id:"existing"},data:{manualLocksJson:JSON.stringify({})}});await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sellerSku:"SKU-EXISTING",title:"Owner unlocked replacement"})]},db);assert.equal((await db.marketplaceListing.findUniqueOrThrow({where:{id:"existing"}})).productTitle,"Owner unlocked replacement","Clearing the manual lock permits a later authoritative refresh");
 const second=await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sellerSku:"SKU-NEW",asin:"B000FAKE01",title:"Fake New",listingStatus:"INACTIVE",mrp:999,sellingPrice:799,mainImageUrl:"https://example.invalid/revised.jpg"})]},db);assert.equal(second.inserted,0);const refreshed=await db.marketplaceListing.findFirstOrThrow({where:{accountId:"a1",sellerSkuId:"SKU-NEW"}});assert.equal(refreshed.productTitle,"Fake New","A newer same-authority report refreshes an automated title");assert.equal(refreshed.listingStatus,"INACTIVE");assert.equal(Number(refreshed.sellingPrice),799);assert.equal(refreshed.mainImageUrl,"https://example.invalid/revised.jpg");assert.ok(refreshed.imageCacheStaleAt,"Changing an authoritative image invalidates its cache");const retry=await mergeMarketplaceCatalogRows({accountId:"a1",marketplace:"AMAZON",rows:[row({sellerSku:"SKU-NEW",asin:"B000FAKE01",title:"Fake New",listingStatus:"INACTIVE",mrp:999,sellingPrice:799,mainImageUrl:"https://example.invalid/revised.jpg"})]},db);assert.equal(retry.enriched,0,"Repeating the same report is idempotent");assert.equal(await db.marketplaceListing.count({where:{accountId:"a1",sellerSkuId:"SKU-NEW"}}),1,"Retry is idempotent");await mergeMarketplaceCatalogRows({accountId:"a2",marketplace:"AMAZON",rows:[{...row({sellerSku:"SKU-NEW",title:"Other account"}),accountId:"a2"}]},db);assert.equal(await db.marketplaceListing.count({where:{sellerSkuId:"SKU-NEW"}}),2,"Same SKU remains account scoped");
 const exactSku=await searchProductInventory(db,{accountId:"a1",query:"SKU-NEW"});assert.equal(exactSku.listings[0]?.sellerSkuId,"SKU-NEW","Exact Seller SKU ranks first");assert.equal((await searchProductInventory(db,{accountId:"a1",query:"INT-NEW"})).listings[0]?.id,created.id,"Exact internal SKU returns product");assert.equal((await searchProductInventory(db,{accountId:"a1",query:"FSN-NEW"})).listings[0]?.id,created.id,"Exact FSN returns product");assert.equal((await searchProductInventory(db,{accountId:"a1",query:"LISTING-NEW"})).listings[0]?.id,created.id,"Exact Listing ID returns product");assert.equal((await searchProductInventory(db,{accountId:"a1",query:"Fake New"})).listings[0]?.id,created.id,"Refreshed title contains search returns product");
 await db.marketplaceListing.create({data:{id:"duplicate-id-listing",accountId:"a1",marketplace:"AMAZON",sellerSkuId:"SKU-DUP-ID",sku:"SKU-DUP-ID",productTitle:"Duplicate identifier product"}});await db.marketplaceListingIdentifier.create({data:{accountId:"a1",marketplaceListingId:"duplicate-id-listing",marketplace:"AMAZON",identifierType:"ASIN",rawValue:"B000FAKE01",normalizedValue:"B000FAKE01"}});const otherAccountListing=await db.marketplaceListing.findFirstOrThrow({where:{accountId:"a2",sellerSkuId:"SKU-NEW"}});await db.marketplaceListingIdentifier.create({data:{accountId:"a2",marketplaceListingId:otherAccountListing.id,marketplace:"AMAZON",identifierType:"ASIN",rawValue:"B000FAKE01",normalizedValue:"B000FAKE01"}});const duplicateIdentifier=await searchProductInventory(db,{accountId:"a1",query:"B000FAKE01"});assert.equal(duplicateIdentifier.exactCount,2,"Duplicate identifier within account is visible for review");assert.equal(duplicateIdentifier.listings.every(item=>item.accountId==="a1"),true,"Same identifier in another account never crosses account scope");
 await db.marketplaceListing.update({where:{id:"duplicate-id-listing"},data:{listingStatus:"INACTIVE",mainImageUrl:null}});assert.equal((await searchProductInventory(db,{accountId:"a1",status:"inactive"})).listings.some(item=>item.id==="duplicate-id-listing"),true,"Inactive listing filter works");assert.equal((await searchProductInventory(db,{accountId:"a1",image:"missing"})).listings.some(item=>item.id==="duplicate-id-listing"),true,"Missing-image filter works");
 const support=classifyFlipkartHeaders(["Seller SKU","Product Type","Colour"]);assert.equal(support.classification,"FLIPKART_CATEGORY_CATALOG");const imageOnly=classifyFlipkartHeaders(["Product Title","Category","Image URL 1"]);assert.equal(imageOnly.classification,"UNKNOWN");const parsed=flipkartCatalogRows({accountId:"a1",sourceFileId:"fake",rows:[{"Seller SKU":"FK-1","Product Type":"Pendant","Colour":"Silver"}]});assert.equal(parsed.rows[0].sellerSku,"FK-1");assert.equal(parsed.rows[0].productType,"Pendant");assert.equal(safeCatalogImageUrl("file:///private/fake.jpg"),null);assert.equal(await db.marketplaceListing.count({where:{sellerSkuId:"MISSING"}}),0,"Missing refresh rows never delete products");
}finally{await db.$disconnect();rmSync(file,{force:true});}
console.log("Product Inventory classification and merge tests passed.");
