import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { completeConsignmentPickWithRoute, completeOrderPickWithRoute, type PostPickRoute } from "../src/lib/workflow/route-selection";
import { packCustomerOrderShipmentSafely } from "../src/lib/workflow/order-pack-scope";
import { completeOrderMarkingTask } from "../src/lib/workflow/order-route-tasks";
import { completeOrderAssemblyTask } from "../src/lib/workflow/order-assembly";
import { completeWorkTask } from "../src/lib/workflow/task-store";
import { parseOrderAssemblyMetadata } from "../src/lib/workflow/order-assembly-metadata";
import { parseConsignmentAssemblyMetadata, parseOrderMarkingMetadata } from "../src/lib/workflow/route-task-metadata";
import { resolveUniversalWork } from "../src/lib/workflow/universal-resolver";
import { getOrderMarkingQueue } from "../src/lib/workflow/order-route-tasks";

const root = resolve(process.cwd(), ".codex-tmp"); mkdirSync(root, { recursive: true });
const file = resolve(root, "production-flow.db"); rmSync(file, { force: true });
const sqlite = new DatabaseSync(file); sqlite.exec("PRAGMA foreign_keys=ON;");
for (const name of readdirSync(resolve("prisma/migrations"), { withFileTypes: true }).filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort()) sqlite.exec(readFileSync(join("prisma/migrations", name, "migration.sql"), "utf8"));
sqlite.close();
const db = new PrismaClient({ datasourceUrl: `file:${file.replace(/\\/g, "/")}` });
const routes: Array<[PostPickRoute, string[]]> = [["DIRECT_PACK", ["PICK", "PACK"]], ["MARK", ["PICK", "MARK", "PACK"]], ["ASSEMBLE", ["PICK", "ASSEMBLE", "PACK"]], ["MARK_ASSEMBLE", ["PICK", "MARK", "ASSEMBLE", "PACK"]]];

try {
  await db.account.createMany({ data: [{ id: "account", name: "Production Flow", code: "PF", companyName: "Fake", marketplace: "FLIPKART" }, { id: "other", name: "Other", code: "OT", companyName: "Fake", marketplace: "FLIPKART" }] });
  await db.user.createMany({ data: [{ id: "owner", username: "owner-flow", passwordHash: "fake", name: "Owner", role: "OWNER", active: true }, { id: "picker", username: "picker-flow", passwordHash: "fake", name: "Picker", role: "PICKER", active: true, accountId: "account", canPick: true }, { id: "packer", username: "packer-flow", passwordHash: "fake", name: "Packer", role: "PACKER", active: true, accountId: "account", canPack: true }, { id:"viewer",username:"viewer-flow",passwordHash:"fake",name:"Viewer",role:"PICKER",active:true,accountId:"account",canViewAllWork:true }] });
  await db.uploadBatch.create({ data: { id: "upload", accountId: "account", fileName: "fake.csv" } });
  await db.markingAsset.create({ data: { id: "marking", name: "Reviewed marking", masterDesignId: "MD-1", markingPosition: "Front centre", markingWidthMm: 20, markingHeightMm: 10, powerSetting: 70, speedSetting: 500, instructions: "Use the reviewed fixture settings.", active: true, status: "ACTIVE" } });
  for (const [index, [route, stages]] of routes.entries()) {
    const orderId = `order-${index}`;
    const processRoute = route === "DIRECT_PACK" ? "PICK_PACK" : route === "MARK" ? "PICK_MARK_PACK" : route === "ASSEMBLE" ? "PICK_ASSEMBLE_PACK" : "PICK_MARK_ASSEMBLE_PACK";
    await db.marketplaceListing.create({ data: { id: `listing-${index}`, accountId: "account", marketplace: "FLIPKART", sellerSkuId: `SKU-${index}`, sku: `SKU-${index}`, productTitle: `Product ${index}`, mainImageUrl: `https://example.test/product-${index}.jpg` } });
    await db.marketplaceListingIdentifier.create({ data: { accountId: "account", marketplace: "FLIPKART", marketplaceListingId: `listing-${index}`, identifierType: "SELLER_SKU", rawValue: `SKU-${index}`, normalizedValue: `SKU-${index}`, active: true } });
    await db.productProcessRule.create({ data: { id: `rule-${index}`, accountId: "account", marketplaceListingId: `listing-${index}`, route: processRoute, markingRequired: route === "MARK" || route === "MARK_ASSEMBLE", markingAssetId: route === "MARK" || route === "MARK_ASSEMBLE" ? "marking" : null, assemblyRequired: route === "ASSEMBLE" || route === "MARK_ASSEMBLE", assemblyTitle: route === "ASSEMBLE" || route === "MARK_ASSEMBLE" ? "Attach reviewed component" : null, assemblyInstructions: route === "ASSEMBLE" || route === "MARK_ASSEMBLE" ? "Attach the synthetic component securely." : null, active: true } });
    await db.order.create({ data: { id: orderId, accountId: "account", batchId: "upload", marketplace: "FLIPKART", awb: `AWB-${index}`, trackingId: `TRACK-${index}`, orderItemId: `ITEM-${index}`, sku: `SKU-${index}`, qty: 2, orderNo: `ORDER-${index}`, pickStatus: "READY", packStatus: "READY", status: "READY" } });
    const first = await completeOrderPickWithRoute({ orderIds: [orderId], accountId: "account", actorUserId: "picker", route, clientRequestId: `order-route-${index}` }, db);
    const replay = await completeOrderPickWithRoute({ orderIds: [orderId], accountId: "account", actorUserId: "picker", route, clientRequestId: `order-route-${index}` }, db);
    assert.equal(first.idempotent, false); assert.equal(replay.idempotent, true);
    assert.deepEqual((await db.workTask.findMany({ where: { orderId }, orderBy: { sequenceNumber: "asc" } })).map((task) => task.stage), stages);
    await assert.rejects(() => completeOrderPickWithRoute({ orderIds: [orderId], accountId: "account", actorUserId: "picker", route: route === "DIRECT_PACK" ? "MARK" : "DIRECT_PACK" }, db), /different route/i);
    const tasks=await db.workTask.findMany({where:{orderId},orderBy:{sequenceNumber:"asc"}});const mark=tasks.find(task=>task.stage==="MARK");const assembly=tasks.find(task=>task.stage==="ASSEMBLE");const pack=tasks.find(task=>task.stage==="PACK")!;
    if(mark){assert.ok(parseOrderMarkingMetadata(mark.metadataJson),"Order Mark has a valid immutable instruction snapshot");const scan=await resolveUniversalWork({actorUserId:"owner",accountId:"account",code:`SKU-${index}`,intent:"MARK"},db);assert.ok(scan.candidates.some(candidate=>candidate.actionType==="ORDER_MARK"&&candidate.taskId===mark.id),"Universal Scanner finds Order MARK work");const viewerScan=await resolveUniversalWork({actorUserId:"viewer",accountId:"account",code:`SKU-${index}`,intent:"MARK"},db);assert.equal(viewerScan.candidates.find(candidate=>candidate.taskId===mark.id)?.canAct,false,"canViewAllWork does not grant marking mutation");assert.ok((await getOrderMarkingQueue({accountId:"account",actorUserId:"viewer",search:`SKU-${index}`},db)).some(task=>task.id===mark.id),"View-only user can inspect the marking card");await assert.rejects(()=>completeOrderMarkingTask({taskId:mark.id,accountId:"account",actorUserId:"viewer",expectedStatus:"READY",clientRequestId:`viewer-mark-${index}`},db),/permission/i);await assert.rejects(()=>packCustomerOrderShipmentSafely({actorUserId:"packer",accountId:"account",orderId,source:"packing-detail"},db),/Marking is required/i);const duplicateRequest=`mark-${index}`;const results=await Promise.all([completeOrderMarkingTask({taskId:mark.id,accountId:"account",actorUserId:"owner",expectedStatus:"READY",clientRequestId:duplicateRequest},db),completeOrderMarkingTask({taskId:mark.id,accountId:"account",actorUserId:"owner",expectedStatus:"READY",clientRequestId:duplicateRequest},db)]);assert.equal(results.filter(result=>!result.idempotent).length,1);assert.equal(await db.workActionLog.count({where:{taskId:mark.id,clientRequestId:duplicateRequest}}),1,"Duplicate Mark completion writes one action log");}
    if(assembly){assert.ok(parseOrderAssemblyMetadata(assembly.metadataJson),"Order Assembly has valid metadata");assert.equal((await db.workTask.findUniqueOrThrow({where:{id:assembly.id}})).status,"READY");const scan=await resolveUniversalWork({actorUserId:"owner",accountId:"account",code:`SKU-${index}`,intent:"ASSEMBLE"},db);assert.ok(scan.candidates.some(candidate=>candidate.taskId===assembly.id),"Universal Scanner finds Order ASSEMBLE work");await assert.rejects(()=>packCustomerOrderShipmentSafely({actorUserId:"packer",accountId:"account",orderId,source:"packing-detail"},db),/Assembly is required/i);await completeOrderAssemblyTask({taskId:assembly.id,accountId:"account",actorUserId:"owner",expectedStatus:"READY",clientRequestId:`assembly-${index}`},db);}
    assert.equal((await db.workTask.findUniqueOrThrow({where:{id:pack.id}})).status,"READY");await packCustomerOrderShipmentSafely({actorUserId:"packer",accountId:"account",orderId,source:"packing-detail",clientRequestId:`pack-${index}`},db);
  }

  await db.consignmentBatch.create({ data: { id: "batch", accountId: "account", marketplace: "FLIPKART", externalConsignmentNumber: "CN-1", displayName: "Fake", status: "ACTIVE", sourceFileName: "fake.csv", sourceFileSha256: "fake" } });
  for (const [index, [route, stages]] of routes.entries()) {
    const lineId = `line-${index}`, taskId = `pick-${index}`;
    const processRoute = route === "DIRECT_PACK" ? "PICK_PACK" : route === "MARK" ? "PICK_MARK_PACK" : route === "ASSEMBLE" ? "PICK_ASSEMBLE_PACK" : "PICK_MARK_ASSEMBLE_PACK";
    await db.marketplaceListing.create({ data: { id: `clisting-${index}`, accountId: "account", marketplace: "FLIPKART", sellerSkuId: `CSKU-${index}`, sku: `CSKU-${index}`, productTitle: `Consignment Product ${index}` } });
    await db.productProcessRule.create({ data: { id: `crule-${index}`, accountId: "account", marketplaceListingId: `clisting-${index}`, route: processRoute, markingRequired: route === "MARK" || route === "MARK_ASSEMBLE", markingAssetId: route === "MARK" || route === "MARK_ASSEMBLE" ? "marking" : null, assemblyRequired: route === "ASSEMBLE" || route === "MARK_ASSEMBLE", assemblyTitle: route === "ASSEMBLE" || route === "MARK_ASSEMBLE" ? "Consignment assembly" : null, assemblyInstructions: route === "ASSEMBLE" || route === "MARK_ASSEMBLE" ? "Follow the reviewed consignment assembly steps." : null, active: true } });
    await db.consignmentLine.create({ data: { id: lineId, consignmentBatchId: "batch", accountId: "account", rowNumber: index + 2, sellerSkuSource: `CSKU-${index}`, sellerSkuSnapshot: `CSKU-${index}`, requiredQuantity: 3, marketplaceListingId:`clisting-${index}`, matchStatus: "OWNER_SELECTED", activated: true } });
    await db.workTask.create({ data: { id: taskId, accountId: "account", sourceType: "CONSIGNMENT", consignmentLineId: lineId, stage: "PICK", sequenceNumber: 1, requiredQuantity: 3, status: "READY" } });
    await completeConsignmentPickWithRoute({ taskId, accountId: "account", actorUserId: "owner", expectedQuantity: 0, route, clientRequestId: `consignment-route-${index}` }, db);
    const tasks=await db.workTask.findMany({ where: { consignmentLineId: lineId }, orderBy: { sequenceNumber: "asc" } });assert.deepEqual(tasks.map((task) => task.stage), stages);
    for(const task of tasks.slice(1)){if(task.stage==="MARK")assert.ok(parseOrderMarkingMetadata(task.metadataJson));if(task.stage==="ASSEMBLE")assert.ok(parseConsignmentAssemblyMetadata(task.metadataJson));assert.equal((await db.workTask.findUniqueOrThrow({where:{id:task.id}})).status,"READY");const replayId=`consignment-${index}-${task.stage}`;await completeWorkTask({taskId:task.id,accountId:"account",actorUserId:"owner",expectedQuantity:0,clientRequestId:replayId},db);const replay=await completeWorkTask({taskId:task.id,accountId:"account",actorUserId:"owner",expectedQuantity:0,clientRequestId:replayId},db);assert.equal(replay.idempotent,true);}
  }

  await assert.rejects(() => completeOrderPickWithRoute({ orderIds: ["order-0"], accountId: "other", actorUserId: "owner", route: "DIRECT_PACK" }, db), /unavailable/i);
  await db.order.createMany({data:[{id:"amazon-a",accountId:"account",batchId:"upload",marketplace:"AMAZON",awb:"AMZ-ITEM-A",trackingId:"AMZ-TRACK",shipmentId:"AMZ-SHIP",orderItemId:"AMZ-ITEM-A",sku:"AMZ-SKU-A",qty:1,orderNo:"AMZ-ORDER",pickStatus:"PICKED",packStatus:"READY",status:"READY"},{id:"amazon-b",accountId:"account",batchId:"upload",marketplace:"AMAZON",awb:"AMZ-ITEM-B",trackingId:"AMZ-TRACK",shipmentId:"AMZ-SHIP",orderItemId:"AMZ-ITEM-B",sku:"AMZ-SKU-B",qty:2,orderNo:"AMZ-ORDER",pickStatus:"READY",packStatus:"READY",status:"READY"}]});
  let amazonScan=await resolveUniversalWork({actorUserId:"packer",accountId:"account",code:"AMZ-TRACK",intent:"PACK"},db);const waiting=amazonScan.candidates.find(candidate=>candidate.actionType==="ORDER_PACK");assert.equal(waiting?.shipmentItemCount,2);assert.equal(waiting?.canAct,false,"Amazon package cannot partially pack while a sibling is unpicked");
  await completeOrderPickWithRoute({orderIds:["amazon-b"],accountId:"account",actorUserId:"picker",route:"DIRECT_PACK",clientRequestId:"amazon-pick"},db);amazonScan=await resolveUniversalWork({actorUserId:"packer",accountId:"account",code:"AMZ-TRACK",intent:"PACK"},db);const ready=amazonScan.candidates.find(candidate=>candidate.actionType==="ORDER_PACK");assert.equal(ready?.shipmentItemCount,2);assert.equal(ready?.canAct,true,"Tracking scan returns the complete Amazon package");await packCustomerOrderShipmentSafely({actorUserId:"packer",accountId:"account",orderId:ready!.sourceId,source:"universal-scan",clientRequestId:"amazon-pack"},db);assert.equal(await db.order.count({where:{trackingId:"AMZ-TRACK",packStatus:"PACKED"}}),2);
  assert.equal((await db.order.findUniqueOrThrow({ where: { id: "order-0" } })).packStatus, "PACKED");
} finally { await db.$disconnect(); rmSync(file, { force: true }); }
console.log("Production flow temporary-database tests passed.");
