import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { assertInside, BACKUP_ROOT, compareSnapshots, MIGRATION_TEST_PATH, ROOT, TEMP_ROOT } from "../scripts/real-db/safety.mjs";

assert.equal(assertInside(resolve(BACKUP_ROOT,"safe.db"),BACKUP_ROOT,"Backup"),resolve(BACKUP_ROOT,"safe.db"));assert.throws(()=>assertInside(resolve(ROOT,"escape.db"),BACKUP_ROOT,"Backup"),/must stay inside/);assert.equal(assertInside(MIGRATION_TEST_PATH,TEMP_ROOT,"Migration test"),MIGRATION_TEST_PATH);assert.throws(()=>assertInside(resolve(ROOT,"dev.db"),TEMP_ROOT,"Migration test"),/must stay inside/);
const unchanged={counts:{Account:2,User:4},tableNames:["Account","User"],identityBounds:{Account:"a:b",User:"u:v"}};assert.equal(compareSnapshots(unchanged,unchanged).ok,true);const reduced={...unchanged,counts:{Account:1,User:4}};assert.deepEqual(compareSnapshots(unchanged,reduced).reductions,[{table:"Account",before:2,after:1}]);
const scripts=["scripts/real-db/backup.mjs","scripts/real-db/test-migrations.mjs","scripts/real-db/migrate.mjs","scripts/real-db/verify.mjs"].map((path)=>readFileSync(path,"utf8")).join("\n");assert.doesNotMatch(scripts,/migrate\s+reset|db\s+push|db\s+seed|prisma\s+seed/i);assert.match(scripts,/backupSha256/);assert.match(scripts,/appliedMigrations/);assert.match(scripts,/sourceSha256/);assert.match(scripts,/test\.passed/);assert.match(scripts,/compareSnapshots/);assert.match(readFileSync("scripts/real-db/backup.mjs","utf8"),/createVerifiedBackup/);assert.match(readFileSync("scripts/real-db/safety.mjs","utf8"),/flag: "wx"/);
const refused=spawnSync(process.execPath,["scripts/real-db/migrate.mjs"],{cwd:ROOT,encoding:"utf8"});assert.equal(refused.status,2);assert.match(`${refused.stdout}${refused.stderr}`,/Real migration was not run/);
const review=readFileSync("app/owner/manual-review/page.tsx","utf8");assert.match(review,/requireUser\(\["OWNER"\]\)/);assert.doesNotMatch(review,/prisma\.[a-zA-Z]+\.(?:create|update|delete|upsert|createMany|updateMany|deleteMany)/);assert.doesNotMatch(review,/databasePath|passwordHash|SESSION_SECRET|managedRelativePath/);
const ignore=readFileSync(".gitignore","utf8");for(const pattern of ["backups/","*.db","*.db-wal","*.db-shm","*.db-journal",".codex-tmp"])assert.ok(ignore.includes(pattern),`${pattern} remains ignored`);for(const schema of ["prisma/schema.prisma","prisma/schema.postgres.prisma"])assert.doesNotMatch(readFileSync(schema,"utf8"),/model\s+(?:Inventory|StockLedger|StockBalance)\b/);const mobileDiff=spawnSync("git",["diff","--quiet","--","mobile-app"],{cwd:ROOT});assert.equal(mobileDiff.status,0,"mobile-app remains unchanged");
console.log("Real database migration safety tests passed.");
