import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => readFileSync(path.join(root, file), "utf8");

const consignments = read("app/owner/consignments/page.tsx");
const consignmentDetail = read("app/owner/consignments/[batchId]/page.tsx");
const consignmentIssues = read("app/owner/consignments/[batchId]/issues/page.tsx");
const newConsignment = read("app/owner/consignments/new/page.tsx");
const imports = read("app/owner/imports/page.tsx");
const importDetail = read("app/owner/imports/[jobId]/page.tsx");
const importProgress = read("components/ImportJobProgress.tsx");
const uploadField = read("components/FileUploadField.tsx");
const format = read("lib/format.ts");
const users = read("app/owner/users/page.tsx");
const accounts = read("app/owner/accounts/page.tsx");
const reports = read("app/reports/page.tsx");
const groupedCard = read("app/work/GroupedWorkCard.tsx");
const workDialog = read("components/WorkRouteDialog.tsx");
const scannerDialog = read("components/ScannerPickRouteDialog.tsx");
const workHub = read("app/work/LiveWorkHubSummary.tsx");
const stageSummary = read("app/work/LiveStageSummary.tsx");
const workProblems = read("app/work/problems/page.tsx");
const dataManagement = read("app/owner/data-management/page.tsx");
const dataActionDetails = read("components/DataActionDetails.tsx");

assert.match(consignments, /Review and activate/);
assert.match(consignments, /View completion record/);
assert.match(consignments, /Valid lines/);
assert.match(consignments, /Required units/);
assert.match(consignments, /Generated tasks|Problem tasks/);
assert.match(consignmentDetail, /Matched listings/);
assert.match(consignmentDetail, /Replace and reparse draft/);
assert.match(consignmentIssues, /encodeURIComponent\(group\.issueType\)/);
assert.match(consignmentIssues, /INFORMATION/);
assert.match(consignmentIssues, /aria-disabled="true"/);
assert.match(newConsignment, /Safe upload sequence/);
assert.match(newConsignment, /No worker tasks are created/);

assert.match(imports, /marketplace === "AMAZON" \? undefined/);
assert.match(imports, /Not enabled in this release/);
assert.match(imports, /More counts and downloads/);
assert.match(imports, /Rows processed/);
assert.match(imports, /Warning\/error rows/);
assert.match(importDetail, /Start another import/);
assert.match(importDetail, /Request safe cancellation/);
assert.match(importProgress, /Support reference: IMP-/);
assert.match(importProgress, /Source files processed/);
assert.doesNotMatch(importProgress, /href="\/picker"/);

assert.match(uploadField, /type="file"/);
assert.match(uploadField, /aria-live="polite"/);
assert.match(uploadField, /No file selected/);
assert.match(uploadField, /file\.size/);
assert.match(format, /timeZone: "Asia\/Kolkata"/);
assert.match(format, /timeZoneName: "short"/);
assert.match(users, /Manage access, password and recent sessions/);
assert.match(users, /Create a new user/);
assert.match(accounts, /Edit account details/);
assert.match(accounts, /Locked because marketplace data exists/);
assert.match(accounts, /Open scoped view/);
assert.match(reports, /Report scope · live as of/);
assert.match(reports, /Open problems count the selected account scope regardless of date/);
assert.match(reports, /Exports unavailable: no rows for current filters/);
assert.match(reports, /aria-disabled="true"/);
assert.match(groupedCard, /Complete Pick/);
assert.match(groupedCard, /Complete Pack/);
assert.doesNotMatch(groupedCard, /Picked All|Pack Completed/);
assert.match(groupedCard, /role="progressbar"/);
assert.match(groupedCard, /aria-valuenow/);
assert.match(groupedCard, /More identifiers/);
for (const dialog of [workDialog, scannerDialog]) {
  assert.match(dialog, /ROUTE_CHANGE_REASONS/);
  assert.match(dialog, /name="routeReason"/);
  assert.match(dialog, /name="confirmMissingInstructions"/);
  assert.match(dialog, /I understand and want to continue/);
  assert.match(dialog, /event\.key !== "Tab"/);
  assert.match(dialog, /triggerRef\.current\?\.focus/);
}
assert.match(workHub, /Actions enabled/);
assert.match(workHub, /Assigned to me/);
assert.match(workHub, /Oldest waiting/);
assert.match(stageSummary, /role="tablist"/);
assert.match(stageSummary, /aria-selected/);
assert.match(workProblems, /No problems to show/);
assert.match(workProblems, /aria-disabled="true"/);
assert.match(dataManagement, /Swipe to see all data sections/);
assert.match(dataManagement, /aria-current=/);
assert.match(dataManagement, /<DataActionDetails/);
assert.match(dataActionDetails, /<details/);
assert.match(dataManagement, /executeOwnerDataAction/);
assert.match(dataManagement, /StatusBadge/);
assert.match(dataManagement, /formatDateTime/);
assert.match(dataManagement, /autoFocus/);
assert.match(dataManagement, /Quarantined files will appear here with their retention deadline/);
assert.doesNotMatch(dataManagement, /createdAt\.toLocaleString|purgeAfter\?\.toLocaleString/);

console.log("Stage 4.6 reconciled owner-operations UI contract tests passed.");
