import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(path, "utf8");
const resolver = read("src/lib/workflow/universal-resolver.ts");
const actions = read("src/lib/workflow/universal-actions.ts");
const panel = read("components/UniversalScannerPanel.tsx");
const packing = read("app/packing/page.tsx");
const shell = read("components/AppShell.tsx");
const hub = read("app/work/page.tsx");
const taskStore = read("src/lib/workflow/task-store.ts");
const schema = read("prisma/schema.prisma");
const scanInput = read("components/UniversalScanInput.tsx");
const scanActions = read("app/work/scan/actions.ts");
const markingRoute = read("app/work/tasks/[taskId]/marking-file/route.ts");
const packScope = read("src/lib/workflow/order-pack-scope.ts");
const packingActions = read("app/packing/actions.ts");
const packingDetailActions = read("app/packing/[awb]/actions.ts");
const mobilePackingAction = read("app/api/mobile/packing/confirm/route.ts");
const orderPicking = read("src/lib/workflow/order-picking.ts");

assert.match(resolver, /getAuthorizedWorkAccounts/);
assert.match(resolver, /resolveUniversalWork/);
assert.doesNotMatch(resolver, /contains:/, "Scan resolver must not use fuzzy contains matching");
assert.match(resolver, /take:\s*limit \* 4/, "Resolver result loading is bounded");
assert.match(resolver, /WORK_TASK_ID/);
assert.doesNotMatch(resolver, /markingFileAvailable/, "Worker candidates do not advertise marking-file delivery");
assert.match(resolver, /CUSTOMER_ORDER_SHIPMENT/);
assert.match(resolver, /assignedTasks[\s\S]*generalTasks[\s\S]*new Map/, "Assigned exact tasks are queried and merged before final bounding");
assert.match(resolver, /FNSKU[\s\S]*SELLER_SKU[\s\S]*FSN[\s\S]*ASIN[\s\S]*LISTING_ID/, "Identifier ranking is explicit");
assert.doesNotMatch(resolver, /managedRelativePath|passwordHash|DATABASE_URL|SESSION_SECRET/);
assert.match(panel, /Scanning never changes work/);
assert.match(panel, /Selected-account lookup only/);
assert.match(scanActions, /submittedAccountId!==selectedAccount\.id/, "Scanner actions reject a client-switched account");
assert.match(panel, /No action was performed/);
assert.match(packing, /UniversalScannerPanel/);
assert.match(packing, /canPack\s*\?[\s\S]*getPackingDashboard/, "Packing counts are queried only for pack-authorized users");
assert.match(packing, /data-customer-order-packing/, "Legacy customer packing is a separate authorized section");
assert.match(packing, /canUseScanner[\s\S]*redirect\(roleHomePath/, "Users without scanner permissions are rejected");
assert.match(actions, /getAuthorizedWorkAccounts/);
assert.match(actions, /This account is no longer assigned to you/);
assert.match(actions, /ORDER_PICK[\s\S]*markCustomerOrdersPickedSafely/, "Universal Order Pick uses the shared picking service");
assert.match(orderPicking, /assertWorkerAccountAccess[\s\S]*\$transaction[\s\S]*assertWorkerAccountAccess/, "Order Pick re-authorizes inside its transaction");
assert.match(actions, /packCustomerOrderShipmentSafely/);
assert.match(packScope, /unpickedCount[\s\S]*problemCount[\s\S]*packable/);
assert.match(packScope, /assertWorkerAccountAccess[\s\S]*\$transaction[\s\S]*assertWorkerAccountAccess/, "Packing re-authorizes before and inside its transaction");
assert.match(packScope, /resolveOrderPackScope[\s\S]*assertOrderPackScopeEligible[\s\S]*verifiedOrderIds/);
assert.match(packScope, /update\.count !== verifiedOrderIds\.length/, "Shared service rejects stale partial updates");
for (const mutationSource of [actions, packingActions, packingDetailActions, mobilePackingAction]) {
  assert.match(mutationSource, /packCustomerOrderShipmentSafely/, "Every customer packing mutation uses the safe service");
  assert.doesNotMatch(mutationSource, /buildConfirmPackedOrderWhere/, "No packing mutation uses the legacy scope helper");
}
assert.match(scanActions, /if\(error\)params\.set\("q",code\)/, "Only failed actions preserve the scanned code");
assert.match(scanInput, /selectOnMount[\s\S]*input\.select\(\)/, "Failed scans select existing text for replacement");
assert.match(scanInput, /onFocus=\{\(event\) => event\.currentTarget\.select\(\)\}/, "Focused scan text is replaceable by hardware input");
assert.doesNotMatch(panel, /Open preview|Download marking file/, "Worker scanner cards do not offer marking-file delivery");
assert.match(panel, /Master Design ID|Marking instructions/, "Worker scanner cards retain operational marking guidance");
assert.doesNotMatch(panel, /managedRelativePath/);
assert.match(markingRoute, /assertWorkerAccountAccess\(user\.id,taskAccount\.accountId\)/, "Marking downloads re-authorize the task account");
assert.match(shell, /canManageConsignments|canViewAllWork/);
assert.match(hub, /canManageConsignments|canViewAllWork/);
assert.match(taskStore, /recoverIdempotentReplay/);
assert.match(taskStore, /Request ID was already used with a different payload/);
assert.match(schema, /identifierType, normalizedValue, accountId/);
assert.doesNotMatch(schema, /model\s+(Inventory|StockLedger|StockBalance)/);
assert.doesNotMatch(read("mobile-app/App.tsx"), /PHASE_4_1_SCANNER_CORRECTIONS/, "Mobile app remains outside Phase 4.1");

console.log("Universal scanner source policy tests passed.");
