import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync,readFileSync,readdirSync,rmSync } from "node:fs";
import { join,resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { applyUniversalCandidateAction } from "../src/lib/workflow/universal-actions";
import { getAuthorizedWorkAccounts,normalizeUniversalScanCode,resolveUniversalWork } from "../src/lib/workflow/universal-resolver";

const tmp=resolve(process.cwd(),".codex-tmp");mkdirSync(tmp,{recursive:true});const file=resolve(tmp,"universal-scan.db");rmSync(file,{force:true,maxRetries:5,retryDelay:100});const raw=new DatabaseSync(file);raw.exec("PRAGMA foreign_keys=ON;");const migrations=resolve(process.cwd(),"prisma","migrations");for(const name of readdirSync(migrations,{withFileTypes:true}).filter((entry)=>entry.isDirectory()).map((entry)=>entry.name).sort())raw.exec(readFileSync(join(migrations,name,"migration.sql"),"utf8"));raw.close();const db=new PrismaClient({datasourceUrl:`file:${file.replace(/\\/g,"/")}`});
try{
 await db.account.createMany({data:[{id:"a1",name:"Account One",code:"A1",companyName:"Fake",marketplace:"FLIPKART",active:true},{id:"a2",name:"Account Two",code:"A2",companyName:"Fake",marketplace:"FLIPKART",active:true},{id:"a3",name:"Hidden Account",code:"A3",companyName:"Fake",marketplace:"MEESHO",active:true}]});
 await db.user.createMany({data:[{id:"owner",username:"scan-owner",passwordHash:"fake",name:"Owner",role:"OWNER",active:true,accountId:"a1"},{id:"worker",username:"scan-worker",passwordHash:"fake",name:"Worker",role:"PICKER",active:true,accountId:"a1",canPick:true,canPack:true,canMark:true},{id:"hidden",username:"hidden-worker",passwordHash:"fake",name:"Hidden",role:"PACKER",active:true,accountId:"a3",canPack:true}]});await db.user.update({where:{id:"worker"},data:{assignedAccounts:{connect:{id:"a2"}}}});
 const ownerScope=await getAuthorizedWorkAccounts("owner",db);assert.equal(ownerScope.accounts.length,3);const workerScope=await getAuthorizedWorkAccounts("worker",db);assert.deepEqual(workerScope.accounts.map((account)=>account.id).sort(),["a1","a2"]);
 await db.marketplaceListing.createMany({data:[{id:"l1",accountId:"a1",marketplace:"FLIPKART",sellerSkuId:"SHARED-SKU",sku:"SHARED-SKU",fsn:"FSN-SCAN",listingId:"LID-A1",productTitle:"Fake Product One"},{id:"l2",accountId:"a2",marketplace:"FLIPKART",sellerSkuId:"SHARED-SKU",sku:"SHARED-SKU",fsn:"FSN-SCAN",listingId:"LID-A2",productTitle:"Fake Product Two"}]});await db.marketplaceListingIdentifier.createMany({data:[{accountId:"a1",marketplaceListingId:"l1",marketplace:"FLIPKART",identifierType:"SELLER_SKU",rawValue:"SHARED-SKU",normalizedValue:"SHARED-SKU"},{accountId:"a2",marketplaceListingId:"l2",marketplace:"FLIPKART",identifierType:"SELLER_SKU",rawValue:"SHARED-SKU",normalizedValue:"SHARED-SKU"},{accountId:"a1",marketplaceListingId:"l1",marketplace:"FLIPKART",identifierType:"FSN",rawValue:"FSN-SCAN",normalizedValue:"FSN-SCAN"},{accountId:"a1",marketplaceListingId:"l1",marketplace:"FLIPKART",identifierType:"LISTING_ID",rawValue:"LID-A1",normalizedValue:"LID-A1"},{accountId:"a1",marketplaceListingId:"l1",marketplace:"FLIPKART",identifierType:"FNSKU",rawValue:"FNSKU-SCAN",normalizedValue:"FNSKU-SCAN"},{accountId:"a1",marketplaceListingId:"l1",marketplace:"FLIPKART",identifierType:"BARCODE",rawValue:"890000000001",normalizedValue:"890000000001"}]});
 await db.uploadBatch.createMany({data:[{id:"u1",accountId:"a1",fileName:"fake.csv"},{id:"u2",accountId:"a2",fileName:"fake.csv"}]});await db.order.createMany({data:[{id:"o1",accountId:"a1",batchId:"u1",marketplace:"FLIPKART",awb:"AWB-SCAN-1",trackingId:"TRACK-SCAN-1",shipmentId:"SHIP-SCAN-1",orderItemId:"ITEM-SCAN-1",sku:"SHARED-SKU",qty:2,orderNo:"ORDER-SCAN-1",pickStatus:"READY",packStatus:"READY"},{id:"o2",accountId:"a2",batchId:"u2",marketplace:"FLIPKART",awb:"AWB-SCAN-2",trackingId:"TRACK-SCAN-2",shipmentId:"SHIP-SCAN-2",orderItemId:"ITEM-SCAN-2",sku:"OTHER-SKU",qty:1,orderNo:"ORDER-SCAN-2",pickStatus:"PICKED",packStatus:"READY"},{id:"o3",accountId:"a1",batchId:"u1",marketplace:"FLIPKART",awb:"AWB-DONE",trackingId:"TRACK-DONE",sku:"DONE-SKU",qty:1,orderNo:"ORDER-DONE",pickStatus:"PICKED",packStatus:"PACKED",status:"PACKED",packedAt:new Date()}]});await db.workTask.createMany({data:[{id:"o2-pick",accountId:"a2",sourceType:"ORDER",orderId:"o2",stage:"PICK",sequenceNumber:1,requiredQuantity:1,completedQuantity:1,status:"COMPLETED",completedAt:new Date()},{id:"o2-pack",accountId:"a2",sourceType:"ORDER",orderId:"o2",stage:"PACK",sequenceNumber:2,requiredQuantity:1,status:"READY"}]});
 await db.consignmentBatch.createMany({data:[{id:"b1",accountId:"a1",marketplace:"FLIPKART",externalConsignmentNumber:"CN-SCAN-1",displayName:"Fake Batch One",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha1"},{id:"b2",accountId:"a2",marketplace:"FLIPKART",externalConsignmentNumber:"CN-SCAN-2",displayName:"Fake Batch Two",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha2"}]});await db.markingAsset.create({data:{id:"ma1",name:"Fake Marking Asset",status:"READY",active:true,instructions:"Use the fake operational settings."}});await db.markingAssetFile.create({data:{id:"maf1",markingAssetId:"ma1",attachmentType:"MARKING_FILE",versionNumber:1,originalFileName:"fake-marking.pdf",managedRelativePath:"fake/never-returned.pdf",contentType:"application/pdf",fileExtension:".pdf",fileSizeBytes:10,sha256:"fake-sha",activeVersion:true}});await db.consignmentLine.createMany({data:[{id:"c1",consignmentBatchId:"b1",accountId:"a1",rowNumber:2,requiredQuantity:3,matchStatus:"EXACT_SKU",marketplaceListingId:"l1",processRoute:"PICK_PACK",activated:true,sellerSkuSnapshot:"SHARED-SKU",fsnSnapshot:"FSN-SCAN",listingIdSnapshot:"LID-A1"},{id:"c2",consignmentBatchId:"b2",accountId:"a2",rowNumber:2,requiredQuantity:4,matchStatus:"EXACT_SKU",marketplaceListingId:"l2",processRoute:"PICK_PACK",activated:true,sellerSkuSnapshot:"SHARED-SKU",fsnSnapshot:"FSN-SCAN",listingIdSnapshot:"LID-A2"},{id:"c3",consignmentBatchId:"b1",accountId:"a1",rowNumber:3,requiredQuantity:2,matchStatus:"EXACT_SKU",marketplaceListingId:"l1",processRoute:"PICK_MARK_PACK",markingAssetId:"ma1",activated:true,sellerSkuSnapshot:"SHARED-SKU",fsnSnapshot:"FSN-SCAN",listingIdSnapshot:"LID-A1"}]});await db.workTask.createMany({data:[{id:"t1",accountId:"a1",sourceType:"CONSIGNMENT",consignmentLineId:"c1",stage:"PICK",sequenceNumber:1,requiredQuantity:3,status:"READY"},{id:"t2",accountId:"a2",sourceType:"CONSIGNMENT",consignmentLineId:"c2",stage:"PACK",sequenceNumber:2,requiredQuantity:4,status:"READY"},{id:"t3",accountId:"a1",sourceType:"CONSIGNMENT",consignmentLineId:"c3",stage:"MARK",sequenceNumber:2,requiredQuantity:2,status:"READY"},{id:"tp",accountId:"a1",sourceType:"CONSIGNMENT",consignmentLineId:"c3",stage:"PACK",sequenceNumber:3,requiredQuantity:2,status:"PROBLEM",assignedUserId:"owner",problemReason:"OTHER",problemReportedByUserId:"owner",problemReportedAt:new Date()}]});
 assert.equal(normalizeUniversalScanCode("  SHARED-SKU\r\n"),"SHARED-SKU");assert.throws(()=>normalizeUniversalScanCode("BAD\tCODE"),/invalid/i);await assert.rejects(()=>resolveUniversalWork({actorUserId:"worker",code:"x",accountId:"a3"},db),/outside/i);
 for(const code of ["AWB-SCAN-1","TRACK-SCAN-1","ORDER-SCAN-1","SHIP-SCAN-1","ITEM-SCAN-1"]){const result=await resolveUniversalWork({actorUserId:"worker",code},db);assert.ok(result.candidates.some((candidate)=>candidate.orderId==="o1"),`${code} finds the order`);}
 for(const code of ["FSN-SCAN","LID-A1","FNSKU-SCAN","890000000001","t1"]){const result=await resolveUniversalWork({actorUserId:"worker",code},db);assert.ok(result.candidates.some((candidate)=>candidate.taskId),`${code} finds an active consignment task`);}
 const marking=await resolveUniversalWork({actorUserId:"worker",code:"FNSKU-SCAN",intent:"MARK"},db);assert.ok(marking.candidates.some((candidate)=>candidate.taskId==="t3"&&candidate.markingInstructions==="Use the fake operational settings."));assert.ok(marking.candidates.every((candidate)=>!("managedRelativePath" in candidate)),"Worker marking guidance never exposes a managed path");
 const before=await db.workTask.findUniqueOrThrow({where:{id:"t1"}});const orderBefore=await db.order.findUniqueOrThrow({where:{id:"o1"}});const shared=await resolveUniversalWork({actorUserId:"worker",code:"SHARED-SKU"},db);assert.ok(shared.candidates.some((candidate)=>candidate.orderId==="o1"));assert.deepEqual(new Set(shared.candidates.filter((candidate)=>candidate.taskId).map((candidate)=>candidate.accountId)),new Set(["a1","a2"]));assert.ok(shared.candidates.some((candidate)=>candidate.actionType==="CONSIGNMENT_PICK"));assert.ok(shared.candidates.some((candidate)=>candidate.taskId==="t2"&&candidate.stage==="PACK"&&!candidate.canAct&&candidate.workflowPrerequisites?.stages.PICK.state==="MISSING"),"Pack is visible but locked when Pick work is missing.");assert.ok(!shared.candidates.some((candidate)=>candidate.taskId==="tp"),"Worker cannot see another worker's problem");const ownerProblems=await resolveUniversalWork({actorUserId:"owner",code:"SHARED-SKU"},db);assert.ok(ownerProblems.candidates.some((candidate)=>candidate.taskId==="tp"&&candidate.actionType==="PROBLEM"));const repeated=await resolveUniversalWork({actorUserId:"worker",code:"SHARED-SKU"},db);assert.deepEqual(repeated.candidates.map((candidate)=>candidate.candidateKey),shared.candidates.map((candidate)=>candidate.candidateKey),"Candidate ordering is deterministic");assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"t1"}})).completedQuantity,before.completedQuantity,"Scan alone never mutates task");assert.equal((await db.order.findUniqueOrThrow({where:{id:"o1"}})).pickStatus,orderBefore.pickStatus,"Scan alone never mutates order");assert.equal((await resolveUniversalWork({actorUserId:"worker",code:"SHARED-SKU",limit:1},db)).candidates.length,1);
 const completed=await resolveUniversalWork({actorUserId:"worker",code:"AWB-DONE"},db);assert.equal(completed.candidates.length,1);assert.equal(completed.candidates[0].status,"PACKED");assert.equal(completed.candidates[0].canAct,false);assert.equal(completed.candidates[0].actionType,"READ_ONLY");assert.ok(completed.completedMatchCount>0);
 await assert.rejects(()=>applyUniversalCandidateAction({actorUserId:"worker",accountId:"a1",sourceId:"o1",action:"ORDER_PICK",expectedStatus:"PICKED",clientRequestId:"stale-o1"},db),/changed/i);await applyUniversalCandidateAction({actorUserId:"worker",accountId:"a1",sourceId:"o1",action:"ORDER_PICK",expectedStatus:"READY",clientRequestId:"pick-o1"},db);const pickReplay=await applyUniversalCandidateAction({actorUserId:"worker",accountId:"a1",sourceId:"o1",action:"ORDER_PICK",expectedStatus:"READY",clientRequestId:"pick-o1"},db);assert.equal(pickReplay.idempotent,true);await applyUniversalCandidateAction({actorUserId:"worker",accountId:"a2",sourceId:"o2",action:"ORDER_PACK",expectedStatus:"READY",clientRequestId:"pack-o2"},db);const packReplay=await applyUniversalCandidateAction({actorUserId:"worker",accountId:"a2",sourceId:"o2",action:"ORDER_PACK",expectedStatus:"READY",clientRequestId:"pack-o2"},db);assert.equal(packReplay.idempotent,true);assert.equal((await db.order.findUniqueOrThrow({where:{id:"o2"}})).packStatus,"PACKED");
 await db.user.update({where:{id:"worker"},data:{assignedAccounts:{disconnect:{id:"a2"}}}});await assert.rejects(()=>applyUniversalCandidateAction({actorUserId:"worker",accountId:"a2",sourceId:"t2",action:"TASK_INCREMENT",expectedQuantity:0,clientRequestId:"stale"},db),/no longer assigned/i);
}finally{await db.$disconnect();try{rmSync(file,{force:true,maxRetries:5,retryDelay:100});}catch{}}
console.log("Universal cross-account resolver integration tests passed.");
