import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdirSync,readFileSync,readdirSync,rmSync } from "node:fs";
import { join,resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { claimWorkTask, completeWorkTask, incrementWorkTaskProgress, reassignConsignmentStage, reassignWorkTask, reportWorkTaskProblem, resolveWorkTaskProblem, setWorkTaskProgress } from "../src/lib/workflow/task-store";
import { getWorkerTaskQueue, getWorkHubCounts } from "../src/lib/workflow/queues";

const tmp=resolve(process.cwd(),".codex-tmp");mkdirSync(tmp,{recursive:true});const file=resolve(tmp,"workflow-worker.db");rmSync(file,{force:true,maxRetries:5,retryDelay:100});const raw=new DatabaseSync(file);raw.exec("PRAGMA foreign_keys=ON;");const root=resolve(process.cwd(),"prisma","migrations");for(const name of readdirSync(root,{withFileTypes:true}).filter((e)=>e.isDirectory()).map((e)=>e.name).sort())raw.exec(readFileSync(join(root,name,"migration.sql"),"utf8"));raw.close();const db=new PrismaClient({datasourceUrl:`file:${file.replace(/\\/g,"/")}`});
try{
 await db.account.createMany({data:[{id:"acct",name:"Fake",code:"FAKE",companyName:"Fake Co",marketplace:"FLIPKART",active:true},{id:"other-acct",name:"Other",code:"OTHER",companyName:"Fake Co",marketplace:"FLIPKART",active:true}]});
 await db.user.createMany({data:[
  {id:"owner",username:"owner",passwordHash:"fake",name:"Owner",role:"OWNER",active:true,accountId:"acct"},
  {id:"picker1",username:"picker1",passwordHash:"fake",name:"Picker One",role:"PICKER",active:true,accountId:"acct",canPick:true},
  {id:"picker2",username:"picker2",passwordHash:"fake",name:"Picker Two",role:"PICKER",active:true,accountId:"acct",canPick:true},
  {id:"packer",username:"packer",passwordHash:"fake",name:"Packer",role:"PACKER",active:true,accountId:"acct",canPack:true},
  {id:"marker",username:"marker",passwordHash:"fake",name:"Marker",role:"PACKER",active:true,accountId:"acct",canMark:true},
  {id:"manager",username:"manager",passwordHash:"fake",name:"Manager",role:"PACKER",active:true,accountId:"acct",canManageConsignments:true,canViewAllWork:true},
  {id:"viewer",username:"viewer",passwordHash:"fake",name:"View All",role:"PICKER",active:true,accountId:"acct",canViewAllWork:true,canPick:true,canPack:true},
  {id:"inactive",username:"inactive",passwordHash:"fake",name:"Inactive",role:"PICKER",active:false,accountId:"acct",canPick:true},
  {id:"unassigned",username:"unassigned",passwordHash:"fake",name:"Unassigned",role:"PICKER",active:true,accountId:"other-acct",canPick:true}
  ,{id:"no-report",username:"no-report",passwordHash:"fake",name:"No Report",role:"PICKER",active:true,accountId:"acct",canPick:true,canReportProblem:false}
 ]});
 await db.marketplaceListing.create({data:{id:"listing",accountId:"acct",marketplace:"FLIPKART",sellerSkuId:"SKU-1",sku:"INTERNAL-1",fsn:"FSN-1",listingId:"LID-1",productTitle:"Fake Product"}});
 await db.marketplaceListingIdentifier.createMany({data:[["SELLER_SKU","SKU-1"],["FSN","FSN-1"],["LISTING_ID","LID-1"]].map(([identifierType,value])=>({accountId:"acct",marketplaceListingId:"listing",marketplace:"FLIPKART",identifierType:identifierType as "SELLER_SKU"|"FSN"|"LISTING_ID",rawValue:value,normalizedValue:value}))});
 await db.consignmentBatch.create({data:{id:"batch",accountId:"acct",marketplace:"FLIPKART",externalConsignmentNumber:"CN-1",displayName:"Fake Batch",status:"ACTIVE",sourceFileName:"fake.csv",sourceFileSha256:"sha"}});
 await db.consignmentLine.create({data:{id:"line",consignmentBatchId:"batch",accountId:"acct",rowNumber:2,requiredQuantity:10,matchStatus:"EXACT_SKU",marketplaceListingId:"listing",processRoute:"PICK_PACK",activated:true,productTitleSnapshot:"Fake Product",sellerSkuSnapshot:"SKU-1",fsnSnapshot:"FSN-1",listingIdSnapshot:"LID-1"}});
 await db.workTask.createMany({data:[{id:"pick",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line",stage:"PICK",sequenceNumber:1,requiredQuantity:10,status:"READY"},{id:"pack",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line",stage:"PACK",sequenceNumber:2,requiredQuantity:10,status:"LOCKED"}]});
 await assert.rejects(()=>claimWorkTask({taskId:"pick",accountId:"acct",actorUserId:"inactive"},db),/unavailable/i);
 await assert.rejects(()=>claimWorkTask({taskId:"pick",accountId:"acct",actorUserId:"unassigned"},db),/assigned/i);
 await assert.rejects(()=>claimWorkTask({taskId:"pick",accountId:"acct",actorUserId:"packer"},db),/permission/i);
 const claims=await Promise.allSettled([claimWorkTask({taskId:"pick",accountId:"acct",actorUserId:"picker1",clientRequestId:"claim-a"},db),claimWorkTask({taskId:"pick",accountId:"acct",actorUserId:"picker2",clientRequestId:"claim-b"},db)]);assert.equal(claims.filter((result)=>result.status==="fulfilled").length,1,"One concurrent claimant succeeds");const claimed=await db.workTask.findUniqueOrThrow({where:{id:"pick"}});assert.ok(["picker1","picker2"].includes(claimed.assignedUserId??""));const worker=claimed.assignedUserId!;
 const other=worker==="picker1"?"picker2":"picker1";await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:other,expectedQuantity:0,increment:1},db),/taken/i);
 let result=await incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:0,increment:1,clientRequestId:"inc-1"},db);assert.equal(result.completedQuantity,1);
 result=await incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:1,increment:5,clientRequestId:"inc-5"},db);assert.equal(result.completedQuantity,6);
 await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:6,increment:5},db),/range/i);
 await assert.rejects(()=>setWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:5,targetQuantity:7},db),/refresh/i);
 const duplicate=await incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:0,increment:1,clientRequestId:"inc-1"},db);assert.equal(duplicate.completedQuantity,1);assert.equal(duplicate.idempotent,true);
 await assert.rejects(()=>completeWorkTask({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:1,clientRequestId:"inc-1"},db),/different action/i);
 await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:other,expectedQuantity:1,increment:1,clientRequestId:"inc-1"},db),/taken|another worker/i);
 await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:"unassigned",expectedQuantity:1,increment:1,clientRequestId:"inc-1"},db),/assigned/i);
 const concurrent=await Promise.all([incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:6,increment:1,clientRequestId:"inc-concurrent"},db),incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:6,increment:1,clientRequestId:"inc-concurrent"},db)]);assert.deepEqual(concurrent.map((item)=>item.completedQuantity),[7,7]);assert.equal(await db.workActionLog.count({where:{taskId:"pick",clientRequestId:"inc-concurrent"}}),1,"Concurrent replay mutates once");
 await completeWorkTask({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:7,clientRequestId:"complete-pick"},db);assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"pack"}})).status,"READY");
 await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pick",accountId:"acct",actorUserId:worker,expectedQuantity:10,increment:1},db),/current status|range/i);
 const problemRequest={taskId:"pack",accountId:"acct",actorUserId:"packer",expectedQuantity:0,reason:"PACKING_BLOCKED",note:"Fake blocked",clientRequestId:"problem-1"};await Promise.all([reportWorkTaskProblem(problemRequest,db),reportWorkTaskProblem(problemRequest,db)]);let problem=await db.workTask.findUniqueOrThrow({where:{id:"pack"}});assert.equal(problem.status,"PROBLEM");assert.equal(problem.completedQuantity,0);assert.equal((await db.consignmentBatch.findUniqueOrThrow({where:{id:"batch"}})).status,"PROBLEM");assert.equal(await db.workActionLog.count({where:{taskId:"pack",clientRequestId:"problem-1"}}),1,"Concurrent problem retry records one action");
 const viewerProblems=await getWorkerTaskQueue({actorUserId:"viewer",accountId:"acct",stage:"PACK",status:"problem"},db);assert.equal(viewerProblems.tasks.length,1,"View-all worker can read account problems");
 await assert.rejects(()=>resolveWorkTaskProblem({taskId:"pack",accountId:"acct",actorUserId:"viewer",resolutionNote:"Not allowed"},db),/resolution permission/i);
 await assert.rejects(()=>reassignWorkTask({taskId:"pack",accountId:"acct",actorUserId:"viewer",assignedUserId:null},db),/management permission/i);
 await assert.rejects(()=>reassignConsignmentStage({batchId:"batch",accountId:"acct",actorUserId:"viewer",stage:"PACK",assignedUserId:null},db),/management permission/i);
 await assert.rejects(()=>incrementWorkTaskProgress({taskId:"pack",accountId:"acct",actorUserId:"packer",expectedQuantity:0,increment:1},db),/authoritative Pack Completed/i);
 const resolveRequest={taskId:"pack",accountId:"acct",actorUserId:"manager",resolutionNote:"Fake issue resolved",clientRequestId:"resolve-1"};await Promise.all([resolveWorkTaskProblem(resolveRequest,db),resolveWorkTaskProblem(resolveRequest,db)]);problem=await db.workTask.findUniqueOrThrow({where:{id:"pack"}});assert.equal(problem.status,"READY");assert.equal(problem.problemReason,"PACKING_BLOCKED","Problem history remains");assert.equal(await db.workActionLog.count({where:{taskId:"pack",clientRequestId:"resolve-1"}}),1,"Concurrent resolution retry records one action");
 await completeWorkTask({taskId:"pack",accountId:"acct",actorUserId:"packer",expectedQuantity:0,clientRequestId:"complete-pack"},db);assert.ok((await db.consignmentLine.findUniqueOrThrow({where:{id:"line"}})).completedAt);assert.equal((await db.consignmentBatch.findUniqueOrThrow({where:{id:"batch"}})).status,"COMPLETED");
 const active=await getWorkerTaskQueue({actorUserId:"packer",accountId:"acct",stage:"PACK",search:"SKU-1"},db);assert.equal(active.tasks.length,0,"Completed task is excluded from active exact search");const history=await getWorkerTaskQueue({actorUserId:"packer",accountId:"acct",stage:"PACK",search:"FSN-1",status:"completed"},db);assert.equal(history.tasks.length,1);
 const exactListing=await getWorkerTaskQueue({actorUserId:"owner",accountId:"acct",stage:"PACK",search:"LID-1",status:"completed"},db);assert.equal(exactListing.tasks.length,1);
 await db.consignmentBatch.create({data:{id:"batch-mark",accountId:"acct",marketplace:"FLIPKART",externalConsignmentNumber:"CN-2",displayName:"Marked Batch",status:"ACTIVE",sourceFileName:"fake-mark.csv",sourceFileSha256:"sha-mark"}});
 await db.consignmentLine.create({data:{id:"line-mark",consignmentBatchId:"batch-mark",accountId:"acct",rowNumber:2,requiredQuantity:2,matchStatus:"OWNER_SELECTED",marketplaceListingId:"listing",processRoute:"PICK_MARK_PACK",activated:true,productTitleSnapshot:"Fake Product",sellerSkuSnapshot:"SKU-1",fsnSnapshot:"FSN-1",listingIdSnapshot:"LID-1"}});
 await db.workTask.createMany({data:[{id:"pick-mark",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-mark",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"READY"},{id:"mark",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-mark",stage:"MARK",sequenceNumber:2,requiredQuantity:2,status:"LOCKED"},{id:"pack-mark",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-mark",stage:"PACK",sequenceNumber:3,requiredQuantity:2,status:"LOCKED"}]});
 await assert.rejects(()=>reassignWorkTask({taskId:"mark",accountId:"acct",actorUserId:"owner",assignedUserId:"picker1"},db),/stage permission/i);const assignRequest={taskId:"mark",accountId:"acct",actorUserId:"owner",assignedUserId:"marker",clientRequestId:"assign-mark-1"};await Promise.all([reassignWorkTask(assignRequest,db),reassignWorkTask(assignRequest,db)]);assert.equal(await db.workActionLog.count({where:{taskId:"mark",clientRequestId:"assign-mark-1"}}),1,"Concurrent assignment retry records one action");await assert.rejects(()=>reassignWorkTask({...assignRequest,assignedUserId:"owner"},db),/different payload/i);
 await assert.rejects(()=>reportWorkTaskProblem({taskId:"pick-mark",accountId:"acct",actorUserId:"no-report",expectedQuantity:0,reason:"OTHER"},db),/reporting permission/i);
 await reportWorkTaskProblem({taskId:"pick-mark",accountId:"acct",actorUserId:"picker1",expectedQuantity:0,reason:"OTHER",clientRequestId:"owner-resolve-setup"},db);const ownProblem=await getWorkerTaskQueue({actorUserId:"picker1",accountId:"acct",stage:"PICK",status:"problem"},db);assert.equal(ownProblem.tasks.length,1,"Normal worker sees their assigned or reported problem");await resolveWorkTaskProblem({taskId:"pick-mark",accountId:"acct",actorUserId:"owner",resolutionNote:"Owner resolved fake issue",clientRequestId:"owner-resolve"},db);
 await completeWorkTask({taskId:"pick-mark",accountId:"acct",actorUserId:"owner",expectedQuantity:0,clientRequestId:"owner-pick"},db);const readyMark=await db.workTask.findUniqueOrThrow({where:{id:"mark"}});assert.equal(readyMark.status,"READY");assert.equal(readyMark.assignedUserId,"marker","Explicit future-stage assignment survives unlock");assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"pack-mark"}})).status,"LOCKED");
 await assert.rejects(()=>claimWorkTask({taskId:"mark",accountId:"acct",actorUserId:"packer"},db),/permission/i);await completeWorkTask({taskId:"mark",accountId:"acct",actorUserId:"marker",expectedQuantity:0,clientRequestId:"mark-complete"},db);assert.equal((await db.workTask.findUniqueOrThrow({where:{id:"pack-mark"}})).status,"READY");
 await completeWorkTask({taskId:"pack-mark",accountId:"acct",actorUserId:"packer",expectedQuantity:0,clientRequestId:"pack-mark-complete"},db);assert.equal((await db.consignmentBatch.findUniqueOrThrow({where:{id:"batch-mark"}})).status,"COMPLETED");
 const completedPackCounts=(await getWorkHubCounts(await db.user.findUniqueOrThrow({where:{id:"owner"}}),"acct",db)).PACK;assert.ok(completedPackCounts.completedToday>=2,"Completed PACK tasks remain in completed-today counts after their lines complete");const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);await db.workTask.update({where:{id:"pack"},data:{completedAt:yesterday}});const todayHistory=await getWorkerTaskQueue({actorUserId:"owner",accountId:"acct",stage:"PACK",search:"SKU-1",status:"completed"},db);assert.equal(todayHistory.tasks.length,1,"Completed-today excludes older work");
 await db.consignmentBatch.create({data:{id:"batch-count",accountId:"acct",marketplace:"FLIPKART",externalConsignmentNumber:"CN-COUNT",displayName:"Count Batch",status:"ACTIVE",sourceFileName:"fake-count.csv",sourceFileSha256:"sha-count"}});
 await db.consignmentLine.createMany({data:["own","other","free","reported"].map((suffix,index)=>({id:`line-${suffix}`,consignmentBatchId:"batch-count",accountId:"acct",rowNumber:index+2,requiredQuantity:2,matchStatus:"EXACT_SKU" as const,marketplaceListingId:"listing",processRoute:"PICK_PACK" as const,activated:true,productTitleSnapshot:"Fake Product",sellerSkuSnapshot:"SKU-1"}))});
 await db.workTask.createMany({data:[{id:"count-own",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-own",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"IN_PROGRESS",assignedUserId:"picker1"},{id:"count-other",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-other",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"READY",assignedUserId:"picker2"},{id:"count-free",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-free",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"READY"},{id:"count-problem",accountId:"acct",sourceType:"CONSIGNMENT",consignmentLineId:"line-reported",stage:"PICK",sequenceNumber:1,requiredQuantity:2,status:"PROBLEM",assignedUserId:"picker2",problemReason:"OTHER",problemReportedByUserId:"picker1",problemReportedAt:new Date()}]});
 const pickerCounts=(await getWorkHubCounts(await db.user.findUniqueOrThrow({where:{id:"picker1"}}),"acct",db)).PICK;assert.equal(pickerCounts.ready,1,"Normal ready excludes another worker assignment");assert.equal(pickerCounts.inProgress,1);assert.equal(pickerCounts.problems,1,"Reporter sees their problem count");
 const viewCounts=(await getWorkHubCounts(await db.user.findUniqueOrThrow({where:{id:"viewer"}}),"acct",db)).PICK;assert.equal(viewCounts.ready,2,"View-all count is account-wide");assert.equal(viewCounts.problems,1);
 assert.equal(await db.workActionLog.count({where:{taskId:"pick",clientRequestId:"inc-1"}}),1);
}finally{await db.$disconnect();try{rmSync(file,{force:true,maxRetries:5,retryDelay:100});}catch{/* Windows may release the SQLite handle only after process exit. */}}
console.log("Workflow worker transaction and authorization tests passed.");
