import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { COMPARISON_PATH, compareSnapshots, databaseFileName, inspectDatabase, latestVerifiedManifest, MIGRATION_RESULT_PATH, POST_COUNTS_PATH, resolveRealDatabasePath, sha256File, writeJson } from "./safety.mjs";

if(!process.argv.includes("--confirm-real-migration")){console.error("Real migration was not run. First run backup, test-migrations, and verify; then add --confirm-real-migration.");process.exit(2);}
const databasePath=resolveRealDatabasePath();const before=inspectDatabase(databasePath);const {manifest}=latestVerifiedManifest();if(!existsSync(MIGRATION_RESULT_PATH))throw new Error("Migration-test proof is missing.");const test=JSON.parse(readFileSync(MIGRATION_RESULT_PATH,"utf8"));const currentSha=await sha256File(databasePath);if(manifest.verified!==true||test.passed!==true||test.applicationSuitesPassed!==true||manifest.sourcePath!==databasePath||test.sourcePath!==databasePath||test.backupSha256!==manifest.backupSha256||currentSha!==manifest.sourceSha256)throw new Error("Real migration refused: backup/test proof is missing or the database changed after backup.");
console.log(`Resolved real database: ${databasePath}`);console.log(`Verified backup: ${manifest.backupPath}`);console.log(`Pending migrations: ${before.pendingMigrations.join(", ")||"none"}`);const expected=databaseFileName(databasePath);const terminal=readline.createInterface({input,output});const typed=await terminal.question(`Type ${expected} to migrate this exact database: `);terminal.close();if(typed.trim()!==expected){console.error("Typed confirmation did not match. Real migration was not run.");process.exit(2);}
const command=process.platform==="win32"?"npx.cmd":"npx";const executable=process.platform==="win32"?"cmd.exe":command;const args=["prisma","migrate","deploy","--schema","prisma/schema.prisma"];const executableArgs=process.platform==="win32"?["/d","/s","/c",command,...args]:args;const result=spawnSync(executable,executableArgs,{cwd:process.cwd(),env:{...process.env,DATABASE_URL:`file:${databasePath.replace(/\\/g,"/")}`},stdio:"inherit"});if(result.status!==0)throw new Error(`Real migration failed with exit code ${result.status??1}.`);
const after=inspectDatabase(databasePath);const comparison=compareSnapshots(before,after);writeJson(POST_COUNTS_PATH,after);writeJson(COMPARISON_PATH,comparison);if(after.integrity.join(",")!=="ok"||after.foreignKeyViolationCount||after.pendingMigrations.length||!comparison.ok)throw new Error("Post-migration verification failed. Stop using the app and inspect the verified backup.");console.log(JSON.stringify({migrated:true,databasePath,integrity:after.integrity,foreignKeyViolationCount:after.foreignKeyViolationCount,pendingMigrations:after.pendingMigrations,comparison},null,2));
