"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAccount, requireUser } from "@/lib/auth";
import { claimWorkTask, completeWorkTask, incrementWorkTaskProgress, reassignConsignmentStage, reassignWorkTask, reportWorkTaskProblem, resolveWorkTaskProblem, setWorkTaskProgress } from "@/src/lib/workflow/task-store";

function value(form:FormData,name:string,max=1000){return String(form.get(name)??"").normalize("NFKC").trim().slice(0,max);}
function number(form:FormData,name:string){return Number(value(form,name,30));}
function returnPath(form:FormData){const path=value(form,"returnPath",300);return (path.startsWith("/work")||path.startsWith("/owner/consignments"))&&!path.startsWith("//")?path:"/work";}
function resultPath(path:string,key:string,message?:string){const join=path.includes("?")?"&":"?";return `${path}${join}${key}=${encodeURIComponent(message??"1")}`;}
async function context(){const user=await requireUser();const account=await requireAccount(user);return{user,account};}
async function runAction(path:string,success:string,fallback:string,mutation:()=>Promise<unknown>){let error:string|null=null;try{await mutation();}catch(cause){error=cause instanceof Error?cause.message:fallback;}if(error)redirect(resultPath(path,"error",error));revalidatePath(path);redirect(resultPath(path,"success",success));}

export async function claimTaskAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Task started","Could not claim task.",()=>claimWorkTask({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,clientRequestId:value(form,"clientRequestId",120)}));}
export async function incrementTaskAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Progress saved","Could not update task.",()=>incrementWorkTaskProgress({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,expectedQuantity:number(form,"expectedQuantity"),increment:number(form,"increment"),clientRequestId:value(form,"clientRequestId",120)}));}
export async function setTaskProgressAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Progress saved","Could not update task.",()=>setWorkTaskProgress({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,expectedQuantity:number(form,"expectedQuantity"),targetQuantity:number(form,"targetQuantity"),clientRequestId:value(form,"clientRequestId",120),action:"set"}));}
export async function completeTaskAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Stage completed","Could not complete task.",()=>completeWorkTask({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,expectedQuantity:number(form,"expectedQuantity"),clientRequestId:value(form,"clientRequestId",120)}));}
export async function reportTaskProblemAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Problem reported","Could not report problem.",()=>reportWorkTaskProblem({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,expectedQuantity:number(form,"expectedQuantity"),reason:value(form,"reason",80),note:value(form,"note",1000),clientRequestId:value(form,"clientRequestId",120)}));}
export async function resolveTaskProblemAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Problem resolved","Could not resolve problem.",()=>resolveWorkTaskProblem({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,resolutionNote:value(form,"resolutionNote",1000),clientRequestId:value(form,"clientRequestId",120)}));}
export async function reassignTaskAction(form:FormData){const {user,account}=await context();const path=returnPath(form);await runAction(path,"Assignment updated","Could not assign task.",()=>reassignWorkTask({taskId:value(form,"taskId",80),accountId:account.id,actorUserId:user.id,assignedUserId:value(form,"assignedUserId",80)||null,clientRequestId:value(form,"clientRequestId",120)||undefined}));}
export async function assignConsignmentStageAction(form:FormData){const {user,account}=await context();const path=returnPath(form);const stage=value(form,"stage",20);await runAction(path,"Stage assignment updated","Could not assign stage.",()=>{if(!["PICK","MARK","PACK"].includes(stage))throw new Error("Invalid stage.");return reassignConsignmentStage({batchId:value(form,"batchId",80),accountId:account.id,actorUserId:user.id,stage:stage as "PICK"|"MARK"|"PACK",assignedUserId:value(form,"assignedUserId",80)||null,clientRequestId:value(form,"clientRequestId",120)||undefined});});}
