"use client";
import Link from "next/link";
import { useEffect,useState,type ReactNode } from "react";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import type { GroupedWorkCard as Card } from "@/src/lib/workflow/grouped-work";
import type { WorkChangeDetail } from "./LiveWorkRefresh";
import { completeGroupedStageAction } from "./stage-actions";

export function GroupedWorkCard({card:initialCard,canAct}:{card:Card;canAct:boolean}){
 const [card,setCard]=useState(initialCard),[processing,setProcessing]=useState(false),[removed,setRemoved]=useState(false);
 useEffect(()=>{setCard(initialCard);setRemoved(false);},[initialCard]);
 useEffect(()=>{const changed=async(event:Event)=>{const detail=(event as CustomEvent<WorkChangeDetail>).detail;if(detail.groupKey!==card.groupKey)return;if(detail.eventType==="STAGE_COMPLETED"&&detail.stage===card.stage){setRemoved(true);return;}try{const response=await fetch(`/api/work/groups/${card.stage.toLowerCase()}/${card.groupKey}?source=${card.sourceType}`,{cache:"no-store"});if(response.status===404){setRemoved(true);return;}if(response.ok){const data=await response.json() as{card:Card};setCard(data.card);}}catch{}};window.addEventListener("work-change",changed);return()=>window.removeEventListener("work-change",changed);},[card.groupKey,card.sourceType,card.stage]);
 if(removed)return null;
 const token=`${card.groupKey}:${card.groupVersion}`,details=`/work/groups/${card.stage.toLowerCase()}/${card.groupKey}?source=${card.sourceType}`;
 const hidden=(suffix:string,next?:string,useRecommended=false)=><><input type="hidden" name="stage" value={card.stage}/><input type="hidden" name="sourceType" value={card.sourceType}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="nextStage" value={next??""}/><input type="hidden" name="useRecommended" value={useRecommended?"1":"0"}/><input type="hidden" name="clientRequestId" value={`${token}:${suffix}`}/></>;
 if(processing)return <div className="rounded-md border bg-white p-5 font-bold text-slate-600" aria-live="polite">Processing group…</div>;
 return <article onClickCapture={event=>{if((event.target as HTMLElement).closest('button[type="submit"]'))setProcessing(true);}} className="grid gap-4 rounded-md border bg-white p-4 shadow-sm md:grid-cols-[7rem_minmax(12rem,1fr)_minmax(10rem,auto)_minmax(16rem,auto)] md:items-center">
  <ProductImage src={card.productImageUrl} alt={card.productTitle??card.sellerSku} size="md" showBadge={false}/>
  <div className="min-w-0"><div className="flex flex-wrap gap-1"><Badge dark>{card.sourceType==="ORDER"?"DAILY ORDERS":"CONSIGNMENT"}</Badge><Badge>{card.marketplace}</Badge><Badge>{card.status.replaceAll("_"," ")}</Badge></div><p className="mt-2 text-xl font-black">{card.sellerSku}</p><p className="line-clamp-2 text-sm text-slate-600">{card.productTitle??"Untitled product"}</p><p className="mt-2 break-words text-sm font-bold">{card.operationalIdentifier??card.reference}</p></div>
  <div className="rounded-md bg-slate-50 p-3 text-sm font-bold"><p className="text-2xl font-black">{card.completedQuantity}/{card.requiredQuantity}</p><p>{card.memberCount} {card.sourceType==="ORDER"?"orders":"items"}</p><p>{card.completeMemberCount} complete · {card.partialMemberCount} partial</p><p>Pending {card.pendingQuantity}</p>{card.problemCount?<p className="text-rose-700">{card.problemCount} problem {card.problemCount===1?"member":"members"}</p>:null}<p className="mt-2 text-xs text-slate-600">{card.hasExplicitSavedRoute?`Saved route: ${card.savedProcessRoute??"Configured"}`:"SYSTEM FALLBACK — DIRECT TO PACK"}</p><p className="text-xs text-slate-500">Recommended next: {card.recommendedNextStage??"Complete"}</p><p className="text-xs text-slate-500">{card.assignedUserName?`Assigned ${card.assignedUserName}`:"Unassigned"}</p></div>
  {canAct?<div className="grid grid-cols-2 gap-2">{card.stage==="PICK"?<><Action label="Picked">{hidden("default",undefined,true)}</Action><Action label="Marking" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="MARK"} warnsMissing={card.missingInstructionStages.includes("MARK")}>{hidden("mark","MARK")}</Action><Action label="Assembly" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="ASSEMBLE"} warnsMissing={card.missingInstructionStages.includes("ASSEMBLE")}>{hidden("assembly","ASSEMBLE")}</Action><Details href={details}/></>:card.stage==="MARK"?<><Action label="Marked">{hidden("default",undefined,true)}</Action><Action label="Send to Pack" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="PACK"}>{hidden("pack","PACK")}</Action><Action label="Send to Assembly" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="ASSEMBLE"} warnsMissing={card.missingInstructionStages.includes("ASSEMBLE")}>{hidden("assembly","ASSEMBLE")}</Action><Details href={details}/></>:card.stage==="ASSEMBLE"?<><Action label="Assembled">{hidden("default",undefined,true)}</Action><Action label="Send to Pack" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="PACK"}>{hidden("pack","PACK")}</Action><Action label="Send to Marking" reasonRequired={card.hasExplicitSavedRoute&&card.recommendedNextStage!=="MARK"} warnsMissing={card.missingInstructionStages.includes("MARK")}>{hidden("mark","MARK")}</Action><Details href={details}/></>:<><Action label="Pack Completed">{hidden("complete")}</Action><Link href={`${details}&problem=1`} className="flex min-h-11 items-center justify-center rounded-md border font-bold text-rose-700">Problem</Link><Details href={details}/></>}</div>:<div className="rounded-md bg-slate-50 p-3 text-sm font-bold text-slate-600"><p>Read-only work view</p><Details href={details}/></div>}
 </article>;
}
function Badge({children,dark=false}:{children:ReactNode;dark?:boolean}){return <span className={`rounded-full px-2 py-1 text-xs font-black ${dark?"bg-slate-950 text-white":"bg-slate-100"}`}>{children}</span>}
function Action({label,children,reasonRequired=false,warnsMissing=false}:{label:string;children:ReactNode;reasonRequired?:boolean;warnsMissing?:boolean}){return <form action={completeGroupedStageAction} className={reasonRequired||warnsMissing?"col-span-2 rounded-md border border-amber-300 bg-amber-50 p-2":""}>{children}{warnsMissing?<label className="mb-2 flex min-h-11 items-center gap-2 text-xs font-bold text-amber-950"><input type="checkbox" name="confirmMissingInstructions" value="1" required/>Saved instructions are unavailable. Create clearly labelled manual-route work.</label>:null}{reasonRequired?<><label className="mb-2 block text-xs font-bold text-amber-950">Route-change reason<select name="routeReason" required className="mt-1 min-h-11 w-full rounded-md border bg-white px-2 text-sm"><option value="">Choose reason</option>{["Assembly required","Marking required","Wrong saved route","Special order requirement","Product needs correction","Other"].map(reason=><option key={reason}>{reason}</option>)}</select></label><input name="routeOtherReason" maxLength={240} placeholder="If Other, add a short reason" className="mb-2 min-h-11 w-full rounded-md border bg-white px-2 text-sm"/></>:null}<SubmitButton pendingText="Processing...">{label}</SubmitButton></form>}
function Details({href}:{href:string}){return <Link href={href} className="flex min-h-11 items-center justify-center rounded-md border px-3 text-center font-bold">Details</Link>}
