"use client";
import Link from "next/link";
import { useState,type ReactNode } from "react";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import type { GroupedWorkCard as Card } from "@/src/lib/workflow/grouped-work";
import { completeGroupedStageAction } from "./stage-actions";

export function GroupedWorkCard({card,canAct}:{card:Card;canAct:boolean}){const [processing,setProcessing]=useState(false),token=`${card.groupKey}:${card.groupVersion}`,details=`/work/groups/${card.stage.toLowerCase()}/${card.groupKey}?source=${card.sourceType}`;const hidden=(suffix:string,next?:string,useRecommended=false)=><><input type="hidden" name="stage" value={card.stage}/><input type="hidden" name="sourceType" value={card.sourceType}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="nextStage" value={next??""}/><input type="hidden" name="useRecommended" value={useRecommended?"1":"0"}/><input type="hidden" name="clientRequestId" value={`${token}:${suffix}`}/></>;
 if(processing)return <div className="rounded-md border bg-white p-5 font-bold text-slate-600" aria-live="polite">Processing group…</div>;
 return <article onClickCapture={event=>{if((event.target as HTMLElement).closest('button[type="submit"]'))setProcessing(true);}} className="grid gap-4 rounded-md border bg-white p-4 shadow-sm sm:grid-cols-[6rem_minmax(0,1fr)]"><ProductImage src={card.productImageUrl} alt={card.productTitle??card.sellerSku} size="md" showBadge={false}/><div className="min-w-0"><div className="flex flex-wrap gap-1"><span className="rounded-full bg-slate-950 px-2 py-1 text-xs font-black text-white">{card.sourceType==="ORDER"?"DAILY ORDERS":"CONSIGNMENT"}</span><span className="rounded-full bg-pink-50 px-2 py-1 text-xs font-black text-berry">{card.marketplace}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{card.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-xl font-black">{card.sellerSku}</p><p className="line-clamp-2 text-sm text-slate-600">{card.productTitle??"Untitled product"}</p><p className="mt-2 break-words text-sm font-bold">{card.operationalIdentifier??card.reference}</p><div className="mt-3 flex flex-wrap gap-3 text-sm font-bold"><span>{card.memberCount} {card.sourceType==="ORDER"?"orders":"items"}</span><span>Qty {card.requiredQuantity}</span><span>Completed {card.completedQuantity}</span><span>Pending {card.pendingQuantity}</span>{card.problemCount?<span className="text-rose-700">Problem {card.problemCount}</span>:null}</div><p className="mt-2 text-xs text-slate-500">Recommended: {card.recommendedNextStage??"Complete"} / {card.assignedUserName?`Assigned ${card.assignedUserName}`:"Unassigned"}</p>{canAct?<div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{card.stage==="PICK"?<><Action label="Picked">{hidden("default",undefined,true)}</Action><Action label="Marking">{hidden("mark","MARK")}</Action><Action label="Assembly">{hidden("assembly","ASSEMBLE")}</Action><Details href={details}/></>:card.stage==="MARK"?<><Action label="Marked">{hidden("default",undefined,true)}</Action><Action label="Send to Pack">{hidden("pack","PACK")}</Action><Action label="Send to Assembly">{hidden("assembly","ASSEMBLE")}</Action><Details href={details}/></>:card.stage==="ASSEMBLE"?<><Action label="Assembled">{hidden("default",undefined,true)}</Action><Action label="Send to Pack">{hidden("pack","PACK")}</Action><Action label="Send to Marking">{hidden("mark","MARK")}</Action><Details href={details}/></>:<><Action label="Pack Completed">{hidden("complete")}</Action><Link href={`${details}&problem=1`} className="flex min-h-11 items-center justify-center rounded-md border font-bold text-rose-700">Problem</Link><Details href={details}/></>}</div>:<div className="mt-4 flex items-center justify-between rounded-md bg-slate-50 p-3 text-sm font-bold text-slate-600"><span>Read-only work view</span><Details href={details}/></div>}</div></article>;
}
function Action({label,children}:{label:string;children:ReactNode}){return <form action={completeGroupedStageAction}>{children}<SubmitButton pendingText="Processing...">{label}</SubmitButton></form>}
function Details({href}:{href:string}){return <Link href={href} className="flex min-h-11 items-center justify-center rounded-md border px-3 text-center font-bold">Open Details</Link>}
