"use client";
import Link from "next/link";
import { useEffect,useState,type ReactNode } from "react";
import type { GroupedWorkCard as Card } from "@/src/lib/workflow/grouped-work";
import type { WorkChangeDetail } from "./LiveWorkRefresh";
import { WorkImageGallery } from "@/components/WorkImageGallery";
import { WorkRouteDialog } from "@/components/WorkRouteDialog";
import { completeGroupedStageAction } from "./stage-actions";
import { SubmitButton } from "@/components/SubmitButton";

export function GroupedWorkCard({card:initialCard,canAct}:{card:Card;canAct:boolean}){
 const [card,setCard]=useState(initialCard),[removed,setRemoved]=useState(false);useEffect(()=>{setCard(initialCard);setRemoved(false);},[initialCard]);useEffect(()=>{const changed=async(event:Event)=>{const detail=(event as CustomEvent<WorkChangeDetail>).detail;if(detail.groupKey!==card.groupKey)return;if(detail.eventType==="STAGE_COMPLETED"&&detail.stage===card.stage){setRemoved(true);return;}try{const response=await fetch(`/api/work/groups/${card.stage.toLowerCase()}/${card.groupKey}?source=${card.sourceType}`,{cache:"no-store"});if(response.status===404){setRemoved(true);return;}if(response.ok)setCard(((await response.json())as{card:Card}).card);}catch{}};window.addEventListener("work-change",changed);return()=>window.removeEventListener("work-change",changed);},[card.groupKey,card.sourceType,card.stage]);if(removed)return null;
 const details=`/work/groups/${card.stage.toLowerCase()}/${card.groupKey}?source=${card.sourceType}`,token=`${card.groupKey}:${card.groupVersion}`,isPackage=card.sourceType==="ORDER"&&card.stage==="PACK";
 const identity=isPackage?`Package ${card.trackingId??card.operationalIdentifier??card.reference}`:card.sourceType==="ORDER"?`Order Item ${card.orderItemId??card.reference}`:`Consignment line ${card.consignmentLineId?.slice(-8)??card.reference}`;
 const hidden=<><input type="hidden" name="stage" value={card.stage}/><input type="hidden" name="sourceType" value={card.sourceType}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="clientRequestId" value={`${token}:complete`}/></>;
 return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" data-responsive-work-card data-source={card.sourceType} data-stage={card.stage}><div className="grid gap-4 p-4 md:grid-cols-[150px_minmax(0,1fr)_220px] md:items-center xl:grid-cols-[minmax(200px,240px)_minmax(0,1fr)_300px]">
  <WorkImageGallery images={[card.productImageUrl]} alt={card.productTitle??card.sellerSku}/><div className="min-w-0"><div className="flex flex-nowrap gap-1"><Badge dark>{card.sourceType==="ORDER"?"CUSTOMER ORDER":"CONSIGNMENT"}</Badge><Badge>{card.marketplace}</Badge><Badge>{card.stage}</Badge><Badge>{card.status.replaceAll("_"," ")}</Badge></div><p className="mt-3 text-xs font-black uppercase tracking-wide text-berry">{identity}</p><h2 className="mt-1 break-words text-xl font-black leading-tight">{card.productTitle??"Untitled product"}</h2><p className="mt-1 break-all font-mono text-sm font-bold">Seller SKU {card.sellerSku}</p><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{card.orderItemId?<Item label="Order Item ID" value={card.orderItemId}/>:null}{card.orderNumber?<Item label="Order ID" value={card.orderNumber}/>:null}{card.shipmentId?<Item label="Shipment ID" value={card.shipmentId}/>:null}{card.trackingId?<Item label="Tracking ID" value={card.trackingId}/>:null}{card.consignmentNumber?<Item label="Consignment" value={card.consignmentNumber}/>:null}<Item label="Current stage" value={card.stage}/><Item label="Route" value={card.hasExplicitSavedRoute?card.savedProcessRoute??"Saved":"System fallback — Direct to Pack"}/><Item label="Assignment" value={card.assignedUserName??"Unassigned"}/>{card.problemCount?<Item label="Problem state" value={`${card.problemCount} problem`}/>:null}</dl></div>
  <div className="w-full rounded-2xl border border-slate-200 bg-slate-50 p-3 md:max-w-[220px] md:justify-self-end xl:max-w-[300px]" data-quantity-panel>{isPackage?<><p className="text-sm font-black text-slate-500">Package quantity</p><p className="mt-1 text-3xl font-black">{card.requiredQuantity}</p><p className="mt-2 font-bold">Order items: {card.memberCount}</p><p className="font-bold">Total package quantity: {card.requiredQuantity}</p></>:<><p className="text-sm font-black text-slate-500">Quantity to process</p><p className="mt-1 text-3xl font-black">{card.requiredQuantity}</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span><b>Completed</b><br/>{card.completedQuantity}</span><span><b>Pending</b><br/>{card.pendingQuantity}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-teal-600" style={{width:`${Math.min(100,card.requiredQuantity?card.completedQuantity/card.requiredQuantity*100:0)}%`}}/></div></>}</div>
 </div><div className={`grid gap-2 border-t bg-slate-50 p-3 ${card.stage==="PACK"?"grid-cols-2":"grid-cols-2"}`} data-work-actions>{canAct?card.stage==="PACK"?<><form action={completeGroupedStageAction}>{hidden}<SubmitButton pendingText="Packing...">Pack Completed</SubmitButton></form><Details href={details}/><Link href={`${details}#problems`} className="col-span-2 flex min-h-11 items-center justify-center rounded-xl border border-rose-300 bg-white font-black text-rose-700">Problem</Link></>:<><WorkRouteDialog card={{stage:card.stage,sourceType:card.sourceType,groupKey:card.groupKey,groupVersion:card.groupVersion,taskId:card.memberTaskIds[0],completedQuantity:card.completedQuantity,hasExplicitSavedRoute:card.hasExplicitSavedRoute,savedProcessRoute:card.savedProcessRoute,missingInstructionStages:card.missingInstructionStages}} triggerLabel={card.stage==="PICK"?"Picked All":card.stage==="MARK"?"Marking Completed":"Assembly Completed"}/><Link href={`${details}#quantity`} className="flex min-h-11 items-center justify-center rounded-xl border bg-white font-black">Partial Quantity</Link><Link href={`${details}#problems`} className="flex min-h-11 items-center justify-center rounded-xl border border-rose-300 bg-white font-black text-rose-700">Problem</Link><Details href={details}/></>:<><p className="col-span-2 rounded-xl bg-white p-3 text-sm font-bold text-slate-600">Read-only work view</p><Details href={details}/></>}</div></article>;
}
function Badge({children,dark=false}:{children:ReactNode;dark?:boolean}){return <span className={`shrink-0 whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-black xl:text-[11px] ${dark?"bg-slate-950 text-white":"bg-slate-100 text-slate-700"}`}>{children}</span>}
function Item({label,value}:{label:string;value:string}){return <div className="min-w-0"><dt className="text-xs font-black text-slate-500">{label}</dt><dd className="break-all font-semibold">{value}</dd></div>}
function Details({href}:{href:string}){return <Link href={href} className="flex min-h-11 items-center justify-center rounded-xl border bg-white px-3 text-center font-black">Details</Link>}
