"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { applyFallbackVersion,applyLiveBootstrap,applyLiveEvent,beginLiveReconnect,initialLiveWorkClientState } from "@/src/lib/workflow/live-work-client-state";

export type WorkChangeDetail={id:number;eventType:string;sourceType:string;stage:string|null;groupKey:string|null;entityId:string|null};
export function LiveWorkRefresh({stage,source}:{stage:string;source?:string}){
 const router=useRouter(),liveState=useRef(initialLiveWorkClientState()),summaryTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),[fallback,setFallback]=useState(false);
 useEffect(()=>{let events:EventSource|undefined,cancelled=false;liveState.current=initialLiveWorkClientState();const query=new URLSearchParams({stage});if(source)query.set("source",source);
  const updateSummary=()=>{if(summaryTimer.current)clearTimeout(summaryTimer.current);summaryTimer.current=setTimeout(async()=>{try{const response=await fetch(`/api/work/live/summary?stage=${encodeURIComponent(stage)}`,{cache:"no-store"});if(!response.ok)return;const data=await response.json() as{summary:unknown};window.dispatchEvent(new CustomEvent("work-summary-change",{detail:{summary:data.summary}}));}catch{}},120);};
  const check=async()=>{if(document.hidden||events?.readyState===1)return;try{const response=await fetch(`/api/work/live/version?${query}`,{cache:"no-store"});if(!response.ok)return;const data=await response.json() as{version:number},applied=applyFallbackVersion(liveState.current,data.version);liveState.current=applied.state;if(applied.changed){const scrollY=window.scrollY,active=document.activeElement as HTMLElement|null,focusId=active?.id||active?.getAttribute("name");router.refresh();requestAnimationFrame(()=>{window.scrollTo({top:scrollY});if(focusId)(document.getElementById(focusId)||document.querySelector(`[name="${CSS.escape(focusId)}"]`) as HTMLElement|null)?.focus();});}}catch{}};
  const start=async()=>{try{const response=await fetch(`/api/work/live/bootstrap?${query}`,{cache:"no-store"});if(!response.ok)throw new Error("bootstrap failed");const data=await response.json() as{cursor:number;summary?:unknown};if(cancelled)return;liveState.current=applyLiveBootstrap(liveState.current,data.cursor);if(data.summary)window.dispatchEvent(new CustomEvent("work-summary-change",{detail:{summary:data.summary}}));if(typeof EventSource==="undefined")throw new Error("EventSource unavailable");const streamQuery=new URLSearchParams(query);streamQuery.set("after",String(liveState.current.cursor));events=new EventSource(`/api/work/live?${streamQuery}`);events.onmessage=event=>{const detail=JSON.parse(event.data) as WorkChangeDetail,applied=applyLiveEvent(liveState.current,Number(event.lastEventId));liveState.current=applied.state;if(applied.accepted){window.dispatchEvent(new CustomEvent<WorkChangeDetail>("work-change",{detail}));updateSummary();}};events.onopen=()=>setFallback(false);events.onerror=()=>{liveState.current=beginLiveReconnect(liveState.current);setFallback(true);};events.addEventListener("access-revoked",()=>{events?.close();liveState.current=beginLiveReconnect(liveState.current);setFallback(true);});}catch{liveState.current=beginLiveReconnect(liveState.current);setFallback(true);}};void start();
  const poll=setInterval(()=>void check(),30000),visible=()=>{if(!document.hidden)void check();};document.addEventListener("visibilitychange",visible);return()=>{cancelled=true;events?.close();clearInterval(poll);if(summaryTimer.current)clearTimeout(summaryTimer.current);document.removeEventListener("visibilitychange",visible);};
 },[router,source,stage]);
 return <p className="mb-3 text-xs font-bold text-slate-500" aria-live="polite">{fallback?"Live reconnecting — bounded polling active":"Live work updates connected"}</p>;
}
