import Link from "next/link";
import type { WorkStage } from "@prisma/client";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { capabilityHomePath,requireAccount,requireUser } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getSmartStageSummary } from "@/src/lib/workflow/grouped-work";
import { LiveWorkHubSummary } from "./LiveWorkHubSummary";
export default async function WorkHubPage(){const user=await requireUser(),allowed=(["PICK","MARK","ASSEMBLE","PACK"] as WorkStage[]).filter(stage=>hasWorkPermission(user,stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack")||user.canViewAllWork);if(!allowed.length)redirect(capabilityHomePath(user));const account=await requireAccount(user),values=await Promise.all(allowed.map(stage=>getSmartStageSummary({actorUserId:user.id,accountId:account.id,stage}))),initial=Object.fromEntries(allowed.map((stage,index)=>[stage,values[index]]));return <AppShell><PageHeader eyebrow={`${account.marketplace} / ${account.accountDisplayName??account.name}`} title="Work Hub" description="Choose a stage. Daily Orders and Consignments remain visibly separated."/><LiveWorkHubSummary initial={initial}/><section className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/work/scan" className="rounded-md border bg-white p-5 shadow-sm"><p className="text-xs font-black text-berry">SELECTED ACCOUNT</p><p className="mt-2 text-xl font-black">Universal Scan</p><p className="text-sm text-slate-600">Every work state is visible. Scanning alone never mutates.</p></Link><Link href="/work/problems" className="rounded-md border bg-white p-5 shadow-sm"><p className="text-xs font-black text-rose-700">WORK EXCEPTIONS</p><p className="mt-2 text-xl font-black">Problems</p><p className="text-sm text-slate-600">Review assignment and interrupted-stage problems.</p></Link></section></AppShell>}
