import Link from "next/link";
import { redirect } from "next/navigation";
import type { WorkStage } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { requireAccount,requireUser,roleHomePath } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getGroupedWork,getSmartStageSummary,type GroupedWorkSource } from "@/src/lib/workflow/grouped-work";
import { GroupedWorkCard } from "./GroupedWorkCard";
import { LiveStageSummary } from "./LiveStageSummary";
import { LiveWorkRefresh } from "./LiveWorkRefresh";

const TITLES:Record<WorkStage,string>={PICK:"Pick",MARK:"Marking",ASSEMBLE:"Assembly",PACK:"Packing"};
export async function SmartStagePage({stage,searchParams}:{stage:WorkStage;searchParams:Promise<{source?:string;page?:string;success?:string;error?:string}>}){
 const user=await requireUser(),account=await requireAccount(user),permission=stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack";if(!hasWorkPermission(user,permission)&&!user.canViewAllWork)redirect(roleHomePath(user.role));
 const query=await searchParams,summary=await getSmartStageSummary({actorUserId:user.id,accountId:account.id,stage}),projectionUnavailable=summary.ORDER.projectionUnavailable||summary.CONSIGNMENT.projectionUnavailable,available=(['ORDER','CONSIGNMENT'] as GroupedWorkSource[]).filter(item=>summary[item].cardCount>0);let source=(query.source==="ORDER"||query.source==="CONSIGNMENT"?query.source:null) as GroupedWorkSource|null;if(source&&!available.includes(source))source=null;if(!source&&available.length===1)source=available[0];const page=Math.max(1,Number(query.page)||1),result=source?await getGroupedWork({actorUserId:user.id,accountId:account.id,stage,sourceType:source,page}):null,canAct=hasWorkPermission(user,permission);
 return <AppShell><PageHeader eyebrow={`${account.marketplace} / ${account.accountDisplayName??account.name}`} title={TITLES[stage]} description="Selected-account work only. Choose a source when both Daily Orders and Consignments are active."/><LiveWorkRefresh stage={stage} source={source??undefined}/><LiveStageSummary initial={summary} selectedSource={source??undefined}/>{projectionUnavailable?<div role="alert" className="mb-4 rounded-md border border-amber-400 bg-amber-50 p-4 text-amber-950"><p className="font-black">Work projection unavailable</p><p className="mt-1 text-sm">Worker actions are hidden until an owner runs the bounded projection inspection and repair command.</p></div>:null}{query.success?<p className="mb-3 rounded-md bg-teal-50 p-3 font-bold text-teal-800">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</p>:null}{projectionUnavailable?null:!available.length?<div className="rounded-md border border-dashed bg-white p-8 text-center"><p className="text-xl font-black">No active {TITLES[stage].toLowerCase()} work</p><p className="mt-2 text-sm text-slate-600">New eligible work will appear here automatically.</p></div>:!source?<div className="grid gap-4 md:grid-cols-2">{available.map(item=><SourceCard key={item} stage={stage} source={item} summary={summary[item]}/>)}</div>:<><section className="space-y-3">{result?.cards.map(card=><GroupedWorkCard key={card.groupKey} card={card} canAct={canAct}/>)}</section>{result&&!result.cards.length?<p className="rounded-md border border-dashed bg-white p-6 text-center font-bold">No actionable cards in this source.</p>:null}<div className="mt-5 flex justify-between">{page>1?<Link href={`?source=${source}&page=${page-1}`} className="rounded-md border px-4 py-2 font-bold">Previous</Link>:<span/>}{result?.hasMore?<Link href={`?source=${source}&page=${page+1}`} className="rounded-md border px-4 py-2 font-bold">Next</Link>:null}</div></>}</AppShell>;
}
function SourceCard({stage,source,summary}:{stage:WorkStage;source:GroupedWorkSource;summary:{cardCount:number;itemCount:number;requiredQuantity:number;problems:number;assignedToMe:number;oldestWaitingAt:string|null}}){return <Link href={`?source=${source}`} className="rounded-md border bg-white p-6 shadow-sm hover:border-berry"><p className="text-xs font-black text-berry">{source==="ORDER"?"DAILY ORDERS":"CONSIGNMENTS"}</p><p className="mt-2 text-2xl font-black">Open {stage[0]}{stage.slice(1).toLowerCase()}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><span>Cards {summary.cardCount}</span><span>Items {summary.itemCount}</span><span>Quantity {summary.requiredQuantity}</span><span>Problems {summary.problems}</span><span>Assigned to me {summary.assignedToMe}</span><span>Oldest {summary.oldestWaitingAt?new Date(summary.oldestWaitingAt).toLocaleString():"—"}</span></div></Link>}
