"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { WorkStage } from "@prisma/client";
import { requireAccount,requireUser } from "@/lib/auth";
import { completeGroupedStage } from "@/src/lib/workflow/grouped-transition";
import { completeSelectedGroupMembers, setGroupedProgress } from "@/src/lib/workflow/grouped-progress";
import { completePickWithNextRoute } from "@/src/lib/workflow/route-selection";
import { prisma } from "@/lib/prisma";

const value=(form:FormData,name:string,max=200)=>String(form.get(name)??"").normalize("NFKC").trim().slice(0,max);
export async function completeGroupedStageAction(form:FormData){const user=await requireUser();const account=await requireAccount(user);const stage=value(form,"stage",20) as WorkStage,sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",next=value(form,"nextStage",20) as WorkStage;const path=`/work/${stage.toLowerCase()}?source=${sourceType}`;let error="";try{await completeGroupedStage({actorUserId:user.id,selectedAccountId:account.id,sourceType,stage,groupKey:value(form,"groupKey",80),expectedGroupVersion:value(form,"groupVersion",80),nextStage:next||undefined,useRecommendedNextStage:value(form,"useRecommended",5)==="1",routeReason:value(form,"routeReason",80)||undefined,routeOtherReason:value(form,"routeOtherReason",240)||undefined,workerNote:value(form,"workerNote",240)||undefined,confirmMissingInstructions:value(form,"confirmMissingInstructions",5)==="1",clientRequestId:value(form,"clientRequestId",160)});}catch(cause){error=cause instanceof Error?cause.message:"Could not update work.";}for(const route of ["pick","mark","assemble","pack"])revalidatePath(`/work/${route}`);revalidatePath("/work");redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Work routed successfully.")}`}`);}

export async function completeExactPickRouteAction(form:FormData){const user=await requireUser();const account=await requireAccount(user),sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",taskId=value(form,"taskId",80),route=value(form,"route",40),path=`/work/pick?source=${sourceType}`;let error="";try{const task=await prisma.workTask.findFirst({where:{id:taskId,accountId:account.id,sourceType,stage:"PICK"},select:{id:true,orderId:true,completedQuantity:true}});if(!task)throw new Error("Pick work changed; refresh the queue.");const common={accountId:account.id,actorUserId:user.id,route,routeReason:value(form,"routeReason",80)||undefined,routeOtherReason:value(form,"routeOtherReason",240)||undefined,workerNote:value(form,"workerNote",240)||undefined,confirmMissingInstructions:value(form,"confirmMissingInstructions",5)==="1",clientRequestId:value(form,"clientRequestId",160)};if(sourceType==="ORDER"){if(!task.orderId)throw new Error("Order work is unavailable.");await completePickWithNextRoute({sourceType:"ORDER",orderIds:[task.orderId],...common});}else await completePickWithNextRoute({sourceType:"CONSIGNMENT",taskId:task.id,expectedQuantity:Number(value(form,"expectedQuantity",20)),...common});}catch(cause){error=cause instanceof Error?cause.message:"Could not route picked work.";}for(const stage of ["pick","mark","assemble","pack"])revalidatePath(`/work/${stage}`);revalidatePath("/work");redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Picking completed and routed.")}`}`);}

export async function setGroupedProgressAction(form:FormData){const user=await requireUser();const account=await requireAccount(user);const stage=value(form,"stage",20) as WorkStage,sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",groupKey=value(form,"groupKey",80);const path=`/work/groups/${stage.toLowerCase()}/${groupKey}?source=${sourceType}`;let error="";try{await setGroupedProgress({actorUserId:user.id,selectedAccountId:account.id,sourceType,stage,groupKey,expectedGroupVersion:value(form,"groupVersion",80),targetCompletedQuantity:Number(value(form,"targetQuantity",20)),useRecommendedNextStage:true,confirmMissingInstructions:value(form,"confirmMissingInstructions",5)==="1",workerNote:value(form,"workerNote",240)||undefined,clientRequestId:value(form,"clientRequestId",160)});}catch(cause){error=cause instanceof Error?cause.message:"Could not save group progress.";}revalidatePath(path.split("?")[0]);revalidatePath(`/work/${stage.toLowerCase()}`);redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Progress saved and complete members routed.")}`}`);}

export async function completeSelectedGroupMembersAction(form:FormData){const user=await requireUser();const account=await requireAccount(user);const stage=value(form,"stage",20) as WorkStage,sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",groupKey=value(form,"groupKey",80);const path=`/work/groups/${stage.toLowerCase()}/${groupKey}?source=${sourceType}`;let error="";try{await completeSelectedGroupMembers({actorUserId:user.id,selectedAccountId:account.id,sourceType,stage,groupKey,expectedGroupVersion:value(form,"groupVersion",80),selectedTaskIds:form.getAll("selectedTaskId").map(item=>String(item)).slice(0,500),useRecommendedNextStage:true,confirmMissingInstructions:value(form,"confirmMissingInstructions",5)==="1",workerNote:value(form,"workerNote",240)||undefined,clientRequestId:value(form,"clientRequestId",160)});}catch(cause){error=cause instanceof Error?cause.message:"Could not complete selected members.";}revalidatePath(path.split("?")[0]);revalidatePath(`/work/${stage.toLowerCase()}`);redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Selected members completed and routed.")}`}`);}
