"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { WorkStage } from "@prisma/client";
import { requireAccount,requireUser } from "@/lib/auth";
import { completeGroupedStage } from "@/src/lib/workflow/grouped-transition";
import { setGroupedProgress } from "@/src/lib/workflow/grouped-progress";

const value=(form:FormData,name:string,max=200)=>String(form.get(name)??"").normalize("NFKC").trim().slice(0,max);
export async function completeGroupedStageAction(form:FormData){const user=await requireUser();const account=await requireAccount(user);const stage=value(form,"stage",20) as WorkStage,sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",next=value(form,"nextStage",20) as WorkStage;const path=`/work/${stage.toLowerCase()}?source=${sourceType}`;let error="";try{await completeGroupedStage({actorUserId:user.id,selectedAccountId:account.id,sourceType,stage,groupKey:value(form,"groupKey",80),expectedGroupVersion:value(form,"groupVersion",80),nextStage:next||undefined,useRecommendedNextStage:value(form,"useRecommended",5)==="1",clientRequestId:value(form,"clientRequestId",160)});}catch(cause){error=cause instanceof Error?cause.message:"Could not update work.";}for(const route of ["pick","mark","assemble","pack"])revalidatePath(`/work/${route}`);revalidatePath("/work");redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Work routed successfully.")}`}`);}

export async function setGroupedProgressAction(form:FormData){const user=await requireUser();const account=await requireAccount(user);const stage=value(form,"stage",20) as WorkStage,sourceType=value(form,"sourceType",20) as "ORDER"|"CONSIGNMENT",groupKey=value(form,"groupKey",80);const path=`/work/groups/${stage.toLowerCase()}/${groupKey}?source=${sourceType}`;let error="";try{await setGroupedProgress({actorUserId:user.id,selectedAccountId:account.id,sourceType,stage,groupKey,expectedGroupVersion:value(form,"groupVersion",80),targetCompletedQuantity:Number(value(form,"targetQuantity",20)),clientRequestId:value(form,"clientRequestId",160)});}catch(cause){error=cause instanceof Error?cause.message:"Could not save group progress.";}revalidatePath(path.split("?")[0]);revalidatePath(`/work/${stage.toLowerCase()}`);redirect(`${path}&${error?`error=${encodeURIComponent(error)}`:`success=${encodeURIComponent("Partial progress saved.")}`}`);}
