import Link from "next/link";
import type { WorkStage } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { requireAccount, requireUser } from "@/lib/auth";
import { getWorkerTaskQueue } from "@/src/lib/workflow/queues";
import { WorkTaskCard } from "./WorkTaskCard";

export async function WorkerQueuePage({stage,title,description,searchParams}:{stage:WorkStage;title:string;description:string;searchParams:Promise<{page?:string;q?:string;status?:string;success?:string;error?:string}>}){
 const user=await requireUser();const account=await requireAccount(user);const query=await searchParams;const status=query.status==="completed"?"completed":query.status==="problem"?"problem":"active";const page=Math.max(1,Number(query.page)||1);
 const result=await getWorkerTaskQueue({actorUserId:user.id,accountId:account.id,stage,page,search:query.q,status});const base=stage==="PICK"?"/work/consignments/pick":stage==="MARK"?"/work/marking":stage==="ASSEMBLE"?"/work/consignments/assemble":"/work/consignments/pack";const returnPath=`${base}?q=${encodeURIComponent(query.q??"")}&status=${status}&page=${page}`;
 return <AppShell><PageHeader eyebrow="Consignment work" title={title} description={description}><Link href="/work" className="rounded-md border px-4 py-2 text-sm font-bold">Work Hub</Link></PageHeader>{query.success?<div className="mb-3 rounded-md bg-teal-50 p-3 text-sm font-bold text-teal-800">{query.success}</div>:null}{query.error?<div className="mb-3 rounded-md bg-rose-50 p-3 text-sm font-bold text-rose-700">{query.error}</div>:null}
 <section className="mb-4 rounded-md border bg-white p-3 shadow-sm"><form className="grid gap-2 sm:grid-cols-[1fr_auto]"><input name="q" defaultValue={query.q} autoFocus placeholder="Scan or enter exact SKU, FSN, Listing ID, barcode or consignment" className="min-h-12 rounded-md border px-3 text-base"/><button className="min-h-12 rounded-md bg-slate-950 px-5 font-black text-white">Find work</button></form><p className="mt-2 text-xs text-slate-500">Exact identifiers are checked first. Search alone never changes progress.</p><div className="mt-3 flex gap-2 overflow-x-auto">{[["active","Ready / in progress"],["problem","Problems"],["completed","Completed today"]].map(([key,label])=><Link key={key} href={`?status=${key}&q=${encodeURIComponent(query.q??"")}`} className={`shrink-0 rounded-full px-3 py-2 text-sm font-bold ${status===key?"bg-berry text-white":"bg-slate-100"}`}>{label}</Link>)}</div></section>
 <p className="mb-3 text-sm font-bold text-slate-600">{result.total} tasks / {account.accountDisplayName??account.name}</p><section className="space-y-3">{result.tasks.map((task)=><WorkTaskCard key={task.id} task={task} returnPath={returnPath} user={result.user}/>)}</section>{!result.tasks.length?<div className="rounded-md border border-dashed bg-white p-6 text-center"><p className="font-black">No {stage.toLowerCase()} work found.</p><p className="mt-1 text-sm text-slate-600">Try another exact identifier or return to the Work Hub.</p></div>:null}
 <div className="mt-5 flex justify-between text-sm font-bold"><span>Showing {(page-1)*result.pageSize+(result.total?1:0)}-{Math.min(page*result.pageSize,result.total)} of {result.total}</span><div className="flex gap-2">{page>1?<Link href={`?page=${page-1}&q=${encodeURIComponent(query.q??"")}&status=${status}`} className="rounded-md border px-3 py-2">Previous</Link>:null}{page*result.pageSize<result.total?<Link href={`?page=${page+1}&q=${encodeURIComponent(query.q??"")}&status=${status}`} className="rounded-md border px-3 py-2">Load more</Link>:null}</div></div></AppShell>;
}
