import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import type { WorkerQueueTask } from "@/src/lib/workflow/queues";
import type { User } from "@prisma/client";
import { getWorkTaskCapabilities } from "@/src/lib/workflow/worker-access";
import { parseConsignmentCatalogSnapshot } from "@/src/lib/consignments/amazon/catalog-snapshot";
import Link from "next/link";
import { claimTaskAction, completePickWithRouteAction, completeTaskAction, reportTaskProblemAction, setTaskProgressAction } from "./actions";

export function WorkTaskCard({task,returnPath,user}:{task:WorkerQueueTask;returnPath:string;user:User}){
 const line=task.consignmentLine;if(!line)return null;const remaining=task.requiredQuantity-task.completedQuantity;const token=`${task.id}:${task.updatedAt.toISOString()}:${task.completedQuantity}`;const asset=line.markingAsset;const catalog=parseConsignmentCatalogSnapshot(line.catalogSnapshotJson);const amazon=line.consignmentBatch.marketplace==="AMAZON";
 const capabilities=getWorkTaskCapabilities(user,task);
 const hidden=(suffix:string)=><><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="expectedQuantity" value={task.completedQuantity}/><input type="hidden" name="clientRequestId" value={`${token}:${suffix}`}/><input type="hidden" name="returnPath" value={returnPath}/></>;
 return <article className="grid gap-4 rounded-md border bg-white p-4 shadow-sm lg:grid-cols-[8rem_1fr_1.35fr]">
  <ProductImage src={line.productImageSnapshot??catalog?.mainImageUrl??line.marketplaceListing?.mainImageUrl} alt={line.productTitleSnapshot??catalog?.title??line.sellerSkuSnapshot??"Consignment product"} size="lg" showBadge={false}/>
  <div><div className="flex flex-wrap gap-1"><span className="rounded-full bg-slate-950 px-2 py-1 text-xs font-black text-white">CONSIGNMENT</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{task.stage}</span><span className="rounded-full bg-pink-50 px-2 py-1 text-xs font-black text-berry">{line.consignmentBatch.marketplace}</span><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-black text-teal-800">{task.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-xl font-black">{line.sellerSkuSnapshot??line.sellerSkuSource??"No SKU"}</p><p className="line-clamp-2 text-sm text-slate-600">{line.productTitleSnapshot??catalog?.title??line.productNameSource??"Untitled product"}</p><p className="mt-2 text-xs text-slate-500">{task.account.accountDisplayName??task.account.name} / {line.consignmentBatch.displayName} / {line.consignmentBatch.externalConsignmentNumber}</p>{amazon?<p className="mt-1 break-words text-xs text-slate-500">ASIN {line.asinSnapshot??line.asinSource??"missing"} / FNSKU {line.fnskuSnapshot??line.fnskuSource??"missing"}</p>:<p className="mt-1 text-xs text-slate-500">FSN {line.fsnSnapshot??line.fsnSource??"missing"} / Listing {line.listingIdSnapshot??"missing"}</p>}{catalog?.category?<p className="mt-1 text-xs font-semibold text-slate-600">{catalog.category}{catalog.subCategory?` / ${catalog.subCategory}`:""}</p>:null}<div className="mt-3 grid grid-cols-2 gap-2"><Quantity label="Quantity to process" value={task.requiredQuantity}/><Quantity label="Completed" value={task.completedQuantity}/></div><p className="mt-2 text-xs font-semibold text-slate-500">Route {line.processRoute?.replaceAll("_"," → ")??"Choose after Pick"} / {task.assignedUser?"Assigned: "+task.assignedUser.name:"Unassigned / claimable"}</p><Link href={`/owner/consignments/${line.consignmentBatch.id}`} className="mt-3 inline-flex min-h-11 items-center rounded-md border px-3 py-2 text-sm font-bold">Details</Link></div>
  <div className="space-y-3">{task.stage==="MARK"&&asset?<details className="rounded-md bg-slate-50 p-3"><summary className="cursor-pointer font-black">Marking instructions</summary><div className="mt-2 grid gap-1 text-sm"><p>{asset.masterDesignId??"No Master Design ID"} / {asset.name}</p><p>{asset.material??catalog?.material??"Material not set"} / {asset.markingPosition??"Position not set"}</p><p>{asset.markingWidthMm??"-"} x {asset.markingHeightMm??"-"} mm / Power {asset.powerSetting??"-"} / Speed {asset.speedSetting??"-"} / Frequency {asset.frequencySetting??"-"} / Passes {asset.passes??"-"}</p><p>{asset.instructions??"No extra instructions"}</p><Link href={`/work/marking/${task.id}`} className="mt-2 inline-flex min-h-11 items-center rounded-md border bg-white px-3 py-2 text-center font-bold">Product and marking details</Link></div></details>:null}
  {task.status==="PROBLEM"?<div className="rounded-md border border-rose-200 bg-rose-50 p-3 text-sm"><p className="font-black text-rose-800">{task.problemReason?.replaceAll("_"," ")??"Problem"}</p>{task.actionLogs[0]?.note?<p className="mt-1 text-slate-700">{task.actionLogs[0].note}</p>:null}<p className="mt-1 text-xs text-slate-500">Reported by {task.problemReportedBy?.name??"Unknown worker"}{task.problemReportedAt?` / ${task.problemReportedAt.toLocaleString()}`:""} / progress {task.completedQuantity} of {task.requiredQuantity}</p></div>:null}
  {capabilities.canClaim?<form action={claimTaskAction}>{hidden("claim")}<SubmitButton pendingText="Starting...">Start {task.stage.toLowerCase()}</SubmitButton></form>:null}
  {capabilities.canProgress?<div className="grid gap-2"><form action={setTaskProgressAction} className="flex gap-2">{hidden("set")}<input name="targetQuantity" aria-label="Exact completed quantity" type="number" min={task.completedQuantity} max={task.requiredQuantity} step="1" defaultValue={task.completedQuantity} className="min-h-11 min-w-0 flex-1 rounded-md border px-3"/><SubmitButton pendingText="Saving..." variant="secondary">Save exact quantity</SubmitButton></form>{task.stage==="PICK"?<form action={completePickWithRouteAction} className="grid gap-2 rounded-md border border-berry/30 bg-pink-50 p-3">{hidden("complete-route")}<label className="text-sm font-black">After picking<select name="route" required defaultValue="" className="mt-2 min-h-11 w-full rounded-md border bg-white px-3"><option value="" disabled>Choose next route</option><option value="DIRECT_PACK">Direct to Pack</option><option value="MARK">Marking</option><option value="ASSEMBLE">Assembly</option><option value="MARK_ASSEMBLE">Marking + Assembly</option></select></label><SubmitButton pendingText="Routing...">Complete {remaining} and route</SubmitButton></form>:<form action={completeTaskAction}>{hidden("complete")}<SubmitButton pendingText="Completing...">Complete remaining {remaining}</SubmitButton></form>}</div>:capabilities.readOnly?<p className="rounded-md bg-slate-50 p-3 text-sm font-bold text-slate-600">Read-only work view</p>:null}
  {capabilities.canReportProblem?<details className="rounded-md border p-3"><summary className="cursor-pointer text-sm font-bold text-rose-700">Report problem</summary><form action={reportTaskProblemAction} className="mt-3 grid gap-2">{hidden("problem")}<select name="reason" required className="min-h-11 rounded-md border px-2">{["PRODUCT_NOT_FOUND","WRONG_PRODUCT","QUANTITY_SHORT","DAMAGED_PRODUCT","MARKING_INSTRUCTION_MISSING","MARKING_IMAGE_MISSING","MARKING_FAILED","PACKING_BLOCKED","IDENTIFIER_NOT_MATCHING","OTHER"].map((reason)=><option key={reason}>{reason.replaceAll("_"," ")}</option>)}</select><textarea name="note" maxLength={1000} placeholder="Optional note" className="min-h-20 rounded-md border p-2"/><SubmitButton pendingText="Reporting..." variant="secondary">Report problem</SubmitButton></form></details>:null}
  <details className="text-sm"><summary className="cursor-pointer font-bold">Prior stages</summary><div className="mt-2 flex flex-wrap gap-1">{line.workTasks.map((item)=><span key={item.id} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{item.stage}: {item.status}</span>)}</div></details></div>
 </article>;
}
function Quantity({label,value}:{label:string;value:number}){return <div className="rounded-md bg-slate-50 p-2 text-center"><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-black">{value}</p></div>;}
