import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser } from "@/lib/auth";
import { createManualListingAction } from "../manual-actions";

export default async function NewListingPage(){const user=await requireUser(["OWNER"]),account=await requireAccount(user);return <AppShell><div className="mx-auto max-w-3xl"><PageHeader eyebrow="Manual catalog" title="Create Product Inventory Listing" description="Seller SKU is required. All descriptive fields are optional; this does not create physical stock."/><ListingForm action={createManualListingAction} marketplace={account.marketplace}/></div></AppShell>}
export function ListingForm({action,marketplace,listing}:{action:(data:FormData)=>Promise<void>;marketplace:string;listing?:{id:string;sellerSkuId:string;productTitle:string|null;subCategory:string|null;fsn:string|null;listingId:string|null;listingStatus:string|null;mrp:number|null;sellingPrice:number|null;liveBrand:string|null;liveCategory:string|null;description:string|null;mainImageUrl:string|null}}){return <form action={action} className="space-y-4 rounded-md border bg-white p-4"><input type="hidden" name="listingId" value={listing?.id??""}/><div className="grid gap-3 sm:grid-cols-2"><Read label="Marketplace" value={marketplace}/><label className="font-bold">Seller SKU<input name="sellerSku" required readOnly={Boolean(listing)} defaultValue={listing?.sellerSkuId} className="mt-1 min-h-11 w-full rounded-md border px-3 read-only:bg-slate-100"/></label><Field name="productTitle" label="Title" value={listing?.productTitle}/><Field name="brand" label="Brand" value={listing?.liveBrand}/><Field name="category" label="Category" value={listing?.liveCategory}/><Field name="subCategory" label="Sub-category" value={listing?.subCategory}/><Field name="fsn" label="FSN / ASIN" value={listing?.fsn}/><Field name="listingId" label="Listing ID" value={listing?.listingId}/><Field name="listingStatus" label="Listing status" value={listing?.listingStatus}/><Field name="mrp" label="MRP" value={listing?.mrp}/><Field name="sellingPrice" label="Selling price" value={listing?.sellingPrice}/><Field name="mainImageUrl" label="Main image URL" value={listing?.mainImageUrl}/><label className="sm:col-span-2 font-bold">Description<textarea name="description" defaultValue={listing?.description??""} maxLength={12000} rows={5} className="mt-1 w-full rounded-md border px-3 py-2"/></label></div><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="manualLocked" defaultChecked/> Protect entered values from automated refresh</label><SubmitButton pendingText="Saving listing...">Save Listing</SubmitButton></form>}
function Field({name,label,value}:{name:string;label:string;value?:string|number|null}){return <label className="font-bold">{label}<input name={name} defaultValue={value??""} className="mt-1 min-h-11 w-full min-w-0 rounded-md border px-3"/></label>};function Read({label,value}:{label:string;value:string}){return <div className="rounded-md bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="font-black">{value}</p></div>}
