import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount } from "@/lib/auth";
import { requireConsignmentAccess } from "@/lib/consignment-auth";
import { formatDateTime } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { cancelConsignmentAction, reparseConsignmentAction, replaceConsignmentSourceAction, selectConsignmentMainFileAction } from "../actions";
import { TaskAssignmentPanel } from "./TaskAssignmentPanel";

export default async function ConsignmentDetailPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<{ activated?: string; error?: string }> }) {
  const user = await requireConsignmentAccess("view"); const account = await requireAccount(user); const { batchId } = await params; const query = await searchParams;
  const batch = await prisma.consignmentBatch.findFirst({ where: { id: batchId, accountId: account.id }, include: { files: { orderBy: { createdAt: "asc" } }, _count: { select: { lines: true, issues: true } } } }); if (!batch) notFound();
  const taskCount = await prisma.workTask.count({ where: { accountId: account.id, consignmentLine: { consignmentBatchId: batch.id } } });
  return <AppShell><PageHeader eyebrow="Consignment detail" title={batch.displayName} description={`${batch.externalConsignmentNumber} / ${account.accountDisplayName ?? account.name}`}><Link href={`/owner/consignments/${batch.id}/review`} className="rounded-md bg-berry px-4 py-2 text-sm font-bold text-white">Open review</Link></PageHeader>
    {query.activated ? <div className="mb-4 rounded-md bg-teal-50 p-3 font-bold text-teal-800">Consignment is active. {taskCount} tasks exist.</div> : null}{query.error ? <div className="mb-4 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</div> : null}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">{[["Status",batch.status],["Lines",batch._count.lines],["Required",batch.totalRequiredQuantity],["Matched",batch.matchedLines],["Issues",batch._count.issues],["Tasks",taskCount]].map(([label,value]) => <div key={label} className="rounded-md border bg-white p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-black">{String(value).replaceAll("_"," ")}</p></div>)}</section>
    <TaskAssignmentPanel batchId={batch.id} accountId={account.id} canManage={user.role === "OWNER" || user.canManageConsignments}/>
    <section className="mt-5 rounded-md border bg-white p-4"><h2 className="font-black">{batch.marketplace} source and reference files</h2><p className="mt-1 text-sm text-slate-600">Only the selected shipment file creates work quantities. Catalog/listing files enrich operational snapshots and never create inventory.</p><div className="mt-3 grid gap-2">{batch.files.map((file) => <div key={file.id} className="flex flex-col gap-2 rounded-md border p-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{file.originalFileName}</p>{file.isCurrentSource ? <span className="rounded-full bg-teal-100 px-2 py-1 text-[11px] font-black text-teal-800">CURRENT SHIPMENT SOURCE</span> : null}</div><p className="text-xs text-slate-500">{file.fileType.replaceAll("_"," ")} / {Math.ceil(file.fileSizeBytes/1024)} KB / SHA-256 {file.sha256.slice(0,12)}...</p></div>{file.managedRelativePath ? <a href={`/owner/consignments/${batch.id}/files/${file.id}`} className="rounded-md border px-3 py-2 text-center text-sm font-bold">Download</a> : null}</div>)}</div></section>
    {(user.role === "OWNER" || user.canManageConsignments) && batch.status === "REVIEW_REQUIRED" && batch.files.filter((file) => file.fileType === (batch.marketplace === "AMAZON" ? "AMAZON_SHIPMENT" : "CONSIGNMENT_DETAILS")).length > 1 ? <section className="mt-5 rounded-md border border-amber-200 bg-amber-50 p-4"><h2 className="font-black">Choose the shipment source</h2><p className="mt-1 text-sm">Multiple files have a meaningful shipment header signature. Nothing is activated until you choose one.</p><div className="mt-3 grid gap-2">{batch.files.filter((file) => file.fileType === (batch.marketplace === "AMAZON" ? "AMAZON_SHIPMENT" : "CONSIGNMENT_DETAILS")).map((file) => <form key={file.id} action={selectConsignmentMainFileAction} className="flex items-center justify-between gap-2 rounded-md bg-white p-3"><span className="truncate text-sm font-bold">{file.originalFileName}</span><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="fileId" value={file.id}/><SubmitButton pendingText="Parsing...">Use this file</SubmitButton></form>)}</div></section> : null}
    {(user.role === "OWNER" || user.canImportConsignments || user.canManageConsignments) && ["DRAFT","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"].includes(batch.status) ? <form action={replaceConsignmentSourceAction} className="mt-5 rounded-md border bg-white p-4"><h2 className="font-black">Corrected draft source</h2><p className="mt-1 text-sm text-slate-600">Replace and reparse this non-active draft. Active consignments cannot be replaced.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="batchId" value={batch.id}/><input type="file" name="file" accept={batch.marketplace === "AMAZON" ? ".csv,.tsv,.txt,.xlsx,.xlsm,.zip" : ".csv,.zip,.txt"} required className="min-h-11 flex-1 rounded-md border p-2"/><SubmitButton pendingText="Replacing...">Replace source</SubmitButton></div></form> : null}
    <div className="mt-5 flex flex-wrap gap-2"><Link href={`/owner/consignments/${batch.id}/issues`} className="rounded-md border px-4 py-2 font-bold">View issues</Link><Link href="/owner/consignments" className="rounded-md border px-4 py-2 font-bold">All consignments</Link>{(user.role === "OWNER" || user.canManageConsignments) && !["ACTIVE","COMPLETED","CANCELLED"].includes(batch.status) ? <><form action={reparseConsignmentAction}><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Reparsing..." variant="secondary">Reparse source</SubmitButton></form><form action={cancelConsignmentAction}><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Cancelling..." variant="secondary">Cancel draft</SubmitButton></form></> : null}</div>
    <p className="mt-5 text-xs text-slate-500">Created {formatDateTime(batch.createdAt)}{batch.activatedAt ? ` / activated ${formatDateTime(batch.activatedAt)}` : ""}</p>
  </AppShell>;
}
