import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { FileUploadField } from "@/components/FileUploadField";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount } from "@/lib/auth";
import { requireConsignmentAccess } from "@/lib/consignment-auth";
import { formatDateTime } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { amazonShipmentCandidates } from "@/src/lib/consignments/amazon/candidate-policy";
import { getConsignmentActivationEligibility } from "@/src/lib/workflow/task-store";
import { cancelConsignmentAction, reparseConsignmentAction, replaceConsignmentSourceAction, selectConsignmentMainFileAction } from "../actions";
import { TaskAssignmentPanel } from "./TaskAssignmentPanel";

export default async function ConsignmentDetailPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<{ activated?: string; error?: string }> }) {
  const user = await requireConsignmentAccess("view"); const account = await requireAccount(user); const { batchId } = await params; const query = await searchParams;
  const batch = await prisma.consignmentBatch.findFirst({ where: { id: batchId, accountId: account.id }, include: { files: { orderBy: { createdAt: "asc" } }, _count: { select: { lines: true, issues: true } } } }); if (!batch) notFound();
  const [taskGroups, activationEligibility] = await Promise.all([
    prisma.workTask.groupBy({ by:["stage"], where: { accountId: account.id, consignmentLine: { consignmentBatchId: batch.id } }, _count:{_all:true} }),
    getConsignmentActivationEligibility(batch.id, account.id)
  ]);
  const taskCount=taskGroups.reduce((sum,group)=>sum+group._count._all,0);const stageCount=(stage:string)=>taskGroups.find((group)=>group.stage===stage)?._count._all??0;
  const shipmentCandidates=batch.files.flatMap((file)=>batch.marketplace!=="AMAZON"?file.fileType==="CONSIGNMENT_DETAILS"?[{file,tableName:"Text report",label:file.originalFileName}]:[]:amazonShipmentCandidates(file.candidateTablesJson).map((item)=>({file,tableName:item.tableName,label:item.label})));
  const reviewLabel=batch.status==="ACTIVE"?"View progress":batch.status==="COMPLETED"?"View completion record":activationEligibility.blockingCount?"Resolve issues":activationEligibility.canActivate?"Review and activate":batch.status==="DRAFT"||batch.status==="PARSING"||batch.status==="FAILED"?"Continue setup":"View review";
  return <AppShell><PageHeader eyebrow="Consignment detail" title={batch.displayName} description={`${batch.externalConsignmentNumber} / ${account.accountDisplayName ?? account.name}`}><div className="flex flex-wrap items-center gap-2"><StatusBadge value={batch.status}/><Link href={`/owner/consignments/${batch.id}/review`} className="inline-flex min-h-11 items-center rounded-md bg-berry px-4 py-2 text-sm font-bold text-white">{reviewLabel}</Link></div></PageHeader>
    {query.activated ? <section className="mb-4 rounded-md border border-teal-200 bg-teal-50 p-4 text-teal-900"><p className="font-black">Consignment activated successfully.</p><p className="mt-1 text-sm font-bold">Total work quantity {batch.totalRequiredQuantity} / Pick {stageCount("PICK")} / Mark {stageCount("MARK")} / Assembly {stageCount("ASSEMBLE")} / Pack {stageCount("PACK")}</p><div className="mt-3 flex flex-wrap gap-2"><Link href="/work/consignments/pick" className="rounded-md bg-teal-800 px-3 py-2 text-sm font-bold text-white">Open Pick Work</Link><Link href="/work/marking" className="rounded-md border border-teal-700 px-3 py-2 text-sm font-bold">Open Marking Work</Link><Link href="/work/consignments/assemble" className="rounded-md border border-teal-700 px-3 py-2 text-sm font-bold">Open Assembly Work</Link><Link href="/work/consignments/pack" className="rounded-md border border-teal-700 px-3 py-2 text-sm font-bold">Open Packing Work</Link><Link href="/owner/consignments" className="rounded-md border border-teal-700 px-3 py-2 text-sm font-bold">Back to Consignments</Link></div></section> : null}{query.error ? <div className="mb-4 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</div> : null}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Batch status",batch.status],["Valid lines",batch._count.lines],["Required units",batch.totalRequiredQuantity],["Matched listings",batch.matchedLines],["Import issues",batch._count.issues],["Generated tasks",taskCount]].map(([label,value]) => <div key={label} className="rounded-md border bg-white p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-black">{String(value).replaceAll("_"," ")}</p></div>)}</section>
    {!["ACTIVE","COMPLETED","CANCELLED"].includes(batch.status) ? <section className={`mt-4 rounded-md border p-4 ${activationEligibility.blockingCount ? "border-rose-200 bg-rose-50" : activationEligibility.warningCount ? "border-amber-200 bg-amber-50" : "border-teal-200 bg-teal-50"}`}><h2 className="font-black">{activationEligibility.blockingCount ? "Activation blocked" : activationEligibility.canActivate ? activationEligibility.actionLabel : "Activation unavailable"}</h2><p className="mt-1 text-sm text-slate-700">{activationEligibility.lifecycleMessage}</p></section> : null}
    <TaskAssignmentPanel batchId={batch.id} accountId={account.id} canManage={user.role === "OWNER" || user.canManageConsignments}/>
    <section className="mt-5 rounded-md border bg-white p-4"><h2 className="font-black">{batch.marketplace} source and reference files</h2><p className="mt-1 text-sm text-slate-600">Only the selected shipment file creates work quantities. Catalog/listing files enrich operational snapshots and never create inventory.</p><div className="mt-3 grid gap-2">{batch.files.map((file) => <div key={file.id} className="flex flex-col gap-2 rounded-md border p-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{file.originalFileName}</p>{file.isCurrentSource ? <span className="rounded-full bg-teal-100 px-2 py-1 text-[11px] font-black text-teal-800">CURRENT SHIPMENT SOURCE</span> : null}</div><p className="text-xs text-slate-500">{file.fileType.replaceAll("_"," ")} / {Math.ceil(file.fileSizeBytes/1024)} KB / SHA-256 {file.sha256.slice(0,12)}...</p></div>{file.managedRelativePath ? <a href={`/owner/consignments/${batch.id}/files/${file.id}`} className="inline-flex min-h-11 items-center rounded-md border px-3 py-2 text-center text-sm font-bold">Download</a> : null}</div>)}</div></section>
    {(user.role === "OWNER" || user.canManageConsignments) && ["DRAFT","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"].includes(batch.status) && shipmentCandidates.length > 1 ? <section className="mt-5 rounded-md border border-amber-200 bg-amber-50 p-4"><h2 className="font-black">Choose the shipment source</h2><p className="mt-1 text-sm">Choose one exact stored file and worksheet. Supporting listing and catalog reports remain attached to this draft.</p><div className="mt-3 grid gap-2">{shipmentCandidates.map((candidate) => <form key={`${candidate.file.id}:${candidate.tableName}`} action={selectConsignmentMainFileAction} className="flex items-center justify-between gap-2 rounded-md bg-white p-3"><span className="min-w-0 break-words text-sm font-bold">{candidate.file.originalFileName} / {candidate.label}</span><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="fileId" value={candidate.file.id}/><input type="hidden" name="tableName" value={candidate.tableName}/><SubmitButton pendingText="Parsing...">{candidate.file.isCurrentSource&&candidate.file.selectedTableName===candidate.tableName?"Selected":"Use this worksheet"}</SubmitButton></form>)}</div></section> : null}
    {(user.role === "OWNER" || user.canImportConsignments || user.canManageConsignments) && ["DRAFT","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"].includes(batch.status) ? <form action={replaceConsignmentSourceAction} className="mt-5 rounded-md border bg-white p-4"><h2 className="font-black">Corrected draft source</h2><p className="mt-1 text-sm text-slate-600">Replace and reparse this non-active draft. Active consignments cannot be replaced.</p><div className="mt-3 grid gap-3"><input type="hidden" name="batchId" value={batch.id}/><FileUploadField name="file" label="Replacement source" accept={batch.marketplace === "AMAZON" ? ".csv,.tsv,.txt,.xlsx,.xlsm,.zip" : ".csv,.zip,.txt"} required hint="The current draft remains unchanged if the replacement cannot be parsed safely."/><div><SubmitButton pendingText="Replacing...">Replace and reparse draft</SubmitButton></div></div></form> : null}
    <div className="mt-5 flex flex-wrap gap-2"><Link href={`/owner/consignments/${batch.id}/issues`} className="inline-flex min-h-11 items-center rounded-md border px-4 py-2 font-bold">View issues</Link><Link href="/owner/consignments" className="inline-flex min-h-11 items-center rounded-md border px-4 py-2 font-bold">All consignments</Link>{(user.role === "OWNER" || user.canManageConsignments) && !["ACTIVE","COMPLETED","CANCELLED"].includes(batch.status) ? <><form action={reparseConsignmentAction}><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Reparsing..." variant="secondary">Reparse source</SubmitButton></form><form action={cancelConsignmentAction}><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Cancelling..." variant="secondary">Cancel draft</SubmitButton></form></> : null}</div>
    <p className="mt-5 text-xs text-slate-500">Created {formatDateTime(batch.createdAt)}{batch.activatedAt ? ` / activated ${formatDateTime(batch.activatedAt)}` : ""}</p>
  </AppShell>;
}
