CREATE TYPE "WorkRequestKind" AS ENUM ('CLAIM','INCREMENT','SET_PROGRESS','COMPLETE','REPORT_PROBLEM','RESOLVE_PROBLEM','REASSIGN','UNASSIGN','BULK_ASSIGN');
ALTER TABLE "WorkActionLog" ADD COLUMN "requestKind" "WorkRequestKind";
