import Link from "next/link";
import { universalCandidateAction } from "@/app/work/scan/actions";
import { getAuthorizedWorkAccounts, resolveUniversalWork, type UniversalScanIntent, type UniversalSourceFilter, type UniversalWorkCandidate } from "@/src/lib/workflow/universal-resolver";
import { ProductImage } from "./ProductImage";
import { ScannerDetailsButton } from "./ScannerDetailsButton";
import { ScannerMarkRouteDialog } from "./ScannerMarkRouteDialog";
import { ScannerPickRouteDialog } from "./ScannerPickRouteDialog";
import { SubmitButton } from "./SubmitButton";
import { UniversalScanInput } from "./UniversalScanInput";
import { FeedbackBanner } from "./ui/FeedbackBanner";
import { buttonStyles } from "./ui/buttonStyles";

type ScannerProps = { actorUserId: string; selectedAccountId: string; query?: string; intent?: UniversalScanIntent; sourceFilter?: UniversalSourceFilter; success?: string; error?: string; actionPath?: string };
type ScanContext = { returnPath: string; code: string; intent: UniversalScanIntent; sourceFilter: UniversalSourceFilter; accountFilter?: string };

export async function ProfessionalUniversalScanner({ actorUserId, selectedAccountId, query, intent = "ANY", sourceFilter = "ALL", success, error, actionPath = "/work/scan" }: ScannerProps) {
  const scope = await getAuthorizedWorkAccounts(actorUserId);
  const selectedAccount = scope.accounts.find((account) => account.id === selectedAccountId);
  if (!selectedAccount) throw new Error("The selected account is no longer assigned to this user.");
  let result: Awaited<ReturnType<typeof resolveUniversalWork>> | null = null;
  let lookupError: string | null = null;
  if (query) try { result = await resolveUniversalWork({ actorUserId, code: query, intent, sourceFilter, accountId: selectedAccountId }); }
  catch (cause) { lookupError = cause instanceof Error ? cause.message : "Search failed."; }
  const visibleCompleted = result?.candidates.filter((candidate) => ["PACKED", "COMPLETED"].includes(candidate.status)).length ?? 0;
  const active = (result?.candidates.length ?? 0) - visibleCompleted;
  const completed = result ? Math.max(visibleCompleted, result.completedMatchCount) : 0;

  return <section className="grid gap-5" data-universal-scanner>
    <div className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5" data-scanner-controls>
      <form id="universal-scan-form" action={actionPath} className="grid gap-4">
        <div className="grid min-w-0 gap-3 lg:grid-cols-[minmax(20rem,1fr)_auto] lg:items-end">
          <UniversalScanInput initialValue={query} selectOnMount={Boolean(error || lookupError)} />
          <button className={buttonStyles({ className: "min-h-14 px-7 text-base" })}>Find work</button>
        </div>
        <div className="grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-[12rem_14rem_1fr] md:items-center">
          <FilterSelect label="Stage" name="intent" value={intent} options={[["ANY", "All work"], ["PICK", "Pick"], ["MARK", "Mark"], ["ASSEMBLE", "Assembly"], ["PACK", "Pack"]]}/>
          <FilterSelect label="Source" name="source" value={sourceFilter} options={[["ALL", "All sources"], ["CUSTOMER_ORDERS", "Customer Orders"], ["CONSIGNMENTS", "Consignments"]]}/>
          <div className="md:text-right"><p className="text-sm font-semibold text-slate-900">{selectedAccount.marketplace} · {selectedAccount.accountDisplayName ?? selectedAccount.name}</p><p className="mt-1 text-xs text-slate-500">Selected-account lookup only. Scanning does not change work.</p></div>
        </div>
        <input type="hidden" name="accountId" value={selectedAccountId}/>
      </form>
      <div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><Link href="/work/pack" className={buttonStyles({ variant: "secondary" })}>Pack workspace</Link><Link href="/work" className={buttonStyles({ variant: "quiet" })}>Work Hub</Link></div>
    </div>
    {success ? <FeedbackBanner tone="success" announcement="status" title="Ready for the next scan">{success}</FeedbackBanner> : null}
    {error || lookupError ? <FeedbackBanner tone="error" announcement="alert" title="Scan needs attention">{error ?? lookupError}</FeedbackBanner> : null}
    {result ? <div className="grid gap-4" data-scanner-results>
      <div className="flex flex-wrap items-center justify-between gap-2 text-sm text-slate-600"><p><strong className="text-slate-950">{active}</strong> active{completed ? <> · <strong className="text-slate-950">{completed}</strong> completed read-only</> : null}</p><p>Exact lookup · {result.durationMs} ms</p></div>
      {result.candidates.length
        ? result.candidates.map((candidate) => <CandidateCard key={candidate.candidateKey} candidate={candidate} scan={{ returnPath: actionPath, code: result!.normalizedInput, intent, sourceFilter, accountFilter: selectedAccountId }}/>)
        : <EmptyResult completed={result.completedMatchCount > 0}/>
      }
    </div> : <div className="rounded-xl border border-dashed border-slate-300 bg-stone-50 p-8 text-center"><h2 className="text-lg font-semibold text-slate-950">Scanner ready</h2><p className="mt-2 text-sm text-slate-600">Scan an AWB, Tracking ID, SKU, listing identifier, barcode, Order reference, task ID, or Consignment number.</p></div>}
  </section>;
}

function FilterSelect({ label, name, value, options }: { label: string; name: string; value: string; options: string[][] }) { return <label className="text-xs font-semibold uppercase tracking-wide text-slate-600">{label}<select name={name} defaultValue={value} className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-900">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function EmptyResult({ completed }: { completed: boolean }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center"><h2 className="text-lg font-semibold text-slate-950">{completed ? "Matching work is already complete" : "No exact work found"}</h2><p className="mt-2 text-sm text-slate-600">Nothing was changed. Check the code or selected seller account and scan again.</p></div>; }

type CandidateAction = { value: "ORDER_MARK_COMPLETE" | "ORDER_PACK" | "ASSEMBLY_CLAIM" | "ASSEMBLY_COMPLETE" | "ASSEMBLY_PROBLEM" | "TASK_CLAIM" | "TASK_COMPLETE"; label: string; variant?: "primary" | "secondary" | "danger" };

function CandidateCard({ candidate, scan }: { candidate: UniversalWorkCandidate; scan: ScanContext }) {
  const actions: CandidateAction[] = [];
  const unresolvedMark = Boolean(candidate.stage === "MARK" && candidate.stageRouteDecision && !candidate.stageRouteDecision.preselectedNextStage && candidate.stageRouteDecision.selectableNextStages.length);
  if (candidate.canAct) {
    if (candidate.actionType === "ORDER_PACK") actions.push({ value: "ORDER_PACK", label: "Pack Completed" });
    else if (candidate.actionType === "ORDER_MARK") actions.push({ value: "ORDER_MARK_COMPLETE", label: "Marking Completed" });
    else if (candidate.actionType === "ORDER_ASSEMBLY") { if (candidate.status === "READY" && !candidate.assignedUserId) actions.push({ value: "ASSEMBLY_CLAIM", label: "Start Assembly", variant: "secondary" }); actions.push({ value: "ASSEMBLY_COMPLETE", label: "Assembly Completed" }, { value: "ASSEMBLY_PROBLEM", label: "Report Problem", variant: "danger" }); }
    else if (!["ORDER_SEND_TO_ASSEMBLY", "CONSIGNMENT_PICK"].includes(candidate.actionType)) { if (candidate.status === "READY" && !candidate.assignedUserId) actions.push({ value: "TASK_CLAIM", label: `Start ${stageLabel(candidate.stage)}`, variant: "secondary" }); if (candidate.stage !== "PICK" && !unresolvedMark && candidate.status !== "COMPLETED") actions.push({ value: "TASK_COMPLETE", label: completionLabel(candidate.stage) }); }
  }
  const token = `scan:${candidate.candidateKey}:${candidate.status}:${candidate.completedQuantity}`;
  return <article className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white" data-scanner-candidate data-action-scope={candidate.actionType}>
    <header className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-3"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-600">{candidate.sourceLabel}</span><span className="text-xs font-medium text-slate-500">{candidate.marketplace} · {candidate.accountName}</span></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${stateTone(candidate)}`}>{scopeLabel(candidate)}</span></header>
    <div className="grid gap-5 p-4 sm:grid-cols-[6rem_minmax(0,1fr)] sm:p-5 xl:grid-cols-[6rem_minmax(0,1fr)_18rem_14rem]">
      <ProductImage src={candidate.productImageUrl} alt={candidate.productTitle ?? candidate.sellerSku ?? "Work product"} size="scanner" showBadge={false}/>
      <div className="min-w-0"><p className="break-all text-sm font-semibold text-berry">{candidate.displayReference}</p><h2 className="mt-1 break-words text-xl font-semibold text-slate-950">{candidate.sellerSku ?? candidate.productSummary ?? "Operational work"}</h2><p className="mt-1 line-clamp-2 text-sm text-slate-600">{candidate.productSummary ?? candidate.productTitle ?? "No product title available"}</p><dl className="mt-4 grid gap-x-4 gap-y-2 text-sm sm:grid-cols-2">{candidate.trackingId ? <Meta label="Tracking" value={candidate.trackingId}/> : null}{candidate.awb ? <Meta label="AWB" value={candidate.awb}/> : null}{candidate.orderNumber ? <Meta label="Order" value={candidate.orderNumber}/> : null}{candidate.consignmentNumber ? <Meta label="Consignment" value={candidate.consignmentNumber}/> : null}{candidate.taskReference ? <Meta label="Task" value={candidate.taskReference}/> : null}{candidate.itemReference ? <Meta label="Item" value={candidate.itemReference}/> : null}</dl><p className="mt-3 text-xs text-slate-500">Matched {candidate.matchType.replaceAll("_", " ").toLowerCase()} {candidate.matchedIdentifierMasked}</p>{candidate.assignedUserName ? <p className="mt-2 text-sm font-medium text-slate-700">Assigned to {candidate.assignedUserName}</p> : null}{candidate.stage === "MARK" ? <MarkingInstructions candidate={candidate}/> : null}{candidate.stage === "ASSEMBLE" ? <div className="mt-3 rounded-md bg-slate-50 p-3"><p className="font-semibold text-slate-950">{candidate.assemblyTitle ?? "Assembly"}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{candidate.assemblyInstructions ?? "Instructions unavailable. Ask an owner."}</p></div> : null}</div>
      <Workflow candidate={candidate}/>
      <div className="grid content-start gap-2 sm:col-span-2 sm:grid-cols-2 xl:col-span-1 xl:grid-cols-1" data-scanner-actions>
        {candidate.canAct && (candidate.actionType === "ORDER_PICK" || candidate.actionType === "CONSIGNMENT_PICK") && candidate.routeDecision ? <ScannerPickRouteDialog candidate={{ actionType: candidate.actionType, accountId: candidate.accountId, sourceId: candidate.sourceId, status: candidate.status, completedQuantity: candidate.completedQuantity, candidateKey: candidate.candidateKey, recommendationSource: candidate.routeDecision.recommendationSource, savedRoute: candidate.routeDecision.savedRoute, options: candidate.routeDecision.options }} scan={scan}/> : null}
        {candidate.canAct && unresolvedMark ? <ScannerMarkRouteDialog candidate={candidate} scan={scan}/> : null}
        {candidate.canAct && candidate.actionType === "ORDER_SEND_TO_ASSEMBLY" ? <AssemblyDiversionForm candidate={candidate} scan={scan} token={token}/> : null}
        {actions.map((action) => <CandidateActionForm key={action.value} candidate={candidate} action={action} scan={scan} token={token}/>)}
        {candidate.status === "PROBLEM" ? <Link href={`/work/problems?source=${candidate.sourceType === "CONSIGNMENT_TASK" ? "CONSIGNMENT" : "ORDER"}`} className={buttonStyles({ variant: "danger", className: "w-full" })}>Open Problem</Link> : null}
        <ScannerDetailsButton candidate={candidate} href={detailsHref(candidate)}/><a href="#universal-scan-form" className={buttonStyles({ variant: "quiet", className: "w-full" })}>Scan Next</a>
      </div>
    </div>
  </article>;
}

function CandidateActionForm({ candidate, action, scan, token }: { candidate: UniversalWorkCandidate; action: CandidateAction; scan: ScanContext; token: string }) { return <form action={universalCandidateAction}><input type="hidden" name="returnPath" value={scan.returnPath}/><input type="hidden" name="code" value={scan.code}/><input type="hidden" name="intent" value={scan.intent}/><input type="hidden" name="source" value={scan.sourceFilter}/><input type="hidden" name="accountFilter" value={scan.accountFilter ?? ""}/><input type="hidden" name="accountId" value={candidate.accountId}/><input type="hidden" name="sourceId" value={candidate.sourceId}/><input type="hidden" name="action" value={action.value}/><input type="hidden" name="expectedQuantity" value={candidate.completedQuantity}/><input type="hidden" name="expectedVersion" value={candidate.taskVersion}/><input type="hidden" name="expectedStatus" value={candidate.status}/><input type="hidden" name="clientRequestId" value={`${token}:${action.value}`}/><SubmitButton pendingText="Saving..." variant={action.variant ?? "primary"} className="w-full">{action.label}</SubmitButton></form>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="break-all font-medium text-slate-900">{value}</dd></div>; }
function stageLabel(stage?: string) { return stage === "PICK" ? "Pick" : stage === "MARK" ? "Marking" : stage === "ASSEMBLE" ? "Assembly" : stage === "PACK" ? "Pack" : "Work"; }
function completionLabel(stage?: string) { return stage === "MARK" ? "Marking Completed" : stage === "ASSEMBLE" ? "Assembly Completed" : stage === "PACK" ? "Pack Completed" : "Complete Pick"; }
function scopeLabel(candidate: UniversalWorkCandidate) { if (["PACKED", "COMPLETED"].includes(candidate.status)) return candidate.status === "PACKED" ? "Packed" : "Completed"; if (candidate.status === "PROBLEM") return "Work paused"; if (candidate.actionType === "ORDER_PACK" || candidate.stage === "PACK") return candidate.canAct ? "Pack ready" : "Pack locked"; if (candidate.actionType === "ORDER_SEND_TO_ASSEMBLY") return "Ready for routing"; if (candidate.stage === "PICK" && candidate.status === "PICK_PENDING") return "Pick pending"; return `${stageLabel(candidate.stage)} ${candidate.status.replaceAll("_", " ").toLowerCase()}`; }
function stateTone(candidate: UniversalWorkCandidate) { if (["PACKED", "COMPLETED"].includes(candidate.status)) return "bg-teal-50 text-teal-900"; if (candidate.status === "PROBLEM") return "bg-rose-50 text-rose-900"; if (candidate.canAct) return "bg-pink-50 text-berry"; return "bg-amber-50 text-amber-950"; }

function Workflow({ candidate }: { candidate: UniversalWorkCandidate }) { const complete = ["PACKED", "COMPLETED"].includes(candidate.status), problem = candidate.status === "PROBLEM"; return <div className="min-w-0 sm:col-span-2 xl:col-span-1" data-scanner-workflow><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Workflow</h3><div className={`mt-2 rounded-md p-3 text-sm ${complete ? "bg-teal-50 text-teal-950" : problem ? "bg-rose-50 text-rose-950" : "bg-stone-100 text-slate-900"}`}><p className="font-semibold">{scopeLabel(candidate)}</p>{candidate.problemReason ? <p className="mt-1">Reason: {candidate.problemReason.replaceAll("_", " ").toLowerCase()}</p> : null}{complete ? <p className="mt-1">Completed by {candidate.packedByName ?? "recorded worker"}{candidate.packedAt ? ` · ${candidate.packedAt.toLocaleString()}` : ""}</p> : null}</div>{candidate.workflowPrerequisites ? <div className="mt-3 divide-y divide-slate-100 rounded-md border border-slate-200">{(["PICK", "MARK", "ASSEMBLE", "PACK"] as const).map((stage) => { const item = candidate.workflowPrerequisites!.stages[stage], ready = item.state === "SATISFIED" || item.state === "NOT_REQUIRED"; return <div key={stage} className="flex items-center justify-between gap-3 px-3 py-2 text-xs"><span className="font-semibold text-slate-700">{stageLabel(stage)}</span><span className={ready ? "text-teal-800" : "text-amber-900"}>{item.state.replaceAll("_", " ").toLowerCase()}</span></div>; })}</div> : null}<div className="mt-3 grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-sm"><p><span className="block text-xs text-slate-500">{candidate.shipmentItemCount ? "Items" : "Quantity"}</span><strong>{candidate.shipmentItemCount ?? candidate.requiredQuantity}</strong></p><p><span className="block text-xs text-slate-500">{candidate.shipmentTotalQuantity ? "Total units" : "Completed"}</span><strong>{candidate.shipmentTotalQuantity ?? candidate.completedQuantity}</strong></p></div>{candidate.readOnlyReason ? <p className="mt-3 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">{candidate.readOnlyReason}</p> : null}</div>; }
function detailsHref(candidate: UniversalWorkCandidate) { if (candidate.sourceType === "CONSIGNMENT_TASK") return `/work/consignments/items/${encodeURIComponent(candidate.taskId ?? candidate.sourceId)}`; if (candidate.workGroupKey && candidate.stage) return `/work/groups/${candidate.stage.toLowerCase()}/${encodeURIComponent(candidate.workGroupKey)}?source=ORDER`; if (candidate.stage) return `/work/${candidate.stage.toLowerCase()}?source=ORDER`; return `/packing/${encodeURIComponent(candidate.orderId ?? candidate.sourceId)}`; }
function AssemblyDiversionForm({ candidate, scan, token }: { candidate: UniversalWorkCandidate; scan: ScanContext; token: string }) { return <details className="rounded-md border border-slate-200 px-3"><summary className="min-h-11 cursor-pointer py-3 font-semibold text-berry">Send to Assembly</summary><form action={universalCandidateAction} className="mb-3 grid gap-2"><input type="hidden" name="returnPath" value={scan.returnPath}/><input type="hidden" name="code" value={scan.code}/><input type="hidden" name="intent" value={scan.intent}/><input type="hidden" name="source" value={scan.sourceFilter}/><input type="hidden" name="accountFilter" value={scan.accountFilter ?? ""}/><input type="hidden" name="accountId" value={candidate.accountId}/><input type="hidden" name="sourceId" value={candidate.sourceId}/><input type="hidden" name="action" value="ASSEMBLY_SEND"/><input type="hidden" name="expectedQuantity" value={candidate.completedQuantity}/><input type="hidden" name="expectedStatus" value={candidate.status}/><input type="hidden" name="clientRequestId" value={`${token}:ASSEMBLY_SEND`}/><input name="manualTitle" maxLength={160} placeholder="Assembly title (optional)" className="min-h-11 rounded-md border border-slate-300 px-3"/><textarea name="manualInstructions" required={candidate.assemblyInstructionsRequired} maxLength={2000} placeholder={candidate.assemblyInstructionsRequired ? "Assembly instructions required" : "Optional rule note"} className="min-h-24 rounded-md border border-slate-300 p-3"/><input name="manualImageUrl" maxLength={2048} placeholder="Optional safe image URL" className="min-h-11 rounded-md border border-slate-300 px-3"/><SubmitButton pendingText="Sending...">Send to Assembly</SubmitButton></form></details>; }
function MarkingInstructions({ candidate }: { candidate: UniversalWorkCandidate }) { return <details className="mt-3 rounded-md bg-slate-50 px-3"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold">Marking instructions</summary><div className="mb-3 grid gap-1 text-sm text-slate-700"><p>{candidate.markingMasterDesignId ?? "No Master Design ID"} · {candidate.markingAssetName ?? "No marking asset"}</p><p>{candidate.markingPosition ?? "Position not set"}</p><p>{candidate.markingWidthMm ?? "–"} × {candidate.markingHeightMm ?? "–"} mm · Power {candidate.markingPower ?? "–"} · Speed {candidate.markingSpeed ?? "–"} · Frequency {candidate.markingFrequency ?? "–"} · Passes {candidate.markingPasses ?? "–"}</p><p>{candidate.markingInstructions ?? "No extra instructions"}</p></div></details>; }
