import Link from "next/link";
import { universalCandidateAction } from "@/app/work/scan/actions";
import { getAuthorizedWorkAccounts, resolveUniversalWork, type UniversalScanIntent, type UniversalSourceFilter, type UniversalWorkCandidate } from "@/src/lib/workflow/universal-resolver";
import { ProductImage } from "./ProductImage";
import { SubmitButton } from "./SubmitButton";
import { UniversalScanInput } from "./UniversalScanInput";
import { ROUTE_CHANGE_REASONS } from "@/src/lib/workflow/route-decision-policy";

export async function UniversalScannerPanel({ actorUserId, selectedAccountId, query, intent = "ANY", sourceFilter="ALL", success, error, actionPath = "/work/scan" }: { actorUserId: string; selectedAccountId: string; query?: string; intent?: UniversalScanIntent; sourceFilter?: UniversalSourceFilter; success?: string; error?: string; actionPath?: string }) {
  const scope = await getAuthorizedWorkAccounts(actorUserId);
  const selectedAccount=scope.accounts.find(account=>account.id===selectedAccountId);if(!selectedAccount)throw new Error("The selected account is no longer assigned to this user.");
  let result: Awaited<ReturnType<typeof resolveUniversalWork>> | null = null;
  let lookupError: string | null = null;
  if (query) try { result = await resolveUniversalWork({ actorUserId, code: query, intent, sourceFilter, accountId:selectedAccountId }); } catch (cause) { lookupError = cause instanceof Error ? cause.message : "Search failed."; }
  return <section className="space-y-4" data-universal-scanner>
    <form id="universal-scan-form" action={actionPath} className="rounded-md border bg-white p-4 shadow-sm">
      <div className="grid gap-2 lg:grid-cols-[1fr_auto_auto_auto]"><UniversalScanInput initialValue={query} selectOnMount={Boolean(error || lookupError)}/><select name="intent" defaultValue={intent} className="min-h-14 rounded-md border px-3 font-bold">{["ANY","PICK","MARK","ASSEMBLE","PACK"].map((item)=><option key={item} value={item}>{item === "ANY" ? "All work" : item}</option>)}</select><select name="source" defaultValue={sourceFilter} className="min-h-14 rounded-md border px-3 font-bold"><option value="ALL">All sources</option><option value="CUSTOMER_ORDERS">Customer Orders</option><option value="CONSIGNMENTS">Consignments</option></select><button className="min-h-14 rounded-md bg-berry px-6 font-black text-white">Find work</button></div>
      <input type="hidden" name="accountId" value={selectedAccountId}/><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold">{selectedAccount.marketplace} / {selectedAccount.accountDisplayName??selectedAccount.name}</span><span className="text-xs text-slate-500">Selected-account lookup only. Scanning never changes work.</span></div>
    </form>
    {success ? <div className="rounded-md border border-teal-200 bg-teal-50 p-3 font-bold text-teal-800">{success}</div> : null}
    {error || lookupError ? <div className="rounded-md border border-rose-200 bg-rose-50 p-3 font-bold text-rose-700">{error ?? lookupError}</div> : null}
    {result ? <><div className="flex flex-wrap justify-between gap-2 text-sm font-bold text-slate-600"><span>{result.candidates.length} active result(s) in the selected account</span><span>{result.durationMs} ms</span></div>{result.candidates.length ? <div className="grid gap-3">{result.candidates.map((candidate)=><UniversalCandidateCard key={candidate.candidateKey} candidate={candidate} code={result.normalizedInput} intent={intent} sourceFilter={sourceFilter} accountFilter={selectedAccountId} returnPath={actionPath}/>)}</div> : <div className="rounded-md border border-dashed bg-white p-6 text-center"><p className="font-black">{result.completedMatchCount ? "No active work found. Matching work is already completed." : "No exact active work found."}</p><p className="mt-1 text-sm text-slate-600">No action was performed.</p></div>}</> : null}
    <div className="flex flex-wrap gap-2"><Link href="/packing" className="min-h-11 rounded-md border px-4 py-2 text-sm font-bold">Customer Order Packing</Link><Link href="/work" className="min-h-11 rounded-md border px-4 py-2 text-sm font-bold">Work Hub</Link></div>
  </section>;
}

function WorkflowStateGrid({workflow}:{workflow:NonNullable<UniversalWorkCandidate["workflowPrerequisites"]>}){return <div className="mt-2 grid grid-cols-2 gap-1 sm:grid-cols-4">{(["PICK","MARK","ASSEMBLE","PACK"] as const).map(stage=>{const item=workflow.stages[stage],ok=item.state==="SATISFIED"||item.state==="NOT_REQUIRED";return <div key={stage} className={`rounded-md border px-2 py-2 text-xs font-black ${ok?"border-teal-200 bg-teal-50 text-teal-900":"border-amber-200 bg-amber-50 text-amber-950"}`}><p>{stage[0]}{stage.slice(1).toLowerCase()}</p><p className="mt-1 font-medium">{item.state.replaceAll("_"," ").toLowerCase()}</p></div>})}</div>}

type CandidateAction = { value: "ORDER_MARK_COMPLETE" | "ORDER_PACK" | "ASSEMBLY_SEND" | "ASSEMBLY_CLAIM" | "ASSEMBLY_COMPLETE" | "ASSEMBLY_PROBLEM" | "TASK_CLAIM" | "TASK_COMPLETE"; label: string };
function UniversalCandidateCard({ candidate, code, intent, sourceFilter, accountFilter, returnPath }: { candidate: UniversalWorkCandidate; code: string; intent: UniversalScanIntent; sourceFilter: UniversalSourceFilter; accountFilter?: string; returnPath: string }) {
  const actions: CandidateAction[] = [];
  if (candidate.canAct) {
    if (candidate.actionType === "ORDER_PACK") actions.push({ value: "ORDER_PACK", label: "Pack Completed" });
    else if (candidate.actionType === "ORDER_MARK") actions.push({ value: "ORDER_MARK_COMPLETE", label: "Complete marking" });
    else if (candidate.actionType === "ORDER_SEND_TO_ASSEMBLY") { /* Explicit form rendered below. */ }
    else if (candidate.actionType === "ORDER_ASSEMBLY") { if (candidate.status === "READY" && !candidate.assignedUserId) actions.push({ value: "ASSEMBLY_CLAIM", label: "Start" }); actions.push({ value: "ASSEMBLY_COMPLETE", label: "Assembly Completed" }, { value: "ASSEMBLY_PROBLEM", label: "Report Problem" }); }
    else { if (candidate.status === "READY" && !candidate.assignedUserId) actions.push({ value: "TASK_CLAIM", label: "Start" }); if(candidate.stage!=="PICK"&&candidate.status!=="COMPLETED") actions.push({ value: "TASK_COMPLETE", label: candidate.stage==="ASSEMBLE"?"Assembly Completed":candidate.stage==="PACK"?"Pack Completed":"Complete stage" }); }
  }
  const token = `scan:${candidate.candidateKey}:${candidate.status}:${candidate.completedQuantity}`;
  return <article className="grid min-w-0 gap-3 overflow-hidden rounded-md border bg-white p-4 shadow-sm sm:grid-cols-[6rem_minmax(0,1fr)_auto]">
    <ProductImage src={candidate.productImageUrl} alt={candidate.productTitle ?? candidate.sellerSku ?? "Work product"} size="md" showBadge={false}/>
    <div className="min-w-0"><div className="flex flex-wrap gap-1"><span className="rounded-full bg-slate-950 px-2 py-1 text-xs font-black text-white">{candidate.sourceLabel}</span><span className="rounded-full bg-pink-50 px-2 py-1 text-xs font-bold text-berry">{candidate.marketplace}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{candidate.accountName}</span></div>
      <p className="mt-2 break-all text-sm font-black text-slate-950">{candidate.displayReference}</p>
      <p className="mt-1 text-xl font-black">{candidate.sellerSku ?? "No SKU"}</p><p className="line-clamp-2 text-sm text-slate-600">{candidate.productSummary ?? candidate.productTitle ?? "Untitled work"}</p>
      <div className="mt-2 grid gap-1 text-xs text-slate-600 sm:grid-cols-2">{candidate.awb ? <p className="break-all"><b>AWB:</b> {candidate.awb}</p> : null}{candidate.trackingId ? <p className="break-all"><b>Tracking ID:</b> {candidate.trackingId}</p> : null}{candidate.orderNumber ? <p className="break-words"><b>Order:</b> {candidate.orderNumber}</p> : null}{candidate.shipmentId ? <p className="break-words"><b>Shipment:</b> {candidate.shipmentId}</p> : null}{candidate.consignmentNumber ? <p className="break-words"><b>Consignment:</b> {candidate.consignmentNumber}</p> : null}{candidate.taskReference ? <p><b>Stage:</b> {candidate.stage} / {candidate.taskReference}</p> : null}{candidate.itemReference ? <p><b>Item:</b> {candidate.itemReference}</p> : null}{candidate.fsn ? <p className="break-words"><b>FSN:</b> {candidate.fsn}</p> : null}{candidate.listingId ? <p className="break-words"><b>Listing:</b> {candidate.listingId}</p> : null}{candidate.asin ? <p className="break-words"><b>ASIN:</b> {candidate.asin}</p> : null}{candidate.fnsku ? <p className="break-words"><b>FNSKU:</b> {candidate.fnsku}</p> : null}</div>
      <WorkState candidate={candidate}/>{candidate.workflowPrerequisites?<WorkflowStateGrid workflow={candidate.workflowPrerequisites}/>:null}{candidate.shipmentItemCount ? <div className="mt-2 flex flex-wrap gap-2 text-sm font-bold"><span>{candidate.shipmentItemCount} shipment item(s)</span><span>Total qty {candidate.shipmentTotalQuantity}</span>{candidate.status!=="PACKED"?<><span>Picked {candidate.pickedItemCount}</span><span>Waiting {candidate.unpickedItemCount}</span></>:null}</div> : <div className="mt-2 flex flex-wrap gap-3 text-sm font-bold"><span>Quantity to process {candidate.requiredQuantity}</span><span>Completed {candidate.completedQuantity}</span></div>}
      <p className="mt-1 text-xs text-slate-500">Matched {candidate.matchType.replaceAll("_", " ")} {candidate.matchedIdentifierMasked}</p>
      {candidate.stage === "MARK" ? <MarkingInstructions candidate={candidate}/> : null}{candidate.stage === "ASSEMBLE" ? <div className="mt-3 rounded-md bg-slate-50 p-3"><p className="font-black">{candidate.assemblyTitle ?? "Assembly"}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{candidate.assemblyInstructions ?? "Instructions unavailable. Ask an owner."}</p><p className="mt-1 text-xs font-bold text-slate-500">Source: {candidate.assemblySource ?? "Unknown"}</p></div> : null}{candidate.assignedUserName ? <p className="mt-1 text-xs text-slate-500">Assigned to {candidate.assignedUserName}</p> : null}{candidate.readOnlyReason ? <p className="mt-2 text-sm font-bold text-amber-700">{candidate.readOnlyReason}</p> : null}</div>
    <div className="grid content-center gap-2">{candidate.canAct && (candidate.actionType==="ORDER_PICK"||candidate.actionType==="CONSIGNMENT_PICK")?<ScannerPickRoutes candidate={candidate} code={code} intent={intent} sourceFilter={sourceFilter} accountFilter={accountFilter} returnPath={returnPath} token={token}/>:null}{candidate.canAct && candidate.actionType === "ORDER_SEND_TO_ASSEMBLY" ? <AssemblyDiversionForm candidate={candidate} code={code} intent={intent} accountFilter={accountFilter} returnPath={returnPath} token={token}/> : null}{actions.map((action)=><form key={action.value} action={universalCandidateAction}><input type="hidden" name="returnPath" value={returnPath}/><input type="hidden" name="code" value={code}/><input type="hidden" name="intent" value={intent}/><input type="hidden" name="source" value={sourceFilter}/><input type="hidden" name="accountFilter" value={accountFilter ?? ""}/><input type="hidden" name="accountId" value={candidate.accountId}/><input type="hidden" name="sourceId" value={candidate.sourceId}/><input type="hidden" name="action" value={action.value}/><input type="hidden" name="expectedQuantity" value={candidate.completedQuantity}/><input type="hidden" name="expectedStatus" value={candidate.status}/><input type="hidden" name="clientRequestId" value={`${token}:${action.value}`}/><SubmitButton pendingText="Saving...">{action.label}</SubmitButton></form>)}<Link href={detailsHref(candidate)} className="flex min-h-11 items-center justify-center rounded-md border px-3 text-center font-bold">Open Details</Link><a href="#universal-scan-form" className="flex min-h-11 items-center justify-center rounded-md border px-3 text-center font-bold">Scan Next</a></div>
  </article>;
}

const PICK_ROUTE_LABELS={DIRECT_PACK:"Direct to Pack",MARK:"Send to Marking",ASSEMBLE:"Send to Assembly",MARK_ASSEMBLE:"Marking then Assembly"} as const;
function ScannerPickRoutes({candidate,code,intent,sourceFilter,accountFilter,returnPath,token}:{candidate:UniversalWorkCandidate;code:string;intent:UniversalScanIntent;sourceFilter:UniversalSourceFilter;accountFilter?:string;returnPath:string;token:string}){
  const decision=candidate.routeDecision;if(!decision)return null;
  return <details className="rounded-md border border-berry/30 bg-pink-50 p-2 sm:w-80"><summary className="min-h-11 cursor-pointer py-2 font-black text-berry">Picked — choose next route</summary><p className={`mb-2 rounded-md px-2 py-2 text-xs font-black ${decision.recommendationSource==="SYSTEM_FALLBACK"?"bg-amber-100 text-amber-950":"bg-white text-slate-700"}`}>{decision.recommendationSource==="SYSTEM_FALLBACK"?"SYSTEM FALLBACK — DIRECT TO PACK":`Saved route: ${PICK_ROUTE_LABELS[decision.savedRoute]}`}</p><div className="grid gap-2">{decision.options.map(option=>{
    const needsConfirmation=option.reasonRequired||option.missingInstructionStages.length>0;
    const hidden=<><input type="hidden" name="returnPath" value={returnPath}/><input type="hidden" name="code" value={code}/><input type="hidden" name="intent" value={intent}/><input type="hidden" name="source" value={sourceFilter}/><input type="hidden" name="accountFilter" value={accountFilter??""}/><input type="hidden" name="accountId" value={candidate.accountId}/><input type="hidden" name="sourceId" value={candidate.sourceId}/><input type="hidden" name="action" value={candidate.actionType==="ORDER_PICK"?"ORDER_PICK_ROUTE":"TASK_PICK_ROUTE"}/><input type="hidden" name="route" value={option.route}/><input type="hidden" name="expectedQuantity" value={candidate.completedQuantity}/><input type="hidden" name="expectedStatus" value={candidate.status}/><input type="hidden" name="clientRequestId" value={`${token}:${option.route}`}/></>;
    if(!needsConfirmation)return <form key={option.route} action={universalCandidateAction}>{hidden}<SubmitButton pendingText="Routing..." variant={option.route===decision.savedRoute?"primary":"secondary"}>{PICK_ROUTE_LABELS[option.route]}</SubmitButton></form>;
    return <details key={option.route} className="rounded-md border border-amber-300 bg-amber-50 p-2"><summary className="min-h-11 cursor-pointer py-2 text-sm font-black text-amber-950">{PICK_ROUTE_LABELS[option.route]}</summary><form action={universalCandidateAction} className="grid gap-2">{hidden}{option.reasonRequired?<><label className="text-xs font-black text-amber-950">Route-change reason<select name="routeReason" required className="mt-1 min-h-11 w-full rounded-md border bg-white px-2 text-sm"><option value="">Choose reason</option>{ROUTE_CHANGE_REASONS.map(reason=><option key={reason}>{reason}</option>)}</select></label><input name="routeOtherReason" maxLength={240} placeholder="If Other, enter a short reason" className="min-h-11 rounded-md border bg-white px-2 text-sm"/></>:null}{option.missingInstructionStages.length?<><div className="rounded-md border border-amber-400 bg-white p-2 text-xs font-bold text-amber-950">Saved {option.missingInstructionStages.map(stage=>stage==="MARK"?"Marking":"Assembly").join(" and ")} instructions are unavailable. No instructions or machine settings will be invented.</div><label className="flex min-h-11 items-center gap-2 text-xs font-bold text-amber-950"><input type="checkbox" name="confirmMissingInstructions" value="1" required/>Continue with clearly labelled manual-route work</label></>:null}<label className="text-xs font-bold">Optional worker operational note<textarea name="workerNote" maxLength={240} className="mt-1 min-h-20 w-full rounded-md border bg-white p-2 text-sm"/></label><div className="grid grid-cols-2 gap-2"><SubmitButton pendingText="Routing...">Continue</SubmitButton><a href="#universal-scan-form" className="flex min-h-11 items-center justify-center rounded-md border bg-white px-3 text-sm font-bold">Cancel</a></div></form></details>;
  })}</div></details>;
}

function detailsHref(candidate:UniversalWorkCandidate){if(candidate.sourceType==="CONSIGNMENT_TASK")return `/work/consignments/items/${encodeURIComponent(candidate.taskId??candidate.sourceId)}`;if(candidate.workGroupKey&&candidate.stage)return `/work/groups/${candidate.stage.toLowerCase()}/${encodeURIComponent(candidate.workGroupKey)}?source=ORDER`;if(candidate.stage)return `/work/${candidate.stage.toLowerCase()}?source=ORDER`;return `/packing/${encodeURIComponent(candidate.orderId??candidate.sourceId)}`;}
function WorkState({candidate}:{candidate:UniversalWorkCandidate}){const packed=candidate.status==="PACKED"||candidate.status==="COMPLETED",label=packed?"PACKED":candidate.status==="PROBLEM"?`${candidate.stage??"Current"} problem`:candidate.status==="PACK_READY"?"Pack ready":candidate.stage==="MARK"?`Mark ${candidate.status==="IN_PROGRESS"?"in progress":"pending"} · Pack locked`:candidate.stage==="ASSEMBLE"?`Assembly ${candidate.status==="IN_PROGRESS"?"in progress":"pending"} · Pack locked`:candidate.stage==="PICK"||candidate.status==="PICK_PENDING"?`Pick ${candidate.status==="IN_PROGRESS"?"in progress":"pending"} · Pack locked`:candidate.status.replaceAll("_"," ");return <div className={`mt-3 rounded-md border p-3 text-sm font-black ${packed?"border-teal-300 bg-teal-50 text-teal-900":"border-amber-300 bg-amber-50 text-amber-950"}`}><p>{label}</p>{candidate.problemReason?<p className="mt-1 font-medium">Reason: {candidate.problemReason.replaceAll("_"," ")}</p>:null}{packed?<p className="mt-1 font-medium">Packed by {candidate.packedByName??"recorded worker"}{candidate.packedAt?` · ${candidate.packedAt.toLocaleString()}`:""}</p>:null}</div>}

function AssemblyDiversionForm({candidate,code,intent,accountFilter,returnPath,token}:{candidate:UniversalWorkCandidate;code:string;intent:UniversalScanIntent;accountFilter?:string;returnPath:string;token:string}) {
  return <details className="rounded-md border p-2 sm:w-72"><summary className="min-h-11 cursor-pointer py-2 font-bold text-berry">Send to Assembly</summary><form action={universalCandidateAction} className="mt-2 grid gap-2"><input type="hidden" name="returnPath" value={returnPath}/><input type="hidden" name="code" value={code}/><input type="hidden" name="intent" value={intent}/><input type="hidden" name="accountFilter" value={accountFilter ?? ""}/><input type="hidden" name="accountId" value={candidate.accountId}/><input type="hidden" name="sourceId" value={candidate.sourceId}/><input type="hidden" name="action" value="ASSEMBLY_SEND"/><input type="hidden" name="expectedQuantity" value={candidate.completedQuantity}/><input type="hidden" name="expectedStatus" value={candidate.status}/><input type="hidden" name="clientRequestId" value={`${token}:ASSEMBLY_SEND`}/><input name="manualTitle" maxLength={160} placeholder="Assembly title (optional)" className="min-h-11 rounded-md border px-3"/><textarea name="manualInstructions" required={candidate.assemblyInstructionsRequired} maxLength={2000} placeholder={candidate.assemblyInstructionsRequired ? "Assembly instructions required" : "Optional rule note"} className="min-h-24 rounded-md border p-3"/><input name="manualImageUrl" maxLength={2048} placeholder="Optional safe image URL" className="min-h-11 rounded-md border px-3"/><SubmitButton pendingText="Sending...">Send to Assembly</SubmitButton></form></details>;
}

function MarkingInstructions({ candidate }: { candidate: UniversalWorkCandidate }) {
  return <details className="mt-3 rounded-md bg-slate-50 p-3"><summary className="cursor-pointer font-black">Marking instructions</summary><div className="mt-2 grid gap-1 text-sm"><p>{candidate.markingMasterDesignId ?? "No Master Design ID"} / {candidate.markingAssetName ?? "No marking asset"}</p><p>{candidate.markingPosition ?? "Position not set"}</p><p>{candidate.markingWidthMm ?? "-"} x {candidate.markingHeightMm ?? "-"} mm / Power {candidate.markingPower ?? "-"} / Speed {candidate.markingSpeed ?? "-"} / Frequency {candidate.markingFrequency ?? "-"} / Passes {candidate.markingPasses ?? "-"}</p><p>{candidate.markingInstructions ?? "No extra instructions"}</p></div></details>;
}
