import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getOrderMarkingQueue } from "@/src/lib/workflow/order-route-tasks";
import { parseOrderMarkingMetadata } from "@/src/lib/workflow/route-task-metadata";
import { completeOrderMarkingAction,reportOrderMarkingProblemAction } from "./actions";

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;error?:string;success?:string}>}){
 const user=await requireUser();const account=await requireAccount(user);const query=await searchParams;const tasks=await getOrderMarkingQueue({accountId:account.id,actorUserId:user.id,search:query.q});const canMutate=hasWorkPermission(user,"canMark");
 return <AppShell><PageHeader eyebrow="Customer order work" title="Order Marking" description="Use the reviewed marking snapshot. Completing Marking unlocks only the next saved route stage."/>{query.error?<p className="mb-3 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</p>:null}{query.success?<p className="mb-3 rounded-md bg-teal-50 p-3 font-bold text-teal-800">Saved.</p>:null}<form className="mb-4 flex gap-2 rounded-md border bg-white p-3"><input name="q" defaultValue={query.q} placeholder="AWB, Tracking ID, order item, order or SKU" className="min-h-11 min-w-0 flex-1 rounded-md border px-3"/><button className="rounded-md bg-slate-950 px-4 font-bold text-white">Find</button></form>
 <section className="grid gap-3">{tasks.map(task=>{const metadata=parseOrderMarkingMetadata(task.metadataJson);const assignedElsewhere=Boolean(task.assignedUserId&&task.assignedUserId!==user.id&&user.role!=="OWNER");const actionable=canMutate&&!assignedElsewhere&&["READY","IN_PROGRESS"].includes(task.status)&&Boolean(metadata);const token=`${task.id}:${task.updatedAt.toISOString()}:${task.status}`;return <article key={task.id} className="grid gap-4 rounded-md border bg-white p-4 shadow-sm lg:grid-cols-[7rem_minmax(0,1fr)_minmax(15rem,auto)]"><ProductImage src={metadata?.productImageSnapshot??task.order?.imageUrl} alt={metadata?.productTitleSnapshot??task.order?.productDescription??task.order?.sku??"Order"} size="md" showBadge={false}/><div className="min-w-0"><div className="flex flex-wrap gap-1"><span className="rounded-full bg-slate-950 px-2 py-1 text-xs font-black text-white">CUSTOMER ORDER</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">MARK</span><span className="rounded-full bg-pink-50 px-2 py-1 text-xs font-black text-berry">{task.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-xl font-black">{metadata?.productTitleSnapshot??task.order?.productDescription??task.order?.sku}</p><p className="font-bold">SKU {task.order?.sku}</p><p className="break-words text-sm text-slate-600">Tracking {task.order?.trackingId??"-"} / Item {task.order?.orderItemId??"-"} / Order {task.order?.orderNo??"-"} / Qty {task.requiredQuantity}</p><p className="text-xs text-slate-500">{task.assignedUser?.name?`Assigned ${task.assignedUser.name}`:"Unassigned"}</p>{task.status==="PROBLEM"?<div className="mt-3 rounded-md bg-rose-50 p-3 text-sm text-rose-800"><p className="font-black">{task.problemReason?.replaceAll("_"," ")??"Marking problem"}</p>{task.actionLogs[0]?.note?<p>{task.actionLogs[0].note}</p>:null}<p className="text-xs">Reported by {task.problemReportedBy?.name??"worker"}</p></div>:null}</div>
 <div className="space-y-3">{metadata?<div className="rounded-md bg-slate-50 p-3 text-sm"><p className="font-black">{metadata.masterDesignId??"No Master Design ID"} / {metadata.markingAssetName}</p><p>{metadata.material??"Material not set"} / {metadata.markingPosition??"Position not set"}</p><p>{metadata.markingWidthMm??"-"} x {metadata.markingHeightMm??"-"} mm / Power {metadata.powerSetting??"-"} / Speed {metadata.speedSetting??"-"} / Frequency {metadata.frequencySetting??"-"} / Passes {metadata.passes??"-"}</p><p className="mt-1 whitespace-pre-wrap">{metadata.instructions??"No extra instructions"}</p><div className="mt-2 flex flex-wrap gap-2"><a href={`/work/tasks/${task.id}/marking-file?type=preview`} target="_blank" rel="noreferrer" className="rounded-md border bg-white px-3 py-2 font-bold">Open marking preview</a><a href={`/work/tasks/${task.id}/marking-file`} className="rounded-md border bg-white px-3 py-2 font-bold">Marking file</a></div></div>:<p className="rounded-md bg-rose-50 p-3 text-sm font-bold text-rose-800">Instructions are malformed. This task is read-only until an owner corrects it.</p>}
 {actionable?<><form action={completeOrderMarkingAction}><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="expectedStatus" value={task.status}/><input type="hidden" name="clientRequestId" value={`${token}:complete`}/><SubmitButton pendingText="Completing...">Complete marking</SubmitButton></form>{user.role==="OWNER"||user.canReportProblem?<details className="rounded-md border p-3"><summary className="cursor-pointer font-bold text-rose-700">Report problem</summary><form action={reportOrderMarkingProblemAction} className="mt-2 grid gap-2"><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="expectedStatus" value={task.status}/><input type="hidden" name="clientRequestId" value={`${token}:problem`}/><select name="reason" className="min-h-11 rounded-md border px-2">{["WRONG_PRODUCT","MARKING_FILE_MISSING","MARKING_FILE_WRONG","MARKING_FAILED","DAMAGED_PRODUCT","QUANTITY_SHORT","OTHER"].map(reason=><option key={reason}>{reason.replaceAll("_"," ")}</option>)}</select><textarea name="note" maxLength={1000} className="min-h-20 rounded-md border p-2" placeholder="Optional note"/><SubmitButton pendingText="Reporting..." variant="secondary">Report problem</SubmitButton></form></details>:null}</>:<p className="rounded-md bg-slate-50 p-3 text-sm font-bold text-slate-600">{assignedElsewhere?"Assigned to another worker.":user.canViewAllWork&&!canMutate?"Read-only work view.":task.status==="PROBLEM"?"Problem awaiting review.":"Not actionable."}</p>}</div></article>})}</section>{!tasks.length?<p className="rounded-md border border-dashed bg-white p-6 text-center font-bold">No active order marking work.</p>:null}</AppShell>;
}
