import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount, requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { WORK_TASK_INCLUDE } from "@/src/lib/workflow/queues";
import { assertWorkerAccountAccess } from "@/src/lib/workflow/worker-access";
import { reassignTaskAction, resolveTaskProblemAction } from "../actions";
import { WorkTaskCard } from "../WorkTaskCard";

export default async function WorkProblemsPage({searchParams}:{searchParams:Promise<{page?:string;success?:string;error?:string}>}){const user=await requireUser();const account=await requireAccount(user);await assertWorkerAccountAccess(user.id,account.id);const query=await searchParams;const page=Math.max(1,Number(query.page)||1);const take=50;const manager=user.role==="OWNER"||user.canManageConsignments||user.canViewAllWork;const visibility=manager?{}:{OR:[{assignedUserId:user.id},{problemReportedByUserId:user.id}]};const where={accountId:account.id,sourceType:"CONSIGNMENT" as const,status:"PROBLEM" as const,...visibility};const [tasks,total,workers]=await Promise.all([prisma.workTask.findMany({where,include:WORK_TASK_INCLUDE,orderBy:{problemReportedAt:"asc"},skip:(page-1)*take,take}),prisma.workTask.count({where}),manager?prisma.user.findMany({where:{active:true,OR:[{accountId:account.id},{assignedAccounts:{some:{id:account.id}}}]},select:{id:true,name:true,role:true,canPick:true,canMark:true,canPack:true}}):[]]);const returnPath=`/work/problems?page=${page}`;
return <AppShell><PageHeader eyebrow="Blocked consignment work" title="Work Problems" description="Problem history and quantities are preserved. Resolving returns work to Ready or In progress."><Link href="/work" className="rounded-md border px-4 py-2 text-sm font-bold">Work Hub</Link></PageHeader>{query.success?<div className="mb-3 rounded-md bg-teal-50 p-3 font-bold text-teal-800">{query.success}</div>:null}{query.error?<div className="mb-3 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</div>:null}<section className="space-y-4">{tasks.map((task)=><div key={task.id}><WorkTaskCard task={task} returnPath={returnPath}/>{manager?<div className="mt-2 grid gap-2 rounded-md border border-amber-200 bg-amber-50 p-3 sm:grid-cols-2"><form action={resolveTaskProblemAction} className="grid gap-2"><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="clientRequestId" value={`${task.id}:resolve:${task.updatedAt.toISOString()}`}/><input type="hidden" name="returnPath" value={returnPath}/><textarea name="resolutionNote" required maxLength={1000} placeholder="Resolution note" className="min-h-20 rounded-md border p-2"/><SubmitButton pendingText="Resolving...">Resolve and return to work</SubmitButton></form><form action={reassignTaskAction} className="grid gap-2"><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="returnPath" value={returnPath}/><select name="assignedUserId" defaultValue={task.assignedUserId??""} className="min-h-11 rounded-md border px-2"><option value="">Unassigned</option>{workers.filter((worker)=>worker.role==="OWNER"||(task.stage==="PICK"&&(worker.canPick||worker.role==="PICKER"))||(task.stage==="MARK"&&worker.canMark)||(task.stage==="PACK"&&(worker.canPack||worker.role==="PACKER"))).map((worker)=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select><SubmitButton pendingText="Assigning..." variant="secondary">Update assignment</SubmitButton></form></div>:null}</div>)}</section>{!tasks.length?<div className="rounded-md border border-dashed bg-white p-6 text-center font-black">No open task problems.</div>:null}<div className="mt-5 flex justify-between text-sm font-bold"><span>Showing {(page-1)*take+(total?1:0)}-{Math.min(page*take,total)} of {total}</span><div className="flex gap-2">{page>1?<Link href={`?page=${page-1}`} className="rounded-md border px-3 py-2">Previous</Link>:null}{page*take<total?<Link href={`?page=${page+1}`} className="rounded-md border px-3 py-2">Next</Link>:null}</div></div></AppShell>;}
