import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount } from "@/lib/auth";
import { requireConsignmentAccess } from "@/lib/consignment-auth";
import { prisma } from "@/lib/prisma";
import { resolveConsignmentIssueAction } from "../../actions";

export default async function ConsignmentIssuesPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<{ page?: string; severity?: string; type?: string; error?: string }> }) {
 const user=await requireConsignmentAccess("view"); const account=await requireAccount(user); const {batchId}=await params; const query=await searchParams; const page=Math.max(1,Number(query.page)||1); const take=50;
 const batch=await prisma.consignmentBatch.findFirst({where:{id:batchId,accountId:account.id},select:{id:true,displayName:true}}); if(!batch) notFound();
 const where={consignmentBatchId:batch.id,severity:query.severity?query.severity as never:undefined,issueType:query.type?{contains:query.type}:undefined};
 const [issues,total,groups]=await Promise.all([prisma.consignmentImportIssue.findMany({where,orderBy:[{resolved:"asc"},{rowNumber:"asc"},{createdAt:"asc"}],skip:(page-1)*take,take,include:{consignmentLine:{select:{sellerSkuSource:true,fsnSource:true}}}}),prisma.consignmentImportIssue.count({where}),prisma.consignmentImportIssue.groupBy({by:["issueType","severity"],where:{consignmentBatchId:batch.id,resolved:false},_count:{_all:true}})]);
 const canManage=user.role==="OWNER"||user.canManageConsignments;
 return <AppShell><PageHeader eyebrow="Safe issue drill-down" title={`${batch.displayName} issues`} description="Only operational identifiers and controlled messages are shown; raw source rows are not stored here."><Link href={`/owner/consignments/${batch.id}/review`} className="rounded-md bg-berry px-4 py-2 text-sm font-bold text-white">Back to review</Link></PageHeader>
 {query.error==="blocking-source"?<p role="alert" className="mb-4 rounded-md border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">Blocking import errors cannot be marked reviewed manually. Correct or replace the source and reparse it.</p>:null}
 <div className="mb-4 flex flex-wrap gap-2">{groups.map((group)=><span key={`${group.issueType}-${group.severity}`} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold">{group.issueType.replaceAll("_"," ")}: {group._count._all}</span>)}</div>
 <form className="mb-4 grid gap-2 rounded-md border bg-white p-3 sm:grid-cols-[12rem_1fr_auto]"><select name="severity" defaultValue={query.severity??""} className="min-h-11 rounded-md border px-3"><option value="">All severities</option><option>ERROR</option><option>WARNING</option><option>INFO</option></select><input name="type" defaultValue={query.type} placeholder="Issue type" className="min-h-11 rounded-md border px-3"/><button className="rounded-md bg-slate-950 px-4 font-bold text-white">Filter</button></form>
 <div className="grid gap-3">{issues.map((issue)=><article key={issue.id} className="rounded-md border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><span className={`rounded-full px-2 py-1 text-xs font-black ${issue.severity==="ERROR"?"bg-rose-50 text-rose-700":issue.severity==="WARNING"?"bg-amber-50 text-amber-800":"bg-blue-50 text-blue-700"}`}>{issue.severity}</span><span className="ml-2 text-sm font-black">{issue.issueType.replaceAll("_"," ")}</span></div><span className="text-xs text-slate-500">{issue.rowNumber ? "Row " + issue.rowNumber : "Batch"} / {issue.resolved?"Resolved":"Open"}</span></div><p className="mt-3 text-sm">{issue.message}</p><p className="mt-2 text-xs text-slate-500">SKU {issue.consignmentLine?.sellerSkuSource??"not available"} / FSN {issue.consignmentLine?.fsnSource??"not available"}</p>{canManage&&!issue.resolved&&issue.severity!=="ERROR"?<form action={resolveConsignmentIssueAction} className="mt-3"><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="issueId" value={issue.id}/><SubmitButton pendingText="Resolving..." variant="secondary">Mark reviewed</SubmitButton></form>:canManage&&!issue.resolved?<p className="mt-3 rounded-md bg-rose-50 p-3 text-xs font-bold text-rose-800">Correct or replace the source and reparse it to clear this blocking error.</p>:null}</article>)}</div>
 <div className="mt-5 flex justify-between text-sm font-bold"><span>Showing {(page-1)*take+(total?1:0)}-{Math.min(page*take,total)} of {total}</span><div className="flex gap-2">{page>1?<Link href={`?page=${page-1}&severity=${query.severity??""}&type=${query.type??""}`} className="rounded-md border px-3 py-2">Previous</Link>:null}{page*take<total?<Link href={`?page=${page+1}&severity=${query.severity??""}&type=${query.type??""}`} className="rounded-md border px-3 py-2">Next</Link>:null}</div></div>
 </AppShell>;
}
