ALTER TABLE "User" ADD COLUMN "canPick" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "canPack" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "canReportProblem" BOOLEAN NOT NULL DEFAULT true;
