import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import type { ReactNode } from "react";
import type { WorkStage } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser,roleHomePath } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getGroupedWorkDetails,type GroupedWorkSource } from "@/src/lib/workflow/grouped-work";
import { GroupedWorkCard } from "../../../GroupedWorkCard";
import { ExactMemberSelection } from "../../../ExactMemberSelection";
import { setGroupedProgressAction } from "../../../stage-actions";

const STAGES=new Set(["PICK","MARK","ASSEMBLE","PACK"]);
const show=(value:unknown)=>typeof value==="string"&&value.trim()?value:typeof value==="number"?String(value):null;
function Field({label,value}:{label:string;value:unknown}){const displayed=show(value);return displayed?<div><dt className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</dt><dd className="break-words font-bold">{displayed}</dd></div>:null;}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="mt-4 rounded-md border bg-white p-5"><h2 className="text-lg font-black">{title}</h2><div className="mt-3">{children}</div></section>;}

export default async function GroupDetailsPage({params,searchParams}:{params:Promise<{stage:string;groupKey:string}>;searchParams:Promise<{source?:string;success?:string;error?:string;page?:string;historyPage?:string}>}){
 const route=await params,query=await searchParams,stage=route.stage.toUpperCase() as WorkStage,source=query.source as GroupedWorkSource;
 if(!STAGES.has(stage)||!(["ORDER","CONSIGNMENT"] as string[]).includes(source))notFound();
 const user=await requireUser(),account=await requireAccount(user),permission=stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack";
 if(!hasWorkPermission(user,permission)&&!user.canViewAllWork)redirect(roleHomePath(user.role));
 const page=Math.max(1,Number(query.page)||1),historyPage=Math.max(1,Number(query.historyPage)||1);let details;try{details=await getGroupedWorkDetails({actorUserId:user.id,accountId:account.id,stage,sourceType:source,groupKey:route.groupKey,page,historyPage});}catch{notFound();}
 const {card,tasks,history}=details,canAct=hasWorkPermission(user,permission),first=tasks[0],snapshot=first?.workCardSnapshot??{},routeSnapshot=first?.routeSnapshot??{},instructions=first?.instructions??{},maxPartial=card.requiredQuantity-1,needsMissingConfirmation=Boolean(card.recommendedNextStage&&card.missingInstructionStages.includes(card.recommendedNextStage));
 return <AppShell>
  <PageHeader eyebrow={(source==="ORDER"?"Daily Orders":"Consignments")+" / "+stage} title={card.sellerSku+" group"} description="Product identity, instructions, workflow history, problems and every underlying record."/>
  <Link href={"/work/"+stage.toLowerCase()+"?source="+source} className="mb-4 inline-flex min-h-11 items-center font-bold text-berry">← Back to {stage.toLowerCase()}</Link>
  {query.success?<p className="mb-3 rounded-md bg-teal-50 p-3 font-bold text-teal-800">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</p>:null}
  <GroupedWorkCard card={card} canAct={canAct}/>
  <Section title="Overview"><div className="grid gap-5 md:grid-cols-[10rem_1fr]"><ProductImage src={card.productImageUrl} alt={card.productTitle??card.sellerSku} size="lg" showBadge={false}/><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Product" value={card.productTitle}/><Field label="Seller SKU" value={card.sellerSku}/><Field label="Account" value={account.accountDisplayName??account.name}/><Field label="Marketplace" value={card.marketplace}/><Field label="Current stage" value={card.stage}/><Field label="Status" value={card.status}/><Field label="Required quantity" value={card.requiredQuantity}/><Field label="Completed quantity" value={card.completedQuantity}/><Field label="Recommended next" value={card.recommendedNextStage??"Complete"}/><Field label="Recommended route" value={snapshot.routeRecommendation??routeSnapshot.processRoute}/><Field label="Actual stages" value={Array.isArray(routeSnapshot.actualStages)?routeSnapshot.actualStages.join(" → "):null}/><Field label="Assigned worker" value={card.assignedUserName??"Unassigned"}/></dl></div></Section>
  <Section title="Marketplace identifiers"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Flipkart FSN" value={first?.order?.fsn??first?.consignmentLine?.fsnSnapshot}/><Field label="Flipkart Listing ID" value={first?.consignmentLine?.listingIdSnapshot}/><Field label="Amazon ASIN" value={first?.consignmentLine?.asinSnapshot}/><Field label="Amazon FNSKU" value={first?.consignmentLine?.fnskuSnapshot}/><Field label="External ID" value={first?.consignmentLine?.externalIdSnapshot}/><Field label="EAN / Barcode" value={first?.consignmentLine?.barcodeSnapshot??snapshot.operationalBarcode}/></dl></Section>
  <Section title="Instructions"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Process rule" value={instructions.processRuleId}/><Field label="Marking asset" value={instructions.markingAssetId}/><Field label="Master design" value={instructions.masterDesignId}/><Field label="Marking position" value={instructions.markingPosition}/><Field label="Width (mm)" value={instructions.markingWidthMm}/><Field label="Height (mm)" value={instructions.markingHeightMm}/><Field label="Machine power" value={instructions.powerSetting}/><Field label="Machine speed" value={instructions.speedSetting}/><Field label="Marking instructions" value={instructions.instructions}/><Field label="Assembly title" value={instructions.assemblyTitle}/><Field label="Assembly instructions" value={instructions.assemblyInstructions}/><Field label="Assembly reference" value={instructions.assemblyImageUrl}/></dl>{!Object.keys(instructions).length?<p className="text-sm text-slate-600">No additional instructions are required for this stage.</p>:null}</Section>
  {canAct&&stage!=="PACK"&&card.pendingQuantity>1?<Section title="Fast quantity mode"><p className="text-sm text-slate-600">Enter processed quantity. The server allocates assigned-to-you members first, then oldest source record and stable ID. Fully completed members route forward; one partial member stays here.</p><form action={setGroupedProgressAction} className="mt-3 grid max-w-xl gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="stage" value={stage}/><input type="hidden" name="sourceType" value={source}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="clientRequestId" value={card.groupKey+":"+card.groupVersion+":partial"}/><input name="targetQuantity" aria-label="Exact group completed quantity" type="number" min={card.completedQuantity+1} max={maxPartial} defaultValue={card.completedQuantity+1} required className="min-h-11 min-w-0 rounded-md border px-3"/><SubmitButton pendingText="Saving..." variant="secondary">Save and Route Complete Members</SubmitButton>{needsMissingConfirmation?<label className="sm:col-span-2 flex min-h-11 items-center gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm font-bold"><input type="checkbox" name="confirmMissingInstructions" value="1" required/>Saved {card.recommendedNextStage} instructions are unavailable. Create clearly labelled manual-route work.</label>:null}<label className="sm:col-span-2 text-sm font-bold">Optional worker note<input name="workerNote" maxLength={240} className="mt-1 min-h-11 w-full rounded-md border px-3"/></label></form></Section>:null}
  {canAct&&stage!=="PACK"?<Section title="Exact member-selection mode"><p className="mb-3 text-sm text-slate-600">Select exact eligible records. IDs and eligibility are reloaded inside one transaction; no quantity from this screen is trusted.</p><ExactMemberSelection stage={stage} sourceType={source} groupKey={card.groupKey} groupVersion={card.groupVersion} missingInstructionStage={needsMissingConfirmation?card.recommendedNextStage:null} members={tasks.filter(task=>task.status==="READY"||task.status==="IN_PROGRESS").map((task,index)=>({id:task.id,reference:task.order?.orderItemId??task.order?.orderNo??`Consignment row ${task.consignmentLine?.rowNumber??index+1}`,requiredQuantity:task.requiredQuantity,completedQuantity:task.completedQuantity,status:task.status,assignment:task.assignedUser?.name??"Unassigned"}))}/></Section>:null}
  <Section title={"Underlying work ("+details.total+")"}><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-2">#</th><th className="p-2">Order / line</th><th className="p-2">Shipment / tracking</th><th className="p-2">Quantity</th><th className="p-2">Status</th><th className="p-2">Worker</th></tr></thead><tbody>{tasks.map((task,index)=><tr key={task.id} className="border-b last:border-0"><td className="p-2">{(page-1)*details.pageSize+index+1}</td><td className="p-2 font-bold">{task.order?.orderItemId??task.order?.orderNo??"Consignment row "+(task.consignmentLine?.rowNumber??index+1)}</td><td className="p-2">{task.order?.shipmentId??task.order?.trackingId??task.order?.awb??task.consignmentLine?.fnskuSnapshot??task.consignmentLine?.barcodeSnapshot??"—"}</td><td className="p-2">{task.completedQuantity}/{task.requiredQuantity}</td><td className="p-2">{task.status.replaceAll("_"," ")}</td><td className="p-2">{task.assignedUser?.name??"Unassigned"}</td></tr>)}</tbody></table></div><div className="mt-3 flex justify-between">{page>1?<Link href={`?source=${source}&page=${page-1}&historyPage=${historyPage}`} className="rounded-md border px-3 py-2 font-bold">Previous</Link>:<span/>}{details.hasMore?<Link href={`?source=${source}&page=${page+1}&historyPage=${historyPage}`} className="rounded-md border px-3 py-2 font-bold">Next</Link>:null}</div></Section>
  <Section title={`Workflow and assignment history (${details.historyTotal})`}>{history.length?<ol className="space-y-2">{history.map(log=><li key={log.id} className="rounded-md bg-slate-50 p-3 text-sm"><span className="font-bold">{log.action.replaceAll("_"," ")}</span> by {log.actorUser.name} · {log.createdAt.toLocaleString()}{log.quantityAfter!=null?" · Quantity "+log.quantityAfter:""}<span className="block text-xs text-slate-500">Work item {log.taskRef}</span></li>)}</ol>:<p className="text-sm text-slate-600">No worker actions have been recorded yet.</p>}<div className="mt-3 flex justify-between">{historyPage>1?<Link href={`?source=${source}&page=${page}&historyPage=${historyPage-1}`} className="rounded-md border px-3 py-2 font-bold">Newer history</Link>:<span/>}{details.historyHasMore?<Link href={`?source=${source}&page=${page}&historyPage=${historyPage+1}`} className="rounded-md border px-3 py-2 font-bold">Older history</Link>:null}</div></Section>
  <Section title="Problems"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{card.problemCount?card.problemCount+" work item(s) need attention.":"No open problems in this group."}</p>{tasks.filter(task=>task.problemReason).map(task=><p key={task.id} className="mt-1 text-sm text-rose-700">{task.problemReason?.replaceAll("_"," ")}{task.problemResolutionNote?" — "+task.problemResolutionNote:""}</p>)}</div><Link href="/work/problems" className="inline-flex min-h-11 items-center rounded-md border px-4 font-bold text-rose-700">Open problem controls</Link></div></Section>
 </AppShell>;
}
