import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound,redirect } from "next/navigation";
import type { ReactNode } from "react";
import type { WorkStage } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { StructuredDetails, type DetailSection } from "@/components/StructuredDetails";
import { SubmitButton } from "@/components/SubmitButton";
import { capabilityHomePath,requireAccount,requireUser } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getGroupedWorkDetails,type GroupedWorkSource } from "@/src/lib/workflow/grouped-work";
import { GroupedWorkCard } from "../../../GroupedWorkCard";
import { PackWorkCard } from "../../../pack/PackWorkCard";
import { setGroupedProgressAction } from "../../../stage-actions";

const STAGES=new Set(["PICK","MARK","ASSEMBLE","PACK"]);
const detailValue=(value:unknown):string|number|null=>typeof value==="string"||typeof value==="number"?value:value===true?"Yes":value===false?"No":null;
function Section({title,children,id}:{title:string;children:ReactNode;id?:string}){return <section id={id} className="mt-4 rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">{title}</h2><div className="mt-3">{children}</div></section>}

export default async function GroupDetailsPage({params,searchParams}:{params:Promise<{stage:string;groupKey:string}>;searchParams:Promise<{source?:string;success?:string;error?:string;page?:string;historyPage?:string}>}){
 const route=await params,query=await searchParams,stage=route.stage.toUpperCase() as WorkStage,source=query.source as GroupedWorkSource;if(!STAGES.has(stage)||!(["ORDER","CONSIGNMENT"] as string[]).includes(source))notFound();
 const user=await requireUser(),account=await requireAccount(user),permission=stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack";if(!hasWorkPermission(user,permission)&&!user.canViewAllWork)redirect(capabilityHomePath(user));
 const page=Math.max(1,Number(query.page)||1),historyPage=Math.max(1,Number(query.historyPage)||1);let details;try{details=await getGroupedWorkDetails({actorUserId:user.id,accountId:account.id,stage,sourceType:source,groupKey:route.groupKey,page,historyPage});}catch{notFound();}
 const {card,tasks,history}=details,canAct=hasWorkPermission(user,permission),first=tasks[0],snapshot=first?.workCardSnapshot??{},routeSnapshot=first?.routeSnapshot??{},instructions=first?.instructions??{},maxPartial=card.requiredQuantity-1,order=first?.order,line=first?.consignmentLine,isOwner=user.role==="OWNER";
 const sections:DetailSection[]=[
  {title:"Overview",fields:[{label:"Product",value:card.productTitle},{label:"Seller SKU",value:card.sellerSku},{label:"Account",value:account.accountDisplayName??account.name},{label:"Marketplace",value:card.marketplace},{label:"Required quantity",value:card.requiredQuantity},{label:"Completed quantity",value:card.completedQuantity},{label:"Pending quantity",value:card.pendingQuantity},{label:"Current stage",value:card.stage},{label:"Status",value:card.status},{label:"Assignment",value:card.assignedUserName??"Unassigned"}]},
  {title:"Images",fields:[{label:"Primary image",value:card.productImageUrl,href:card.productImageUrl}]},
  {title:"Quantity and Members",fields:[{label:"Required quantity",value:card.requiredQuantity},{label:"Completed quantity",value:card.completedQuantity},{label:"Pending quantity",value:card.pendingQuantity},{label:"Member records",value:details.total}]},
  {title:"Instructions",fields:[{label:"Recommended route",value:detailValue(snapshot.routeRecommendation)??detailValue(routeSnapshot.processRoute)},{label:"Marking instructions",value:detailValue(instructions.instructions)},{label:"Assembly instructions",value:detailValue(instructions.assemblyInstructions)},{label:"Worker note",value:detailValue(instructions.workerNote)}]},
  {title:"Identifiers",fields:[{label:"Order Item ID",value:order?.orderItemId},{label:"Tracking ID",value:order?.trackingId},{label:"FSN",value:order?.fsn??line?.fsnSnapshot},{label:"Listing ID",value:line?.listingIdSnapshot},{label:"ASIN",value:line?.asinSnapshot},{label:"FNSKU",value:line?.fnskuSnapshot},{label:"External ID",value:line?.externalIdSnapshot}]},
  {title:"Timeline",fields:[{label:"Oldest waiting",value:new Date(card.oldestWaitingAt).toLocaleString()},{label:"Current stage",value:card.stage},{label:"Current status",value:card.status}]},
  {title:"Problems and History",fields:[{label:"Open problems",value:card.problemCount||null},{label:"Problem reason",value:first?.problemReason},{label:"History records",value:details.historyTotal}]},
  {title:"Marketplace Listing",fields:[{label:"FSN",value:order?.fsn??line?.fsnSnapshot},{label:"Listing ID",value:line?.listingIdSnapshot},{label:"ASIN",value:line?.asinSnapshot},{label:"FNSKU",value:line?.fnskuSnapshot},{label:"External ID",value:line?.externalIdSnapshot},{label:"EAN / Barcode",value:line?.barcodeSnapshot??detailValue(snapshot.operationalBarcode)}]},
  {title:"Pricing and Settlement",fields:[{label:"Invoice No.",value:null},{label:"Invoice Amount",value:null},{label:"Selling Price Per Item",value:null},{label:"Shipping and Handling Charges",value:null},{label:"CGST",value:null},{label:"IGST",value:null},{label:"SGST",value:null}]},
  {title:"Fulfilment and Stock References",description:"Reference-only fields never create physical inventory.",fields:[{label:"Ready to Make",value:null},{label:"Dispatch After date",value:null},{label:"Dispatch by date",value:null}]},
  {title:"Package and Shipping",fields:[{label:"Tracking ID",value:order?.trackingId},{label:"AWB",value:order?.awb},{label:"Shipment ID",value:order?.shipmentId},{label:"Package Length",value:null},{label:"Package Breadth",value:null},{label:"Package Height",value:null},{label:"Package Weight",value:null}]},
  {title:"Tax and Legal",fields:[{label:"HSN CODE",value:null},{label:"Form requirement",value:null}]},
  {title:"Live Marketplace Data",fields:[{label:"Current marketplace",value:card.marketplace}]},
  {title:"Description and Specifications",fields:[{label:"Product",value:order?.productDescription??card.productTitle}]},
  {title:"Processing and Workflow",fields:[{label:"Recommended route",value:detailValue(snapshot.routeRecommendation)??detailValue(routeSnapshot.processRoute)},{label:"Actual stages",value:Array.isArray(routeSnapshot.actualStages)?routeSnapshot.actualStages.map(detailValue).filter(Boolean).join(" → "):null},{label:"Recommended next",value:card.recommendedNextStage??"Complete"},{label:"Master Design ID",value:detailValue(instructions.masterDesignId)},{label:"Marking position",value:detailValue(instructions.markingPosition)},{label:"Dimensions",value:detailValue(instructions.markingWidthMm)&&detailValue(instructions.markingHeightMm)?`${detailValue(instructions.markingWidthMm)} × ${detailValue(instructions.markingHeightMm)} mm`:null},{label:"Power",value:detailValue(instructions.powerSetting)},{label:"Speed",value:detailValue(instructions.speedSetting)},{label:"Frequency",value:detailValue(instructions.frequencySetting)},{label:"Passes",value:detailValue(instructions.passes)},{label:"Marking instructions",value:detailValue(instructions.instructions)},{label:"Assembly title",value:detailValue(instructions.assemblyTitle)},{label:"Assembly instructions",value:detailValue(instructions.assemblyInstructions)},{label:"Worker note",value:detailValue(instructions.workerNote)}]},
  {title:"Order Information",fields:[{label:"Ordered On",value:order?.importedAt?.toLocaleString()},{label:"ORDER ITEM ID",value:order?.orderItemId},{label:"Order Id",value:order?.orderNo},{label:"Shipment ID",value:order?.shipmentId},{label:"Order State",value:order?.status},{label:"FSN",value:order?.fsn},{label:"SKU",value:order?.sku},{label:"Product",value:order?.productDescription},{label:"Tracking ID",value:order?.trackingId},{label:"Quantity",value:order?.qty},...(isOwner?[{label:"Buyer name",value:null,sensitive:true},{label:"Ship to name",value:null,sensitive:true},{label:"City",value:order?.city,sensitive:true},{label:"State",value:order?.state,sensitive:true},{label:"PIN Code",value:null,sensitive:true}]:[])]},
  {title:"Attachments",fields:[{label:"Attachment name",value:null},{label:"Attachment type",value:null},{label:"File status",value:null}]},
  {title:"Problems",fields:[{label:"Open problems",value:card.problemCount||null},{label:"Problem reason",value:first?.problemReason}]},
  {title:"History",fields:[{label:"History records",value:details.historyTotal},{label:"Oldest waiting",value:new Date(card.oldestWaitingAt).toLocaleString()}]}
 ];
 const title=source==="ORDER"&&stage==="PACK"?`Package ${card.trackingId??card.reference}`:card.orderItemId?`Order Item ${card.orderItemId}`:card.consignmentLineId?`Consignment line ${card.consignmentLineId.slice(-8)}`:`${card.sellerSku} details`;
 return <AppShell><PageHeader eyebrow={(source==="ORDER"?"Customer Order":"Consignment")+" / "+stage} title={title} description="Complete structured operational details with role-gated sensitive fields."/><Link href={`/work/${stage.toLowerCase()}?source=${source}`} className="mb-4 inline-flex min-h-11 items-center font-black text-berry">← Back to {stage.toLowerCase()}</Link>{query.success?<p className="mb-3 rounded-xl bg-teal-50 p-3 font-bold text-teal-800">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{query.error}</p>:null}{stage==="PACK"?<PackWorkCard card={card} canAct={canAct} canReportProblem={user.role==="OWNER"||user.canReportProblem}/>:<GroupedWorkCard card={card} canAct={canAct}/>}<div className="mt-4"><StructuredDetails sections={sections}/></div>
  {canAct&&stage!=="PACK"&&card.pendingQuantity>1?<Section id="quantity" title="Partial Quantity"><p className="text-sm text-slate-600">Save a partial quantity for this exact work item. Completion and route confirmation remain separate.</p><form action={setGroupedProgressAction} className="mt-3 grid max-w-xl gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="stage" value={stage}/><input type="hidden" name="sourceType" value={source}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="clientRequestId" value={randomUUID()}/><input name="targetQuantity" aria-label="Exact completed quantity" type="number" min={card.completedQuantity+1} max={maxPartial} defaultValue={card.completedQuantity+1} required className="min-h-11 min-w-0 rounded-xl border px-3"/><SubmitButton pendingText="Saving..." variant="secondary">Save Partial Quantity</SubmitButton></form></Section>:null}
  <Section title={`Package / member records (${details.total})`}><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-2">#</th><th className="p-2">Order / line</th><th className="p-2">Shipment / tracking</th><th className="p-2">Quantity</th><th className="p-2">Status</th><th className="p-2">Worker</th></tr></thead><tbody>{tasks.map((task,index)=><tr key={task.id} className="border-b last:border-0"><td className="p-2">{(page-1)*details.pageSize+index+1}</td><td className="p-2 font-bold">{task.order?.orderItemId??task.order?.orderNo??`Consignment row ${task.consignmentLine?.rowNumber??index+1}`}</td><td className="p-2">{task.order?.shipmentId??task.order?.trackingId??task.order?.awb??task.consignmentLine?.fnskuSnapshot??task.consignmentLine?.barcodeSnapshot??"—"}</td><td className="p-2">{task.completedQuantity}/{task.requiredQuantity}</td><td className="p-2">{task.status.replaceAll("_"," ")}</td><td className="p-2">{task.assignedUser?.name??"Unassigned"}</td></tr>)}</tbody></table></div><div className="mt-3 flex justify-between">{page>1?<Link href={`?source=${source}&page=${page-1}&historyPage=${historyPage}`} className="rounded-xl border px-3 py-2 font-bold">Previous</Link>:<span/>}{details.hasMore?<Link href={`?source=${source}&page=${page+1}&historyPage=${historyPage}`} className="rounded-xl border px-3 py-2 font-bold">Next</Link>:null}</div></Section>
  <Section title={`Workflow and assignment history (${details.historyTotal})`}>{history.length?<ol className="space-y-2">{history.map(log=><li key={log.id} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="font-bold">{log.action.replaceAll("_"," ")}</span> by {log.actorUser.name} · {log.createdAt.toLocaleString()}{log.quantityAfter!=null?` · Quantity ${log.quantityAfter}`:""}<span className="block text-xs text-slate-500">Work item {log.taskRef}</span></li>)}</ol>:<p className="text-sm text-slate-600">No worker actions have been recorded yet.</p>}<div className="mt-3 flex justify-between">{historyPage>1?<Link href={`?source=${source}&page=${page}&historyPage=${historyPage-1}`} className="rounded-xl border px-3 py-2 font-bold">Newer history</Link>:<span/>}{details.historyHasMore?<Link href={`?source=${source}&page=${page}&historyPage=${historyPage+1}`} className="rounded-xl border px-3 py-2 font-bold">Older history</Link>:null}</div></Section>
  <Section id="problems" title="Problems"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{card.problemCount?`${card.problemCount} work item(s) need attention.`:"No open problems."}</p>{tasks.filter(task=>task.problemReason).map(task=><p key={task.id} className="mt-1 text-sm text-rose-700">{task.problemReason?.replaceAll("_"," ")}{task.problemResolutionNote?` — ${task.problemResolutionNote}`:""}</p>)}</div><Link href="/work/problems" className="inline-flex min-h-11 items-center rounded-xl border px-4 font-bold text-rose-700">Open problem controls</Link></div></Section>
 </AppShell>;
}
