import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import type { WorkStage } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser,roleHomePath } from "@/lib/auth";
import { hasWorkPermission } from "@/lib/work-permissions";
import { getGroupedWorkDetails,type GroupedWorkSource } from "@/src/lib/workflow/grouped-work";
import { GroupedWorkCard } from "../../../GroupedWorkCard";
import { setGroupedProgressAction } from "../../../stage-actions";

const STAGES=new Set(["PICK","MARK","ASSEMBLE","PACK"]);
export default async function GroupDetailsPage({params,searchParams}:{params:Promise<{stage:string;groupKey:string}>;searchParams:Promise<{source?:string;success?:string;error?:string}>}){const route=await params,query=await searchParams,stage=route.stage.toUpperCase() as WorkStage,source=query.source as GroupedWorkSource;if(!STAGES.has(stage)||!(["ORDER","CONSIGNMENT"] as string[]).includes(source))notFound();const user=await requireUser(),account=await requireAccount(user),permission=stage==="PICK"?"canPick":stage==="MARK"?"canMark":stage==="ASSEMBLE"?"canAssemble":"canPack";if(!hasWorkPermission(user,permission)&&!user.canViewAllWork)redirect(roleHomePath(user.role));let details;try{details=await getGroupedWorkDetails({actorUserId:user.id,accountId:account.id,stage,sourceType:source,groupKey:route.groupKey});}catch{notFound();}const {card,tasks}=details,canAct=hasWorkPermission(user,permission),maxPartial=card.requiredQuantity-1;
 return <AppShell><PageHeader eyebrow={`${source==="ORDER"?"Daily Orders":"Consignments"} / ${stage}`} title={`${card.sellerSku} group`} description="Review every underlying record before applying partial progress or an atomic stage action."/><Link href={`/work/${stage.toLowerCase()}?source=${source}`} className="mb-4 inline-flex min-h-11 items-center font-bold text-berry">← Back to {stage.toLowerCase()}</Link>{query.success?<p className="mb-3 rounded-md bg-teal-50 p-3 font-bold text-teal-800">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-md bg-rose-50 p-3 font-bold text-rose-700">{query.error}</p>:null}<GroupedWorkCard card={card} canAct={canAct}/>
 {canAct&&card.pendingQuantity>1?<section className="mt-4 rounded-md border bg-white p-5"><h2 className="text-lg font-black">Partial group progress</h2><p className="mt-1 text-sm text-slate-600">Set the exact completed quantity for this group. Allocation is deterministic; full completion and routing still require the stage button above.</p><form action={setGroupedProgressAction} className="mt-3 flex max-w-xl flex-col gap-2 sm:flex-row"><input type="hidden" name="stage" value={stage}/><input type="hidden" name="sourceType" value={source}/><input type="hidden" name="groupKey" value={card.groupKey}/><input type="hidden" name="groupVersion" value={card.groupVersion}/><input type="hidden" name="clientRequestId" value={`${card.groupKey}:${card.groupVersion}:partial`}/><input name="targetQuantity" aria-label="Exact group completed quantity" type="number" min={card.completedQuantity+1} max={maxPartial} defaultValue={card.completedQuantity+1} required className="min-h-11 min-w-0 flex-1 rounded-md border px-3"/><SubmitButton pendingText="Saving..." variant="secondary">Save Partial Progress</SubmitButton></form></section>:null}
 <section className="mt-4 rounded-md border bg-white p-5"><h2 className="text-lg font-black">Underlying records ({tasks.length})</h2><div className="mt-3 space-y-3">{tasks.map((task,index)=>{const sourceRecord=task.order??task.consignmentLine;return <article key={task.id} className="grid gap-3 rounded-md border p-3 sm:grid-cols-[4rem_minmax(0,1fr)]"><ProductImage src={String(task.workCardSnapshot.primaryImage??task.order?.imageUrl??task.consignmentLine?.productImageSnapshot??"")||null} alt={String(task.workCardSnapshot.productTitle??card.sellerSku)} size="sm" showBadge={false}/><div><div className="flex flex-wrap gap-2 text-xs font-bold"><span>#{index+1}</span><span>{task.status}</span><span>{task.completedQuantity}/{task.requiredQuantity}</span><span>{task.assignedUser?.name??"Unassigned"}</span></div><p className="mt-1 break-words font-bold">{task.order?.orderNo??task.consignmentLine?.consignmentBatch.externalConsignmentNumber??task.id}</p><p className="text-sm text-slate-600">{task.order?.trackingId??task.order?.awb??task.consignmentLine?.fnskuSnapshot??task.consignmentLine?.barcodeSnapshot??task.consignmentLine?.sellerSkuSnapshot??"No operational identifier"}</p><details className="mt-2 text-sm"><summary className="cursor-pointer font-bold">Instructions and route snapshot</summary><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap rounded bg-slate-950 p-3 text-xs text-white">{JSON.stringify({instructions:task.instructions,route:task.routeSnapshot,identity:sourceRecord?task.workCardSnapshot:{}},null,2)}</pre></details>{task.actionLogs.length?<details className="mt-2 text-sm"><summary className="cursor-pointer font-bold">History ({task.actionLogs.length})</summary><ul className="mt-2 space-y-1">{task.actionLogs.map(log=><li key={log.id}>{log.createdAt.toLocaleString()} — {log.action.replaceAll("_"," ")} — {log.actorUser.name}{log.quantityAfter!=null?` (${log.quantityAfter})`:""}</li>)}</ul></details>:null}</div></article>})}</div></section></AppShell>;
}
