"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAccount, requireUser } from "@/lib/auth";
import { claimOrderAssemblyTask, completeOrderAssemblyTask, reassignOrderAssemblyTask, reportOrderAssemblyProblem, resolveOrderAssemblyProblem, sendOrderToAssembly, skipOrderAssemblyTask } from "@/src/lib/workflow/order-assembly";

function value(form: FormData, name: string, max = 2_000) { return String(form.get(name) ?? "").normalize("NFKC").trim().slice(0, max); }
function returnPath(form: FormData) { const path = value(form, "returnPath", 300); return path.startsWith("/") && !path.startsWith("//") ? path : "/work/assembly"; }
function resultPath(path: string, key: string, message: string) { return `${path}${path.includes("?") ? "&" : "?"}${key}=${encodeURIComponent(message)}`; }
async function run(form: FormData, success: string, mutation: (context: { userId: string; accountId: string }) => Promise<unknown>) { const user = await requireUser(); const account = await requireAccount(user); const path = returnPath(form); let error: string | null = null; try { await mutation({ userId: user.id, accountId: account.id }); } catch (cause) { error = cause instanceof Error ? cause.message : "Assembly action failed."; } revalidatePath("/work/assembly"); revalidatePath("/packing"); revalidatePath("/picker"); redirect(resultPath(path, error ? "assemblyError" : "assemblySuccess", error ?? success)); }

export async function sendOrderToAssemblyAction(form: FormData) { await run(form, "Order sent to assembly.", ({ userId, accountId }) => sendOrderToAssembly({ actorUserId: userId, accountId, orderId: value(form, "orderId", 100), manualTitle: value(form, "manualTitle", 160), manualInstructions: value(form, "manualInstructions", 2_000), manualImageUrl: value(form, "manualImageUrl", 2_048), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function claimOrderAssemblyAction(form: FormData) { await run(form, "Assembly started.", ({ userId, accountId }) => claimOrderAssemblyTask({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function completeOrderAssemblyAction(form: FormData) { await run(form, "Assembly completed. Order is ready for packing.", ({ userId, accountId }) => completeOrderAssemblyTask({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), expectedStatus: value(form, "expectedStatus", 30), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function reportOrderAssemblyProblemAction(form: FormData) { await run(form, "Assembly problem reported.", ({ userId, accountId }) => reportOrderAssemblyProblem({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), expectedStatus: value(form, "expectedStatus", 30), reason: value(form, "reason", 80), note: value(form, "note", 1_000), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function resolveOrderAssemblyProblemAction(form: FormData) { await run(form, "Assembly problem resolved.", ({ userId, accountId }) => resolveOrderAssemblyProblem({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), resolutionNote: value(form, "resolutionNote", 1_000), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function skipOrderAssemblyAction(form: FormData) { await run(form, "Assembly skipped by owner. Order may proceed to packing.", ({ userId, accountId }) => skipOrderAssemblyTask({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), reason: value(form, "reason", 1_000), clientRequestId: value(form, "clientRequestId", 160) })); }
export async function reassignOrderAssemblyAction(form: FormData) { await run(form, "Assembly assignment updated.", ({ userId, accountId }) => reassignOrderAssemblyTask({ actorUserId: userId, accountId, taskId: value(form, "taskId", 100), assignedUserId: value(form, "assignedUserId", 100) || null, clientRequestId: value(form, "clientRequestId", 160) })); }
