import type { User } from "@prisma/client";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import { hasWorkPermission } from "@/lib/work-permissions";
import { ORDER_ASSEMBLY_PROBLEM_CATEGORIES, safeOrderAssemblyMetadata, type OrderAssemblyQueueTask } from "@/src/lib/workflow/order-assembly";
import { claimOrderAssemblyAction, completeOrderAssemblyAction, reassignOrderAssemblyAction, reportOrderAssemblyProblemAction, resolveOrderAssemblyProblemAction, skipOrderAssemblyAction } from "./actions";

export function OrderAssemblyCard({ task, user, workers, returnPath }: { task: OrderAssemblyQueueTask; user: User; workers: Array<{ id: string; name: string }>; returnPath: string }) {
  const order = task.order; if (!order) return null;
  const metadata = safeOrderAssemblyMetadata(task);
  const canAssemble = hasWorkPermission(user, "canAssemble");
  const assignmentAllows = user.role === "OWNER" || !task.assignedUserId || task.assignedUserId === user.id;
  const canProgress = canAssemble && assignmentAllows && ["READY", "IN_PROGRESS"].includes(task.status);
  const token = `${task.id}:${task.updatedAt.toISOString()}:${task.status}`;
  const hidden = (suffix: string) => <><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="expectedStatus" value={task.status}/><input type="hidden" name="clientRequestId" value={`${token}:${suffix}`}/><input type="hidden" name="returnPath" value={returnPath}/></>;
  return <article className="grid min-w-0 gap-4 overflow-hidden rounded-md border bg-white p-4 shadow-sm lg:grid-cols-[7rem_minmax(0,1fr)_1.15fr]">
    <div className="grid gap-2"><ProductImage src={metadata?.productImageSnapshot ?? order.imageUrl} alt={metadata?.productTitleSnapshot ?? order.sku} size="lg" showBadge={false}/>{metadata?.assemblyImageUrl && metadata.assemblyImageUrl !== metadata.productImageSnapshot ? <ProductImage src={metadata.assemblyImageUrl} alt="Assembly guide" size="lg" showBadge={false}/> : null}</div>
    <div className="min-w-0"><div className="flex flex-wrap gap-1"><span className="rounded-full bg-pink-50 px-2 py-1 text-xs font-black text-berry">ORDER ASSEMBLY</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{task.status.replaceAll("_", " ")}</span><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-bold text-teal-800">{metadata?.source === "PROCESS_RULE" ? "Process Rule" : "Manual"}</span></div><p className="mt-2 text-xl font-black">{order.sku}</p><p className="line-clamp-2 text-sm text-slate-600">{metadata?.productTitleSnapshot ?? order.productDescription ?? "Untitled order"}</p><div className="mt-2 grid gap-1 text-xs text-slate-600 sm:grid-cols-2"><p className="break-all"><b>AWB:</b> {order.awb}</p>{order.trackingId ? <p className="break-all"><b>Tracking:</b> {order.trackingId}</p> : null}<p className="break-words"><b>Order:</b> {order.orderNo}</p>{order.shipmentId ? <p className="break-words"><b>Shipment:</b> {order.shipmentId}</p> : null}<p><b>Quantity:</b> {task.requiredQuantity}</p><p><b>Account:</b> {task.account.accountDisplayName ?? task.account.name}</p></div><p className="mt-2 text-xs font-semibold text-slate-500">{task.assignedUser ? `Assigned to ${task.assignedUser.name}` : "Unassigned / claimable"}</p></div>
    <div className="space-y-3"><section className="rounded-md bg-slate-50 p-3"><h3 className="font-black">{metadata?.assemblyTitle ?? "Assembly instructions unavailable"}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{metadata?.assemblyInstructions ?? "Task metadata is malformed. Ask the owner to review this task."}</p></section>
      {task.status === "PROBLEM" ? <div className="rounded-md border border-rose-200 bg-rose-50 p-3 text-sm"><p className="font-black text-rose-800">{task.problemReason?.replaceAll("_", " ")}</p>{task.actionLogs[0]?.note ? <p className="mt-1">{task.actionLogs[0].note}</p> : null}<p className="mt-1 text-xs text-slate-500">Reported by {task.problemReportedBy?.name ?? "Unknown"}</p></div> : null}
      {canProgress && task.status === "READY" && !task.assignedUserId ? <form action={claimOrderAssemblyAction}>{hidden("claim")}<SubmitButton pendingText="Starting...">Start Assembly</SubmitButton></form> : null}
      {canProgress ? <form action={completeOrderAssemblyAction}>{hidden("complete")}<SubmitButton pendingText="Completing..." className="min-h-12 w-full">Assembly Completed</SubmitButton></form> : !canAssemble || !assignmentAllows ? <p className="rounded-md bg-slate-50 p-3 text-sm font-bold text-slate-600">Read-only assembly view</p> : null}
      {canProgress && (user.role === "OWNER" || user.canReportProblem) ? <details className="rounded-md border p-3"><summary className="cursor-pointer font-bold text-rose-700">Report Problem</summary><form action={reportOrderAssemblyProblemAction} className="mt-3 grid gap-2">{hidden("problem")}<select name="reason" className="min-h-11 rounded-md border px-2">{ORDER_ASSEMBLY_PROBLEM_CATEGORIES.map((reason) => <option key={reason} value={reason}>{reason.replaceAll("_", " ")}</option>)}</select><textarea name="note" maxLength={1000} className="min-h-20 rounded-md border p-2" placeholder="Optional details"/><SubmitButton pendingText="Reporting..." variant="secondary">Save problem</SubmitButton></form></details> : null}
      {user.role === "OWNER" ? <details className="rounded-md border border-amber-200 bg-amber-50 p-3"><summary className="cursor-pointer font-bold">Owner controls</summary><div className="mt-3 grid gap-3">{task.status === "PROBLEM" ? <form action={resolveOrderAssemblyProblemAction} className="grid gap-2">{hidden("resolve")}<textarea name="resolutionNote" required maxLength={1000} className="min-h-20 rounded-md border p-2" placeholder="Resolution note"/><SubmitButton pendingText="Resolving...">Resolve problem</SubmitButton></form> : null}<form action={reassignOrderAssemblyAction} className="grid gap-2">{hidden("assign")}<select name="assignedUserId" defaultValue={task.assignedUserId ?? ""} className="min-h-11 rounded-md border px-2"><option value="">Unassigned</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select><SubmitButton pendingText="Assigning..." variant="secondary">Update assignment</SubmitButton></form>{task.status !== "COMPLETED" && task.status !== "SKIPPED" ? <form action={skipOrderAssemblyAction} className="grid gap-2">{hidden("skip")}<textarea name="reason" required maxLength={1000} className="min-h-20 rounded-md border p-2" placeholder="Required skip reason"/><SubmitButton pendingText="Skipping..." variant="secondary">Skip Assembly</SubmitButton></form> : null}</div></details> : null}
    </div>
  </article>;
}
