"use server";
import { redirect } from "next/navigation";
import { requireAccount,requireUser } from "@/lib/auth";
import { findImportJobById,resumeMappedImportJob } from "@/src/lib/import-jobs/store";
import { definitionForImportJob } from "@/src/lib/imports/import-purpose-definitions";
import { saveHeaderProfile } from "@/src/lib/imports/header-profiles";
import { startImportJob } from "@/src/lib/import-jobs/runner";
import { startProductInventoryJob } from "@/src/lib/product-inventory/jobs";
import { resumeMappedConsignmentImport } from "@/src/lib/consignments/resume-mapped-import";

export async function saveImportHeaderMappingAction(form:FormData){const user=await requireUser(["OWNER"]),account=await requireAccount(user),jobId=String(form.get("jobId")??""),job=await findImportJobById(jobId);if(!job||job.accountId!==account.id||job.status!=="NEEDS_MAPPING")redirect("/owner/imports/"+jobId+"?mapping=invalid");const definition=definitionForImportJob(job);if(!definition)redirect("/owner/imports/"+jobId+"?mapping=unsupported");let progress:{headers?:string[]};try{progress=JSON.parse(job.progressJson??"{}") as{headers?:string[]};}catch{progress={};}const headers=progress.headers??[],mapping:Record<string,string>={};for(const field of definition.fields){const source=String(form.get("map_"+field.key)??"").normalize("NFKC").trim();if(source){if(!headers.includes(source))redirect("/owner/imports/"+jobId+"/mapping?error=header");mapping[field.key]=source;}}const required=definition.fields.filter(field=>field.required).map(field=>field.key),optional=definition.fields.filter(field=>!field.required).map(field=>field.key);if(!required.every(field=>mapping[field]))redirect("/owner/imports/"+jobId+"/mapping?error=required");await saveHeaderProfile({actorUserId:user.id,accountId:account.id,marketplace:definition.marketplace,importPurpose:definition.purpose,profileName:String(form.get("profileName")??definition.label).slice(0,160),headers,mapping,requiredFields:required,optionalFields:optional});await resumeMappedImportJob(job.id);if(job.importType.includes("CONSIGNMENT")){const result=await resumeMappedConsignmentImport({jobId:job.id,accountId:account.id,user});redirect(`/owner/consignments/${result.batchId}/review?mapping=saved`);}if(job.importType.endsWith("PRODUCT_INVENTORY"))startProductInventoryJob(job.id);else startImportJob(job.id);redirect("/owner/imports/"+job.id+"?mapping=saved");}
