import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser } from "@/lib/auth";
import { findImportJobById } from "@/src/lib/import-jobs/store";
import { productCatalogRegistry } from "@/src/lib/imports/canonical-field-registry";
import { definitionForImportJob } from "@/src/lib/imports/import-purpose-definitions";
import { parseHeaderMappingProgress } from "@/src/lib/imports/mapping-request";
import { detectCanonicalColumns,encodeSourceColumnRef,sourceColumnLabel,type CanonicalColumnDetection,type SourceColumnRefV2 } from "@/src/lib/imports/source-column-mapping";
import { saveImportHeaderMappingAction } from "./actions";

const normalize=(value:string)=>value.normalize("NFKC").trim().toLocaleLowerCase().replace(/[\s_.\-/\\]+/g," ");
function fallbackDetection(field:{targetHeader:string},columns:SourceColumnRefV2[]){const matches=columns.filter(column=>normalize(column.rawHumanHeader)===normalize(field.targetHeader));return matches.length===1?matches[0]:null;}
function detectionLabel(detection:CanonicalColumnDetection|undefined){if(!detection)return null;if(detection.state==="TECHNICAL_KEY")return"Detected from stable technical key";if(detection.state==="EXACT_HEADER")return"Detected from exact header";if(detection.state==="APPROVED_ALIAS")return"Detected from approved alias";if(detection.state==="AMBIGUOUS")return"Several possible columns; choose one";if(detection.state==="MISSING_REQUIRED")return"Required mapping needs your review";if(detection.state==="MISSING_PREVIOUSLY_MAPPED_OPTIONAL")return"Previously mapped column is missing";return"Not mapped this import";}

export default async function HeaderMappingPage({params,searchParams}:{params:Promise<{jobId:string}>;searchParams:Promise<{error?:string}>}){
 const user=await requireUser(["OWNER"]),account=await requireAccount(user),{jobId}=await params,query=await searchParams,job=await findImportJobById(jobId);if(!job||job.accountId!==account.id||job.marketplace!==account.marketplace||job.status!=="NEEDS_MAPPING")notFound();const definition=definitionForImportJob(job),request=parseHeaderMappingProgress(job.progressJson);if(!definition||!request)notFound();
 const registry=definition.purpose==="PRODUCT_CATALOG"?productCatalogRegistry(definition.marketplace):null,detections=registry?detectCanonicalColumns({registry,sourceColumns:request.sourceColumns}):[],byMappingKey=new Map(detections.map(detection=>[detection.field.mappingKey,detection])),detectedColumns=new Set(detections.flatMap(detection=>detection.sourceColumn?[encodeSourceColumnRef(detection.sourceColumn)]:[])),ignoredColumns=Math.max(0,request.sourceColumns.length-detectedColumns.size);
 return <AppShell><PageHeader eyebrow={`Owner-only adaptive import / ${definition.label}`} title="Map File Columns" description="Map useful canonical fields to exact source-column positions. This versioned profile will be reused for matching files, including files with repeated header names."/>{query.error?<p className="mb-4 rounded-md bg-rose-50 p-3 font-bold text-rose-700">The mapping was not saved. Map every required field to a valid detected source column.</p>:null}<form action={saveImportHeaderMappingAction} className="rounded-md border bg-white p-5 shadow-sm"><input type="hidden" name="jobId" value={job.id}/><label className="block text-sm font-bold">Profile name<input name="profileName" required defaultValue={`${definition.label} — ${job.fileName}`} className="mt-1 min-h-11 w-full rounded-md border px-3"/></label><div className="mt-4 grid grid-cols-2 gap-3 rounded-md bg-slate-50 p-3 text-sm sm:grid-cols-4"><div><span className="block text-slate-500">Canonical fields</span><strong>{definition.fields.length}</strong></div><div><span className="block text-slate-500">Initially detected</span><strong>{detectedColumns.size}</strong></div><div><span className="block text-slate-500">Source columns</span><strong>{request.sourceColumns.length}</strong></div><div><span className="block text-slate-500">Initially ignored</span><strong>{ignoredColumns}</strong></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{definition.fields.map(field=>{const detection=byMappingKey.get(field.key),detected=detection?detection.sourceColumn:fallbackDetection(field,request.sourceColumns);return <label key={field.key} className="min-w-0 text-sm font-bold">{field.label}{field.required?" *":""}<select name={`map_${field.key}`} required={field.required} defaultValue={detected?encodeSourceColumnRef(detected):""} className="mt-1 min-h-11 w-full min-w-0 max-w-full rounded-md border bg-white px-3"><option value="">{field.required?"Choose a source column":"Not mapped this import"}</option>{request.sourceColumns.map(column=>{const encoded=encodeSourceColumnRef(column);return <option key={encoded} value={encoded}>{sourceColumnLabel(column)}</option>;})}</select>{registry?<span className="mt-1 block font-normal text-slate-500">{detectionLabel(detection)}</span>:null}</label>;})}</div><p className="mt-4 text-sm text-slate-600">Optional fields may stay unmapped; existing stored values will be preserved. The retained upload will retry automatically, so no re-upload is required.</p><SubmitButton pendingText="Saving and retrying..." className="mt-4">Save Profile and Retry</SubmitButton></form></AppShell>;
}
