import { notFound } from "next/navigation";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount,requireUser } from "@/lib/auth";
import { findImportJobById } from "@/src/lib/import-jobs/store";
import { definitionForImportJob } from "@/src/lib/imports/import-purpose-definitions";
import { saveImportHeaderMappingAction } from "./actions";

export default async function HeaderMappingPage({params,searchParams}:{params:Promise<{jobId:string}>;searchParams:Promise<{error?:string}>}){const user=await requireUser(["OWNER"]),account=await requireAccount(user),{jobId}=await params,query=await searchParams,job=await findImportJobById(jobId);if(!job||job.accountId!==account.id||job.status!=="NEEDS_MAPPING")notFound();const definition=definitionForImportJob(job);if(!definition)notFound();let headers:string[]=[];try{const progress=JSON.parse(job.progressJson??"{}") as{headers?:unknown};if(Array.isArray(progress.headers))headers=progress.headers.filter((item):item is string=>typeof item==="string").slice(0,500);}catch{}if(!headers.length)notFound();return <AppShell><PageHeader eyebrow={"Owner-only adaptive import / "+definition.label} title="Map File Headers" description="Map each required canonical field once. The fingerprinted profile will be reused for future files with the same normalized headers."/>{query.error?<p className="mb-4 rounded-md bg-rose-50 p-3 font-bold text-rose-700">Map every required field to one of the detected headers.</p>:null}<form action={saveImportHeaderMappingAction} className="rounded-md border bg-white p-5 shadow-sm"><input type="hidden" name="jobId" value={job.id}/><label className="block text-sm font-bold">Profile name<input name="profileName" required defaultValue={definition.label+" — "+job.fileName} className="mt-1 min-h-11 w-full rounded-md border px-3"/></label><div className="mt-5 grid gap-3 sm:grid-cols-2">{definition.fields.map(field=><label key={field.key} className="text-sm font-bold">{field.label}{field.required?" *":""}<select name={"map_"+field.key} required={field.required} defaultValue="" className="mt-1 min-h-11 w-full rounded-md border bg-white px-3"><option value="">{field.required?"Choose detected header":"Not mapped"}</option>{headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div><p className="mt-4 text-sm text-slate-600">The retained upload will retry automatically; no re-upload is required.</p><SubmitButton pendingText="Saving and retrying..." className="mt-4">Save Profile and Retry</SubmitButton></form></AppShell>;}
