"use server";
import { redirect } from "next/navigation";
import { requireAccount,requireUser } from "@/lib/auth";
import { applyUniversalCandidateAction,type UniversalCandidateAction } from "@/src/lib/workflow/universal-actions";

const value=(form:FormData,name:string,max=180)=>String(form.get(name)??"").normalize("NFKC").trim().slice(0,max);
export async function universalCandidateAction(form:FormData){const user=await requireUser(),selectedAccount=await requireAccount(user),code=value(form,"code"),intent=value(form,"intent",10)||"ANY",source=value(form,"source",30)||"ALL",accountFilter=value(form,"accountFilter",80),returnPath=value(form,"returnPath",40)==="/packing"?"/packing":"/work/scan";let error:string|null=null;
 try{const submittedAccountId=value(form,"accountId",80);if(submittedAccountId!==selectedAccount.id)throw new Error("The selected seller account changed. Refresh before acting.");await applyUniversalCandidateAction({actorUserId:user.id,accountId:selectedAccount.id,sourceId:value(form,"sourceId",80),action:value(form,"action",30) as UniversalCandidateAction,expectedQuantity:Number(value(form,"expectedQuantity",20)),expectedStatus:value(form,"expectedStatus",30),clientRequestId:value(form,"clientRequestId",160),route:value(form,"route",30),routeReason:value(form,"routeReason",80)||undefined,routeOtherReason:value(form,"routeOtherReason",240)||undefined,workerNote:value(form,"workerNote",240)||undefined,confirmMissingInstructions:value(form,"confirmMissingInstructions",5)==="1",manualTitle:value(form,"manualTitle",160),manualInstructions:value(form,"manualInstructions",2000),manualImageUrl:value(form,"manualImageUrl",2048)});}catch(cause){error=cause instanceof Error?cause.message:"Action failed.";}
 const params=new URLSearchParams({intent,source});if(accountFilter)params.set("accountId",accountFilter);if(error)params.set("q",code);params.set(error?"scanError":"scanSuccess",error??"Action completed. Scan the next item.");redirect(`${returnPath}?${params}`);
}
