import Link from "next/link";
import { notFound } from "next/navigation";
import type { Prisma } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { SubmitButton } from "@/components/SubmitButton";
import { requireAccount } from "@/lib/auth";
import { requireConsignmentAccess } from "@/lib/consignment-auth";
import { prisma } from "@/lib/prisma";
import { activateConsignmentAction, bulkReadyMadeAction, clearConsignmentListingAction, selectConsignmentListingAction, setConsignmentRouteAction } from "../../actions";

const PAGE_SIZE = 50;
function routeLabel(route: string | null) { return route === "PICK_PACK" ? "Default processing: Direct to Pack" : route === "PICK_MARK_PACK" ? "Default processing: Marking" : route === "PICK_ASSEMBLE_PACK" ? "Default processing: Assembly" : route === "PICK_MARK_ASSEMBLE_PACK" ? "Default processing: Marking + Assembly" : "No saved default — Direct to Pack preselected"; }

export default async function ConsignmentReviewPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<{ page?: string; filter?: string; error?: string; updated?: string; lineId?: string; listingQ?: string }> }) {
  const user = await requireConsignmentAccess("view"); const account = await requireAccount(user); const { batchId } = await params; const query = await searchParams; const page = Math.max(1, Number(query.page) || 1); const filter = query.filter ?? "all";
  const batch = await prisma.consignmentBatch.findFirst({ where: { id: batchId, accountId: account.id }, include: { _count: { select: { issues: true } } } }); if (!batch) notFound();
  const filterWhere: Prisma.ConsignmentLineWhereInput = filter === "missing-listing" ? { matchStatus: "NOT_FOUND" } : filter === "multiple" ? { matchStatus: "EXACT_MULTIPLE" } : filter === "conflict" ? { matchStatus: "IDENTIFIER_CONFLICT" } : filter === "missing-route" ? { processRoute: null } : filter === "ready-made" ? { processRoute: "PICK_PACK" } : filter === "marking" ? { processRoute: "PICK_MARK_PACK" } : filter === "missing-marking-file" ? { processRoute: "PICK_MARK_PACK", OR: [{ markingAssetId: null }, { markingAsset: { active: false } }, { markingAsset: { AND: [{ masterDesignId: null }, { instructions: null }] } }] } : {};
  const where = { consignmentBatchId: batch.id, accountId: account.id, ...filterWhere };
  const [lines, total, warningCount, errorCount, missingRouteCount, missingMarkingSetupCount, matchCounts, missingTitleCount, missingImageCount] = await Promise.all([
    prisma.consignmentLine.findMany({ where, orderBy: { rowNumber: "asc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE, include: { marketplaceListing: { include: { markingAssetLinks: { where: { active: true, accountId: account.id }, include: { markingAsset: true } } } }, markingAsset: true } }),
    prisma.consignmentLine.count({ where }),
    prisma.consignmentImportIssue.count({ where: { consignmentBatchId: batch.id, severity: "WARNING", resolved: false } }),
    prisma.consignmentImportIssue.count({ where: { consignmentBatchId: batch.id, severity: "ERROR", resolved: false } }),
    prisma.consignmentLine.count({ where: { consignmentBatchId: batch.id, processRoute: null } }),
    prisma.consignmentLine.count({ where: { consignmentBatchId: batch.id, processRoute: "PICK_MARK_PACK", OR: [{ markingAssetId: null }, { markingAsset: { active: false } }, { markingAsset: { AND: [{ masterDesignId: null }, { instructions: null }] } }] } }),
    prisma.consignmentLine.groupBy({ by: ["matchStatus"], where: { consignmentBatchId: batch.id }, _count: { _all: true } }),
    prisma.consignmentImportIssue.count({ where: { consignmentBatchId: batch.id, issueType: "MISSING_TITLE", resolved: false } }),
    prisma.consignmentImportIssue.count({ where: { consignmentBatchId: batch.id, issueType: "MARKING_IMAGE_MISSING", resolved: false } })
  ]);
  const candidates = query.lineId && query.listingQ?.trim() ? await prisma.marketplaceListing.findMany({ where: { accountId: account.id, marketplace: batch.marketplace, OR: [{ sellerSkuId: { contains: query.listingQ.trim() } }, { sku: { contains: query.listingQ.trim() } }, { fsn: { contains: query.listingQ.trim() } }, { productTitle: { contains: query.listingQ.trim() } }, { identifiers: { some: { rawValue: { contains: query.listingQ.trim() }, active: true } } }] }, take: 12, select: { id: true, sellerSkuId: true, fsn: true, productTitle: true, mainImageUrl: true } }) : [];
  const candidateIssues = await prisma.consignmentImportIssue.findMany({ where: { consignmentBatchId: batch.id, consignmentLineId: { in: lines.map((line) => line.id) }, issueType: { in: ["EXACT_MULTIPLE", "IDENTIFIER_CONFLICT"] }, resolved: false }, select: { consignmentLineId: true, safeDataJson: true } });
  const candidateIdsByLine = new Map(candidateIssues.map((issue) => { try { const parsed = JSON.parse(issue.safeDataJson ?? "{}"); return [issue.consignmentLineId, Array.isArray(parsed.listingIds) ? parsed.listingIds.filter((id: unknown): id is string => typeof id === "string") : []] as const; } catch { return [issue.consignmentLineId, []] as const; } }));
  const proposedCandidates = await prisma.marketplaceListing.findMany({ where: { accountId: account.id, id: { in: [...new Set([...candidateIdsByLine.values()].flat())] } }, select: { id: true, sellerSkuId: true, fsn: true, productTitle: true, mainImageUrl: true } });
  const canManage = user.role === "OWNER" || user.canManageConsignments;
  const matchCount=new Map(matchCounts.map((item)=>[item.matchStatus,item._count._all]));
  const summaries = [["Source rows",batch.totalSourceRows],["Valid lines",batch.totalValidLines],["Required qty",batch.totalRequiredQuantity],["Exact FNSKU",matchCount.get("EXACT_FNSKU")??0],["Exact SKU",matchCount.get("EXACT_SKU")??0],["Exact ASIN",matchCount.get("EXACT_ASIN")??0],["Exact external ID",matchCount.get("EXACT_EXTERNAL_ID")??0],["Exact barcode",matchCount.get("EXACT_BARCODE")??0],["Not found",batch.unmatchedLines],["Ambiguous",batch.ambiguousLines],["Conflicts",batch.conflictLines],["Ready-made",batch.readyMadeLines],["Marking",batch.markingLines],["Missing title",missingTitleCount],["Missing image",missingImageCount],["Missing route",missingRouteCount],["Missing marking setup",missingMarkingSetupCount],["Warnings",warningCount],["Blocking errors",errorCount]];
  return <AppShell><PageHeader eyebrow="Activation preview" title={batch.displayName} description="Review listing matches and process routes. Tasks are created only by Activate Consignment."><Link href={`/owner/consignments/${batch.id}/issues`} className="rounded-md border px-4 py-2 text-sm font-bold">Issues</Link></PageHeader>
    {query.error ? <div className="mb-4 rounded-md bg-rose-50 p-3 text-sm font-bold text-rose-700">{query.error}</div> : null}{query.updated ? <div className="mb-4 rounded-md bg-teal-50 p-3 text-sm font-bold text-teal-800">Review line updated.</div> : null}
    <section className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">{summaries.map(([label,value]) => <div key={label} className="rounded-md border bg-white p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-lg font-black">{value}</p></div>)}</section>
    <div className="sticky top-20 z-20 mt-4 rounded-md border bg-white/95 p-3 shadow-sm backdrop-blur"><div className="flex gap-2 overflow-x-auto pb-1">{[["all","All"],["missing-listing","Missing listing"],["multiple","Multiple"],["conflict","Conflict"],["missing-route","Missing route"],["ready-made","Ready-made"],["marking","Marking"],["missing-marking-file","Missing marking setup"]].map(([key,label]) => <Link key={key} href={`?filter=${key}`} className={`shrink-0 rounded-full px-3 py-2 text-sm font-bold ${filter===key?"bg-slate-950 text-white":"bg-slate-100"}`}>{label}</Link>)}<Link href={`/owner/consignments/${batch.id}/issues?type=INVALID_QUANTITY`} className="shrink-0 rounded-full bg-slate-100 px-3 py-2 text-sm font-bold">Invalid quantity</Link></div>{canManage ? <form action={bulkReadyMadeAction} className="mt-2"><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Applying...">Apply ready-made to all matched missing-route lines</SubmitButton></form> : null}</div>
    <section className="mt-4 space-y-3">{lines.map((line) => { const listing=line.marketplaceListing; const assets=listing?.markingAssetLinks.map((link)=>link.markingAsset) ?? []; const markingReady=line.processRoute!=="PICK_MARK_PACK" || Boolean(line.markingAsset?.active && (line.markingAsset.masterDesignId || line.markingAsset.instructions)); return <article key={line.id} className="grid gap-4 rounded-md border bg-white p-4 shadow-sm lg:grid-cols-[7rem_1fr_1.4fr]">
      <ProductImage src={listing?.mainImageUrl} alt={listing?.productTitle ?? line.productNameSource ?? "Consignment product"} size="lg" showBadge={false}/>
      <div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">Row {line.rowNumber}</span><span className={`rounded-full px-2 py-1 text-xs font-black ${line.matchStatus.startsWith("EXACT_")&&line.matchStatus!=="EXACT_MULTIPLE"?"bg-teal-50 text-teal-800":"bg-rose-50 text-rose-700"}`}>{line.matchStatus.replaceAll("_"," ")}</span></div><p className="mt-2 text-lg font-black">{listing?.sellerSkuId ?? line.sellerSkuSource ?? "No SKU"}</p><p className="line-clamp-2 text-sm text-slate-600">{listing?.productTitle ?? line.productNameSource ?? "Untitled"}</p><p className="mt-1 text-sm font-bold">Required work: {line.requiredQuantity}</p>{batch.marketplace==="AMAZON"?<p className="mt-1 break-words text-xs text-slate-500">FNSKU {line.fnskuSource??"missing"} / ASIN {line.asinSource??"missing"}</p>:<p className="mt-1 text-xs text-slate-500">FSN {listing?.fsn ?? line.fsnSource ?? "missing"} / Listing {listing?.listingId ?? "not selected"}</p>}<p className="mt-2 text-xs font-semibold">{routeLabel(line.processRoute)}</p>{!markingReady ? <p className="mt-1 text-xs font-bold text-rose-700">Active marking asset with instructions or Master Design ID required</p> : null}</div>
      <div className="space-y-3">{canManage ? <><form action={setConsignmentRouteAction} className="grid gap-2 sm:grid-cols-2"><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="lineId" value={line.id}/><select name="route" defaultValue={line.processRoute==="PICK_MARK_PACK"?"PICK_MARK_PACK":"PICK_PACK"} className="min-h-11 rounded-md border px-2"><option value="PICK_PACK">Ready-made: Pick &gt; Pack</option><option value="PICK_MARK_PACK">Marking: Pick &gt; Mark &gt; Pack</option></select><select name="markingAssetId" defaultValue={line.markingAssetId ?? ""} className="min-h-11 rounded-md border px-2"><option value="">No marking asset</option>{assets.map((asset)=><option key={asset.id} value={asset.id}>{asset.masterDesignId ?? asset.name}</option>)}</select><div className="sm:col-span-2"><SubmitButton pendingText="Saving route...">Save route</SubmitButton></div></form>
      <form className="grid gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="filter" value={filter}/><input type="hidden" name="lineId" value={line.id}/><input name="listingQ" defaultValue={query.lineId===line.id?query.listingQ:""} placeholder="Manual account listing search" className="min-h-11 rounded-md border px-3"/><button className="min-h-11 rounded-md border px-3 font-bold">Search</button></form>{query.lineId===line.id && candidates.length ? <div className="grid gap-2">{candidates.map((candidate)=><form key={candidate.id} action={selectConsignmentListingAction} className="flex items-center gap-2 rounded-md border p-2"><ProductImage src={candidate.mainImageUrl} alt={candidate.productTitle ?? candidate.sellerSkuId} size="sm" showBadge={false}/><div className="min-w-0 flex-1"><p className="truncate font-bold">{candidate.sellerSkuId}</p><p className="truncate text-xs text-slate-500">{candidate.fsn ?? "No FSN"} / {candidate.productTitle ?? "Untitled"}</p></div><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="lineId" value={line.id}/><input type="hidden" name="listingId" value={candidate.id}/><SubmitButton pendingText="Selecting...">Choose</SubmitButton></form>)}</div> : null}
      {(candidateIdsByLine.get(line.id)?.length ?? 0) > 0 ? <div className="grid gap-2 rounded-md bg-amber-50 p-2"><p className="text-xs font-black text-amber-900">Exact candidates require your choice</p>{proposedCandidates.filter((candidate) => candidateIdsByLine.get(line.id)?.includes(candidate.id)).map((candidate)=><form key={candidate.id} action={selectConsignmentListingAction} className="flex items-center gap-2 rounded-md bg-white p-2"><ProductImage src={candidate.mainImageUrl} alt={candidate.productTitle ?? candidate.sellerSkuId} size="sm" showBadge={false}/><div className="min-w-0 flex-1"><p className="truncate font-bold">{candidate.sellerSkuId}</p><p className="truncate text-xs text-slate-500">{candidate.fsn ?? "No FSN"} / {candidate.productTitle ?? "Untitled"}</p></div><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="lineId" value={line.id}/><input type="hidden" name="listingId" value={candidate.id}/><SubmitButton pendingText="Selecting...">Choose</SubmitButton></form>)}</div> : null}
      {listing ? <form action={clearConsignmentListingAction}><input type="hidden" name="batchId" value={batch.id}/><input type="hidden" name="lineId" value={line.id}/><SubmitButton pendingText="Clearing..." variant="secondary">Clear match</SubmitButton></form> : null}</> : <p className="text-sm text-slate-600">View only. A consignment manager must resolve this line.</p>}</div>
    </article>;})}</section>
    {!lines.length ? <div className="mt-4 rounded-md border border-dashed bg-white p-6 text-center font-bold">No lines match this filter.</div> : null}
    <div className="mt-5 flex justify-between text-sm font-bold"><span>Showing {(page-1)*PAGE_SIZE+(total?1:0)}-{Math.min(page*PAGE_SIZE,total)} of {total}</span><div className="flex gap-2">{page>1?<Link href={`?page=${page-1}&filter=${filter}`} className="rounded-md border px-3 py-2">Previous</Link>:null}{page*PAGE_SIZE<total?<Link href={`?page=${page+1}&filter=${filter}`} className="rounded-md border px-3 py-2">Next</Link>:null}</div></div>
    {canManage ? <div className="sticky bottom-16 mt-6 rounded-md border border-berry bg-white p-3 shadow-xl sm:bottom-3"><form action={activateConsignmentAction} className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{warningCount || missingRouteCount ? "Activate with warnings" : "Activate Consignment"}</p><p className="text-xs text-slate-600">{batch.status.replaceAll("_"," ")} / missing defaults, titles and images do not block activation</p></div><input type="hidden" name="batchId" value={batch.id}/><SubmitButton pendingText="Activating safely...">{warningCount || missingRouteCount ? "Activate with warnings" : "Activate Consignment"}</SubmitButton></form></div> : null}
  </AppShell>;
}
