import { performance } from "node:perf_hooks";
import { createTempWorkflowDb } from "../tests/temp-workflow-db";
import { getGroupedWork,getGroupedWorkDetails,getSmartStageSummary } from "../src/lib/workflow/grouped-work";
import { resolveOrderShipmentWorkflowPrerequisites } from "../src/lib/workflow/workflow-prerequisites";
(BigInt.prototype as unknown as {toJSON:()=>number}).toJSON=function(){return Number(this);};
const {db,cleanup}=createTempWorkflowDb("grouped-work-performance"),count=30000,rounds=20;
try{
 await db.account.create({data:{id:"perf",name:"Performance",code:"PERF",marketplace:"FLIPKART"}});await db.user.create({data:{id:"worker",username:"perf-worker",passwordHash:"x",name:"Performance worker",role:"PICKER",accountId:"perf",canPick:true}});await db.uploadBatch.create({data:{id:"batch",accountId:"perf",fileName:"synthetic.csv"}});
 for(let start=0;start<count;start+=500){const end=Math.min(start+500,count);await db.order.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:"o"+index,accountId:"perf",batchId:"batch",marketplace:"FLIPKART",awb:"A"+index,trackingId:"T"+index,sku:"SKU-"+(index%500),qty:1,orderNo:"O"+index};})});await db.workTask.createMany({data:Array.from({length:end-start},(_,offset)=>{const index=start+offset;return{id:"t"+index,accountId:"perf",sourceType:"ORDER" as const,orderId:"o"+index,stage:"PICK" as const,sequenceNumber:1,requiredQuantity:1,status:"READY" as const,workCardSnapshotJson:JSON.stringify({sellerSku:"SKU-"+(index%500),productTitle:"Product "+(index%500)})};})});}
 const coldStarted=performance.now(),first=await getGroupedWork({actorUserId:"worker",accountId:"perf",stage:"PICK",sourceType:"ORDER"},db),coldMs=performance.now()-coldStarted,timings:number[]=[];for(let index=0;index<rounds;index++){const started=performance.now();await getGroupedWork({actorUserId:"worker",accountId:"perf",stage:"PICK",sourceType:"ORDER"},db);timings.push(performance.now()-started);}timings.sort((a,b)=>a-b);const percentile=(fraction:number)=>timings[Math.min(timings.length-1,Math.ceil(timings.length*fraction)-1)];
 const page20=await getGroupedWork({actorUserId:"worker",accountId:"perf",stage:"PICK",sourceType:"ORDER",page:20},db),summary=await getSmartStageSummary({actorUserId:"worker",accountId:"perf",stage:"PICK"},db),details=await getGroupedWorkDetails({actorUserId:"worker",accountId:"perf",stage:"PICK",sourceType:"ORDER",groupKey:first.cards[0].groupKey},db),prerequisiteStarted=performance.now();await resolveOrderShipmentWorkflowPrerequisites({accountId:"perf",orderIds:Array.from({length:500},(_,index)=>"o"+index)},db);const prerequisiteMs=performance.now()-prerequisiteStarted;
 const plans=await db.$queryRawUnsafe<Array<Record<string,unknown>>>('EXPLAIN QUERY PLAN SELECT "groupKey" FROM "WorkGroupProjection" WHERE "accountId"=? AND "stage"=? AND "sourceType"=? ORDER BY "oldestWaitingAt" LIMIT 25',"perf","PICK","ORDER"),receiptPlan=await db.$queryRawUnsafe<Array<Record<string,unknown>>>('EXPLAIN QUERY PLAN SELECT "resultJson" FROM "WorkflowActionReceipt" WHERE "accountId"=? AND "actorUserId"=? AND "requestKind"=? AND "clientRequestId"=?',"perf","worker","GROUP_COMPLETE","request");
 console.log(JSON.stringify({activeWorkItems:count,expectedGroups:500,actualGroups:summary.ORDER.cardCount,expectedQuantity:count,actualQuantity:summary.ORDER.requiredQuantity,firstPageRows:first.cards.length,page20Rows:page20.cards.length,detailsMemberRows:details.tasks.length,coldProjectionMs:Number(coldMs.toFixed(1)),p50Ms:Number(percentile(.5).toFixed(1)),p95Ms:Number(percentile(.95).toFixed(1)),workflowPrerequisites500Ms:Number(prerequisiteMs.toFixed(1)),heapUsedMb:Number((process.memoryUsage().heapUsed/1024/1024).toFixed(1)),queryPlan:plans,receiptQueryPlan:receiptPlan},null,2));
}finally{await cleanup();}
