import type { ConsignmentCatalogSnapshotV1 } from "./types";

function clean(value: unknown, max: number) { const text=String(value??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").trim(); return text ? text.slice(0,max) : undefined; }
export function safeAmazonImageUrl(value: unknown) { const text=clean(value,2048); if(!text)return undefined; try{const url=new URL(text);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)return undefined;return url.toString();}catch{return undefined;} }
function images(values: unknown[]) { return [...new Set(values.map(safeAmazonImageUrl).filter((value):value is string=>Boolean(value)))].slice(0,10); }

export function buildConsignmentCatalogSnapshot(input: Omit<ConsignmentCatalogSnapshotV1,"version">): ConsignmentCatalogSnapshotV1 {
  const imageUrls=images(input.imageUrls??[]); const mainImageUrl=safeAmazonImageUrl(input.mainImageUrl);
  const identifiers=Object.fromEntries(Object.entries(input.identifiers).flatMap(([key,value])=>{const safe=clean(value,key==="asin"?20:key==="fnsku"?100:200);return safe?[[key,safe]]:[];})) as ConsignmentCatalogSnapshotV1["identifiers"];
  return {version:1,marketplace:input.marketplace,title:clean(input.title,500),brand:clean(input.brand,160),category:clean(input.category,200),subCategory:clean(input.subCategory,200),material:clean(input.material,200),color:clean(input.color,120),size:clean(input.size,120),modelNumber:clean(input.modelNumber,160),description:clean(input.description,4000),bulletPoints:(input.bulletPoints??[]).map((item)=>clean(item,500)).filter((item):item is string=>Boolean(item)).slice(0,10),mainImageUrl,imageUrls:images([mainImageUrl,...imageUrls]),identifiers,provenance:{shipmentFileId:clean(input.provenance.shipmentFileId,100),listingFileId:clean(input.provenance.listingFileId,100),catalogFileIds:(input.provenance.catalogFileIds??[]).map((id)=>clean(id,100)).filter((id):id is string=>Boolean(id)).slice(0,20)}};
}

export function parseConsignmentCatalogSnapshot(value:string|null|undefined):ConsignmentCatalogSnapshotV1|null{if(!value||value.length>30000)return null;try{const parsed=JSON.parse(value) as Partial<ConsignmentCatalogSnapshotV1>;if(parsed.version!==1||(parsed.marketplace!=="AMAZON"&&parsed.marketplace!=="FLIPKART")||!parsed.identifiers||!parsed.provenance)return null;return buildConsignmentCatalogSnapshot({marketplace:parsed.marketplace,title:parsed.title,brand:parsed.brand,category:parsed.category,subCategory:parsed.subCategory,material:parsed.material,color:parsed.color,size:parsed.size,modelNumber:parsed.modelNumber,description:parsed.description,bulletPoints:parsed.bulletPoints,mainImageUrl:parsed.mainImageUrl,imageUrls:parsed.imageUrls,identifiers:parsed.identifiers,provenance:parsed.provenance});}catch{return null;}}
