import { createHash, randomUUID } from "node:crypto";
import type { IdentifierType, Prisma, User } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { recordAuditLog } from "@/lib/audit";
import type { RequestMeta } from "@/lib/network";
import { normalizeListingIdentifier } from "@/src/lib/marking/identifiers";
import { sanitizeConsignmentFileName, storeConsignmentBuffer, validateConsignmentUpload } from "../storage";
import { inspectAmazonConsignmentZip } from "./archive";
import { amazonSourceRows, parseAmazonBuffer } from "./parser";
import { buildConsignmentCatalogSnapshot } from "./catalog-snapshot";
import { matchAmazonConsignmentRows } from "./matching";
import type { AmazonConsignmentSourceRow, AmazonParsedFile } from "./types";

const CHUNK=300;
const groups=<T>(values:T[],size=CHUNK)=>Array.from({length:Math.ceil(values.length/size)},(_,index)=>values.slice(index*size,(index+1)*size));
const safe=(value:string,max:number)=>value.normalize("NFKC").trim().slice(0,max);
function number(value:string){const normalized=value.normalize("NFKC").trim().toUpperCase();if(!normalized||normalized.length>100||!/^[A-Z0-9._/-]+$/.test(normalized))throw new Error("Enter a valid Amazon shipment/consignment number.");return normalized;}
type Part={name:string;entryName?:string;data:Buffer;parsed:AmazonParsedFile};
type StoredPart=Part&{fileId:string;fileType:Prisma.ConsignmentImportFileCreateInput["fileType"]};
type Warning={issueType:string;message:string;rowNumber?:number;safeDataJson?:string};

function identifierValues(row:AmazonConsignmentSourceRow):Array<[IdentifierType,string|null]> { return [["SELLER_SKU",row.sellerSku],["FNSKU",row.fnsku],["ASIN",row.asin],["EXTERNAL_ID",row.externalId],["EAN",row.ean],["UPC",row.upc],["GTIN",row.gtin],["MODEL_NUMBER",row.modelNumber]]; }
function listingScalars(row:AmazonConsignmentSourceRow):Partial<Prisma.MarketplaceListingCreateManyInput> { const images=row.imageUrls.slice(0,10);return{...(row.productTitle?{productTitle:row.productTitle,liveTitle:row.productTitle}:{}),...(row.brand?{liveBrand:row.brand}:{}),...(row.category?{liveCategory:row.category}:{}),...(row.subCategory?{subCategory:row.subCategory}:{}),...(row.description?{description:row.description}:{}),...(row.bulletPoints.length?{productHighlights:row.bulletPoints.join("\n")}:{}),...(row.listingStatus?{listingStatus:row.listingStatus}:{}),...(row.mainImageUrl?{mainImageUrl:row.mainImageUrl}:{}),...Object.fromEntries(images.map((url,index)=>[`imageUrl${index+1}`,url])),lastImportedAt:new Date()}; }
function listingUpdate(row:AmazonConsignmentSourceRow):Prisma.MarketplaceListingUpdateInput{return listingScalars(row);}

async function syncAmazonListings(accountId:string,parts:StoredPart[]){
 const warnings:Warning[]=[];const listingRows=parts.flatMap((part)=>part.parsed.tables.filter((table)=>table.profile==="ALL_LISTINGS").flatMap((table)=>table.rows.map((row)=>({row,part}))));
 const catalogRows=parts.flatMap((part)=>part.parsed.tables.filter((table)=>table.profile==="CATEGORY_CATALOG"||table.profile==="PRODUCT_CATALOG").flatMap((table)=>table.rows.map((row)=>({row,part}))));
 const uniqueListingRows=[...new Map(listingRows.filter(({row})=>row.sellerSku).map((item)=>[item.row.sellerSku!.toUpperCase(),item])).values()];
 const sellerSkus=uniqueListingRows.map(({row})=>row.sellerSku!);const existing=[] as Awaited<ReturnType<typeof prisma.marketplaceListing.findMany>>;
 for(const chunk of groups(sellerSkus))existing.push(...await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON",sellerSkuId:{in:chunk}}}));
 const existingKeys=new Set(existing.map((listing)=>listing.sellerSkuId.toUpperCase()));const missing=uniqueListingRows.filter(({row})=>!existingKeys.has(row.sellerSku!.toUpperCase()));
  for(const chunk of groups(missing))await prisma.marketplaceListing.createMany({data:chunk.map(({row})=>({accountId,marketplace:"AMAZON",sellerSkuId:row.sellerSku!,sku:row.sellerSku!,...listingScalars(row)}))});
 const listings=[] as Awaited<ReturnType<typeof prisma.marketplaceListing.findMany>>;for(const chunk of groups(sellerSkus))listings.push(...await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON",sellerSkuId:{in:chunk}}}));
 const bySku=new Map(listings.map((listing)=>[listing.sellerSkuId.toUpperCase(),listing]));
 for(const chunk of groups(uniqueListingRows))await prisma.$transaction(chunk.flatMap(({row})=>{const listing=bySku.get(row.sellerSku!.toUpperCase());return listing?[prisma.marketplaceListing.update({where:{id:listing.id},data:listingUpdate(row)})]:[];}));

 async function syncIdentifiers(items:Array<{listingId:string;row:AmazonConsignmentSourceRow}>){
   const proposed=items.flatMap(({listingId,row})=>identifierValues(row).flatMap(([identifierType,rawValue])=>{const normalizedValue=normalizeListingIdentifier(identifierType,rawValue);return rawValue&&normalizedValue?[{listingId,identifierType,rawValue,normalizedValue}]:[]}));
   const current=[] as Array<{marketplaceListingId:string;identifierType:IdentifierType;normalizedValue:string}>;for(const chunk of groups(proposed))current.push(...await prisma.marketplaceListingIdentifier.findMany({where:{accountId,marketplace:"AMAZON",active:true,OR:chunk.map((item)=>({identifierType:item.identifierType,normalizedValue:item.normalizedValue}))},select:{marketplaceListingId:true,identifierType:true,normalizedValue:true}}));
   const owner=new Map(current.map((item)=>[`${item.identifierType}:${item.normalizedValue}`,item.marketplaceListingId]));const accepted=[] as typeof proposed;
   for(const item of proposed){const prior=owner.get(`${item.identifierType}:${item.normalizedValue}`);if(prior){if(prior!==item.listingId)warnings.push({issueType:"CATALOG_IDENTIFIER_CONFLICT",message:`${item.identifierType} conflicts with another Amazon listing; the existing mapping was preserved.`});continue;}owner.set(`${item.identifierType}:${item.normalizedValue}`,item.listingId);accepted.push(item);}
   for(const chunk of groups(accepted))await prisma.marketplaceListingIdentifier.createMany({data:chunk.map((item)=>({accountId,marketplaceListingId:item.listingId,marketplace:"AMAZON",identifierType:item.identifierType,rawValue:item.rawValue,normalizedValue:item.normalizedValue,source:"AMAZON_CONSIGNMENT_IMPORT"}))});
 }
 await syncIdentifiers(uniqueListingRows.flatMap(({row})=>{const listing=bySku.get(row.sellerSku!.toUpperCase());return listing?[{listingId:listing.id,row}]:[];}));

 const allListings=await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON"},select:{id:true,sellerSkuId:true,identifiers:{where:{active:true},select:{identifierType:true,normalizedValue:true}}}});const identityMap=new Map<string,string[]>();for(const listing of allListings)for(const identifier of listing.identifiers){const key=`${identifier.identifierType}:${identifier.normalizedValue}`;identityMap.set(key,[...(identityMap.get(key)??[]),listing.id]);}
 const enriched:Array<{listingId:string;row:AmazonConsignmentSourceRow}>=[];
 for(const item of catalogRows){const candidateIds=[...new Set(identifierValues(item.row).flatMap(([type,value])=>{const normalized=normalizeListingIdentifier(type,value);return normalized?identityMap.get(`${type}:${normalized}`)??[]:[]}))];if(candidateIds.length!==1){if(candidateIds.length>1)warnings.push({issueType:"CATALOG_IDENTIFIER_CONFLICT",message:"Catalog identifiers resolve multiple Amazon listings; enrichment was not applied.",rowNumber:item.row.rowNumber});continue;}enriched.push({listingId:candidateIds[0],row:item.row});}
 for(const chunk of groups(enriched))await prisma.$transaction(chunk.map((item)=>prisma.marketplaceListing.update({where:{id:item.listingId},data:listingUpdate(item.row)})));
 await syncIdentifiers(enriched);
 return{warnings,listingFileIds:parts.filter((part)=>part.fileType==="AMAZON_ALL_LISTINGS").map((part)=>part.fileId),catalogFileIds:parts.filter((part)=>part.fileType==="AMAZON_CATEGORY_CATALOG"||part.fileType==="AMAZON_PRODUCT_CATALOG").map((part)=>part.fileId)};
}

export async function importAmazonConsignmentDraft(input:{accountId:string;user:Pick<User,"id">;externalConsignmentNumber:string;displayName?:string;destinationText?:string;files:File[];request?:RequestMeta;existingBatchId?:string}){
 const accountId=input.accountId;
 const account=await prisma.account.findFirst({where:{id:input.accountId,active:true,marketplace:"AMAZON"},select:{id:true}});if(!account)throw new Error("Select an active Amazon account.");if(!input.files.length)throw new Error("Choose at least one Amazon file.");
 const externalConsignmentNumber=number(input.externalConsignmentNumber);const inputBuffers:Array<{file:File;data:Buffer;extension:string}>=[];for(const file of input.files){const extension=validateConsignmentUpload(file);const data=Buffer.from(await file.arrayBuffer());if(data.length!==file.size)throw new Error("Upload size changed while reading.");inputBuffers.push({file,data,extension});}
 const sourceHash=createHash("sha256").update(inputBuffers.map((item)=>createHash("sha256").update(item.data).digest("hex")).join("|")).digest("hex");
 const duplicate=input.existingBatchId?null:await prisma.consignmentBatch.findFirst({where:{accountId,marketplace:"AMAZON",OR:[{externalConsignmentNumber},{sourceFileSha256:sourceHash}]},select:{id:true,status:true}});if(duplicate)throw new Error(`Consignment already exists as ${duplicate.id} (${duplicate.status}).`);
 const batchId=input.existingBatchId??`cnb_${randomUUID().replace(/-/g,"")}`;const batch=input.existingBatchId?await prisma.consignmentBatch.findFirst({where:{id:batchId,accountId,status:{in:["DRAFT","PARSING","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"]}}}):await prisma.consignmentBatch.create({data:{id:batchId,accountId,marketplace:"AMAZON",externalConsignmentNumber,displayName:safe(input.displayName||`Amazon ${externalConsignmentNumber}`,160),destinationText:input.destinationText?safe(input.destinationText,500):null,status:"PARSING",sourceFileName:sanitizeConsignmentFileName(input.files[0].name),sourceFileSha256:sourceHash,createdByUserId:input.user.id}});if(!batch)throw new Error("Amazon draft is unavailable for reparse.");
 if(input.existingBatchId)await prisma.$transaction([prisma.consignmentImportIssue.deleteMany({where:{consignmentBatchId:batchId}}),prisma.consignmentLine.deleteMany({where:{consignmentBatchId:batchId,activated:false}}),prisma.consignmentBatch.update({where:{id:batchId},data:{status:"PARSING",sourceFileSha256:sourceHash,totalSourceRows:0,totalValidLines:0,totalRequiredQuantity:0,matchedLines:0,unmatchedLines:0,ambiguousLines:0,conflictLines:0,markingLines:0,readyMadeLines:0}})]);
 try{
  const parts:Part[]=[];for(const inputFile of inputBuffers){if(inputFile.extension===".zip"){const archive=await inspectAmazonConsignmentZip(inputFile.data);parts.push(...archive.entries.map((entry)=>({name:entry.entryName,entryName:entry.entryName,data:entry.data,parsed:entry.parsed})));}else parts.push({name:inputFile.file.name,data:inputFile.data,parsed:await parseAmazonBuffer(inputFile.data,inputFile.file.name)});}
  const storedParts:StoredPart[]=[];for(const part of parts){const fileType=part.parsed.fileType;const stored=await storeConsignmentBuffer({batchId,area:fileType==="AMAZON_SHIPMENT"?"source":"supporting",originalName:part.name,data:part.data});const record=await prisma.consignmentImportFile.create({data:{consignmentBatchId:batchId,fileType,originalFileName:stored.originalFileName,managedRelativePath:stored.managedRelativePath,fileSizeBytes:stored.fileSizeBytes,sha256:stored.sha256,entryName:part.entryName,parsed:true,rowCount:part.parsed.totalRows,notes:`Amazon ${part.parsed.tables.map((table)=>table.profile).join(", ")}`}});storedParts.push({...part,fileId:record.id,fileType});}
  const shipmentParts=storedParts.filter((part)=>part.fileType==="AMAZON_SHIPMENT");const shipmentCandidateCount=storedParts.reduce((sum,part)=>sum+part.parsed.shipmentCandidateCount,0);if(shipmentCandidateCount!==1){await prisma.$transaction([prisma.consignmentImportIssue.create({data:{consignmentBatchId:batchId,issueType:shipmentCandidateCount?"MULTIPLE_MAIN_FILES":"MISSING_MAIN_FILE",severity:"ERROR",message:shipmentCandidateCount?"Multiple Amazon shipment sources were detected; owner selection or source replacement is required.":"No Amazon shipment header signature was found."}}),prisma.consignmentBatch.update({where:{id:batchId},data:{status:shipmentCandidateCount?"REVIEW_REQUIRED":"FAILED"}})]);return{batchId,requiresMainSelection:shipmentCandidateCount>1};}
  const main=shipmentParts[0];await prisma.consignmentImportFile.update({where:{id:main.fileId},data:{isCurrentSource:true}});await prisma.consignmentBatch.update({where:{id:batchId},data:{sourceUploadRelativePath:(await prisma.consignmentImportFile.findUniqueOrThrow({where:{id:main.fileId}})).managedRelativePath,sourceFileName:main.name}});
  const enrichment=await syncAmazonListings(accountId,storedParts);const shipmentRows=amazonSourceRows(main.parsed,"SHIPMENT").map((row)=>({...row,sourceFileId:main.fileId}));const matches=await matchAmazonConsignmentRows(accountId,shipmentRows);
  const selectedIds=[...new Set(matches.flatMap((match)=>match.decision.listing?[match.decision.listing.id]:[]))];const listings=await prisma.marketplaceListing.findMany({where:{id:{in:selectedIds},accountId,marketplace:"AMAZON"},include:{identifiers:{where:{active:true}},processRules:{where:{active:true},take:2,include:{markingAsset:true}}}});const listingMap=new Map(listings.map((listing)=>[listing.id,listing]));
  const lines:Prisma.ConsignmentLineCreateManyInput[]=[];const issues:Prisma.ConsignmentImportIssueCreateManyInput[]=[];
  for(const match of matches){const row=match.row;const lineId=`cnl_${randomUUID().replace(/-/g,"")}`;const listing=match.decision.listing?listingMap.get(match.decision.listing.id):null;const rule=listing?.processRules[0];const identifiers=Object.fromEntries((listing?.identifiers??[]).map((identifier)=>[identifier.identifierType,identifier.rawValue]));const snapshot=buildConsignmentCatalogSnapshot({marketplace:"AMAZON",title:listing?.productTitle??row.productTitle??undefined,brand:listing?.liveBrand??row.brand??undefined,category:listing?.liveCategory??row.category??undefined,subCategory:listing?.subCategory??row.subCategory??undefined,material:row.material??undefined,color:row.color??undefined,size:row.size??undefined,modelNumber:row.modelNumber??undefined,description:listing?.description??row.description??undefined,bulletPoints:row.bulletPoints,mainImageUrl:listing?.mainImageUrl??row.mainImageUrl??undefined,imageUrls:[listing?.mainImageUrl??undefined,...row.imageUrls].filter((value):value is string=>Boolean(value)),identifiers:{sellerSku:listing?.sellerSkuId??row.sellerSku??undefined,asin:String(identifiers.ASIN??row.asin??"")||undefined,fnsku:String(identifiers.FNSKU??row.fnsku??"")||undefined,externalId:String(identifiers.EXTERNAL_ID??row.externalId??"")||undefined,ean:row.ean??undefined,upc:row.upc??undefined,gtin:row.gtin??undefined},provenance:{shipmentFileId:main.fileId,listingFileId:enrichment.listingFileIds[0],catalogFileIds:enrichment.catalogFileIds}});
    lines.push({id:lineId,consignmentBatchId:batchId,accountId,rowNumber:row.rowNumber,productNameSource:row.productTitle,sellerSkuSource:row.sellerSku,fsnSource:null,asinSource:row.asin,fnskuSource:row.fnsku,externalIdSource:row.externalId,barcodeSource:row.ean??row.upc??row.gtin,brandSource:row.brand,sizeSource:row.size,colorSource:row.color,modelIdSource:row.modelNumber,requiredQuantity:row.requiredQuantity!,marketplaceListingId:listing?.id??null,matchStatus:match.decision.status,matchIdentifierType:match.decision.listing?match.decision.identifierType:null,matchIdentifierValue:match.decision.listing?match.decision.identifierValue:null,matchMessage:"warning" in match.decision?match.decision.warning:null,processRoute:rule?.route??null,processRuleId:rule?.id??null,markingAssetId:rule?.markingAssetId??null,catalogSnapshotJson:JSON.stringify(snapshot)});
    if(!listing)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:match.decision.status,severity:"ERROR",message:"warning" in match.decision?match.decision.warning:"Amazon listing match requires review.",safeDataJson:JSON.stringify({listingIds:match.decision.candidates.map((candidate)=>candidate.id)})});
    if(listing&&!rule)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MISSING_PROCESS_RULE",severity:"ERROR",message:"Matched Amazon listing has no active process rule."});
    if(rule&&rule.route!=="PICK_PACK"&&rule.route!=="PICK_MARK_PACK")issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"UNSUPPORTED_ROUTE",severity:"ERROR",message:"Amazon consignments support Pick-Pack and Pick-Mark-Pack only."});
    if(rule?.route==="PICK_MARK_PACK"&&!rule.markingAsset)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_ASSET_MISSING",severity:"ERROR",message:"Marking route requires a linked active marking asset."});
    if(rule?.route==="PICK_MARK_PACK"&&rule.markingAsset&&!rule.markingAsset.instructions&&!rule.markingAsset.masterDesignId)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_INSTRUCTIONS_MISSING",severity:"ERROR",message:"Marking route requires instructions or a Master Design ID."});
    if(!snapshot.title)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MISSING_TITLE",severity:"WARNING",message:"Amazon product title is missing."});if(!snapshot.mainImageUrl)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_IMAGE_MISSING",severity:rule?.route==="PICK_MARK_PACK"?"WARNING":"INFO",message:"Product image is missing; owner review is recommended."});
  }
  issues.push(...enrichment.warnings.map((warning)=>({consignmentBatchId:batchId,issueType:warning.issueType,severity:"WARNING" as const,message:warning.message,rowNumber:warning.rowNumber,safeDataJson:warning.safeDataJson})));
  for(const chunk of groups(lines))await prisma.consignmentLine.createMany({data:chunk});for(const chunk of groups(issues))if(chunk.length)await prisma.consignmentImportIssue.createMany({data:chunk});const blocking=issues.some((issue)=>issue.severity==="ERROR");
  await prisma.consignmentBatch.update({where:{id:batchId},data:{status:blocking?"REVIEW_REQUIRED":"READY_TO_ACTIVATE",totalSourceRows:shipmentRows.length,totalValidLines:lines.length,totalRequiredQuantity:lines.reduce((sum,line)=>sum+line.requiredQuantity,0),matchedLines:lines.filter((line)=>line.marketplaceListingId).length,unmatchedLines:lines.filter((line)=>line.matchStatus==="NOT_FOUND").length,ambiguousLines:lines.filter((line)=>line.matchStatus==="EXACT_MULTIPLE").length,conflictLines:lines.filter((line)=>line.matchStatus==="IDENTIFIER_CONFLICT").length,markingLines:lines.filter((line)=>line.processRoute==="PICK_MARK_PACK").length,readyMadeLines:lines.filter((line)=>line.processRoute==="PICK_PACK").length}});
  await recordAuditLog({userId:input.user.id,accountId,action:input.existingBatchId?"CONSIGNMENT_REPARSED":"CONSIGNMENT_PARSED",entityType:"ConsignmentBatch",entityId:batchId,metadata:{marketplace:"AMAZON",sourceRows:shipmentRows.length,validLines:lines.length,issueCount:issues.length},request:input.request});return{batchId,requiresMainSelection:false};
 }catch(error){await prisma.consignmentBatch.update({where:{id:batchId},data:{status:"FAILED"}}).catch(()=>undefined);await prisma.consignmentImportIssue.create({data:{consignmentBatchId:batchId,issueType:"IMPORT_FAILED",severity:"ERROR",message:error instanceof Error?error.message.slice(0,500):"Amazon import failed."}}).catch(()=>undefined);throw error;}
}
