import { createHash, randomUUID } from "node:crypto";
import type { IdentifierType, Prisma, User } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { recordAuditLog } from "@/lib/audit";
import type { RequestMeta } from "@/lib/network";
import { normalizeListingIdentifier } from "@/src/lib/marking/identifiers";
import { sanitizeConsignmentFileName, storeConsignmentBuffer, validateConsignmentUpload } from "../storage";
import { inspectAmazonConsignmentZip } from "./archive";
import { parseAmazonBuffer } from "./parser";
import { buildConsignmentCatalogSnapshot } from "./catalog-snapshot";
import { matchAmazonConsignmentRows } from "./matching";
import type { AmazonConsignmentSourceRow, AmazonListingEnrichmentV1, AmazonParsedFile, AmazonParserIssue } from "./types";
import { parseSpreadsheetRowsFromPath } from "@/lib/import/files";
import { resolveAdaptiveRows } from "@/src/lib/imports/adaptive-rows";
import { resolveExistingConsignmentPath } from "../storage";
import { completeConsignmentHeaderMapping, pauseConsignmentForHeaderMapping } from "../adaptive-mapping";
import { sanitizeImportJobError } from "@/src/lib/import-jobs/safe-error";

const CHUNK=300;
const groups=<T>(values:T[],size=CHUNK)=>Array.from({length:Math.ceil(values.length/size)},(_,index)=>values.slice(index*size,(index+1)*size));
const safe=(value:string,max:number)=>value.normalize("NFKC").trim().slice(0,max);
function number(value:string){const normalized=value.normalize("NFKC").trim().toUpperCase();if(!normalized||normalized.length>100||!/^[A-Z0-9._/-]+$/.test(normalized))throw new Error("Enter a valid Amazon shipment/consignment number.");return normalized;}
type Part={name:string;entryName?:string;data:Buffer;parsed:AmazonParsedFile;storedFileId?:string};
type StoredPart=Part&{fileId:string;fileType:Prisma.ConsignmentImportFileCreateInput["fileType"]};
type Warning={issueType:string;message:string;rowNumber?:number;safeDataJson?:string};
type SelectedCandidate={fileId:string;tableName:string};
const value=(row:Record<string,unknown>,key:string,max=200)=>String(row[key]??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max)||null;
export function mappedAmazonShipmentRows(rows:Record<string,unknown>[],sourceFileName:string){const normalized:AmazonConsignmentSourceRow[]=[],issues:AmazonParserIssue[]=[],sheet="Mapped headers";let skippedZeroRows=0;for(const [index,row] of rows.entries()){const rowNumber=index+2,raw=value(row,"Shipped",80),sellerSku=value(row,"Merchant SKU"),asin=value(row,"ASIN",40),fnsku=value(row,"FNSKU",100);if(raw!==null&&/^\d+$/.test(raw)){const quantity=Number(raw);if(quantity===0){skippedZeroRows++;continue;}if(Number.isSafeInteger(quantity)){normalized.push({rowNumber,shipmentId:null,shipmentName:null,destinationText:null,sellerSku,asin,fnsku,externalId:null,ean:null,upc:null,gtin:null,requiredQuantity:quantity,productTitle:null,brand:null,category:null,subCategory:null,material:null,color:null,size:null,modelNumber:null,description:null,bulletPoints:[],mainImageUrl:null,imageUrls:[],listingStatus:null,sourceFileId:null,sourceSheet:sheet,sourceProfile:"SHIPMENT"});continue;}}
 const reason=raw===null?"Shipped is blank.":raw.startsWith("-")?"Shipped is negative.":/^[+-]?\d+\.\d+$/.test(raw)?"Shipped is decimal.":"Shipped is not a safe positive whole number.";issues.push({rowNumber,sheet,issueType:"INVALID_QUANTITY",severity:"ERROR",message:`Amazon mapped shipment quantity is invalid: ${reason}`,safeData:{sourceFile:sanitizeConsignmentFileName(sourceFileName),sheet,rowNumber:String(rowNumber),sellerSku,fnsku,asin,reason}});}
 return{rows:normalized,issues,skippedZeroRows};}

function candidateTablesJson(parsed:AmazonParsedFile){return JSON.stringify(parsed.tables.filter((table)=>table.profile!=="UNKNOWN").map((table)=>({tableName:table.sheet,profile:table.profile,sheetUsage:table.sheetUsage,sheetPriority:table.sheetPriority,label:`${table.sheet} - ${table.profile.replaceAll("_"," ")}`,headerRow:table.headerRow,dataRow:table.dataRow,rowCount:table.rows.length,cellCount:table.rows.length*table.headers.length})).slice(0,30));}

function identifierValues(row:AmazonConsignmentSourceRow):Array<[IdentifierType,string|null]> { return [["SELLER_SKU",row.sellerSku],["FNSKU",row.fnsku],["ASIN",row.asin],["EXTERNAL_ID",row.externalId],["EAN",row.ean],["UPC",row.upc],["GTIN",row.gtin],["MODEL_NUMBER",row.modelNumber]]; }
function listingScalars(row:AmazonConsignmentSourceRow):Partial<Prisma.MarketplaceListingCreateManyInput> { const images=row.imageUrls.slice(0,10);return{...(row.productTitle?{productTitle:row.productTitle,liveTitle:row.productTitle}:{}),...(row.brand?{liveBrand:row.brand}:{}),...(row.category?{liveCategory:row.category}:{}),...(row.subCategory?{subCategory:row.subCategory}:{}),...(row.description?{description:row.description}:{}),...(row.bulletPoints.length?{productHighlights:row.bulletPoints.join("\n")}:{}),...(row.listingStatus?{listingStatus:row.listingStatus}:{}),...(row.mainImageUrl?{mainImageUrl:row.mainImageUrl}:{}),...Object.fromEntries(images.map((url,index)=>[`imageUrl${index+1}`,url])),lastImportedAt:new Date()}; }
function listingUpdate(row:AmazonConsignmentSourceRow):Prisma.MarketplaceListingUpdateInput{return listingScalars(row);}
const partSortKeys=new WeakMap<object,string>();
function sourceKey(item:{part:StoredPart;table:StoredPart["parsed"]["tables"][number];row:AmazonConsignmentSourceRow}){const profileRank={ALL_LISTINGS:0,CATEGORY_CATALOG:1,PRODUCT_CATALOG:2,SHIPMENT:3,SUPPORTING:4,UNKNOWN:5}[item.table.profile];const usageRank=item.table.sheetUsage==="OPERATIONAL"?0:item.table.sheetUsage==="UNKNOWN"?1:2;let partKey=partSortKeys.get(item.part);if(!partKey){partKey=`${item.part.name.normalize("NFKC").toLowerCase()}\u0000${createHash("sha256").update(item.part.data).digest("hex")}`;partSortKeys.set(item.part,partKey);}return `${profileRank}\u0000${usageRank}\u0000${String(999-item.table.sheetPriority).padStart(4,"0")}\u0000${partKey}\u0000${item.table.sheet.normalize("NFKC").toLowerCase()}\u0000${String(item.row.rowNumber).padStart(8,"0")}`;}
function mergeCatalogRows(primary:AmazonConsignmentSourceRow,fallback:AmazonConsignmentSourceRow):AmazonConsignmentSourceRow{return{...fallback,...primary,sellerSku:primary.sellerSku??fallback.sellerSku,fnsku:primary.fnsku??fallback.fnsku,asin:primary.asin??fallback.asin,externalId:primary.externalId??fallback.externalId,ean:primary.ean??fallback.ean,upc:primary.upc??fallback.upc,gtin:primary.gtin??fallback.gtin,listingStatus:primary.listingStatus??fallback.listingStatus,productTitle:primary.productTitle??fallback.productTitle,brand:primary.brand??fallback.brand,category:primary.category??fallback.category,subCategory:primary.subCategory??fallback.subCategory,material:primary.material??fallback.material,color:primary.color??fallback.color,size:primary.size??fallback.size,modelNumber:primary.modelNumber??fallback.modelNumber,description:primary.description??fallback.description,bulletPoints:primary.bulletPoints.length?primary.bulletPoints:fallback.bulletPoints,mainImageUrl:primary.mainImageUrl??fallback.mainImageUrl,imageUrls:primary.imageUrls.length?primary.imageUrls:fallback.imageUrls};}
function catalogConflictFields(left:AmazonConsignmentSourceRow,right:AmazonConsignmentSourceRow){const pairs:Array<[string,string|null]>=[["title",left.productTitle&&right.productTitle&&left.productTitle!==right.productTitle?left.productTitle:null],["category",left.category&&right.category&&left.category!==right.category?left.category:null],["brand",left.brand&&right.brand&&left.brand!==right.brand?left.brand:null],["description",left.description&&right.description&&left.description!==right.description?left.description:null],["main image",left.mainImageUrl&&right.mainImageUrl&&left.mainImageUrl!==right.mainImageUrl?left.mainImageUrl:null],["material",left.material&&right.material&&left.material!==right.material?left.material:null],["color",left.color&&right.color&&left.color!==right.color?left.color:null],["size",left.size&&right.size&&left.size!==right.size?left.size:null],["model",left.modelNumber&&right.modelNumber&&left.modelNumber!==right.modelNumber?left.modelNumber:null]];return pairs.flatMap(([field,conflict])=>conflict?[field]:[]);}

async function syncAmazonListings(accountId:string,parts:StoredPart[]){
 const warnings:Warning[]=[];const listingRows=parts.flatMap((part)=>part.parsed.tables.filter((table)=>table.sheetUsage!=="REFERENCE"&&table.profile==="ALL_LISTINGS").flatMap((table)=>table.rows.map((row)=>({row,part,table})))).sort((left,right)=>sourceKey(left).localeCompare(sourceKey(right)));
 const catalogRows=parts.flatMap((part)=>part.parsed.tables.filter((table)=>table.sheetUsage!=="REFERENCE"&&(table.profile==="CATEGORY_CATALOG"||table.profile==="PRODUCT_CATALOG")).flatMap((table)=>table.rows.map((row)=>({row,part,table})))).sort((left,right)=>sourceKey(left).localeCompare(sourceKey(right)));
 const listingAuthority=new Map<string,(typeof listingRows)[number]>();for(const item of listingRows){if(!item.row.sellerSku)continue;const key=item.row.sellerSku.toUpperCase();const prior=listingAuthority.get(key);if(!prior){listingAuthority.set(key,item);continue;}const fields=[["ASIN",prior.row.asin,item.row.asin],["FNSKU",prior.row.fnsku,item.row.fnsku],["listing status",prior.row.listingStatus,item.row.listingStatus]].filter((entry)=>entry[1]&&entry[2]&&entry[1]!==entry[2]).map((entry)=>entry[0]);if(fields.length)warnings.push({issueType:"CATALOG_FIELD_CONFLICT",message:`Amazon All Listings sources disagree on ${fields.join(", ")}; deterministic source priority was preserved.`,safeDataJson:JSON.stringify({sources:[`${prior.part.name}:${prior.table.sheet}`,`${item.part.name}:${item.table.sheet}`],fields})});listingAuthority.set(key,{...prior,row:mergeCatalogRows(prior.row,item.row)});}
 const uniqueListingRows=[...listingAuthority.values()];
 const sellerSkus=uniqueListingRows.map(({row})=>row.sellerSku!);const existing=[] as Awaited<ReturnType<typeof prisma.marketplaceListing.findMany>>;
 for(const chunk of groups(sellerSkus))existing.push(...await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON",sellerSkuId:{in:chunk}}}));
 const existingKeys=new Set(existing.map((listing)=>listing.sellerSkuId.toUpperCase()));const missing=uniqueListingRows.filter(({row})=>!existingKeys.has(row.sellerSku!.toUpperCase()));
  for(const chunk of groups(missing))await prisma.marketplaceListing.createMany({data:chunk.map(({row})=>({accountId,marketplace:"AMAZON",sellerSkuId:row.sellerSku!,sku:row.sellerSku!,...listingScalars(row)}))});
 const listings=[] as Awaited<ReturnType<typeof prisma.marketplaceListing.findMany>>;for(const chunk of groups(sellerSkus))listings.push(...await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON",sellerSkuId:{in:chunk}}}));
 const bySku=new Map(listings.map((listing)=>[listing.sellerSkuId.toUpperCase(),listing]));
 for(const chunk of groups(uniqueListingRows))await prisma.$transaction(chunk.flatMap(({row})=>{const listing=bySku.get(row.sellerSku!.toUpperCase());return listing?[prisma.marketplaceListing.update({where:{id:listing.id},data:listingUpdate(row)})]:[];}));

 async function syncIdentifiers(items:Array<{listingId:string;row:AmazonConsignmentSourceRow}>){
   const proposed=items.flatMap(({listingId,row})=>identifierValues(row).flatMap(([identifierType,rawValue])=>{const normalizedValue=normalizeListingIdentifier(identifierType,rawValue);return rawValue&&normalizedValue?[{listingId,identifierType,rawValue,normalizedValue}]:[]}));
   const current=[] as Array<{marketplaceListingId:string;identifierType:IdentifierType;normalizedValue:string}>;for(const chunk of groups(proposed))current.push(...await prisma.marketplaceListingIdentifier.findMany({where:{accountId,marketplace:"AMAZON",active:true,OR:chunk.map((item)=>({identifierType:item.identifierType,normalizedValue:item.normalizedValue}))},select:{marketplaceListingId:true,identifierType:true,normalizedValue:true}}));
   const owner=new Map(current.map((item)=>[`${item.identifierType}:${item.normalizedValue}`,item.marketplaceListingId]));const accepted=[] as typeof proposed;
   for(const item of proposed){const prior=owner.get(`${item.identifierType}:${item.normalizedValue}`);if(prior){if(prior!==item.listingId)warnings.push({issueType:"CATALOG_IDENTIFIER_CONFLICT",message:`${item.identifierType} conflicts with another Amazon listing; the existing mapping was preserved.`});continue;}owner.set(`${item.identifierType}:${item.normalizedValue}`,item.listingId);accepted.push(item);}
   for(const chunk of groups(accepted))await prisma.marketplaceListingIdentifier.createMany({data:chunk.map((item)=>({accountId,marketplaceListingId:item.listingId,marketplace:"AMAZON",identifierType:item.identifierType,rawValue:item.rawValue,normalizedValue:item.normalizedValue,source:"AMAZON_CONSIGNMENT_IMPORT"}))});
 }
 await syncIdentifiers(uniqueListingRows.flatMap(({row})=>{const listing=bySku.get(row.sellerSku!.toUpperCase());return listing?[{listingId:listing.id,row}]:[];}));

 const allListings=await prisma.marketplaceListing.findMany({where:{accountId,marketplace:"AMAZON"},select:{id:true,sellerSkuId:true,identifiers:{where:{active:true},select:{identifierType:true,normalizedValue:true}}}});const identityMap=new Map<string,string[]>();for(const listing of allListings)for(const identifier of listing.identifiers){const key=`${identifier.identifierType}:${identifier.normalizedValue}`;identityMap.set(key,[...(identityMap.get(key)??[]),listing.id]);}
 const enrichmentAuthority=new Map<string,{listingId:string;row:AmazonConsignmentSourceRow;part:StoredPart;table:StoredPart["parsed"]["tables"][number];sourceFileIds:string[];sourceTables:string[]}>();
 for(const item of catalogRows){const candidateIds=[...new Set(identifierValues(item.row).flatMap(([type,value])=>{const normalized=normalizeListingIdentifier(type,value);return normalized?identityMap.get(`${type}:${normalized}`)??[]:[]}))];if(candidateIds.length!==1){if(candidateIds.length>1)warnings.push({issueType:"CATALOG_IDENTIFIER_CONFLICT",message:"Catalog identifiers resolve multiple Amazon listings; enrichment was not applied.",rowNumber:item.row.rowNumber});continue;}const listingId=candidateIds[0];const prior=enrichmentAuthority.get(listingId);if(!prior){enrichmentAuthority.set(listingId,{listingId,row:item.row,part:item.part,table:item.table,sourceFileIds:[item.part.fileId],sourceTables:[item.table.sheet]});continue;}const fields=catalogConflictFields(prior.row,item.row);if(fields.length)warnings.push({issueType:"CATALOG_FIELD_CONFLICT",message:`Amazon catalog sources disagree on ${fields.join(", ")}; deterministic source priority was preserved.`,rowNumber:item.row.rowNumber,safeDataJson:JSON.stringify({sources:[`${prior.part.name}:${prior.table.sheet}`,`${item.part.name}:${item.table.sheet}`],fields})});enrichmentAuthority.set(listingId,{...prior,row:mergeCatalogRows(prior.row,item.row),sourceFileIds:[...new Set([...prior.sourceFileIds,item.part.fileId])],sourceTables:[...new Set([...prior.sourceTables,item.table.sheet])]});}
 const enriched=[...enrichmentAuthority.values()].map(({listingId,row})=>({listingId,row}));
 for(const chunk of groups(enriched))await prisma.$transaction(chunk.map((item)=>prisma.marketplaceListing.update({where:{id:item.listingId},data:listingUpdate(item.row)})));
 await syncIdentifiers(enriched);
 const enrichmentByListingId=new Map<string,AmazonListingEnrichmentV1>([...enrichmentAuthority.values()].map((item)=>[item.listingId,{version:1,listingId:item.listingId,title:item.row.productTitle??undefined,brand:item.row.brand??undefined,category:item.row.category??undefined,subCategory:item.row.subCategory??undefined,material:item.row.material??undefined,color:item.row.color??undefined,size:item.row.size??undefined,modelNumber:item.row.modelNumber??undefined,description:item.row.description??undefined,bulletPoints:item.row.bulletPoints.length?item.row.bulletPoints:undefined,mainImageUrl:item.row.mainImageUrl??undefined,imageUrls:item.row.imageUrls.length?item.row.imageUrls:undefined,listingStatus:item.row.listingStatus??undefined,sourceFileIds:item.sourceFileIds,sourceTables:item.sourceTables}]));
 return{warnings,listingFileIds:parts.filter((part)=>part.parsed.tables.some((table)=>table.sheetUsage!=="REFERENCE"&&table.profile==="ALL_LISTINGS")).map((part)=>part.fileId),catalogFileIds:parts.filter((part)=>part.parsed.tables.some((table)=>table.sheetUsage!=="REFERENCE"&&(table.profile==="CATEGORY_CATALOG"||table.profile==="PRODUCT_CATALOG"))).map((part)=>part.fileId),enrichmentByListingId};
}

export async function importAmazonConsignmentDraft(input:{accountId:string;user:Pick<User,"id">;externalConsignmentNumber:string;displayName?:string;destinationText?:string;files:File[];request?:RequestMeta;existingBatchId?:string;storedFileIds?:string[];selectedCandidate?:SelectedCandidate}){
 const accountId=input.accountId;
 const account=await prisma.account.findFirst({where:{id:input.accountId,active:true,marketplace:"AMAZON"},select:{id:true}});if(!account)throw new Error("Select an active Amazon account.");if(!input.files.length)throw new Error("Choose at least one Amazon file.");
 const externalConsignmentNumber=number(input.externalConsignmentNumber);const inputBuffers:Array<{file:File;data:Buffer;extension:string;storedFileId?:string}>=[];for(const [index,file] of input.files.entries()){const extension=validateConsignmentUpload(file);const data=Buffer.from(await file.arrayBuffer());if(data.length!==file.size)throw new Error("Upload size changed while reading.");inputBuffers.push({file,data,extension,storedFileId:input.storedFileIds?.[index]});}
 const sourceHash=createHash("sha256").update(inputBuffers.map((item)=>createHash("sha256").update(item.data).digest("hex")).join("|")).digest("hex");
 const duplicate=input.existingBatchId?null:await prisma.consignmentBatch.findFirst({where:{accountId,marketplace:"AMAZON",OR:[{externalConsignmentNumber},{sourceFileSha256:sourceHash}]},select:{id:true,status:true}});if(duplicate)throw new Error(`Consignment already exists as ${duplicate.id} (${duplicate.status}).`);
 const batchId=input.existingBatchId??`cnb_${randomUUID().replace(/-/g,"")}`;const batch=input.existingBatchId?await prisma.consignmentBatch.findFirst({where:{id:batchId,accountId,status:{in:["DRAFT","PARSING","REVIEW_REQUIRED","READY_TO_ACTIVATE","FAILED"]}}}):await prisma.consignmentBatch.create({data:{id:batchId,accountId,marketplace:"AMAZON",externalConsignmentNumber,displayName:safe(input.displayName||`Amazon ${externalConsignmentNumber}`,160),destinationText:input.destinationText?safe(input.destinationText,500):null,status:"PARSING",sourceFileName:sanitizeConsignmentFileName(input.files[0].name),sourceFileSha256:sourceHash,createdByUserId:input.user.id}});if(!batch)throw new Error("Amazon draft is unavailable for reparse.");
 if(input.existingBatchId)await prisma.$transaction([prisma.consignmentImportIssue.deleteMany({where:{consignmentBatchId:batchId}}),prisma.consignmentLine.deleteMany({where:{consignmentBatchId:batchId,activated:false}}),prisma.consignmentBatch.update({where:{id:batchId},data:{status:"PARSING",sourceFileSha256:sourceHash,totalSourceRows:0,totalValidLines:0,totalRequiredQuantity:0,matchedLines:0,unmatchedLines:0,ambiguousLines:0,conflictLines:0,markingLines:0,readyMadeLines:0}})]);
 try{
  const parts:Part[]=[];for(const inputFile of inputBuffers){if(inputFile.extension===".zip"){const archive=await inspectAmazonConsignmentZip(inputFile.data);parts.push(...archive.entries.map((entry)=>({name:entry.entryName,entryName:entry.entryName,data:entry.data,parsed:entry.parsed})));}else parts.push({name:inputFile.file.name,data:inputFile.data,parsed:await parseAmazonBuffer(inputFile.data,inputFile.file.name),storedFileId:inputFile.storedFileId});}
  const storedParts:StoredPart[]=[];for(const part of parts){const fileType=part.parsed.fileType;const candidateJson=candidateTablesJson(part.parsed);const existing=part.storedFileId?await prisma.consignmentImportFile.findFirst({where:{id:part.storedFileId,consignmentBatchId:batchId,managedRelativePath:{not:null}}}):null;if(existing){const record=await prisma.consignmentImportFile.update({where:{id:existing.id},data:{fileType,parsed:true,rowCount:part.parsed.totalRows,candidateTablesJson:candidateJson,notes:`Amazon ${part.parsed.tables.map((table)=>table.profile).join(", ")}`}});storedParts.push({...part,fileId:record.id,fileType});continue;}const stored=await storeConsignmentBuffer({batchId,area:fileType==="AMAZON_SHIPMENT"?"source":"supporting",originalName:part.name,data:part.data});const record=await prisma.consignmentImportFile.create({data:{consignmentBatchId:batchId,fileType,originalFileName:stored.originalFileName,managedRelativePath:stored.managedRelativePath,fileSizeBytes:stored.fileSizeBytes,sha256:stored.sha256,entryName:part.entryName,parsed:true,rowCount:part.parsed.totalRows,candidateTablesJson:candidateJson,notes:`Amazon ${part.parsed.tables.map((table)=>table.profile).join(", ")}`}});storedParts.push({...part,fileId:record.id,fileType});}
  const shipmentCandidates=storedParts.flatMap((part)=>part.parsed.tables.filter((table)=>table.sheetUsage!=="REFERENCE"&&table.profile==="SHIPMENT").map((table)=>({part,table})));let appliedProfileId:string|null=null;if(!shipmentCandidates.length){for(const part of storedParts){const stored=await prisma.consignmentImportFile.findUnique({where:{id:part.fileId},select:{managedRelativePath:true}});if(!stored?.managedRelativePath)continue;const rawRows=await parseSpreadsheetRowsFromPath(await resolveExistingConsignmentPath(stored.managedRelativePath)).catch(()=>[]);if(!rawRows.length)continue;const adaptive=await resolveAdaptiveRows({accountId,marketplace:"AMAZON",purpose:"CONSIGNMENT_QUANTITY",rows:rawRows,layoutKnown:false});if(adaptive.state==="NEEDS_MAPPING"){const job=await pauseConsignmentForHeaderMapping({batchId,accountId,actorUserId:input.user.id,marketplace:"AMAZON",purpose:"CONSIGNMENT_QUANTITY",fileName:part.name,mappingRequest:adaptive.mappingRequest});return{batchId,requiresMainSelection:false,needsMapping:true,mappingJobId:job.id};}const mapped=mappedAmazonShipmentRows(adaptive.rows,part.name);appliedProfileId=adaptive.profileId;const table={sheet:"Mapped headers",sheetUsage:"OPERATIONAL" as const,sheetPriority:100,headers:Object.keys(adaptive.rows[0]??{}),profile:"SHIPMENT" as const,fileType:"AMAZON_SHIPMENT" as const,confidence:100,headerRow:1,dataRow:2,rows:mapped.rows,issues:mapped.issues,sourceRowCount:adaptive.rows.length,skippedZeroRows:mapped.skippedZeroRows};part.parsed.tables.push(table);shipmentCandidates.push({part,table});break;}}
  const selected=input.selectedCandidate?shipmentCandidates.find((candidate)=>candidate.part.fileId===input.selectedCandidate?.fileId&&candidate.table.sheet===input.selectedCandidate.tableName):shipmentCandidates.length===1?shipmentCandidates[0]:null;if(!selected){const hasCandidates=shipmentCandidates.length>0;await prisma.$transaction([prisma.consignmentImportIssue.create({data:{consignmentBatchId:batchId,issueType:hasCandidates?"MULTIPLE_MAIN_FILES":"MISSING_MAIN_FILE",severity:"ERROR",message:hasCandidates?"Multiple Amazon shipment sources were detected; choose one exact file and worksheet.":"No Amazon shipment header signature was found."}}),prisma.consignmentBatch.update({where:{id:batchId},data:{status:hasCandidates?"REVIEW_REQUIRED":"FAILED"}})]);return{batchId,requiresMainSelection:shipmentCandidates.length>1};}await completeConsignmentHeaderMapping({batchId,profileId:appliedProfileId});
  const main=selected.part;await prisma.$transaction([prisma.consignmentImportFile.updateMany({where:{consignmentBatchId:batchId},data:{isCurrentSource:false,selectedTableName:null}}),prisma.consignmentImportFile.update({where:{id:main.fileId},data:{isCurrentSource:true,selectedTableName:selected.table.sheet}})]);await prisma.consignmentBatch.update({where:{id:batchId},data:{sourceUploadRelativePath:(await prisma.consignmentImportFile.findUniqueOrThrow({where:{id:main.fileId}})).managedRelativePath,sourceFileName:main.name}});
  const enrichment=await syncAmazonListings(accountId,storedParts);const shipmentRows=selected.table.rows.map((row)=>({...row,sourceFileId:main.fileId}));const matches=await matchAmazonConsignmentRows(accountId,shipmentRows);
  const selectedIds=[...new Set(matches.flatMap((match)=>match.decision.listing?[match.decision.listing.id]:[]))];const listings=await prisma.marketplaceListing.findMany({where:{id:{in:selectedIds},accountId,marketplace:"AMAZON"},include:{identifiers:{where:{active:true}},processRules:{where:{active:true},take:2,include:{markingAsset:true}}}});const listingMap=new Map(listings.map((listing)=>[listing.id,listing]));
  const lines:Prisma.ConsignmentLineCreateManyInput[]=[];const issues:Prisma.ConsignmentImportIssueCreateManyInput[]=selected.table.issues.map(issue=>({consignmentBatchId:batchId,rowNumber:issue.rowNumber,issueType:issue.issueType,severity:issue.severity,message:issue.message,safeDataJson:issue.safeData?JSON.stringify(issue.safeData):issue.sheet?JSON.stringify({sourceFile:sanitizeConsignmentFileName(main.name),sheet:issue.sheet}):undefined}));
  for(const match of matches){const row=match.row;const lineId=`cnl_${randomUUID().replace(/-/g,"")}`;const listing=match.decision.listing?listingMap.get(match.decision.listing.id):null;const rule=listing?.processRules[0];const identifiers=Object.fromEntries((listing?.identifiers??[]).map((identifier)=>[identifier.identifierType,identifier.rawValue]));const catalog=listing?enrichment.enrichmentByListingId.get(listing.id):undefined;const listingImages=listing?[listing.mainImageUrl,listing.imageUrl1,listing.imageUrl2,listing.imageUrl3,listing.imageUrl4,listing.imageUrl5,listing.imageUrl6,listing.imageUrl7,listing.imageUrl8,listing.imageUrl9,listing.imageUrl10].filter((value):value is string=>Boolean(value)):[];const listingBullets=listing?.productHighlights?.split(/\r?\n/).map((item)=>item.trim()).filter(Boolean)??[];const snapshot=buildConsignmentCatalogSnapshot({marketplace:"AMAZON",title:listing?.productTitle??catalog?.title??row.productTitle??undefined,brand:listing?.liveBrand??catalog?.brand??row.brand??undefined,category:listing?.liveCategory??catalog?.category??row.category??undefined,subCategory:listing?.subCategory??catalog?.subCategory??row.subCategory??undefined,material:catalog?.material??row.material??undefined,color:catalog?.color??row.color??undefined,size:catalog?.size??row.size??undefined,modelNumber:catalog?.modelNumber??row.modelNumber??undefined,description:listing?.description??catalog?.description??row.description??undefined,bulletPoints:catalog?.bulletPoints?.length?catalog.bulletPoints:listingBullets.length?listingBullets:row.bulletPoints,mainImageUrl:listing?.mainImageUrl??catalog?.mainImageUrl??row.mainImageUrl??undefined,imageUrls:[...listingImages,...(catalog?.imageUrls??[]),...row.imageUrls],identifiers:{sellerSku:listing?.sellerSkuId??row.sellerSku??undefined,asin:String(identifiers.ASIN??row.asin??"")||undefined,fnsku:String(identifiers.FNSKU??row.fnsku??"")||undefined,externalId:String(identifiers.EXTERNAL_ID??row.externalId??"")||undefined,ean:row.ean??undefined,upc:row.upc??undefined,gtin:row.gtin??undefined},provenance:{shipmentFileId:main.fileId,listingFileId:enrichment.listingFileIds[0],catalogFileIds:catalog?.sourceFileIds??enrichment.catalogFileIds}});
    lines.push({id:lineId,consignmentBatchId:batchId,accountId,rowNumber:row.rowNumber,productNameSource:row.productTitle,sellerSkuSource:row.sellerSku,fsnSource:null,asinSource:row.asin,fnskuSource:row.fnsku,externalIdSource:row.externalId,barcodeSource:row.ean??row.upc??row.gtin,brandSource:row.brand,sizeSource:row.size,colorSource:row.color,modelIdSource:row.modelNumber,requiredQuantity:row.requiredQuantity!,marketplaceListingId:listing?.id??null,matchStatus:match.decision.status,matchIdentifierType:match.decision.listing?match.decision.identifierType:null,matchIdentifierValue:match.decision.listing?match.decision.identifierValue:null,matchMessage:"warning" in match.decision?match.decision.warning:null,processRoute:rule?.route??null,processRuleId:rule?.id??null,markingAssetId:rule?.markingAssetId??null,catalogSnapshotJson:JSON.stringify(snapshot)});
    if(!listing)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:match.decision.status,severity:"ERROR",message:"warning" in match.decision?match.decision.warning:"Amazon listing match requires review.",safeDataJson:JSON.stringify({listingIds:match.decision.candidates.map((candidate)=>candidate.id)})});
    if(listing&&!rule)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MISSING_PROCESS_RULE",severity:"WARNING",message:"No saved default processing; Direct to Pack will be used."});
    const markingRoute=rule?.route==="PICK_MARK_PACK"||rule?.route==="PICK_MARK_ASSEMBLE_PACK",assemblyRoute=rule?.route==="PICK_ASSEMBLE_PACK"||rule?.route==="PICK_MARK_ASSEMBLE_PACK";
    if(markingRoute&&!rule.markingAsset?.active)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_ASSET_MISSING",severity:"WARNING",message:"No active marking asset is saved; manager guidance is required."});
    if(markingRoute&&rule.markingAsset?.active&&!rule.markingAsset.instructions&&!rule.markingAsset.masterDesignId)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_INSTRUCTIONS_MISSING",severity:"WARNING",message:"No marking instructions or Master Design ID are saved."});
    if(assemblyRoute&&(!rule.assemblyTitle?.trim()||!rule.assemblyInstructions?.trim()))issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"ASSEMBLY_INSTRUCTIONS_MISSING",severity:"WARNING",message:"Saved Assembly title and instructions are incomplete; the worker must confirm a manual-instruction route before continuing."});
    if(!snapshot.title)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MISSING_TITLE",severity:"WARNING",message:"Amazon product title is missing."});if(!snapshot.mainImageUrl)issues.push({consignmentBatchId:batchId,consignmentLineId:lineId,rowNumber:row.rowNumber,issueType:"MARKING_IMAGE_MISSING",severity:markingRoute?"WARNING":"INFO",message:"Product image is missing; owner review is recommended."});
  }
  issues.push(...enrichment.warnings.map((warning)=>({consignmentBatchId:batchId,issueType:warning.issueType,severity:"WARNING" as const,message:warning.message,rowNumber:warning.rowNumber,safeDataJson:warning.safeDataJson})));
  for(const chunk of groups(lines))await prisma.consignmentLine.createMany({data:chunk});for(const chunk of groups(issues))if(chunk.length)await prisma.consignmentImportIssue.createMany({data:chunk});const blocking=issues.some((issue)=>issue.severity==="ERROR");
  const totalSourceRows=selected.table.sourceRowCount??shipmentRows.length+selected.table.issues.filter(issue=>issue.issueType==="INVALID_QUANTITY").length+(selected.table.skippedZeroRows??0);await prisma.consignmentBatch.update({where:{id:batchId},data:{status:blocking?"REVIEW_REQUIRED":"READY_TO_ACTIVATE",totalSourceRows,totalValidLines:lines.length,totalRequiredQuantity:lines.reduce((sum,line)=>sum+line.requiredQuantity,0),matchedLines:lines.filter((line)=>line.marketplaceListingId).length,unmatchedLines:lines.filter((line)=>line.matchStatus==="NOT_FOUND").length,ambiguousLines:lines.filter((line)=>line.matchStatus==="EXACT_MULTIPLE").length,conflictLines:lines.filter((line)=>line.matchStatus==="IDENTIFIER_CONFLICT").length,markingLines:lines.filter((line)=>line.processRoute==="PICK_MARK_PACK"||line.processRoute==="PICK_MARK_ASSEMBLE_PACK").length,readyMadeLines:lines.filter((line)=>line.processRoute==="PICK_PACK").length}});
  await recordAuditLog({userId:input.user.id,accountId,action:input.existingBatchId?"CONSIGNMENT_REPARSED":"CONSIGNMENT_PARSED",entityType:"ConsignmentBatch",entityId:batchId,metadata:{marketplace:"AMAZON",sourceRows:totalSourceRows,validLines:lines.length,skippedZeroRows:selected.table.skippedZeroRows??0,issueCount:issues.length},request:input.request});return{batchId,requiresMainSelection:false};
 }catch(error){const safeFailure=sanitizeImportJobError(error)??"Amazon import failed.";await prisma.consignmentBatch.update({where:{id:batchId},data:{status:"FAILED"}}).catch(()=>undefined);await prisma.consignmentImportIssue.create({data:{consignmentBatchId:batchId,issueType:"IMPORT_FAILED",severity:"ERROR",message:safeFailure}}).catch(()=>undefined);throw new Error(safeFailure);}
}
