import { mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { ROOT, TEMP_ROOT } from "./core.mjs";

const target=resolve(TEMP_ROOT,"fresh-start-qa.db"); mkdirSync(TEMP_ROOT,{recursive:true}); rmSync(target,{force:true});
const db=new DatabaseSync(target); db.exec("PRAGMA foreign_keys=ON;");
const migrations=readdirSync(resolve(ROOT,"prisma/migrations"),{withFileTypes:true}).filter((entry)=>entry.isDirectory()).map((entry)=>entry.name).sort();
for(const name of migrations)db.exec(readFileSync(join(ROOT,"prisma/migrations",name,"migration.sql"),"utf8"));
db.exec('CREATE TABLE IF NOT EXISTS "_prisma_migrations" (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, finished_at DATETIME, migration_name TEXT NOT NULL, logs TEXT, rolled_back_at DATETIME, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, applied_steps_count INTEGER NOT NULL DEFAULT 0)');
const now=new Date().toISOString(); for(const [index,name] of migrations.entries())db.prepare('INSERT INTO "_prisma_migrations" (id,checksum,finished_at,migration_name,applied_steps_count) VALUES (?,?,?,?,1)').run(`qa-migration-${index}`,`qa-checksum-${index}`,now,name);
const users=[
  ["qa-owner","qa-owner","OWNER",1,1,1,1,1,1], ["qa-picker","qa-picker","PICKER",1,0,0,0,0,0], ["qa-marker","qa-marker","PICKER",0,0,1,0,0,0],
  ["qa-assembler","qa-assembler","PICKER",0,0,0,1,0,0], ["qa-packer","qa-packer","PACKER",0,1,0,0,0,0], ["qa-view-all","qa-view-all","PICKER",0,0,0,0,1,0], ["qa-manager","qa-manager","OWNER",1,1,1,1,1,1]
];
for(const [id,username,role,canPick,canPack,canMark,canAssemble,canViewAllWork,manager] of users)db.prepare('INSERT INTO "User" (id,username,passwordHash,name,role,active,canPick,canPack,canMark,canAssemble,canViewAllWork,canReportProblem,canManageMarkingLibrary,canManageProcessRules,canViewConsignments,canImportConsignments,canManageConsignments,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?,?,?,?,1,?,?,?,?,?, ?,?)').run(id,username,"synthetic-qa-hash-not-for-login",`Synthetic ${username}`,role,canPick,canPack,canMark,canAssemble,canViewAllWork,manager,manager,1,manager,manager,now,now);
const accounts=[["qa-flipkart","Synthetic Flipkart","QA-FK","FLIPKART"],["qa-amazon","Synthetic Amazon","QA-AMZ","AMAZON"]];
for(const [id,name,code,marketplace] of accounts)db.prepare('INSERT INTO "Account" (id,name,code,companyName,marketplace,active,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?)').run(id,name,code,"Synthetic QA Company",marketplace,now,now);
for(const [userId] of users)for(const [accountId] of accounts)db.prepare('INSERT INTO "_UserAssignedAccounts" (A,B) VALUES (?,?)').run(accountId,userId);
db.prepare('UPDATE "User" SET accountId=?').run("qa-flipkart");
const listings=[["qa-listing-fk","qa-flipkart","FLIPKART","QA-FK-SELLER","QA-FK-SKU","Synthetic Flipkart Product"],["qa-listing-amz","qa-amazon","AMAZON","QA-AMZ-SELLER","QA-AMZ-SKU","Synthetic Amazon Product"]];
for(const row of listings)db.prepare('INSERT INTO "MarketplaceListing" (id,accountId,marketplace,sellerSkuId,sku,productTitle,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)').run(...row,now,now);
const identifiers=[["qa-id-sku","qa-flipkart","qa-listing-fk","FLIPKART","SELLER_SKU","QA-FK-SKU"],["qa-id-fsn","qa-flipkart","qa-listing-fk","FLIPKART","FSN","QA-FSN-0001"],["qa-id-listing","qa-flipkart","qa-listing-fk","FLIPKART","LISTING_ID","QA-LISTING-0001"],["qa-id-asin","qa-amazon","qa-listing-amz","AMAZON","ASIN","B0QA000001"],["qa-id-fnsku","qa-amazon","qa-listing-amz","AMAZON","FNSKU","X00QA00001"],["qa-id-barcode","qa-amazon","qa-listing-amz","AMAZON","BARCODE","990000000001"]];
for(const [id,accountId,listingId,marketplace,type,value] of identifiers)db.prepare('INSERT INTO "MarketplaceListingIdentifier" (id,accountId,marketplaceListingId,marketplace,identifierType,rawValue,normalizedValue,source,active,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,1,?,?)').run(id,accountId,listingId,marketplace,type,value,value,"SYNTHETIC_QA",now,now);
db.prepare('INSERT INTO "MarkingAsset" (id,name,status,active,createdByUserId,updatedByUserId,createdAt,updatedAt) VALUES (?,?,?,1,?,?,?,?)').run("qa-marking","Synthetic QA Mark","ACTIVE","qa-owner","qa-owner",now,now);
db.prepare('INSERT INTO "ProductProcessRule" (id,accountId,marketplaceListingId,route,markingAssetId,markingRequired,assemblyRequired,active,createdByUserId,updatedByUserId,createdAt,updatedAt) VALUES (?,?,?,?,?,1,0,1,?,?,?,?)').run("qa-rule","qa-flipkart","qa-listing-fk","PICK_MARK_PACK","qa-marking","qa-owner","qa-owner",now,now);
const orders=[["qa-order-simple","qa-flipkart","QA-AWB-0001","QA-FK-SKU","QA-ORDER-0001","READY","READY","READY"],["qa-order-assembly","qa-flipkart","QA-AWB-0002","QA-FK-SKU","QA-ORDER-0002","READY","READY","READY"],["qa-order-problem","qa-flipkart","QA-AWB-0003","QA-FK-SKU","QA-ORDER-0003","PROBLEM","READY","PROBLEM"],["qa-order-complete","qa-amazon","QA-AWB-0004","QA-AMZ-SKU","QA-ORDER-0004","PICKED","PACKED","PACKED"]];
for(const [id,accountId,awb,sku,orderNo,pickStatus,packStatus,status] of orders)db.prepare('INSERT INTO "Order" (id,accountId,marketplace,awb,sku,quantity,orderNumber,pickStatus,packStatus,status,importedAt,createdAt,updatedAt) VALUES (?,?,?,?,?,1,?,?,?,?,?,?,?)').run(id,accountId,accountId==="qa-amazon"?"AMAZON":"FLIPKART",awb,sku,orderNo,pickStatus,packStatus,status,now,now,now);
db.prepare('INSERT INTO "ProblemOrder" (id,accountId,orderId,reason,status,reportedById,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?)').run("qa-problem","qa-flipkart","qa-order-problem","Synthetic QA problem","OPEN","qa-picker",now,now);
const batches=[["qa-consignment-fk","qa-flipkart","FLIPKART","QA-CONS-FK","Synthetic Flipkart consignment"],["qa-consignment-amz","qa-amazon","AMAZON","QA-CONS-AMZ","Synthetic Amazon consignment"]];
for(const [id,accountId,marketplace,number,name] of batches)db.prepare('INSERT INTO "ConsignmentBatch" (id,accountId,marketplace,externalConsignmentNumber,displayName,status,sourceFileName,sourceFileSha256,totalSourceRows,totalValidLines,totalRequiredQuantity,matchedLines,createdByUserId,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,1,1,1,1,?,?,?)').run(id,accountId,marketplace,number,name,"ACTIVE","synthetic-source.xlsx",`synthetic-sha-${id}`,"qa-owner",now,now);
const lines=[["qa-line-fk","qa-consignment-fk","qa-flipkart","qa-listing-fk","QA-FK-SKU","PICK_MARK_PACK","qa-rule","qa-marking"],["qa-line-amz","qa-consignment-amz","qa-amazon","qa-listing-amz","QA-AMZ-SKU","PICK_PACK",null,null]];
for(const [id,batchId,accountId,listingId,sku,route,ruleId,markingId] of lines)db.prepare('INSERT INTO "ConsignmentLine" (id,consignmentBatchId,accountId,rowNumber,sellerSkuSource,requiredQuantity,marketplaceListingId,matchStatus,processRoute,processRuleId,markingAssetId,sellerSkuSnapshot,activated,createdAt,updatedAt) VALUES (?,?,?,1,?,1,?,?,?,?,?,?,1,?,?)').run(id,batchId,accountId,sku,listingId,"EXACT_SKU",route,ruleId,markingId,sku,now,now);
const tasks=[["qa-task-pick","qa-flipkart","ORDER","qa-order-simple",null,"PICK",1,"READY","qa-picker"],["qa-task-assembly","qa-flipkart","ORDER","qa-order-assembly",null,"ASSEMBLE",2,"READY","qa-assembler"],["qa-task-mark","qa-flipkart","CONSIGNMENT",null,"qa-line-fk","MARK",2,"READY","qa-marker"],["qa-task-pack","qa-amazon","CONSIGNMENT",null,"qa-line-amz","PACK",2,"READY","qa-packer"],["qa-task-complete","qa-amazon","ORDER","qa-order-complete",null,"PACK",2,"COMPLETED","qa-packer"]];
for(const [id,accountId,sourceType,orderId,lineId,stage,sequence,status,assigned] of tasks)db.prepare('INSERT INTO "WorkTask" (id,accountId,sourceType,orderId,consignmentLineId,stage,sequenceNumber,requiredQuantity,completedQuantity,status,assignedUserId,completedByUserId,completedAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,1,?,?,?,?,?,?,?)').run(id,accountId,sourceType,orderId,lineId,stage,sequence,status==="COMPLETED"?1:0,status,assigned,status==="COMPLETED"?assigned:null,status==="COMPLETED"?now:null,now,now);
db.prepare('INSERT INTO "WorkActionLog" (id,accountId,taskId,actorUserId,action,quantityBefore,quantityAfter,clientRequestId,requestKind,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?)').run("qa-action-complete","qa-amazon","qa-task-complete","qa-packer","TASK_COMPLETED",0,1,"qa-complete-request","COMPLETE",now);
db.exec("PRAGMA optimize;"); const integrity=db.prepare("PRAGMA integrity_check").get(); const fk=db.prepare("PRAGMA foreign_key_check").all(); db.close();
if(String(Object.values(integrity)[0])!=="ok"||fk.length)throw new Error("Synthetic QA database verification failed.");
console.log(JSON.stringify({created:true,database:".codex-tmp/fresh-start-qa.db",syntheticUsers:users.length,syntheticAccounts:accounts.length,syntheticListings:listings.length,syntheticOrders:orders.length,syntheticConsignments:batches.length,syntheticTasks:tasks.length,integrity:"ok",foreignKeyViolations:0},null,2));
