import { notFound } from "next/navigation";
import { EmptyState } from "@/components/EmptyState";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { StatusBadge } from "@/components/StatusBadge";
import { WorkCardLiveEditor } from "./WorkCardLiveEditor";

const allowed = new Set(["design-system","navigation","dashboard","product-inventory","product-details","imports","work-cards","route-dialogs","scanner","problems","data-management","empty-loading-error"]);

export default async function DesignLabArea({params}:{params:Promise<{area:string}>}) {
  if (process.env.STAGING_UI_AUDIT !== "true" || process.env.STAGE3_SYNTHETIC_STAGING !== "true") notFound();
  const {area}=await params;if(!allowed.has(area))notFound();
  return <main className="min-h-screen bg-stone-50 p-3 sm:p-6">
    <PageHeader eyebrow="Private synthetic design lab" title={area.replaceAll("-"," ")} description="Current implementation primitives beside bounded redesign drafts. No production mutation is connected." action={{href:"/__qa/design-lab",label:"All galleries"}}/>
    <div className="grid gap-6 xl:grid-cols-3">
      <Variant title="Current" status="CURRENT"><Gallery area={area} draft="current"/></Variant>
      <Variant title="Redesign Draft A" status="DRAFT A"><Gallery area={area} draft="a"/></Variant>
      <Variant title="Redesign Draft B" status="DRAFT B"><Gallery area={area} draft="b"/></Variant>
    </div>
    {area==="work-cards"?<WorkCardLiveEditor/>:null}
  </main>;
}

function Variant({title,status,children}:{title:string;status:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2><span className="rounded-full bg-violet-50 px-2 py-1 text-xs font-black text-violet-700">{status}</span></div>{children}</section>;}
function Gallery({area,draft}:{area:string;draft:"current"|"a"|"b"}){
  if(area==="design-system")return <div className="space-y-4"><div className="flex flex-wrap gap-2">{["READY","PROBLEM","COMPLETED","FAILED","WARNING"].map(value=><StatusBadge key={value} value={value}/>)}</div><SampleInputs/><ActionGrid draft={draft}/><div className="grid grid-cols-5 gap-2">{["bg-berry","bg-mint","bg-slate-950","bg-amber-400","bg-rose-600"].map(value=><div key={value} className={`aspect-square rounded-xl ${value}`}/>)}</div></div>;
  if(area==="navigation")return <div className="overflow-hidden rounded-xl border"><div className="bg-slate-950 p-4 text-white"><p className="font-black">Synthetic Warehouse</p><p className="text-xs text-slate-400">STAGE-FK-01</p></div><nav className="grid gap-1 p-2">{["Dashboard","Work Hub","Product Inventory","Imports","Consignments","Problems"].map((label,index)=><button key={label} className={`min-h-11 rounded-lg px-3 text-left font-bold ${index===1?"bg-pink-50 text-berry":"hover:bg-slate-50"}`}>{label}</button>)}</nav></div>;
  if(area==="dashboard")return <div className="grid grid-cols-2 gap-3">{[["Pick","12"],["Mark","4"],["Assembly","3"],["Pack","8"]].map(([label,value])=><div key={label} className="rounded-xl border bg-slate-50 p-3"><p className="text-sm text-slate-500">{label}</p><p className="text-3xl font-black">{value}</p></div>)}</div>;
  if(area==="product-inventory"||area==="product-details")return <div className={`grid gap-4 ${draft==="b"?"sm:grid-cols-[1.2fr_1fr]":""}`}><ProductImage src={draft==="current"?"https://invalid.example.invalid/synthetic.jpg":null} alt="Synthetic product" size="lg"/><div><StatusBadge value="ACTIVE"/><h3 className="mt-2 text-xl font-black">Synthetic Long Product Title for Responsive Layout Review</h3><p className="mt-1 break-all text-sm text-slate-500">STAGE-FK-SKU-WITH-LONG-IDENTIFIER-001</p><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><dt>FSN</dt><dd>STAGE-FSN-001</dd><dt>Route</dt><dd>Pick → Mark → Pack</dd></dl><ActionGrid draft={draft}/></div></div>;
  if(area==="imports")return <div className="space-y-3">{["QUEUED","RUNNING","COMPLETED_WITH_WARNINGS","FAILED"].map((value,index)=><div key={value} className="rounded-xl border p-3"><div className="flex justify-between"><b>Synthetic import {index+1}</b><StatusBadge value={value}/></div><div className="mt-3 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-berry" style={{width:`${[10,55,100,35][index]}%`}}/></div></div>)}</div>;
  if(area==="work-cards")return <WorkCard draft={draft}/>;
  if(area==="route-dialogs")return <div role="dialog" className="rounded-2xl border p-4 shadow-xl"><p className="text-xs font-black uppercase text-berry">Pick complete</p><h3 className="text-xl font-black">Choose next route</h3><p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm font-bold">Saved instructions are unavailable. Continue only after review.</p><div className="mt-3 grid grid-cols-2 gap-2">{["Direct Pack","Mark","Assembly","Mark + Assembly"].map(label=><button key={label} className="min-h-12 rounded-xl border font-bold">{label}</button>)}</div></div>;
  if(area==="scanner")return <div className="space-y-3"><input placeholder="Scan Tracking ID, AWB, SKU…" className="min-h-14 w-full rounded-xl border px-4 text-lg"/><button className="min-h-12 w-full rounded-xl bg-slate-950 font-black text-white">Find work</button><WorkCard draft={draft}/></div>;
  if(area==="problems")return <div className="space-y-3"><StatusBadge value="OPEN"/><h3 className="text-xl font-black">Synthetic damaged item</h3><p className="text-sm text-slate-600">Interrupted stage: Assembly. Earlier completed work remains unchanged.</p><textarea className="min-h-24 w-full rounded-xl border p-3" placeholder="Resolution note"/><ActionGrid draft={draft}/></div>;
  if(area==="data-management")return <div className="space-y-3"><div className="rounded-xl border border-amber-300 bg-amber-50 p-3"><b>Preview only</b><p className="text-sm">12 synthetic records would be affected.</p></div><input type="password" placeholder="Owner password" className="min-h-11 w-full rounded-lg border px-3"/><input placeholder="Type confirmation phrase" className="min-h-11 w-full rounded-lg border px-3"/><ActionGrid draft={draft}/></div>;
  return <div className="space-y-4"><EmptyState title="No synthetic work" description="Change filters or select another account."/><div className="animate-pulse rounded-xl border p-4"><div className="h-5 w-2/3 rounded bg-slate-200"/><div className="mt-3 h-20 rounded bg-slate-100"/></div><div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800"><b>Unable to load this section</b><p className="text-sm">Synthetic error state with a controlled retry.</p></div></div>;
}
function SampleInputs(){return <div className="grid gap-2"><input placeholder="Text input" className="min-h-11 rounded-lg border px-3"/><select className="min-h-11 rounded-lg border px-3"><option>Select option</option></select><label className="flex min-h-11 items-center gap-2"><input type="checkbox"/> Checkbox</label></div>;}
function ActionGrid({draft}:{draft:string}){return <div className={`mt-4 grid gap-2 ${draft==="a"?"grid-cols-2":draft==="b"?"sm:grid-cols-3":"grid-cols-2"}`}><button className="min-h-11 rounded-lg bg-berry px-3 font-bold text-white">Primary</button><button className="min-h-11 rounded-lg border px-3 font-bold">Details</button><button className={`${draft==="current"?"col-span-2":""} min-h-11 rounded-lg border border-rose-200 px-3 font-bold text-rose-700`}>Problem</button></div>;}
function WorkCard({draft}:{draft:string}){return <article className={`grid gap-4 rounded-2xl border p-4 ${draft==="b"?"sm:grid-cols-[9rem_1fr]":""}`}><ProductImage src={null} alt="Synthetic work product" size={draft==="a"?"lg":"md"} showBadge={false}/><div><div className="flex gap-2"><StatusBadge value="READY"/><span className="rounded-full bg-slate-950 px-2 py-1 text-xs font-black text-white">ORDER</span></div><h3 className="mt-2 text-lg font-black">Synthetic Pick Work Item</h3><p className="break-all text-xs text-slate-500">STAGE-TRACKING-LONG-IDENTIFIER-0001</p><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-50 p-2 text-center"><small>Required</small><b className="block text-xl">4</b></div><div className="rounded-lg bg-slate-50 p-2 text-center"><small>Completed</small><b className="block text-xl">1</b></div></div><ActionGrid draft={draft}/></div></article>;}
