import Link from "next/link";
import { ProcessRoute, type Prisma } from "@prisma/client";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ProductImage } from "@/components/ProductImage";
import { requireAccount } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { requireWorkPermission } from "@/lib/work-permissions";
import { ProcessRuleEditor } from "./ProcessRuleEditor";

const LABELS: Record<ProcessRoute,string>={PICK_PACK:"Direct to Pack",PICK_MARK_PACK:"Marking",PICK_ASSEMBLE_PACK:"Assembly",PICK_MARK_ASSEMBLE_PACK:"Marking + Assembly"};

export default async function ProcessRulesPage({ searchParams }: { searchParams?: Promise<Record<string,string|undefined>> }) {
 const user=await requireWorkPermission("canManageProcessRules"); const account=await requireAccount(user); const params=await searchParams; const page=Math.max(1,Number(params?.page)||1); const take=50; const q=params?.q?.trim(); const filter=params?.filter;
 const where:Prisma.MarketplaceListingWhereInput={accountId:account.id,OR:q?[{sellerSkuId:{contains:q}},{sku:{contains:q}},{fsn:{contains:q}},{listingId:{contains:q}},{productTitle:{contains:q}}]:undefined,processRules:filter==="missing-rule"?{none:{active:true}}:filter&&Object.values(ProcessRoute).includes(filter as ProcessRoute)?{some:{active:true,route:filter as ProcessRoute}}:filter==="marking"?{some:{active:true,markingRequired:true}}:filter==="assembly"?{some:{active:true,assemblyRequired:true}}:undefined};
 const [total,listings]=await Promise.all([prisma.marketplaceListing.count({where}),prisma.marketplaceListing.findMany({where,include:{processRules:{where:{active:true},take:1,select:{id:true,route:true,markingAssetId:true,assemblyTitle:true,assemblyInstructions:true,assemblyImageUrl:true}},markingAssetLinks:{where:{active:true,accountId:account.id},include:{markingAsset:{include:{files:{where:{activeVersion:true,attachmentType:"MARKING_FILE"},take:1}}}}}},orderBy:{updatedAt:"desc"},skip:(page-1)*take,take})]);
 const queryFor=(next:number)=>new URLSearchParams({...(q?{q}:{}),...(filter?{filter}:{}),page:String(next)}).toString();
 return <AppShell><PageHeader eyebrow="Workflow foundation" title="Product process rules" description="Set listing routes without changing existing customer Order Pick/Pack status."/><div className="mb-4 flex gap-2"><Link href="/owner/marking-library" className="rounded-md border bg-white px-4 py-2 text-sm font-bold">Marking Library</Link></div>
 {params?.error?<div className="mb-4 rounded-md bg-rose-50 p-3 text-sm font-semibold text-rose-700">{params.error}</div>:null}{params?.updated||params?.disabled?<div className="mb-4 rounded-md bg-teal-50 p-3 text-sm font-semibold text-teal-800">Process rule saved. Existing orders were not changed.</div>:null}
 <form className="mb-5 grid gap-3 rounded-md border bg-white p-4 sm:grid-cols-[1fr_0.7fr_auto]"><input name="q" defaultValue={q} placeholder="SKU, FSN, listing ID or title" className="min-h-11 rounded-md border px-3"/><select name="filter" defaultValue={filter??""} className="min-h-11 rounded-md border px-3"><option value="">All listings</option><option value="missing-rule">Missing rule</option><option value="marking">Marking required</option><option value="assembly">Assembly required</option>{Object.values(ProcessRoute).map((route)=><option key={route} value={route}>{LABELS[route]}</option>)}</select><button className="min-h-11 rounded-md bg-slate-950 px-4 font-bold text-white">Apply</button></form>
 <p className="mb-3 text-sm font-semibold text-slate-600">{total} listings / {account.marketplace} / {account.accountDisplayName??account.name}</p>
 <section className="space-y-4">{listings.map((listing)=>{const rule=listing.processRules[0];const assets=listing.markingAssetLinks.map((link)=>({id:link.markingAsset.id,label:link.markingAsset.masterDesignId??link.markingAsset.name,hasFile:Boolean(link.markingAsset.files.length)}));const missing=rule&&(rule.route==="PICK_MARK_PACK"||rule.route==="PICK_MARK_ASSEMBLE_PACK")&&!assets.some((asset)=>asset.id===rule.markingAssetId&&asset.hasFile);const assembly=rule&&(rule.route==="PICK_ASSEMBLE_PACK"||rule.route==="PICK_MARK_ASSEMBLE_PACK");return <article key={listing.id} className="grid gap-4 rounded-md border bg-white p-4 shadow-sm lg:grid-cols-[6rem_1fr_1.4fr]"><ProductImage src={listing.mainImageUrl} alt={listing.productTitle??listing.sellerSkuId} size="md" showBadge={false}/><div><p className="font-black">{listing.sellerSkuId}</p><p className="line-clamp-2 text-sm text-slate-600">{listing.productTitle??"Untitled"}</p><p className="mt-1 text-xs text-slate-500">{listing.fsn??"No FSN"} / {listing.listingId??"No listing ID"}</p><div className="mt-2 flex flex-wrap gap-1"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{rule?LABELS[rule.route]:"Missing rule"}</span>{missing?<span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-bold text-rose-700">Missing marking file</span>:null}{assembly&&!rule.assemblyInstructions&&!rule.assemblyTitle?<span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-bold text-rose-700">Missing instructions</span>:null}{assembly&&!rule.assemblyImageUrl?<span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800">Missing image warning</span>:null}</div></div><ProcessRuleEditor listingId={listing.id} rule={rule} assets={assets}/></article>})}</section>
 <div className="mt-5 flex justify-between text-sm font-bold"><span>Page {page} of {Math.max(1,Math.ceil(total/take))}</span><div className="flex gap-2">{page>1?<Link href={`?${queryFor(page-1)}`} className="rounded-md border px-3 py-2">Previous</Link>:null}{page*take<total?<Link href={`?${queryFor(page+1)}`} className="rounded-md border px-3 py-2">Next</Link>:null}</div></div>
 </AppShell>;
}
